### ISSUE TITLE
Cloudflare SRV DNS record issue, self-check fails

### ISSUE THREAD

**Issue by nodje** [spantaleev/matrix-docker-ansible-deploy#100]
Sorry I've no experience with this type of record so there may be an obvious solution to this problem.
But so far as I've been able to try, Cloudflare makes it impossible to create a plain "_matrix._tcp" value for an SRV records.

You have to make it "_matrix._tcp.domain.com"

You enter "_matrix._tcp" in "Service"
TCP in protocol
then you HAVE TO add a "Name" which can be "@", your domain or anything.

in doubt I've created both needed records with both Name filled with "<domain.com>" and  "matrix.<domain.com>"

As a consequence I believe I've the self-check ansible command failing with:
```
TASK [matrix-base : Fail if DNS SRV record incorrect (Ansible dig lookup)] ************************************************************
fatal: [matrix.mychinaroots.com]: FAILED! => {"msg": "The conditional check 'lookup_dig_srv is defined and (lookup_dig_srv.target != dns_srv_record_check.expected_target or lookup_dig_srv.port != dns_srv_record_check.expected_port)' failed. The error was: error while e$aluating conditional (lookup_dig_srv is defined and (lookup_dig_srv.target != dns_srv_record_check.expected_target or lookup_dig_srv.p$rt != dns_srv_record_check.expected_port)): 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'target'\n\nThe err$r appears to have been in '/root/project/matrix-docker-ansible-deploy/roles/matrix-base/tasks/self_check_dns_srv.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Fail if $NS SRV record incorrect (Ansible dig lookup)\n  ^ here\n"}
```

Looking at the content of `./roles/matrix-base/tasks/self_check_dns.yml`
it must be the comparison with `service_and_protocol` value that fails.

And quite unnervingly I can't even know whether my setup is ok or not due my lack of SRV record understanding.

Using https://neo.lain.haus/fed-tester/ with <mydomain.com> returns a valid result though, all be it with a Warning `WARN: Self-signed cert found for ...IP blabla` which is weird. As I though I understood Let's Encrypt WAS used to cerate a cert.

**Comment by aaronraimist** [comment]
![img_2130](https://user-images.githubusercontent.com/5855073/53199375-8dd6f000-35e4-11e9-9554-d0d0b826ddd4.jpeg)

My understanding is that this is a properly configured SRV record in Cloudflare.

**Comment by aaronraimist** [comment]
By the way you are welcome to get support via IRC or another matrix account instead of creating an issue  
https://github.com/spantaleev/matrix-docker-ansible-deploy#support

**Comment by nodje** [comment]
OK then my record is good as well.
But it means the `self-check` tag is not working properly (then it's an issue, but thank you for the mentioning the IRC, I should have started overthere)

Did this work with your setup @aaronraimist : `ansible-playbook -i inventory/hosts setup.yml --tags=self-check`

**Comment by spantaleev** [comment]
Which version of Ansible are you on? (You can check the output of `ansible-playbook --version`).

**Comment by nodje** [comment]
```
ansible-playbook 2.7.7
  config file = /root/project/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

**Comment by spantaleev** [comment]
Looks like the authoritative server is responding with "No answer" (or rather not responding?) when it's asked about SRV records which are missing.

I've made the playbook not choke on such `''` (No Answer) responses.
From now on, it will treat them the same way it treats '`NXDOMAIN'` responses (missing record).

Fixed in 639fc0bb5ce527b.

Thanks for reporting this edge-case! :+1:

**Comment by nodje** [comment]
Ok now I get what was wrong.
Cloudflare input dialog for SRV records is very directing, and doesn't go along very well with your explanation (If you don't understand SRV records).
Now that I could take a bit of time to read about SRV (amazing tool, good to be aware of this!), I was able to fix them.

And then it appears that you can get a working setup without correct SRV !??! How is this possible?

**Comment by spantaleev** [comment]
You can get a (mostly) correct setup without SRV records, because we're doing Server Discovery using a `/.well-known/matrix/server` file.

We still install SRV records for now, for compatibility with older servers.
Soon enough, we'll drop those.
You can learn more in the changelog entry that mentions the Synapse v0.99 update: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/433780384ef4cfa1d4d620d0e1493c443cddf0ab/CHANGELOG.md#synapse-v099-support-and-preparation-for-synapse-v10
