### ISSUE TITLE
ansible-playbook 2.10.8 ERROR! couldn't resolve module/action 'docker_network'.

### ISSUE THREAD

**Issue by JoeRu** [spantaleev/matrix-docker-ansible-deploy#1000]
Hi,
i guess this Ansible-Version is too new:

```
➜  matrix-docker-ansible-deploy git:(master) ✗ /usr/bin/ansible-playbook -i inventory/hosts setup.yml --tags=setup-all
ERROR! couldn't resolve module/action 'docker_network'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/ubuntu/matrix-docker-ansible-deploy/roles/matrix-base/tasks/setup_matrix_base.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure Matrix network is created in Docker
  ^ here
```
As i doesn't alter anything inside the default roles - this error should be out of the Ansible-Version - or?

**Comment by JoeRu** [comment]
hmm - its only ubuntu20.10 - installing ansible by pip3 is resolving this problem; Even the Ansible-base version is from ansible itself... Well one reason i hate ansible is this version-trouble. That's really a pain in the a###...

**Comment by spantaleev** [comment]
`ansible-base` is probably just the core. In newer Ansible versions, various modules (like `docker_network`) are part of "collections" and are not installed with the "base" distribution.

On Archlinux, the `ansible-base` contains just the core, and it's `ansible` (which depends on `ansible-base`) that contains the various "collections" (modules).

Not sure how it is for Ubuntu 20.10 and why you're installing `ansible-base` and not `ansible`.
