### ISSUE TITLE
Feature Request: Add support mautrix-wsproxy

### ISSUE THREAD

**Issue by hanthor** [spantaleev/matrix-docker-ansible-deploy#1016]
mautrix-wsproxy is needed to add mautrix-imessage

Being able to bridge iMessages is a very appealing feature especially for Android users who happen to have a Mac.

**Comment by thedanbob** [comment]
Cool, I hadn’t heard about those projects. I would be interested in having this feature too, I’ll try to find some time to work on it.

**Comment by hanthor** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1050

**Comment by hanthor** [comment]
I'm making progress and I'm feeling good, I added wsproxy and now I need to add mautrix-imessage/get an option to run brooklyn

**Comment by avion540** [comment]
Any update on this by any chance?

**Comment by hanthor** [comment]
I almost got it working but got confused by the nginx reverse proxy stuff

**Comment by shreyasajj** [comment]
@hanthor Do you need any help with. I would love to see what you have done so far

**Comment by Geczy** [comment]
any update?

**Comment by danb35** [comment]
It looks like #2261 is the current PR for this.  I'd like to see it land too.

**Comment by luixxiul** [comment]
mautrix-wsproxy was integrated by #2261.
