### ISSUE TITLE
Where are the element-client files located? I'd like to change the initial landing page.

### ISSUE THREAD

**Issue by maneeshsethi** [spantaleev/matrix-docker-ansible-deploy#1038]
What is the proper way to adjust the initial landing page when a client lands on the element site?

**Comment by aaronraimist** [comment]
For clarity can you take a screenshot of the page you want to customize?

**Comment by skepticalwaves** [comment]
Probably this one
![image](https://user-images.githubusercontent.com/66973897/192332314-be1ed3c0-513d-4c85-bcbb-d879f3a60cf4.png)

In general, the docs here list customization thats based on files
https://github.com/vector-im/element-web/tree/develop/docs

For the settings not changeable via existing variables, where can we put files?

**Comment by aaronraimist** [comment]
@skepticalwaves The file lives in `/matrix/client-element/welcome.html` and you can set `matrix_client_element_page_template_welcome_path` to a different path if you want to use another file.

**Comment by luixxiul** [comment]
Closing as answered.
