### ISSUE TITLE
purge_media_cache API call doesn't get through nginx

### ISSUE THREAD

**Issue by nukeop** [spantaleev/matrix-docker-ansible-deploy#1041]
I'm trying to run https://<my server>/_synapse/admin/v1/purge_media_cache?before_ts=1588935646000`, I have a valid admin token.

When I POST to this URL, I get a response from nginx:

```
<html>

<head>
	<title>404 Not Found</title>
</head>

<body>
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx/1.19.6</center>
</body>

</html>
```

Do I need to expose the synapse api differently? `_matrix` endpoints work fine.

**Comment by aaronraimist** [comment]
To expose the admin API to the internet you need to add `matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_admin_api_enabled: true` to your `vars.yml` file

**Comment by nukeop** [comment]
Excellent, this works. Thank you.
