### ISSUE TITLE
Following guide "Setting up postgres backup (optional)" wiped synapse database

### ISSUE THREAD

**Issue by brookwarren** [spantaleev/matrix-docker-ansible-deploy#1042]
**Synapse database wiped when attempting to use postgres backup playbook.**

Followed the Postgres Backup guide here:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-postgres-backup.md

1. Used these options as stated in the guide, only leaving out weeks and months:

```
matrix_postgres_backup_enabled:	true
matrix_postgres_backup_schedule: '@daily'
matrix_postgres_backup_keep_days: 7
matrix_postgres_backup_path: "{{ matrix_base_data_path }}/postgres-backup"
```

2. Only change to vars.yml was to add those 4 options.

3. Ran playbook as stated in guide:

`ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start`

4. Failed to start. Checked matrix-synapse journal and realized there was a problem right away due to:

> matrix-synapse[2498]: 2021-05-08 17:32:51,361 - twisted - 258 - ERROR - sentinel - psycopg2.OperationalError: FATAL:  password authentication failed for user "synapse"

5. Connected to database and saw 0 users:

```
# /usr/local/bin/matrix-postgres-cli
psql (13.2)
Type "help" for help.

matrix=# \connect synapse
You are now connected to database "synapse" as user "matrix".
synapse=# SELECT COUNT(*) FROM users;
 count
-------
     0
(1 row)

```

6. Took a quick backup of the current messed up database in case I need to do additional analysis.

7. Restored database from previous manual backup to get back up and running.

**Comment by spantaleev** [comment]
Perhaps you've been on an old version of the playbook and haven't upgraded properly?

See [this changelog entry](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#2021-01-22)

**Comment by brookwarren** [comment]
Does it take more than a git pull to upgrade it properly? I've only been doing git pulls on this to update it to new components and bring synapse et al versions up to date. The initial download of the playbook was last month.

**Comment by brookwarren** [comment]
That is the page I followed to explain how to keep the playbook updated and I refresh the changelog to check changes every day. I haven't had to adjust anything to avoid any breaking changes yet.
