### ISSUE TITLE
matrix-registration fails on token creation

### ISSUE THREAD

**Issue by squiddmann** [spantaleev/matrix-docker-ansible-deploy#1045]
I get the following error after trying to run the following command:
/usr/local/bin/ansible-playbook -i inventory/hosts setup.yml --tags=generate-matrix-registration-token --extra-vars="one_time=yes ex_date=2021-12-31" --ask-pass --ask-become-pass

skipping: [matrix.example.com]

TASK [matrix-registration : Call matrix-registration token creation API] ***********************************************************************************************
fatal: [matrix.example.com]: FAILED! => changed=false 
  cache_control: no-cache
  connection: close
  content_type: text/html
  elapsed: 0
  msg: 'Status code was 503 and not [200]: HTTP Error 503: Service Unavailable'
  redirected: false
  status: 503
  url: https://matrix.example.com/matrix-registration/token

**Comment by aaronraimist** [comment]
is matrix-registration running?

**Comment by squiddmann** [comment]
Yes, matrix-registration is running. 
https://matrix.example.com/matrix-registration/register appears to be functional from the public ip.

docker ps shows
61ecf55e2ec   zeratax/matrix-registration:v0.7.2   "matrix-registration…"   38 minutes ago   Up 38 minutes             5000/tcp                                                                                                                                                                                                                                  matrix-registration

**Comment by squiddmann** [comment]
There was an issue with my DNS settings. The local resolver wasn't forwarding matrix.example.com to the correct address.
Thanks for your help, aaronraimist.
