### ISSUE TITLE
python-docker

### ISSUE THREAD

**Issue by sando1234** [spantaleev/matrix-docker-ansible-deploy#1056]
Hey, I have problems with installing python-docker. 

Here is the error:

TASK [matrix-base : Ensure Docker is installed] *******************************************************************
fatal: [HOSTNAME]: FAILED! => changed=false
  msg: No package matching 'python-docker' is available

PLAY RECAP ********************************************************************************************************
HOSTNAME      : ok=8    changed=0    unreachable=0    failed=1

when i try it i can only install phython3-docker

**Comment by spantaleev** [comment]
Try adding `ansible_python_interpreter=/usr/bin/python3` to your server line in `inventory/hosts`.

That file already has information about the problem: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/e4dd933cf0f48a8722a43239b07a9335c85c4f14/examples/hosts#L14-L16
