### ISSUE TITLE
Fix tls_hostname deprecation warning

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#1060]
https://matrix.to/#/!PukFFdIcHgtaaHZflT:devture.com/$1621301900156624BMssm:matrix.org?via=matrix.org&via=maunium.net&via=tchncs.de

**Comment by spantaleev** [comment]
This is the error in question.

> TASK [matrix-base : Ensure Matrix network is created in Docker] **********************************************************************************************************************************
> [DEPRECATION WARNING]: The default value "localhost" for tls_hostname is deprecated and will be removed in community.docker 2.0.0. From then on, docker_host will be used to compute 
> tls_hostname. If you want to keep using "localhost", please set that value explicitly. This feature will be removed from community.docker in version 2.0.0. Deprecation warnings can be disabled 
> by setting deprecation_warnings=False in ansible.cfg.

Not sure if we should do anything about this.

We're not passing `tls_hostname` explicitly. Looks like this module will start defaulting to `docker_host`, [which appears](https://docs.ansible.com/ansible/latest/scenario_guides/guide_docker.html#parameters) to default to `unix://var/run/docker.sock`. Such a new default value will probably also work for us.

**Comment by aaronraimist** [comment]
Perhaps we could either set it explicitly to `unix://var/run/docker.sock` or `localhost` at least temporarily until that version is released

**Comment by spantaleev** [comment]
`docker_host: unix://var/run/docker.sock` doesn't help.

`tls_hostname: unix://var/run/docker.sock` does.

Still, it's somewhat silly having to specify `tls_hostname`  while `tls` has a default value of `false`. We don't use TLS, supposedly.  This seems to be an Ansible (collection) bug, which appears to have already been fixed here: https://github.com/ansible-collections/community.docker/pull/143

I guess we need to wait a while and the deprecation message will disappear.
