### ISSUE TITLE
Service Restart Timeout too short

### ISSUE THREAD

**Issue by wol-win** [spantaleev/matrix-docker-ansible-deploy#1062]
In some cases, starting the Matrix homeserver via the ansible-playbook, results in a start-up failure message of a service although the service is properly running seconds later. This sometimes happens with the nginx reverse proxy. Perhaps it is related to the bit weak VPS server. 

Nonetheless, changing cautiously the timeout value in `roles/matrix-common-after/tasks/start.yaml` from 15s to 20s, this failure can be avoided.

It is suggested to expose the timeout value as a variable, so that the default value of 15s can be overwritten in the site specific vars.yaml file.

**Comment by spantaleev** [comment]
I've finally taken the time to make this configurable.

You can now use something like `matrix_common_after_systemd_service_start_wait_for_timeout_seconds: 20` in your `vars.yml` file.

Make sure to read the comment about this variable in [`roles/matrix-common-after/defaults/main.yml`](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-common-after/defaults/main.yml) for picking an appropriate value.
