### ISSUE TITLE
Heisenbridge can't connect to TLS servers

### ISSUE THREAD

**Issue by jgoerzen** [spantaleev/matrix-docker-ansible-deploy#1069]
With Heisenbridge, after adding a server with --tls and attempting to connect, I get:

```
Failed to connect: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
```

The server in question has a proper TLS cert from Let's Encrypt that verifies fine in Firefox.  Maybe the CA certificates aren't installed in the Docker instance for Heisenbridge?  (just speculation)

**Comment by spantaleev** [comment]
Ping @hifi
