### ISSUE TITLE
Fix self building exim on Ansible < 2.8 (or bump min version to 2.8)

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#1070]
```
TASK [matrix-mailer : Ensure exim-relay Docker image is built] I get this error: Unsupported parameters for (docker_image) module: build, force_source, source Supported parameters include: ...
```

https://github.com/spantaleev/matrix-docker-ansible-deploy/blame/1fb54a37cba126235b1688bb5e96226a65b4fe80/roles/matrix-mailer/tasks/setup_mailer.yml#L35

Presumably it needs to be modified to be like the lines below `source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"`

**Comment by spantaleev** [comment]
Thanks for reporting this! Fixed for `matrix-mailer` and a bunch of other roles.
