### ISSUE TITLE
Coturn fails to build for arm32 (Raspberry Pi 4)

### ISSUE THREAD

**Issue by whowantsmybigdata** [spantaleev/matrix-docker-ansible-deploy#1072]
I git pulled and set up again on my Raspberry Pi 4, so arm32, but it wont build coturn anymore with 

<details><summary>this error:</summary>
<code>msg: 'Error building localhost/coturn/coturn - code: 2, message: The command ''/bin/sh -c apk update  && apk add --no-cache         autoconf ca-certificates coreutils g++ git libtool make  && update-ca-certificates'' returned a non-zero code: 2, logs: [u''Step 1/29 : ARG alpine_ver=3.13'', u''\n'', u''Step 2/29 : FROM alpine:${alpine_ver} AS dist-coturn'', u''\n'', u'' ---> b6342193e7c0\n'', u''Step 3/29 : RUN apk update  && apk add --no-cache         autoconf ca-certificates coreutils g++ git libtool make  && update-ca-certificates'', u''\n'', u'' ---> Running in 9716ec9fee9c\n'', u''fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz\n'', u''\x1b[91mERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)\nWARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory\n\x1b[0m'', u''fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz\n'', u''\x1b[91mERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community:
    temporary error (try again later)\nWARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory\n\x1b[0m'', u''2 errors; 14 distinct packages available\n'', u''Removing intermediate container 9716ec9fee9c\n'']'</code>
</details>

Pinging the error-link https://dl-cdn.alpinelinux.org/alpine/v3.13/community didnt work but I did a `wget` (from the same machine where the playbook is running) and it works...
I also tried to setup without coturn and everything else works as normal.

Thanks in advance for any clues!

**Comment by Toorero** [comment]
I am affected on a Raspberry Pi 4 myself too.

**Comment by whowantsmybigdata** [comment]
I dont get it as in the "main" directory there was also no coturn before this upgrade and in the "community" directory there was and still is one when opened through a browser

**Comment by whowantsmybigdata** [comment]
@Toorero do you managed to build it in the meantime? or do you know exactly with which commit this was messed up? i cant find it

**Comment by Toorero** [comment]
I'm sorry but I basically don't know anything about Ansible other then the Wikipedia page. I just wanted to say that I am affected as well.

**Comment by Toorero** [comment]
https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-816603722

**Comment by Toorero** [comment]
This resolved the issue completely also with respect to exim and other alpine based docker images so far.

**Comment by whowantsmybigdata** [comment]
Thanks a ton for the link! Upgrading "libseccomb2" manually to 2.5.1-1 solved the issue for me!
