### ISSUE TITLE
Use jemalloc

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#11]
> We’ve also discovered that jemalloc works *very* well at improving RAM usage on Python 2 under Linux (we haven’t tried it on Python 3 yet) by providing a more fragmentation-resistent malloc implementation; if you are having problems with your Synapse RAM spiking up we recommend giving it a go.  All of the Matrix.org server is using it now.

from https://matrix.org/blog/2018/09/15/this-week-in-matrix-2018-09-14/

**Comment by spantaleev** [comment]
This is probably something that needs to be done inside the Matrix Synapse Docker image?

Which means we:

- either need to build our own image on top of the official one (sounds like a bad idea)

- or something that the matrix.org folks might want to do by default to the official image (we should probably open an issue at the [Synapse repository](https://github.com/matrix-org/synapse)).

**Comment by spantaleev** [comment]
I'll close this, as it's not really an issue for us.

If the Synapse team (or some other party we trust) starts offering jemalloc-enabled Synapse Docker images, we can certainly consider switching to them.

Building our own images seems out of scope and not necessary - Synapse works well enough for most people even without jemalloc.
