### ISSUE TITLE
breaking change postgres broke postgres

### ISSUE THREAD

**Issue by dreamflasher** [spantaleev/matrix-docker-ansible-deploy#1129]
I followed this upgrade guide exactly step by step: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#breaking-change-postgres-changes-that-require-manual-intervention

And now I am stuck with: `stderr: 'psql: FATAL:  password authentication failed for user "matrix"'`

If I try to change the password now I can't even open psql anymore:
```
sudo /usr/local/bin/matrix-postgres-cli

> psql: FATAL:  password authentication failed for user "matrix"
```

What can I do to fix this?

**Comment by aaronraimist** [comment]
I suggest you join the support room either using a Matrix account on another server or using IRC https://github.com/spantaleev/matrix-docker-ansible-deploy#support

It's going to take a bit of question and answer to figure out what step you did wrong.

**Comment by dreamflasher** [comment]
Thank you for your help over in the support channel!

The solution was:

```
sudo docker exec -it matrix-postgres bash
psql
ALTER USER matrix WITH PASSWORD 'password';
```
