### ISSUE TITLE
SSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:SSL alert number 70

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1137]
Hope I'm not duplicating anything. But I followed the steps in the configuring an external webserver documentation and set Nginx as the only webserver running on the system. My configuration is as follows:

* Nginx runs on the base domain.
* `matrix_nginx_proxy_enabled` is set to `false` and `matrix_nginx_proxy_ssl_preset` is set to `modern`.
* Nginx configuration is [here](https://keybase.pub/ethindp/nginx.tar).

I'm getting error 502 when using this config and I'm not sure why. But the title of this issue is the SSL error it gives me when attempting the TLS handshake.

**Comment by spantaleev** [comment]
What's your nginx version? Do you use some additional nginx configuration besides the one generated by the playbook?

Which URL are you accessing when you get that error? Does the base domain work? Does the `matrix.` domain work?

**Comment by ethindp** [comment]
I am using nginx 1.21.0.
The base domain does work (though I have no files for it to show so it
gives me a 404).
I am using the additional configuration that I linked to in my
original comment to secure the server and to ensure it functions as a
capable proxy to the subdomains.
The matrix domain does also work. Attempting to go to
https://matrix.the-gdn.net/.well-known/matrix/server yields JSON as it
should.
The URL I am attempting to access (and the one the playbook tries
accessing with self-check) is
https://the-gdn.net/.well-known/matrix/server. Replacing "server" with
"client" similarly yields a 502 (which internally is this error).

On 6/23/21, Slavi Pantaleev ***@***.***> wrote:
> What's your nginx version? Do you use some additional nginx configuration
> besides the one generated by the playbook?
>
> Which URL are you accessing when you get that error? Does the base domain
> work? Does the `matrix.` domain work?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1137#issuecomment-866633151


-- 
Signed,
Ethin D. Probst

**Comment by spantaleev** [comment]
I'd try removing `include    nginxconfig.io/proxy.conf;` from the `location /.well-known/matrix {` block. Perhaps whatever's in `proxy.conf` causes trouble.

If all else fails, you can use [another method for serving the well-known Matrix files](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md#installing-well-known-files-on-the-base-domains-server).

**Comment by ethindp** [comment]
The problem with that suggestion is the fact that I added proxy.conf
after this problem had started in hopes that that would fix it. But it
didn't. And I still don't know why because if the instructions that
you had put up on the wiki for configuring nginx as the master web
server works for other people, then there's something broken about my
setup. I'd go back to the "default" one, and start inserting stuff to
figure out what the problem is, but that might take a while.
Could it be the `ssl_trusted_certificate` setting that's breaking it?

**Comment by ethindp** [comment]
So I posted this to the Arch Linux forums over [here](https://bbs.archlinux.org/viewtopic.php?id=267461) but haven't gotten replies. I'm not sure what to try now. I'd love to get this working but I've no idea where to begin :-(

**Comment by ethindp** [comment]
I'm willing to give option 1 -- copying the files -- a go. Is there a way I can add custom tasks to run at the end of the playback? Something that's in -- e.g. -- `.gitignor` I can use as a hook mechanism?

**Comment by ethindp** [comment]
Resolved... I think.
