### ISSUE TITLE
Sending files in encrypted chats in Element Web broken by CSP

### ISSUE THREAD

**Issue by davidmehren** [spantaleev/matrix-docker-ansible-deploy#1154]
On two Element Web instances deployed using this playbook, PDF files sent into encrypted chats can't be opened.

To reproduce:
- Send a PDF file into an encrypted chat in Element Web
- Click the "decrypt" link below the file
- Instead of the file getting downloaded, a broken iframe replaces the link: 
![grafik](https://user-images.githubusercontent.com/5023650/124094624-3e791800-da59-11eb-82ea-ec2454a49315.png)
- In the browser console, this error appears: `Refused to frame 'https://element.domain.tld/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

This seems to be caused by https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/0217644b48d23b499e6590829e67348386cb9614, which added the header `Content-Security-Policy "frame-ancestors 'none'"`. The commit references https://github.com/vector-im/element-web#configuration-best-practices.

These instructions seem to be wrong (or at least incomplete), as evidenced by https://github.com/vector-im/element-web/issues/16774, where @turt2live writes
> Typically people will set this on all aspects of Element, which includes the usercontent.html page (which then breaks download links for encrypted media)

This seems to be exactly what happened here.

Ways forward are, afaics:
- Remove the CSP header
- Adjust the header to `frame-ancestors 'self'` which `@ewangilchrist:susflatnine.xyz` in the Matrix room found to be working

In any case, the Element people should probably be poked to document the CSP properly :smile:

**Comment by spantaleev** [comment]
Thanks for the detailed investigation and providing a way to reproduce the problem! :bow: 

I've also confirmed that `frame-ancestors 'self'` fixes the problem, so I've changed to that.
