### ISSUE TITLE
Coturn Docker self-build failing - Wrong version number.

### ISSUE THREAD

**Issue by Eagle-251** [spantaleev/matrix-docker-ansible-deploy#1158]
Self-building of the coturn image is failing on my arm64 test server:
```ansible
fatal: [matrix.fourminorules.xyz]: FAILED! => changed=false
  cmd: /usr/bin/git checkout --force docker/4.5.2-r2-r2
  msg: Failed to checkout docker/4.5.2-r2-r2
  rc: 1
  stderr: |-
    error: pathspec 'docker/4.5.2-r2-r2' did not match any file(s) known to git
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
It looks like this recent commit (04805f35a77e07dddbaf24679521650a07504c1b) may accidently be concatenating  the repo version `matrix_coturn_container_image_self_build_repo_version: "docker/{{ matrix_coturn_version }}-r2"` with the version `matrix_coturn_version: 4.5.2-r2` resulting in ansible trying to chekout `docker/4.5.2-r2-r2`.\

I will make a PR with a fix once I have had a chance to test. If anyone can beat me to it, please do!

**Comment by sakkiii** [comment]
@Eagle-251 thanx for reporting
