### ISSUE TITLE
How to use existing ssl certs?

### ISSUE THREAD

**Issue by r1bnc** [spantaleev/matrix-docker-ansible-deploy#1161]
I already have lets encrypt ssl cert, how do I disable it from being created in ansible. Also, docker is already installed and the script crashes because of the existence of `/etc/apt/sources/docker.list`. But now, the important thing is to disabled lets encrypt ssl creation since I already have it. It's not in the docs iirc.

TIA

**Comment by aaronraimist** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ssl-certificates.md

**Comment by r1bnc** [comment]
Thank you.
