### ISSUE TITLE
Possible to support space hierarchies?

### ISSUE THREAD

**Issue by seanfarley** [spantaleev/matrix-docker-ansible-deploy#1165]
I don't know if this is a setting I can enable or if this is a limitation in synapse; opening this to hopefully find a solution :-)

**Comment by aaronraimist** [comment]
If it isn’t working for you then you are likely on an old commit of the playbook. https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md

**Comment by seanfarley** [comment]
It would seem that it changed in the last month! Thanks! Sorry for the noise!
