### ISSUE TITLE
matrix_postgres_connection_password not mentioned in the configuration

### ISSUE THREAD

**Issue by JokerGermany** [spantaleev/matrix-docker-ansible-deploy#1178]
I wrote it in #matrix-docker-ansible-deploy:devture.com , but perhaps a ticket for tracking this would be good.

I don't think this was mentioned in the configuration. (To be honest i thought it would use sqlite)

But when executing the script i get:
`msg: 'The playbook no longer has a default Postgres password defined in the matrix_postgres_connection_password variable, among lots of other Postgres changes. You need to perform multiple manual steps to resolve this. See our changelog for more details: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#breaking-change-postgres-changes-that-require-manual-intervention'`

**Comment by JokerGermany** [comment]
Nevermind, it was not mentioned in the Configuration, but it was mentioned in the vars.yml

**Comment by aaronraimist** [comment]
> To be honest i thought it would use sqlite

matrix-docker-ansible-deploy tries to have sane defaults and using SQLite with Synapse is not a good idea
