### ISSUE TITLE
Anyway to use Cloudflare Proxy? 

### ISSUE THREAD

**Issue by 0-MegaMind-0** [spantaleev/matrix-docker-ansible-deploy#1187]
I was trying this and like the documentation says enabling cloudflare proxy fail fetching ssl certificates `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`.
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md

Is there any workarounds we can try right now to enable this. I wouldn't like to expose my server IP hosting matrix.

I use my own nginx webserver following this guide https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md

**Comment by sakkiii** [comment]
I don't recommend that you enable the Cloudflare proxy unless you have specific constraints for your project. If your domain does require the Cloudflare's proxy to be turned on by default, only one requirement is needed:

- The domain must allow HTTP requests (without HTTPS) to the path /.well-known/*.

You need to explore the following configuration in the Cloudflare dashboard:

- [Page Rules](https://support.cloudflare.com/hc/en-us/articles/218411427-Understanding-and-Configuring-Cloudflare-Page-Rules-Page-Rules-Tutorial-): You can disable HTTPS for the path /.well-known/*.
- [Always use HTTPS](https://support.cloudflare.com/hc/en-us/articles/204144518-SSL-FAQ) — This configuration is under the "SSL/TLS" tab and it may affect your page rules.

**Comment by 0-MegaMind-0** [comment]
Thanks i enabled the page rules. But I still kept getting SSL errors. Disabled Letsencrypt cert and kept self signed on the host machine and it seemed to work fine. Not yet sure of the exact problem but at least its working fine now Thanks:)
