### ISSUE TITLE
Reminder Bot - Bad hmac value error

### ISSUE THREAD

**Issue by meyerrj** [spantaleev/matrix-docker-ansible-deploy#1191]
With the recent upgrade of Synapse, the matrix-reminder-bot is no longer working.

```
Jul 19 12:33:17 serverhostname matrix-synapse[49054]: 2021-07-19 17:33:17,676 - shared_secret_authenticator - 41 - INFO - POST-217 - Authenticating user: @bot.matrix-reminders:serverhostname
Jul 19 12:33:17 serverhostname matrix-synapse[49054]: 2021-07-19 17:33:17,677 - shared_secret_authenticator - 54 - INFO - POST-217 - Bad hmac value for user: @bot.matrix-reminders:serverhostname
```

I've tried resetting the password for the bot, but the same error is produced.

**Comment by meyerrj** [comment]
Update, it's related to this issue:  https://github.com/anoadragon453/matrix-reminder-bot/issues/86

There's a fix in v0.2.1. Setting the following in my configuration fixed it:

```
matrix_bot_matrix_reminder_bot_version: release-v0.2.1
```

A quick update here should fix it for all.

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/70cb27138c78ad1ee9fb49323d7b160c5e5bbe7b/roles/matrix-bot-matrix-reminder-bot/defaults/main.yml#L5

**Comment by aaronraimist** [comment]
@meyerrj are you going to submit a PR to update it for everyone?

**Comment by meyerrj** [comment]
I can try to get one submitted later tonight or sometime tomorrow.

**Comment by spantaleev** [comment]
Thanks for fixing this in #1194!
