### ISSUE TITLE
Cannot create a new user on the Matrix server (Error: No such container: matrix-synapse) 

### ISSUE THREAD

**Issue by anadahz** [spantaleev/matrix-docker-ansible-deploy#12]
I followed the install [documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/README.md) and successfully run the role with the tags `setup-all` and `start` by issuing the following commands:
```
ansible-playbook -v -i inventory/hosts setup.yml --tags=setup-all
ansible-playbook -v -i inventory/hosts setup.yml --tags=start
```
However when I run the role with the `register-user` tag I get the error : `Error: No such container: matrix-synapse`.

Following verbose output:
```
ansible-playbook -vvvv -i inventory/hosts setup.yml --extra-vars='username=user password=password admin=yes' --tags=register-user
```
                                                                             
```
TASK [matrix-server : Register user] **********************************************************************************************************************************
task path: /home/user/matrix-docker-ansible-deploy/roles/matrix-server/tasks/register_user.yml:23
fatal: [matrix.domain.tld]: FAILED! => {                                            
    "changed": true,                                                                
    "cmd": "/usr/local/bin/matrix-synapse-register-user user password 1",           
    "delta": "0:00:00.103034",                                                      
    "end": "2018-10-13 13:24:39.089012",                                            
    "invocation": {                                                                 
        "module_args": {                                                            
            "_raw_params": "/usr/local/bin/matrix-synapse-register-user user password 1", 
            "_uses_shell": true,                                                    
            "argv": null,                                                           
            "chdir": null,                                                          
            "creates": null,                                                        
            "executable": null,                                                     
            "removes": null,                                                        
            "stdin": null,                                                          
            "warn": true                                                            
        }                                                                           
    },                                                                              
    "msg": "non-zero return code",                                                  
    "rc": 1,                                                                        
    "start": "2018-10-13 13:24:38.985978",                                          
    "stderr": "Error: No such container: matrix-synapse",                           
    "stderr_lines": [                                                               
        "Error: No such container: matrix-synapse"                                  
    ],                                                                              
    "stdout": "",                                                                   
    "stdout_lines": []                                                              
}                                                                                   
                                                                                    
PLAY RECAP **********************************************************************************************************************************
matrix.domain.tld        : ok=2    changed=0    unreachable=0    failed=1           
```

Any ideas to help debug and solve this issue are greatly appreciated.

**Comment by spantaleev** [comment]
Seems like Synapse is not running.

You can try to see why by running:

```bash
systemctl status matrix-synapse
```

or checking the logs using:

```bash
journalctl -u matrix-synapse
```

**Comment by anadahz** [comment]
Thanks for your response @spantaleev, the logs mention the same the `matrix-synapse` container doesn't exist:
```
systemd[1]: Started Matrix Synapse server.
docker[122]: /usr/bin/docker: Error response from daemon: network matrix not found.
systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=125/n/a
docker[169]: Error response from daemon: Cannot kill container: matrix-synapse: No such container: matrix-synapse
docker[197]: Error: No such container: matrix-synapse
```

**Comment by spantaleev** [comment]
Looks like the container won't start because the `matrix` Docker network doesn't exist.
All containers set up by this playbook are meant to utilize that `matrix` network.

The playbook sets up this network from a task in `setup_main.yaml`. It's strange that it doesn't exist for you. I've just set up a brand new server using the playbook to test it out and the network got created as expected.

Can you check the output of `docker network ls`?

You can also safely rerun the playbook (with `--setup-all`) at any time. If the `matrix` Docker network got deleted for some reason, re-running the playbook should bring it back.

By the way, creating the network manually using `docker network create --driver=bridge matrix` should be possible too, but the fact that the playbook didn't create it may indicate some deeper problems.

Which distribution are you using on the server? Which Ansible version are you using to run the playbook with?

**Comment by anadahz** [comment]
> Can you check the output of docker network ls?

```
# docker network ls |grep -i matrix
57b639186bf6        matrix-test_default                 bridge              local
```
> You can also safely rerun the playbook (with --setup-all) at any time. If the matrix Docker network got deleted for some reason, re-running the playbook should bring it back.

I still get the same issue upon re-running the playbook as in https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/12#issue-369803451. 
It seems that the playbook does not create the bridge but shouldn't be throwing an error or a warning when this happens?

> By the way, creating the network manually using docker network create --driver=bridge matrix should be possible too, but the fact that the playbook didn't create it may indicate some deeper problems.

Manually creating the network (with `docker network create --driver=bridge matrix`) and re-running the playbook (with `--setup-all` and `start`) seems to throw no errors and creates the user. However as you mentioned the role should build the (role's default) network `matrix`.

> Which distribution are you using on the server? 

`# cat /etc/*release`
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
> Which Ansible version are you using to run the playbook with?

`# ansible --version`
```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Sep 21 2018, 23:26:48) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

**Comment by spantaleev** [comment]
Does starting the services work after manually creating the Docker network?

**Comment by anadahz** [comment]
>I'm guessing the docker_network Ansible module is not working correctly on its Ansible 2.6.5, which would be the reason why the network is not being created.

I don't think that is related to the version of Ansible, it seems that I have triggered this [bug](https://github.com/ansible/ansible/issues/32926).

> Which distribution are you running Ansible on? 

Fedora 28

> Is 2.6.5 the latest Ansible version there?

True

**Comment by spantaleev** [comment]
Glad you found it!

Since you've created the network manually, it shouldn't cause you any problems running this playbook anymore.

Of course, the actual problem still remains.

I wonder if we can implement some workaround to make this playbook reliable, even though the Docker module for Ansible (or the "driver" it's based on) is obviously buggy. It seems like the Docker module for Ansible is based on one of 2 Python packages - either `docker-py` or `docker`. I'm not sure if both are affected or if the problem got fixed subsequently. ansible/ansible#32926 doesn't say much.

Maybe we should add one more hacky task like this, below the `docker_network` task:

```yaml
- name: Reaaaaally ensure Matrix network is created in Docker
  shell:
    cmd: "docker network create --driver=bridge {{ matrix_docker_network }}"
  ignore_errors: true
  changed_when: false
```

**Comment by anadahz** [comment]
I tested this [patch](https://github.com/spantaleev/matrix-docker-ansible-deploy/compare/master...anadahz:fix/upstream_32926) and seems to be working OK.

@spantaleev what do you think about this workaround?

**Comment by spantaleev** [comment]
Your patch is nice in that it works and demonstrates how to check for the problem happening, but:
- it defines some `get_docker_network` configuration variable in the main configuration file, which may be undesirable (it's not anything that needs to vary and could rather be defined inline)
- by doing the check and creation in a single step, Ansible will always report `changed` entries when running the playbook even though nothing changes sometimes. It's better to avoid that when possible

I've built on top of your patch however, and have done something very similar in 36658addcd688.

Thank you for finding this problem and taking the time to get it reported and fixed! :+1:

**Comment by anadahz** [comment]
Great! @spantaleev thank you for the patch and this wonderful ansible role!
