### ISSUE TITLE
Cannot sign into Matrix instance on Android

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1200]
After creating a user and logging into element, and then logging back out again, element is refusing to allow me in. The method (matrix ID or username/password) doesn't change anything. Whenever I sign in, I get the (absolutely) useless error: "Sorry, an error occurred". This started happening after I signed out and has continued since, but the desktop client seems to work fine. Did I mess up somewhere?

**Comment by aaronraimist** [comment]
You can check your Synapse logs with `sudo journalctl -fu matrix-synapse` but if you can login to other clients like the desktop client then your server is probably fine. It sounds like an Element Android bug.

**Comment by ethindp** [comment]
Yeah, I think its a bug in Element. If this happens to anybody else, here's how you solve it:

1. Open settings and go to Storage.
2. Tap on "Other Apps" and select Element from the list.
3. Tap "Force Stop" to force the app to close -- this might not be necessary but is probably a good idea.
4. Tap "Clear Storage" to delete all app data. This will also clear the cache if any.
5. Open element and sign in again.
