### ISSUE TITLE
Locking down dimension.domain

### ISSUE THREAD

**Issue by 0-MegaMind-0** [spantaleev/matrix-docker-ansible-deploy#1206]
I've enabled dimension but looking at it, its not protected by any login.
So right now anyone can start using `dimension.domain/widgets/jitsi` as their video conferencing app without any protection.
Is there anyway to lockdown dimension so only ex: element / user with certain login / token can use it ?  or maybe just enable a basic nginx auth ?

**Comment by spantaleev** [comment]
Even if you lock down Dimension (or not install it in the first place), Jitsi would still be publicly accessible by default at `https://jitsi.DOMAIN`.

To add authentication support to Jitsi, follow our Jitsi docs: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md#optional-configure-jitsi-authentication-and-guests-mode

**Comment by 0-MegaMind-0** [comment]
Hmm I have not mapped the jitsi Domain or enabled it in matrix.-docker-ansible-deploy so thats not a real issue i'll look into jitsi docs.

**Comment by 0-MegaMind-0** [comment]
Nope enabled authentication. Disabled it and no matter what i do its still open in for anyone to access.
```
matrix_jitsi_enabled: false

matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: false

matrix_jitsi_jicofo_component_secret: ""
matrix_jitsi_jicofo_auth_password: ""
matrix_jitsi_jvb_auth_password: ""
matrix_jitsi_jibri_recorder_password: ""
matrix_jitsi_jibri_xmpp_password: ""
```

Not sure if LDAP Auth would fix it. The best solution i can think right now is to just return 422 when `dimension.domain/widgets/jitsi` is requested with a location block on nginx
