### ISSUE TITLE
usermod: group 'matrix' does not exist

### ISSUE THREAD

**Issue by NekoSpirits** [spantaleev/matrix-docker-ansible-deploy#1218]
I have been trying in vain to run this ansible playbook over the past few weeks, and each time I get stopped after running the "start" tag.

when running the start tag, I get 
`ok=27   changed=2    unreachable=0    failed=0    skipped=153  rescued=0    ignored=0`

Which I take to mean that everything is fine, so I try to run the "self-check" which returns

`ok=17   changed=0    unreachable=0    failed=1    skipped=112  rescued=0    ignored=1  `

the error message that gets spat out is
`fatal: [matrix.cenxui.com]: FAILED! => changed=false 
  msg: 'Failed checking Matrix Client API is up at 'matrix.cenxui.com' (checked endpoint: 'https://matrix.cenxui.com/_matrix/client/versions'). Is Synapse running? Is port 443 open in your firewall? Full error: {''redirected'': False, ''url'': ''https://matrix.cenxui.com/_matrix/client/versions'', ''status'': 502, ''server'': ''openresty'', ''date'': ''Sun, 08 Aug 2021 01:55:58 GMT'', ''content_type'': ''text/html'', ''content_length'': ''154'', ''connection'': ''close'', ''strict_transport_security'': ''max-age=63072000; preload'', ''elapsed'': 0, ''changed'': False, ''failed'': True, ''msg'': ''Status code was 502 and not [200]: HTTP Error 502: Bad Gateway''}'`

Which makes me think the services aren't being launched correctly.

my host_vars file has only the following changes
`matrix_ssl_retrieval_method: none

matrix_nginx_proxy_enabled: false

matrix_mautrix_whatsapp_enabled: true

matrix_mautrix_facebook_enabled: true
matrix_mx_puppet_skype_enabled: true

matrix_mx_puppet_discord_enabled: true`

and my inventory/hosts has 'matrix.cenxui.com ansible_connection=local ansible_ssh_user=root'

I have Nginx reverse proxy manager pointing at the server. However, I believe that this is not contributing to the issue as it's reaching the server, but not running the processes.  

I am reaching out because I am about at my wits end with troubleshooting, and I believe that I have either missed something very obvious or have run into a bug with locally running ansible.

Edit: 
OS: Ubuntu 21.04

I cannot connect even via localhost, which is why I know the processes aren't running

**Comment by aaronraimist** [comment]
> Which makes me think the services aren't being launched correctly.

That's not necessarily what that means. It very well could mean your reverse proxy is configured incorrectly or your DNS is wrong. You can tell if the services are running using systemctl. Like `sudo systemctl status matrix-synapse`.

**Comment by NekoSpirits** [comment]
Ugh, I feel like an idiot, yeah the service is running which is good, so you are right; my reverse proxy must be set up incorrectly. This still doesn't explain why I am unable to connect via localhost? Is that just a quirk of running it through ansible?

**Comment by aaronraimist** [comment]
>Does running without the integrated Nginx proxy change the ports in some way?

Yes. The ports are only exposed on localhost by default when Nginx is disabled https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/421f85defa089cee619ac779d6f558f3b754cf86/group_vars/matrix_servers#L1633

**Comment by aaronraimist** [comment]
> Edit Edit: I am having a bad github day lmao, the original thing I meant to ask was about the adding of the external Nginx user to the "matrix" group, is that a necessary step? that user, nor group exists inside the Nginx Reverse Proxy Manager installation, do I need to learn how to do grouping in order for the reverse proxy to work?

I don't know anything about nginx reverse proxy manager but if it is running on a different server then it doesn't need to be added to any group.

**Comment by NekoSpirits** [comment]
>  if it is running on a different server then it doesn't need to be added to any group.

Thats strange, here in the [documentation for preperation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#preparation), it specifically calls out that 

> > No matter which external webserver you decide to go with, you'll need to:
> 
> Make sure your web server user (something like http, apache, www-data, nginx) is part of the matrix group. You should run something like this: usermod -a -G matrix nginx. This allows your webserver user to access files owned by the matrix group. When using an external nginx webserver, this allows it to read configuration files from /matrix/nginx-proxy/conf.d. When using another server, it would make other files, such as /matrix/static-files/.well-known, accessible to it.

Am I misunderstanding or is this documentation wrong?

**Comment by aaronraimist** [comment]
That documentation is assuming you will run the reverse proxy on the same server as the services that the playbook installs

**Comment by NekoSpirits** [comment]
Okay, I think I understand, thank you very much for your time! just need to troubleshoot proxy shenannigans.

**Comment by NekoSpirits** [comment]
If anyone else runs across this and can't connect outside the local device, I had to manually change the ip's in group_vars/matrix_servers/setup.yml to the physical address of the server
