### ISSUE TITLE
self-signed-certificates fail the self-check because of SSL Validation

### ISSUE THREAD

**Issue by yoitcc** [spantaleev/matrix-docker-ansible-deploy#124]
Hello, 

I am using/installing this playbook in a VirtualBox VM, I did enable:
`matrix_ssl_retrieval_method: self-signed `

After that, starting:
`ansible-playbook -i inventory/hosts setup.yml --tags=self-check`

produces errors at every task that uses the ansible _uri_ module of 

> Full error: {'msg': 'Failed to validate the SSL certificate for domain.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056).', 'failed': True, 'changed': False}"}

My solution began with adding "validate_certs: false" to all uri executions in the self-test tasks and endet with putting
```
module_defaults:
  uri:
    validate_certs: false
```

in my main setup.yml (the one I start this whole playbook with )
After that, all checks were successful.

I suggest adding this info at least to the Documentation about using self-signed certificates, it will get people running a lot faster ;)

[Please excuse my common github-errors, I just created an account now to open this issue, have to look into contribution directly ;)]

**Comment by spantaleev** [comment]
Hello and thank you for taking the time to bring my attention to this problem!

I've made some improvements in 73af8f7bbb5c22a2.
If `matrix_ssl_retrieval_method: self-signed` is used, the playbook will now self-adjust and will no longer validate certificates.

So you should get all-green when running `--tags=self-check`, without having to do any custom modifications.
