### ISSUE TITLE
appservice-irc role references non-existant dockerhub tag

### ISSUE THREAD

**Issue by SierraKiloBravo** [spantaleev/matrix-docker-ansible-deploy#1249]
When running the setup-all ansible tag with appservice-irc configured, the playbook will attempt to pull a image named docker.io/matrixdotorg/matrix-appservice-irc:release-v0.30.0, which is nonexistant. docker.io/matrixdotorg/matrix-appservice-irc:release-0.30.0 does exist, however.

**Comment by spantaleev** [comment]
Fixed already. See #1248

**Comment by SierraKiloBravo** [comment]
Haha, what a coincidence. Thanks!
