### ISSUE TITLE
Dimension service not working after install

### ISSUE THREAD

**Issue by briankendall** [spantaleev/matrix-docker-ansible-deploy#1267]
I just got Matrix up and running on my home server, and everything seems to be working great, with one exception: I can't get Dimension to work.

If I log into https://element.mydomain.com as my admin user, and then access https://dimension.mydomain.com/riot-app/admin, the basic page appears but no content loads. If I look at my Javascript console at the top I see this error:

    zone.js:3372 GET https://dimension.mydomain.com/api/v1/dimension/admin/version?scalar_token=null 401 (Unauthorized)

If I check the dimension logs, I see the following when I try to access its admin page:

    Sep 06 02:38:49 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:49.337 +00:00 info [Webserver] Incoming request: GET /riot-app/admin
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.926 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/version?scalar_token=redacted
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.929 +00:00 warn [MatrixSecurity] Request used old scalar_token auth - this will be removed in a future version
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.942 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/config?scalar_token=redacted
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.944 +00:00 warn [MatrixSecurity] Request used old scalar_token auth - this will be removed in a future version
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.969 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT "UserScalarToken"."id", "UserScalarToken"."userId", "UserScalarToken"."scalarToken", "UserScalarToken"."isDimensionToken", "UserScalarToken"."upstreamId", "user"."userId" AS "user.userId", "user"."isSelfBot" AS "user.isSelfBot" FROM "dimension_scalar_tokens" AS "UserScalarToken" LEFT OUTER JOIN "dimension_users" AS "user" ON "UserScalarToken"."userId" = "user"."userId" WHERE "UserScalarToken"."isDimensionToken" = true AND "UserScalarToken"."scalarToken" = 'null';
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.980 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT "UserScalarToken"."id", "UserScalarToken"."userId", "UserScalarToken"."scalarToken", "UserScalarToken"."isDimensionToken", "UserScalarToken"."upstreamId", "user"."userId" AS "user.userId", "user"."isSelfBot" AS "user.isSelfBot" FROM "dimension_scalar_tokens" AS "UserScalarToken" LEFT OUTER JOIN "dimension_users" AS "user" ON "UserScalarToken"."userId" = "user"."userId" WHERE "UserScalarToken"."isDimensionToken" = true AND "UserScalarToken"."scalarToken" = 'null';
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:50.996 +00:00 error [ScalarService] Invalid token
    Sep 06 02:38:50 MyServer matrix-dimension[26363]: Error: Invalid token
    Sep 06 02:38:50 MyServer matrix-dimension[26363]:     at Function.<anonymous> (/home/node/matrix-dimension/build/app/db/ScalarStore.js:49:23)
    Sep 06 02:38:50 MyServer matrix-dimension[26363]:     at Generator.next (<anonymous>)
    Sep 06 02:38:50 MyServer matrix-dimension[26363]:     at fulfilled (/home/node/matrix-dimension/build/app/db/ScalarStore.js:4:58)
    Sep 06 02:38:51 MyServer matrix-dimension[26363]: Sep-6-2021 06:38:51.023 +00:00 error [ScalarService] Invalid token
    Sep 06 02:38:51 MyServer matrix-dimension[26363]: Error: Invalid token
    Sep 06 02:38:51 MyServer matrix-dimension[26363]:     at Function.<anonymous> (/home/node/matrix-dimension/build/app/db/ScalarStore.js:49:23)
    Sep 06 02:38:51 MyServer matrix-dimension[26363]:     at Generator.next (<anonymous>)
    Sep 06 02:38:51 MyServer matrix-dimension[26363]:     at fulfilled (/home/node/matrix-dimension/build/app/db/ScalarStore.js:4:58)

I followed all of the steps correctly in the "Setting up Dimension" doc page as near as I can tell, and I've confirmed that my values for `matrix_dimension_admins` and `matrix_dimension_access_token` are correct in vars.yml.

My server passes both the services self check and the federation tester.

Any idea what's wrong?

**Comment by briankendall** [comment]
Someone here mentioned they fixed a different issue with dimension by using matrix-postgres-cli to drop the matrix-dimension table and then use the ansible script to recreate it. I tried that, and afterwards the matrix-dimension service would fail and get into a boot loop. Everything else was working, though.

Since this is a new installation with nothing in it so far, I figured I'd just go ahead and uninstalling everything using `matrix-remove-all` and reinstalling to see if that would at least get me back to where I was before, if not get me passed the original error I had. Unfortunately, the exact same error that's getting matrix-dimension in a boot loop is still there, even after uninstalling!

I am now quite stuck and don't know how to get dimension working. Help!

Here's what gets printed if I execute `journalctl -fu matrix-dimension.service`:

    Sep 07 20:27:31 MyServer systemd[1]: Starting Matrix Dimension...
    Sep 07 20:27:31 MyServer systemd[1]: Started Matrix Dimension.
    Sep 07 20:27:31 MyServer matrix-dimension[30983]: Starting matrix-dimension
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: version Error: Cannot find module '../package.json'
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Require stack:
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: - /home/node/matrix-dimension/build/app/version.js
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: - /home/node/matrix-dimension/build/app/index.js
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.require (internal/modules/cjs/loader.js:961:19)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at require (internal/modules/cjs/helpers.js:92:18)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/version.js:8:21)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.load (internal/modules/cjs/loader.js:937:32)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.require (internal/modules/cjs/loader.js:961:19)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at require (internal/modules/cjs/helpers.js:92:18)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/index.js:8:19)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.load (internal/modules/cjs/loader.js:937:32)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at internal/main/run_main_module.js:17:47 {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   code: 'MODULE_NOT_FOUND',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   requireStack: [
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     '/home/node/matrix-dimension/build/app/version.js',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     '/home/node/matrix-dimension/build/app/index.js'
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   ]
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: }
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: /bin/sh: git: not found
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: version Error: Command failed: git rev-parse --short HEAD
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: /bin/sh: git: not found
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at checkExecSyncError (child_process.js:760:11)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.execSync (child_process.js:833:15)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/version.js:16:10)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.load (internal/modules/cjs/loader.js:937:32)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.require (internal/modules/cjs/loader.js:961:19)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at require (internal/modules/cjs/helpers.js:92:18)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/index.js:8:19)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Module.load (internal/modules/cjs/loader.js:937:32)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at internal/main/run_main_module.js:17:47 {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   status: 127,
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   signal: null,
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   output: [
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     null,
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     <Buffer >,
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     <Buffer 2f 62 69 6e 2f 73 68 3a 20 67 69 74 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   ],
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   pid: 14,
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   stdout: <Buffer >,
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 67 69 74 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: }
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Sep-8-2021 00:27:33.294 +00:00 info [index] Starting dimension Unknown
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Sep-8-2021 00:27:33.295 +00:00 info [DimensionStore] Updating schema...
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: (node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: (Use `node --trace-warnings ...` to show where the warning was created)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Sep-8-2021 00:27:33.460 +00:00 verbose [DimensionStore [SQL]] Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY ("name"));
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Sep-8-2021 00:27:33.469 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Sep-8-2021 00:27:33.485 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: { event: 'migrating', name: '20210809223100-ChangeAvatarUrl.js' }
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: Sep-8-2021 00:27:33.496 +00:00 verbose [DimensionStore [SQL]] Executing (default): UPDATE dimension_widgets SET avatarUrl = REPLACE(avatarUrl, '/img/', '/assets/img/')
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: MigrationError: Migration 20210809223100-ChangeAvatarUrl.js (up) failed: Original error: column "avatarurl" does not exist
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at /home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:168:27
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     at async Umzug.runCommand (/home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:124:20) {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   jse_shortmsg: 'Migration 20210809223100-ChangeAvatarUrl.js (up) failed',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   jse_cause: VError: Original error: column "avatarurl" does not exist
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       at Function.wrap (/home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:21:20)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       at new MigrationError (/home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:32:32)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       at /home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:168:27
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       at async Umzug.runCommand (/home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:124:20) {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     jse_shortmsg: 'Original error',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     jse_cause: DatabaseError [SequelizeDatabaseError]: column "avatarurl" does not exist
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:         at Query.formatError (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:         at Query.run (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:         at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:         at async /home/node/matrix-dimension/node_modules/sequelize/lib/sequelize.js:619:16
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:         at async /home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:165:21
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:         at async Umzug.runCommand (/home/node/matrix-dimension/node_modules/umzug/lib/umzug.js:124:20) {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       parent: [DatabaseError],
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       original: [DatabaseError],
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       sql: "UPDATE dimension_widgets SET avatarUrl = REPLACE(avatarUrl, '/img/', '/assets/img/')",
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       parameters: undefined
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     },
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     jse_info: {}
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   },
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   jse_info: {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     direction: 'up',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     name: '20210809223100-ChangeAvatarUrl.js',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     path: '/home/node/matrix-dimension/build/app/db/migrations/20210809223100-ChangeAvatarUrl.js',
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     context: PostgresQueryInterface {
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       sequelize: [Sequelize],
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:       queryGenerator: [PostgresQueryGenerator]
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:     }
    Sep 07 20:27:33 MyServer matrix-dimension[30983]:   }
    Sep 07 20:27:33 MyServer matrix-dimension[30983]: }
    Sep 07 20:27:33 MyServer systemd[1]: matrix-dimension.service: Main process exited, code=exited, status=1/FAILURE
    Sep 07 20:27:33 MyServer systemd[1]: matrix-dimension.service: Failed with result 'exit-code'.

**Comment by spantaleev** [comment]
It's probably safer to:

- stop Dimension first (`systemctl stop matrix-dimension`)
- delete its data (`rm -rf /matrix/dimension`)
- drop its database (`DROP DATABASE matrix_dimension` via `/usr/local/bin/matrix-postgres-cli`)
- re-run the playbook (`.... --tags=setup-all,start`)

We're using the `:latest` container image of [turt2live/matrix-dimension](https://hub.docker.com/r/turt2live/matrix-dimension), which is a moving target. It may be that you're getting some buggy release this time around. Unfortunately, the Dimension team does not publish any static versions to would help us not use `:latest`.

Seems like a similar issue to yours has been reported upstream and fixed here: https://github.com/turt2live/matrix-dimension/issues/431

Perhaps if you re-run the playbook again, it would update you to a working version.

**Comment by briankendall** [comment]
@spantaleev Noted, will try that next time I need to reset and reinstall Dimension.

And yes, I discovered that same error and ended up pulling my own customized Docker container of Dimension that had the same fix in the issue you just linked to. Good to know that it's fixed.

It's distressing, however, to know that the Dimension repo will commit obviously untested code, and that updating it at any moment may cause it to fail! I wonder if we could convince them to at least have a "stable" tag.

**Comment by spantaleev** [comment]
> It's distressing, however, to know that the Dimension repo will commit obviously untested code, and that updating it at any moment may cause it to fail! I wonder if we could convince them to at least have a "stable" tag.

Opening an issue at their repository would be nice.

**Comment by briankendall** [comment]
> Opening an issue at their repository would be nice.

@spantaleev Feel free to give it a 👍:

https://github.com/turt2live/matrix-dimension/issues/432
