### ISSUE TITLE
Hope add an argument to resize shm_size

### ISSUE THREAD

**Issue by yswtrue** [spantaleev/matrix-docker-ansible-deploy#1268]
Sometime we will get this error
`Error running query: could not resize shared memory segment "/PostgreSQL.15877507" to 16777216 bytes: No space left on device`

Hope to add an argument to resize Postgres image shm size.
thanks.

**Comment by aaronraimist** [comment]
You can probably do this by adding something like

```
matrix_postgres_container_extra_arguments:
  - "--shm-size=256m"
```

Assuming this is the shm_size thing you are talking about https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container

**Comment by yswtrue** [comment]
thanks
