### ISSUE TITLE
Feature Request: Add matrix-puppet-slack

### ISSUE THREAD

**Issue by dreamflasher** [spantaleev/matrix-docker-ansible-deploy#127]
Please add https://github.com/matrix-hacks/matrix-puppet-slack 
Thank you!

**Comment by Cadair** [comment]
I have the start of a role for this. Keep meaning to work on integrating it.

**Comment by kingoftheconnors** [comment]
Yes please!

**Comment by spantaleev** [comment]
I've recently spent some time:
- moving bridges to their own roles (see `roles/matrix-bridge*`)
- making them not necessarily depend on Synapse (the `matrix-synapse` role)
- along with some other improvements related to uninstallation (see 3250df67658cfd9).

It's a great moment for adding another bridge role.

**Comment by eMPee584** [comment]
@Cadair : could you post what you have? and did you get it to work?

**Comment by spantaleev** [comment]
Now that appservice-slack has been integrated, is there any good reason to implement matrix-puppet-slack as an alternative?

**Comment by dreamflasher** [comment]
Thank you for adding appservice-slack, and generally thank you for your great work!
Unfortunately, appservice-slack doesn't support teams, which is a blocker for me. 
matrix-puppet-slack supports teams, and threads, and image content so it looks a lot more developed to me.

**Comment by Cadair** [comment]
appservice-slack supports threads, images, edits, reactions and a lot more stuff than puppet slack now.

The big difference is that with puppet slack you login using a personal access token, and only you can use the rooms it creates. This means that you can use puppet slack as a personal slack client where as appservice-slack is for running a multi-user bridge (i.e it doesn't support DMs).

**Comment by dreamflasher** [comment]
Where did you find that information? I was looking for it, but their github page is empty on the supported features.
According to https://matrix.org/bridges/ doesn't support teams – the whole idea for me would be to replace full slack teams, and yes including DMs. So no DMs is also a blocker. 

Looks to me they have different use-cases, so it would be good to have both.

**Comment by Cadair** [comment]
I know it has most of those features because I implemented a lot of them :laughing: 

As you point out the relative features of the two is mostly irrelevant, they have very different use cases.

**Comment by ptman** [comment]
#253

**Comment by ptman** [comment]
https://github.com/matrix-org/matrix-appservice-slack/releases/tag/1.0.0-rc1

**Comment by Cadair** [comment]
The matrix-appservice-slack release still requires you to add an app to the workspace  even for puppeting (currently) so there is still scope for the other puppeting slack bridges.

**Comment by ptman** [comment]
Right, so matrix-appservice-slack is not a complete solution. What about [mx-puppet-slack](https://github.com/Sorunome/mx-puppet-slack) then?

**Comment by dreamflasher** [comment]
@ptman They lack documentation and a feature overview. Do you have more details on that? I'd like to know if they support teams and private messages.

**Comment by ptman** [comment]
The author was very responsive on https://matrix.to/#/#mx-puppet-bridge:sorunome.de . I've only tried the slack bridge, and it seems I'm only in not very active slack workspaces, but channels and PMs seems to work.

**Comment by dreamflasher** [comment]
Thank you. I asked there and currently this bridge does not support teams/communities, thus not a solution, yet.

**Comment by GoliathLabs** [comment]
@spantaleev this can be closed I guess as we already have mx-puppet-slack as well as the appservice for slack

**Comment by dreamflasher** [comment]
@GoliathLabs not really, because none of them support teams/communities.

**Comment by Cadair** [comment]
> @GoliathLabs not really, because none of them support teams/communities.

That is a feature request for the bridge, not this playbook which installs them.

I think this can be closed. @spantaleev ?

**Comment by dreamflasher** [comment]
Not really. One bridge supports it, the other doesn't. This request is about adding the bridge that supports it.

**Comment by Cadair** [comment]
Oh, I got confused between this and mx-puppet-slack, I don't have any thoughts or opinions on this.

**Comment by ptman** [comment]
This bridge is pretty much abandoned and the project supports mautrix-slack. So close?
