### ISSUE TITLE
Ubuntu 16.04 does not provide docker-py 1.10.0

### ISSUE THREAD

**Issue by andresterba** [spantaleev/matrix-docker-ansible-deploy#1277]
Sadly I am still running my matrix server on a Ubuntu 16.04 machine, that was working until now.
The documentation states that this setup should work on Ubuntu 16.04 but it seems like the version of 'python-docker' is too old.

```sh
TASK [matrix-base : Ensure Matrix network is created in Docker] ****************
fatal: [matrix.my.server.com]: FAILED! => changed=false
  msg: 'Error: Docker SDK for Python version is 1.9.0 (hosts''s Python /usr/bin/python3). Minimum version required is 1.10.0.Use `pip install --upgrade docker-py` to upgrade. Hint: if you do not need Python 2.6 support, try `pip uninstall docker-py` instead, followed by `pip install docker`.'
```

Thanks for all the good work on `matrix-docker-ansible-deploy` I'm a happy user since a few years!

**Comment by JokerGermany** [comment]
I hope you use Ubuntu ESM, otherwise this is your smallest problem...

**Comment by andresterba** [comment]
> I hope you use Ubuntu ESM, otherwise this is your smallest problem...

The fix for the problem described above was to migrate to a new VM with a newer Ubuntu version :sweat_smile: (this was also a chance to test the backups^^)
