### ISSUE TITLE
qmxme/ansible don't provide dig or dnspython

### ISSUE THREAD

**Issue by ugs9fsy71cb** [spantaleev/matrix-docker-ansible-deploy#128]
If you use approach described in 
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md
```
docker run -it --rm \                                          
-w /work \
-v `pwd`:/work \
-v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
--entrypoint=/bin/sh \
qmxme/ansible
```
the self-check will fail

`{"changed": false, "msg": "Failed performing DNS SRV record check. You neither have the `dnspython` Python package, nor the `dig` program installed locally. You need to install one of those, so we could perform a DNS SRV record check. Full error from trying to run `dig`: {'msg': 'non-zero return code', 'cmd': 'dig -t srv _matrix._tcp.*********.', 'stdout': '', 'stderr': '/bin/sh: dig: not found', 'rc': 127, 'start': '2019-03-29 14:54:02.120348', 'end': '2019-03-29 14:54:02.121273', 'delta': '0:00:00.000925', 'changed': False, 'failed': True, 'stdout_lines': [], 'stderr_lines': ['/bin/sh: dig: not found']}"}`

**Comment by spantaleev** [comment]
Thanks for the report! :+1: 

I've created a new Docker image ([devture/ansible](https://hub.docker.com/r/devture/ansible/)) which contains an up-to-date version of Ansible and `dnspython`.

`--tags=self-check` succeeds using that image.

I've updated the Ansible instructions in this project to point people to using the new image.
