### ISSUE TITLE
CSV import for Synapse-Admin

### ISSUE THREAD

**Issue by jlpadgett** [spantaleev/matrix-docker-ansible-deploy#1286]
I have set up Synapse-Admin using the playbook and can successfully manage users and rooms via my browser. However, I am unable to utilize the CSV Import option: when I click the button, nothing happens (no error, no pop-up, etc.). Is there something else that must be done during setup to allow this option to be used? Or is this an existing error that most users are not worried about (and, hence, not likely to be fixed)?

**Comment by skepticalwaves** [comment]
This is an issue for synapse-admin

https://github.com/Awesome-Technologies/synapse-admin/
