### ISSUE TITLE
Google Chat

### ISSUE THREAD

**Issue by ljlongwing** [spantaleev/matrix-docker-ansible-deploy#1289]
Is there any plans to retire the use of Google Hangouts and replace it with Google Chat?
https://github.com/mautrix/googlechat
I have hangouts configured and working well, but according to Google, Hangouts is 'going away' and being replaced by Chat....they currently work in tandem with each other, but eventually I expect Hangouts will stop working.  Mautrix has a Google Chat bridge that looks to be a replacement for hangouts, so I was hoping you had plans to do this replacement :)

**Comment by aaronraimist** [comment]
As far as I know it is the same bridge that is already in the playbook. It has just been renamed and updated. https://github.com/mautrix/googlechat/commit/483d3a42ff81f2f895914447d599e681e763d5dc

**Comment by ljlongwing** [comment]
hmmmm....so, it's just an alias for the same project?  Ok...if that's the case then no need to 'replace' it because it's the same thing I guess....but if he's renamed his, should it be renamed in this project?

**Comment by aaronraimist** [comment]
I think the documentation should definitely be updated but I'm not sure about all of the variables. If they were just straight up changed then it would break the config of everyone currently using the bridge. I guess there would need to be a bunch of variables that translate the name from the old one to the new one.

**Comment by pszypowicz** [comment]
They indeed just had a 'search and replace' sort of commit, but currently they keep both old prebuild docker images as mautrix-hangouts, as well as new 'mautrix-googlechat'

Do I understand code properly that in master we still point to the old repo:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b5d84447643ab10c8b66428a1fc9dee75ffaff9c/roles/matrix-bridge-mautrix-hangouts/defaults/main.yml#L11

This would mean that we will not benefit automatically from future updates?

**Comment by aaronraimist** [comment]
That appears to be correct. You can submit a PR to change it. I don't use that bridge so I can't easily test it and don't want to change something that will break things.

**Comment by pszypowicz** [comment]
I think it would make sense to introduce a new role - mautrix-googlechat - and it would be basically a similar approach as they did, by simply modifying the keywords and links to new image. We could then inform that mautrix-hangouts is deprecated and anyone could just move to googlechat.

What should the upgrade procedure be:
1. Removing manually old bridge?
2. Detect if both old and new bridge is used at the same time and fail?

**Comment by spantaleev** [comment]
There's probably no need to maintain both roles operational simultaneously and accumulate cruft and cause confusion.

We can just replace the current role with a new role and list a few of its configuration keys in `tasks/validate_config.yml`, so it would tell you that you need to adjust your `vars.yml` configuration.

As an example, see how we do it in the Synapse role: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b5d84447643ab10c8b66428a1fc9dee75ffaff9c/roles/matrix-synapse/tasks/validate_config.yml#L25-L50

It'd be nice if someone who uses this bridge can take care of this "mass replace" migration and test things out properly. I don't use this bridge, so I can't help much.

----------

We should probably also instruct people to rename the old bridge's database, etc. (unless we stick to using the `matrix_mautrix_hangouts` database). Maybe we should just do this migration at the same time and have a changelog entry to let people know how to cleanly migrate:

1. Stop the bridge (`systemctl stop matrix-mautrix-hangouts`)
2. Use `/usr/local/bin/matrix-postgres-cli` and run `ALTER DATABASE matrix_mautrix_hangouts RENAME TO matrix_mautrix_googlechat;`)
3. Adjust your variables in `vars.yml` (`matrix_mautrix_hangouts_enabled` -> `matrix_mautrix_googlechat_enabled`, etc.)
4. Re-run the playbook (`ansible-playbook ....... --tags=setup-all,start`)

We may be able to automate this migration in the role's `tasks/setup_install.yml`, but it's easier if we just make it manual.

**Comment by spantaleev** [comment]
My understanding is that it will go to the new role. The old role is to be removed completely.

**Comment by luixxiul** [comment]
Resolved with https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1328
