### ISSUE TITLE
Ansible won't notice startup failure of matrix-synapse.service when port already in use

### ISSUE THREAD

**Issue by FatalMerlin** [spantaleev/matrix-docker-ansible-deploy#129]
As the title states, the playbook (tags=start) fails to detect the failed startup of the service when docker can't bind to the port. In my case because the server also hosts GitLab, and it's [Node Exporter](https://docs.gitlab.com/ee/administration/monitoring/prometheus/node_exporter.html) uses this port.

This makes troubleshooting quite hard, since you don't get an error at all and need to dig into the services.

**Comment by spantaleev** [comment]
Thanks for the report! :+1: 

I've added checks to `--tags=start`. Those necessitated bumping the Ansible version requirements, as [described in the changelog](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#ansible--25-is-required).

**Comment by FatalMerlin** [comment]
Thanks for the great work! It works perfectly aside from this :)
