### ISSUE TITLE
Any thoughts on adding Conduit.rs?

### ISSUE THREAD

**Issue by daegalus** [spantaleev/matrix-docker-ansible-deploy#1290]
Wanted to see if there was any possibility of this ansible expanding to include Conduit.rs as an alternative to Synapse in the ansible deploy. Maybe for lower resource deployments.

**Comment by kubo6472** [comment]
Oh, yas, would love to see this. Welp, time to get into ansible.

**Comment by spantaleev** [comment]
You can take inspiration from the `matrix-dendrite` role and from #818.

Updating `group_vars/matrix_servers` in a few places for Conduit would also be necessary.

**Comment by kubo6472** [comment]
Hey, just to let you know on some progress. I've been studying this repo on & off for the last month. I managed to get conduit up and running in docker today, as part of my effort to include it in some other software collection. I copied over files mentioned in that PR. Hopefully in the coming weeks, I'll have something to show.

**Comment by Daniel15** [comment]
This can be closed now.
