### ISSUE TITLE
Installation defaults to matrix.matrix.<your-domain>

### ISSUE THREAD

**Issue by Traace** [spantaleev/matrix-docker-ansible-deploy#1305]
My Domain is somehow set to "matrix.matrix.your-domain" . This creates a .well-known file that leads to a none existing server, thus clients have problems connecting to the synapse server. When edited this file gets overwritten by a playbook.

I expect that the full domain is matrix.your-domain just like in the docs. But that is not the case. Instead I get a double matrix.matrix.<your-domain>

I just followed the documentation but now I am confused and stuck, What steps are needed to get a matrix.your-domain running? Should I just use your-domain and let the playbooks add matrix in front of it?

**Comment by aaronraimist** [comment]
I think you are misunderstanding what the playbook is trying to do. The normal setup is you set `matrix_domain` to a domain that doesn't have any matrix subdomain in it. Usually this is just a plain second level domain (example.com or matrix.org). This is the user facing domain that appears at the end of usernames, room aliases, and spaces.

The Matrix APIs are served from a matrix subdomain but this is not user facing. Users never need to know this exists. It is just to allow you to easily run other websites/services on the base domain and other subdomains.

**Comment by skepticalwaves** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md#configuring-your-dns-server

**Comment by Traace** [comment]
Thanks for the help people :). Understood that, it's working now 👍 

Also I edited my post above, it was a bit misleading. I assumed it was a script fault, but it actually was just my fault.
