### ISSUE TITLE
clarify matrix_nginx_proxy_proxy_synapse_metrics_basic_auth_key

### ISSUE THREAD

**Issue by HarHarLinks** [spantaleev/matrix-docker-ansible-deploy#1308]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b5d84447643ab10c8b66428a1fc9dee75ffaff9c/roles/matrix-nginx-proxy/defaults/main.yml#L186

This ends up in the htpasswd file and thus needs to be formatted fittingly (`man 1 htpasswd`), e.g. modified MD5 by default.
Ansible can handle this: https://docs.ansible.com/ansible/latest/collections/community/general/htpasswd_module.html
If that is for some reason not desireable, e.g. perhaps the hashed version is preferable to keep in the your vars.yml instead of the plain password, then a comment about how to encrypt the pw should be added here.

**Comment by spantaleev** [comment]
You're right that we should document this better. A PR would be welcome to add a comment about it.

Making Ansible manage it using the `htpasswd` module is probably also nice, but that means we'd need to deprecate the existing raw `matrix_nginx_proxy_proxy_synapse_metrics_basic_auth_key` variable and support yet another feature, or we'd need to keep support for both (making things even more complicated).

This is a rarely used feature, so it's probably OK to leave it as it is. Perhaps a comment about how to generate the key would suffice.
