### ISSUE TITLE
Question about matrix bridges

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1310]
The docs don't explain this very well, and neither do the bridges, so thought I might ask here: do the bridges apply to individual users who link them? E.g.: if a friend on my server logs into their FB account, will only they have access to that account, or does that apply to the entire server? I'm pretty sure its user-specific but I wanted to make sure before I go enabling bridges and setting everything up.

**Comment by skepticalwaves** [comment]
For bridges that support individual login, you bridge your own personal account and only you have access.

There are also bot-based room bridges.

**Comment by ethindp** [comment]
Thanks @skepticalwaves. What's the difference between mautrix and mx-puppet (for when there are duplicates)? Like does one offer more features than the other?

**Comment by skepticalwaves** [comment]
You'll have to check the upstream projects for details there.

**Comment by tjarbo** [comment]
Maybe also an interesting resource to check out:  

https://matrix.org/docs/guides/types-of-bridging

**Comment by ethindp** [comment]
Thanks everyone, that helped. Though I do think the docs should include that information -- it isn't always clear even via the documentation of the bridge.
