### ISSUE TITLE
`matrix-dimension` fails to start, missing git and ".../package.json"

### ISSUE THREAD

**Issue by eordano** [spantaleev/matrix-docker-ansible-deploy#1314]
Hi there,

I was testing on my homelab, and trying to enable dimension brought up the following error:

![imagen](https://user-images.githubusercontent.com/42750/135996525-66d9a5a7-3a8c-48c8-9351-eef7cbde727b.png)

Could this by any reason be caused by an extra docker container that I am running in the same docker network as matrix, not configured through ansible?

In any case, dimension is not that important but I just wanted to let you know it was acting strangely!

**Comment by spantaleev** [comment]
This is an error not related to the playbook, but to [Dimension](https://github.com/turt2live/matrix-dimension) itself.

It tries to figure out its own version by running `git` commands: https://github.com/turt2live/matrix-dimension/blob/6964bca40e3b1a58a11b8b3be89841e9a94c65cf/src/version.ts#L13-L20

However, its Docker container image ([Dockerfile](https://github.com/turt2live/matrix-dimension/blob/6964bca40e3b1a58a11b8b3be89841e9a94c65cf/Dockerfile)) does not install `git`. Adding `RUN apk add --no-cache` should solve this error.

If you'd like, you can report this issue upstream or send a PR to them.

**Comment by TheTimeWalker** [comment]
Hey, just to note, there's a pending PR which should fix this error with a more sensible solution: https://github.com/turt2live/matrix-dimension/pull/446

As soon as this is merged, the issue should be resolved

**Comment by TheTimeWalker** [comment]
The PR has been merged, thus the issue should be resolved now
