### ISSUE TITLE
After Install cant join Rooms

### ISSUE THREAD

**Issue by smooth-baking-powder** [spantaleev/matrix-docker-ansible-deploy#1341]
Hi,

i installed now Ansible with this vars.ml:

```
matrix_domain: domain.one
matrix_ssl_lets_encrypt_support_email: 'masked'
matrix_synapse_macaroon_secret_key: 'masked'
matrix_postgres_connection_password: 'masked'

matrix_synapse_enable_registration: true
matrix_synapse_federation_enabled: true
matrix_synapse_federation_domain_whitelist:
matrix_synapse_allow_public_rooms_over_federation: true

matrix_synapse_autocreate_auto_join_rooms: true
matrix_synapse_auto_join_rooms:
- '#masked
- '#masked'


# Nginx
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: '0.0.0.0:81'
matrix_nginx_proxy_container_federation_host_bind_port: '0.0.0.0:8449'
matrix_nginx_proxy_trust_forwarded_proto: true

# Coturn
matrix_coturn_enabled: false
matrix_synapse_turn_shared_secret: "masked"
matrix_synapse_turn_uris:
masked


# Ldap
matrix_synapse_ext_password_provider_ldap_enabled: true
matrix_synapse_ext_password_provider_ldap_uri: masked
matrix_synapse_ext_password_provider_ldap_start_tls: false
matrix_synapse_ext_password_provider_ldap_base: masked
matrix_synapse_ext_password_provider_ldap_attributes_uid: "uid"
matrix_synapse_ext_password_provider_ldap_attributes_mail: "mailPrimaryAddress"
matrix_synapse_ext_password_provider_ldap_attributes_name: "displayname"
matrix_synapse_ext_password_provider_ldap_bind_dn: masked
matrix_synapse_ext_password_provider_ldap_bind_password: "masked"
matrix_synapse_ext_password_provider_ldap_filter: masked


# Registration
matrix_registration_enabled: true
matrix_registration_admin_secret: "masked"


# Adminweb
matrix_synapse_admin_enabled: true

# Signal
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true

# Discord
matrix_appservice_discord_enabled: true
matrix_appservice_discord_client_id: "masked"
matrix_appservice_discord_bot_token: "masked"

# Steam
matrix_mx_puppet_steam_enabled: true

# Instagram
matrix_mautrix_instagram_enabled: true

```

All is integrated except Nginx Proxy:
```
upstream matrix {
        server masked:81
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name matrix.masked;

    ssl on;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate           masked
    ssl_certificate_key       masked
    location / {
        proxy_pass http://matrix;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
		client_max_body_size 4096M;

	access_log            /var/log/nginx/matrix-access.log adv;
	error_log            /var/log/nginx/matrix-error.log notice;

   }
}

server {
    listen 8448 ssl http2 default_server;
    listen [::]:8448 ssl http2 default_server;
    server_name matrix.masked

    ssl on;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate           masked
    ssl_certificate_key      masked
    location / {
        proxy_pass http://masked:8449;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
		client_max_body_size 4096M;

	access_log            /var/log/nginx/matrixfed-access.log adv;
	error_log            /var/log/nginx/matrixfed-error.log notice;

    }
}
```

![grafik](https://user-images.githubusercontent.com/21257329/137977349-9571a131-caa9-4b63-953e-c7755dd2a630.png)
My problem is, i cant join external rooms like: #matrix-docker-ansible-deploy:devture.com
And why my internal Adresses are "channelname:domain.one" and no "channel:matrix.domain.one"? Its confusing

**Comment by corincorvus** [comment]
Synapse is online and i can connect in and outside of my network
![grafik](https://user-images.githubusercontent.com/21257329/138038295-4c00345e-1f9c-4af7-b266-8ca4c90ae77b.png)

Do you have a good configuration? 

In https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md
i didnt find a nginx config. The Link of "template files in the matrix-nginx-proxy role." goes to 404 not found.



> If you are trying to act as that old server then you need to uninstall and reinstall with `matrix_domain` set to the server_name of your previous server.

If i do that, i have "matrix.matrix.domain.one" on element web and address. I have much trouble with the server after do that.

**Comment by corincorvus** [comment]
Hi, 

today i changed my Server and start over with server_name in vars.yml with subdomain.domain.tld.
Deleted postgres DB and new start.

The Problems persists. The Certification is the cert for this subdomain.

Here is my vars.yml. Maybe i did something wrong?

i only can use the subdomain (for your information)

Login and use the Server itself work fine.

```

matrix_domain: matrix.domain.tld
matrix_ssl_lets_encrypt_support_email: 'masked'
matrix_synapse_macaroon_secret_key: 'masked'
matrix_postgres_connection_password: 'masked'

matrix_synapse_enable_registration: true
matrix_synapse_federation_enabled: true
matrix_synapse_federation_domain_whitelist:
matrix_synapse_allow_public_rooms_over_federation: true
matrix_synapse_max_upload_size_mb: 1024




matrix_synapse_autocreate_auto_join_rooms: true
matrix_synapse_auto_join_rooms:
- '#ankuendigungen:domain.tld'
- '#spaces:domain.tld'


# Nginx
matrix_ssl_retrieval_method: none
matrix_well_known_matrix_server_enabled: false
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: '0.0.0.0:81'
matrix_nginx_proxy_container_federation_host_bind_port: '0.0.0.0:8449'
matrix_nginx_proxy_trust_forwarded_proto: true
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate: /matrix/ssl/config/live/matrix.domain.tld/fullchain.pem
matrix_nginx_proxy_proxy_matrix_federation_api_ssl_certificate_key: /matrix/ssl/config/live/matrix.domain.tld/privkey.pem



# Coturn
matrix_coturn_enabled: false
matrix_synapse_turn_shared_secret: "masked"
matrix_synapse_turn_uris:
- turns:turn.domain.tld?transport=udp
- turns:turn.domain.tld?transport=tcp
- turn:turn.domain.tld?transport=udp
- turn:turn.domain.tld?transport=tcp


# Ldap
matrix_synapse_ext_password_provider_ldap_enabled: true
matrix_synapse_ext_password_provider_ldap_uri: "masked"
matrix_synapse_ext_password_provider_ldap_start_tls: false
matrix_synapse_ext_password_provider_ldap_base: "masked"
matrix_synapse_ext_password_provider_ldap_attributes_uid: "uid"
matrix_synapse_ext_password_provider_ldap_attributes_mail: "mailPrimaryAddress"
matrix_synapse_ext_password_provider_ldap_attributes_name: "displayname"
matrix_synapse_ext_password_provider_ldap_bind_dn: "masked"
matrix_synapse_ext_password_provider_ldap_bind_password: "masked"
matrix_synapse_ext_password_provider_ldap_filter: "(|(masked))"


# Registration
matrix_registration_enabled: false
matrix_registration_admin_secret: "masked"


# Adminweb
matrix_synapse_admin_enabled: true

# Signal
matrix_mautrix_signal_enabled: true
matrix_mautrix_signal_relaybot_enabled: true

permissions:
  '*': relay
  YOUR_DOMAIN: user

# Discord
matrix_appservice_discord_enabled: true
matrix_appservice_discord_client_id: "masked"
matrix_appservice_discord_bot_token: "masked"

# Steam
matrix_mx_puppet_steam_enabled: true

# Instagram
matrix_mautrix_instagram_enabled: true


```


![grafik](https://user-images.githubusercontent.com/21257329/139542893-249acc55-5ad5-4058-a2cd-5bb6984a6ac0.png)
![grafik](https://user-images.githubusercontent.com/21257329/139542900-5154345f-4950-437c-80f4-6469973c7054.png)

**Comment by corincorvus** [comment]
Ok. Now i solve this Problem and have another Problem.
![grafik](https://user-images.githubusercontent.com/21257329/139555108-e792e528-08e6-4fed-8503-fc9defcc3826.png)


If i write my subdomain.domain.tld it say: its no matrix homeserver url
![grafik](https://user-images.githubusercontent.com/21257329/139555126-27c9357e-05b7-4377-834c-289222892347.png)

Inside and outside my network.

**Comment by corincorvus** [comment]
I read some code and found the main.yml of matrix-base.

I change this:
```
# Example value: example.com
matrix_domain: ~
matrix_xy_basedn: domain.tld

# This is where your data lives and what we set up.
# This and the Element FQN (see below) are expected to be on the same server.
matrix_server_fqn_matrix: "{{ matrix_domain }}"

# This is where you access federation API.
matrix_server_fqn_matrix_federation: '{{ matrix_server_fqn_matrix }}'

# This is where you access the Element web UI from (if enabled via matrix_client_element_enabled; enabled by default).
# This and the Matrix FQN (see above) are expected to be on the same server.
matrix_server_fqn_element: "element.{{ matrix_xy_basedn }}"

# This is where you access the Hydrogen web client from (if enabled via matrix_client_hydrogen_enabled; disabled by default).
matrix_server_fqn_hydrogen: "hydrogen.{{ matrix_xy_basedn }}"

# This is where you access the Dimension.
matrix_server_fqn_dimension: "dimension.{{ matrix_xy_basedn }}"

# For use with Go-NEB! (github callback url for example)
matrix_server_fqn_bot_go_neb: "goneb.{{ matrix_xy_basedn }}"

# This is where you access Jitsi.
matrix_server_fqn_jitsi: "jitsi.{{ matrix_xy_basedn }}"

# This is where you access Grafana.
matrix_server_fqn_grafana: "stats.{{ matrix_xy_basedn }}"

# This is where you access the Sygnal push gateway.
matrix_server_fqn_sygnal: "sygnal.{{ matrix_xy_basedn }}"

```

and it works. I have Federation, i joined the Playbook Matrix channel and the Matrix Server is usable.

May this can add in any case for subdomain Users without base domain control like me on 24 locations/domains for Communities and societies.

**Comment by juergen852** [comment]
@corincorvus 
I have the same problem.
Did you edit /matrix-docker-ansible-deploy/roles/custom/matrix-base/defaults/main.yml ?

Why did you close the issue?
Should "subdomains / not pure server.tld web access" not be possible as an option with the script?

**Comment by juergen852** [comment]
With standard install, I get same image from FedTester as corincorvus
.well-known seems to work, but FedTest shows error.
 
https://matrix.domainname.at/.well-known/matrix/client 
gives:
{
    "im.vector.riot.e2ee": {
        "default": true
    },
    "io.element.e2ee": {
        "default": true,
        "secure_backup_required": false,
        "secure_backup_setup_methods": []
    },
    "m.homeserver": {
        "base_url": "https://matrix.domainname.at"
    }
}

https://matrix.domainname.at/.well-known/matrix/server:
{
    "m.server": "matrix.domainname.at:8448"
}

**Comment by aaronraimist** [comment]
@juergen852 I would suggest you ask in `#matrix-docker-ansible-deploy:devture.com` or open a new issue.

>  Did you edit /matrix-docker-ansible-deploy/roles/custom/matrix-base/defaults/main.yml ?

You should not edit anything inside the `roles` folder.

**Comment by corincorvus** [comment]
> @corincorvus I have the same problem. Did you edit /matrix-docker-ansible-deploy/roles/custom/matrix-base/defaults/main.yml ?
> 
> Why did you close the issue? Should "subdomains / not pure server.tld web access" not be possible as an option with the script?

You can already use "Subdomain Setup" https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md

You no need to change some main.yml. You can edit the vars.yml like this:
matrix_domain: matrix.domain.tld
matrix_server_fqn_matrix: "matrix.domain.tld"
matrix_server_fqn_element: "element.domain.tld"
matrix_server_fqn_dimension: "dimension.domain.tld"
matrix_server_fqn_jitsi: "jitsi.domain.tld"
matrix_server_fqn_hydrogen: "hydrogen.domain.tld"
matrix_server_fqn_bot_go_neb: "goneb.domain.tld"
matrix_server_fqn_grafana: "stats.domain.tld"
matrix_server_fqn_sygnal: "sygnal.domain.tld"

**Comment by juergen852** [comment]
Install is on fresh Ubuntu 22.04 cloud VPS at Hetzner and I've set the DNS and all CNAMEs and even Reverse DNS. Nothing else installed, just matrix.

Modified Files:
- /matrix-docker-ansible-deploy/inventory/host_vars/matrix.domain1.at/vars.yml
I set:  matrix_domain: domain1.at (Using matrix.domain1.at results in matrix.matrix.domain1.at error at letsencrypt)
- /matrix-docker-ansible-deploy/inventory/hosts : Edit 
[matrix_servers]
matrix.domain1.at ansible_host=95.xxx.xxx.108 ansible_ssh_user=root
- Rules are all vanilla

After setting the following definitions **at the END** of /matrix-docker-ansible-deploy/inventory/host_vars/matrix.domain1.at/vars.yml _(because original script changes ntfy to ntfx.matrix.domain1.at  ( put it after "matrix_server_fqn_ntfy: "ntfy.{{ matrix_domain }}" at around line 95) and neither letsencrypt nor clients would accept)_ **it finally worked !!**

matrix_domain: matrix.domain.tld
matrix_server_fqn_matrix: "matrix.domain.tld"
matrix_server_fqn_element: "element.domain.tld"
matrix_server_fqn_dimension: "dimension.domain.tld"
matrix_server_fqn_jitsi: "jitsi.domain.tld"
matrix_server_fqn_hydrogen: "hydrogen.domain.tld"
matrix_server_fqn_bot_go_neb: "goneb.domain.tld"
matrix_server_fqn_grafana: "stats.domain.tld"
matrix_server_fqn_sygnal: "sygnal.domain.tld"
matrix_server_fqn_ntfy: "ntfy.domain.tld"
