### ISSUE TITLE
[Question] How does this work with DuckDNS?

### ISSUE THREAD

**Issue by Ryu945** [spantaleev/matrix-docker-ansible-deploy#1346]
The guide for setting up dynamic DNS does not seem to apply for DuckDNS.  How do I configure this for DuckDNS?

Also, if the matrix server is on server.duckdns.org and jitsu is on jitsu.server.duckdns.org then is there anything cname related that needs to be setup or does DuckDNS handle it all?

**Comment by borasura** [comment]
Just setup your DDNS at duckdns i.e. <yourdomain>.duckdns.org pointing to your server. As long as all your other services are installed on the same server you don't have to do anything else because any subdomains to your Duckdns DDNS gets routed to your base server automatically.

**Comment by Ryu945** [comment]
Thankyou.  If I understand you correctly, all subdomains will just work as long as they are on the same server.  I am guessing that chains endlessly from what your saying.

DDNS points to  yourdomain.duckdns.org

 site1.yourdomain.duckdns.org     works
 site2.yourdomain.duckdns.org    works

app1.site1.yourdomain.duckdns.org    works
app2.site1.yourdomain.duckdns.org    works

as long as everything is on the same server.
