### ISSUE TITLE
Unable to setup jitsi for arm64. 

### ISSUE THREAD

**Issue by aloobhai** [spantaleev/matrix-docker-ansible-deploy#1349]
**PLAYBOOK FAILED TASK MESSAGE** ( 3 such messages each for matrix-jitsi-prosody.service ,matrix-jitsi-jicofo.service,matrix-jitsi-jvb.service)
 
failed: [matrix.tiktoken.ga] (item=matrix-jitsi-prosody.service) => changed=false 
  ansible_loop_var: item
  item: matrix-jitsi-prosody.service
  msg: matrix-jitsi-prosody.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-jitsi-prosody.service` and `journalctl -fu matrix-jitsi-prosody.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.

After running `systemctl status matrix-jitsi-prosody.service` and `journalctl -fu matrix-jitsi-prosody.service` on the server to investigate. Outputs are given below respectively.

systemctl status matrix-jitsi-prosody.service
● matrix-jitsi-prosody.service - Matrix jitsi-prosody server
     Loaded: loaded (/etc/systemd/system/matrix-jitsi-prosody.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2021-10-24 07:15:27 UTC; 29s ago
    Process: 750385 ExecStartPre=/usr/bin/env sh -c /usr/bin/env docker kill matrix-jitsi-prosody 2>/dev/null (code=exited, status=1/FAILURE)
    Process: 750393 ExecStartPre=/usr/bin/env sh -c /usr/bin/env docker rm matrix-jitsi-prosody 2>/dev/null (code=exited, status=1/FAILURE)
    Process: 750401 ExecStart=/usr/bin/env docker run --rm --name matrix-jitsi-prosody --log-driver=none --network=matrix --network-alias=xmp>
   Main PID: 750401 (code=exited, status=1/FAILURE

systemd[1]: matrix-jitsi-prosody.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 07:15:59 instance-20211022-1429 systemd[1]: matrix-jitsi-prosody.service: Failed with result 'exit-code'.
Oct 24 07:16:29 instance-20211022-1429 systemd[1]: matrix-jitsi-prosody.service: Scheduled restart job, restart counter is at 1051.
Oct 24 07:16:29 instance-20211022-1429 systemd[1]: Stopped Matrix jitsi-prosody server.
Oct 24 07:16:29 instance-20211022-1429 systemd[1]: Starting Matrix jitsi-prosody server...
Oct 24 07:16:29 instance-20211022-1429 systemd[1]: Started Matrix jitsi-prosody server.
Oct 24 07:16:29 instance-20211022-1429 matrix-jitsi-prosody[751772]: WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Oct 24 07:16:30 instance-20211022-1429 matrix-jitsi-prosody[751772]: standard_init_linux.go:228: exec user process caused: exec format error
Oct 24 07:16:30 instance-20211022-1429 systemd[1]: matrix-jitsi-prosody.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 07:16:30 instance-20211022-1429 systemd[1]: matrix-jitsi-prosody.service: Failed with result 'exit-code'.
Oct 24 07:17:00 instance-20211022-1429 systemd[1]: matrix-jitsi-prosody.service: Scheduled restart job, restart counter is at 1052.
Oct 24 07:17:00 instance-20211022-1429 systemd[1]: Stopped Matrix jitsi-prosody server.
Oct 24 07:17:00 instance-20211022-1429 systemd[1]: Starting Matrix jitsi-prosody server...

Summary
I am no expert , but apparently the playbook seems to be building for amd64 instead of arm64( what is required by me).
Is there any way I can manually change the images used by the playbook for jisti? Or is there any config like matrix_architecture: "arm64" ? (the config line before is already applied and therefore matrix and element do work but it wont work for jitsi even after following the steps  in the section 'Rebuilding jitsi configuration' .

**Comment by worldofgeese** [comment]
@aloobhai if or when you get this running, please let us know.

**Comment by seclution** [comment]
Looks like it is the same problem with matrix-bot-go-neb ...


```
failed: [matrix.gedankenfrei.online] (item=matrix-bot-go-neb.service) => changed=false
  ansible_loop_var: item
  item: matrix-bot-go-neb.service
  msg: matrix-bot-go-neb.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-bot-go-neb.service` and `journalctl -fu matrix-bot-go-neb.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.
```

Should somebody open a new issue for that or is there any workaround?

**Comment by MyricaGale** [comment]
Does #1889 fix this issue? The version stable-7439-2 of jitsi seems to work quite nice.

**Comment by smargold476** [comment]
For me that fixes the issue!
