### ISSUE TITLE
Running the playbook on ARM devices with little RAM

### ISSUE THREAD

**Issue by Raanelom** [spantaleev/matrix-docker-ansible-deploy#1357]
At first: thank you guys for the nice work you put into this project!
For me it works almost out of the box, except for one thing: self-building `client-element` on my Raspberry Pi 3B+ (1G RAM) makes it run out of memory. In particular, the Terser Webpack-plugin causes the ansible-playbook-command to fail. This is a known issue: https://github.com/terser/terser/issues/164
It can be fixed by updating the `webpack.config.js`-file as follows:
```javascript
// (...)
// now we need to consider that the CSS needs to be bundled up together.
splitChunks: {
    maxSize: 100000, // <= add this line (I just picked some sensible random value here)
        cacheGroups: {
// (...)
```

Since I'm not that much into Ansible, do you guys have an idea on how to include this maximum in the playbook? For now I just forked the element-client repo and added this line to `webpack.config.js` myself.
Thanks in advance!

**Comment by Raanelom** [comment]
Nice work! I think solution 2 is indeed the way to go here. I'll check it out!

**Comment by RoiArthurB** [comment]
@spantaleev It would be nice to have a variable to force this method too. 

For instance, I'm running everything on a RP4 with 4G of RAM (so the method doesn't apply automatically), but I have some other softwares running too, and I'd like to save them from crashing because it's missing RAM space :)

**Comment by spantaleev** [comment]
@RoiArthurB, it's now possible via the `matrix_client_element_container_image_self_build_low_memory_system_patch_enabled` variable. See 0434e3bf8f3714
