### ISSUE TITLE
Postgres container configuration has insufficient shm size for some queries (and auto-VACUUM)

### ISSUE THREAD

**Issue by skepticalwaves** [spantaleev/matrix-docker-ansible-deploy#1362]
I was playing chicken with my disk space and deicded to try a partial VACUUM and ANALYZE on my server.

When I pulled up a postgres cli and executed it, it quickly failed with:

```
ERROR:  could not resize shared memory segment "/PostgreSQL.<numbers>" to <numbers>  bytes: No space left on device
```

A quick bit of googling told me that docker's default shm filesystem (tempfiles in memory) size is too small for how postgres uses those as memory-maps. So I added:

```
      --shm-size="256m" \
```

To `/etc/systemd/system/matrix-postgres.service` and restarted postgres, and then I was able to execute a VACUUM and ANALYZE.

I suspect I haven't had an auto VACUUM/ANALYZE work in a while due to this bug.

**Comment by aaronraimist** [comment]
This came up before in https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1268 so yeah I agree. It probably makes sense to set to 256m by default or at least update the VACUUM docs to mention that you may need to set this manually. Are you going to submit a PR?

**Comment by spantaleev** [comment]
I've added `--shm-size="256m"` by default. Hope that it's enough for everybody. Well, at least it should be, for more people than the default (`64m`).

**Comment by vrutkovs** [comment]
Quotes must be removed:
```
Oct 30 10:31:15 server0 systemd[1]: Started Matrix Postgres server.
Oct 30 10:31:15 server0 matrix-postgres[24271]: invalid argument "\"256m\"" for "--shm-size" flag: invalid size: '"256m"'
Oct 30 10:31:15 server0 matrix-postgres[24271]: See 'docker run --help'.
Oct 30 10:31:15 server0 systemd[1]: matrix-postgres.service: main process exited, code=exited, status=125/n/a
```
Works with
>--shm-size=256m

**Comment by skepticalwaves** [comment]
> Quotes must be removed:
> 
> ```
> Oct 30 10:31:15 server0 systemd[1]: Started Matrix Postgres server.
> Oct 30 10:31:15 server0 matrix-postgres[24271]: invalid argument "\"256m\"" for "--shm-size" flag: invalid size: '"256m"'
> Oct 30 10:31:15 server0 matrix-postgres[24271]: See 'docker run --help'.
> Oct 30 10:31:15 server0 systemd[1]: matrix-postgres.service: main process exited, code=exited, status=125/n/a
> ```
> 
> Works with
> 
> > --shm-size=256m

How interesting. Quoted worked on my version of docker/systemd.

**Comment by spantaleev** [comment]
Just checked and quoted seems to work for me as well.
