### ISSUE TITLE
Random docker_network error

### ISSUE THREAD

**Issue by InterFelix** [spantaleev/matrix-docker-ansible-deploy#1363]
I am using this chart to build my own GitLab CI/CD config to deploy a matrix server, and after committing a minor change only affecting the GitLab side of things (no config change of the ansible playbook itself), this strange error occurs every time I try to run the playbook setup:
```
ERROR! couldn't resolve module/action 'docker_network'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/builds/buendischer-matrix-server/matrix-docker-ansible-deploy/roles/matrix-base/tasks/setup_matrix_base.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Ensure Matrix network is created in Docker
  ^ here
  ```
  
The last time the pipeline ran the job went through, and there has not been any config change at all.
I already tried overriding `matrix_docker_network` in my vars.yml, to no avail.
As a sidenote, I am using willhallonline/ansible:2.10-ubuntu20.04 as the docker base image from which the playbook is executed.

**Comment by InterFelix** [comment]
I just noticed something:
The last time the job went through, the ansible version being run was 2.10.12, now it is 2.10.15. The docker image seems to have been upgraded in the last few hours with a bump to a new ansible version, which has now broken this playbook.
Sadly, there are no immutable tags for this docker image to fall back to.

**Comment by spantaleev** [comment]
Why aren't you using the [devture/ansible](https://hub.docker.com/r/devture/ansible/) Docker image, like we recommend on our [Ansible docs page](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md#using-ansible-via-docker)?

That one seems a bit more dated though, but at least there's a fixed tag that you can use.

**Comment by InterFelix** [comment]
I considered this before switching to willhallonline's image, but my CI/CD pipeline relies on the base image being Ubuntu currently. I'll consider this, though, shouldn't be too much work to port it over to alpine.

**Comment by spantaleev** [comment]
Your problem with Ansible 2.10 seems to stem from the fact that on some distros Ansible 2.10+ is split into multiple system packages ("Ansible Core" and "Ansible Collections"). All these modules (like `docker_network`, etc.) are probably part of some "collection" package, which is not installed along with the core `ansible` package.

On other distros, it's done in a better way. On Archlinux for example, `ansible` is the package that provides these "module collections" and it pulls in the `ansible-core` package as a dependency. This way, knowledgeable people that just want the core can simply install `ansible-core`, while regular folk that install `ansible` get "the whole package" (Ansible + collections).

So.. it may be that this `willhallonline/ansible` image needs updates to install the "Ansible collections" package too. You can report that problem there. Or you can try to augment the image by yourself, building on top of it, to add what's missing.

**Comment by InterFelix** [comment]
I'm not sure if this is applicable, since willhallonline/ansible installs ansible through `pip`, at least on Ubuntu 20.04.
Also, it uses the `ansible` pip package, not `ansible-base` (which is the name of `ansible-core` in ansible 2.10.

All this is assuming the Git repo for willhallonline/ansible is consistent with the actual building source of the latest version of the docker images, which I kind of doubt, since the Dockerfile in the repo specifies ansible 2.10.7 and the docker image contains 2.10.15 .

**Comment by InterFelix** [comment]
I'll just make the switch to devture/ansible, even though that will require some refactoring of my ssh key injection in the pipeline. It took me ages to get it working on Ubuntu, but I'm hoping I have learnt enough lessons to make it work more quickly on Alpine.

**Comment by InterFelix** [comment]
Happy to report the switch was seamless and easy. Potentially existing problems will surely only manifest in the distant future when I'll have completely forgotten this switch ever took place in the first place.
Closing this.

**Comment by chagai95** [comment]
Just ran into something very similar and this was very helpful, thx!
