### ISSUE TITLE
matrix_jitsi_web_environment_variables_extension is no longer used

### ISSUE THREAD

**Issue by devium** [spantaleev/matrix-docker-ansible-deploy#1377]
The variable `matrix_jitsi_web_environment_variables_extension` is no longer accessed in the Jitsi web environment template:

https://github.com/spantaleev/matrix-docker-ansible-deploy/search?q=matrix_jitsi_web_environment_variables_extension

It was removed here:

https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/2ca92b76b6c79e305da47c4e2075a29f139b830c#diff-84ae435133a6d51e8d6191d08d603e82a998783d74d0349381736a38bfa905e1L42

**Comment by spantaleev** [comment]
This is probably unintentional. Thanks for reporting it! Fixed!
