### ISSUE TITLE
Feature Request: Add self-hosted goneb

### ISSUE THREAD

**Issue by jdreichmann** [spantaleev/matrix-docker-ansible-deploy#138]
Users which are enabling dimension and configuring it are presented with two options currently:
- Use matrix.org's g-oneb instance
- Use a selfhosted one, which they would need to setup
It would be nice to see this playbook also set up a go-neb instance, so users can have self-hosted RSS feeds etc (in general: stuff enabled by go-neb)
https://github.com/matrix-org/go-neb

**Comment by jdreichmann** [comment]
There is already a docker image available: https://github.com/matrix-org/go-neb#docker-image

**Comment by jdreichmann** [comment]
I've started some work on a role for matrix-goneb here: https://github.com/jdreichmann/matrix-docker-ansible-deploy/commits/feat/add-goneb
If anyone wants to join, they are welcome

**Comment by daudo** [comment]
I'm wondering about how far you got with your ansible role. Is it working, anything missing?

Thx.

**Comment by jdreichmann** [comment]
Unfortunately, i did not make much progress with the role, and a lot has been going on in the project since then.
I might have some time to look into it again, but i cannot promise anything, if anyone would want to implement it, they are of course free to do so

**Comment by aaronraimist** [comment]
This was fixed by https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/929
