### ISSUE TITLE
Help me to run my own server synapse with my own branding

### ISSUE THREAD

**Issue by MPTA** [spantaleev/matrix-docker-ansible-deploy#1387]
Hello everyone,
i am going to run my own synapse server for public communication usage . with kindest thanks to the matrix and element teams , i have done some customization on element native apps and need some more configuration on the synapse server , how can get support for my purpose . also i can donate for support. 

thanks for your response.

**Comment by spantaleev** [comment]
If your Synapse customizations are limited to configuration options, you can customize anything that's part of `homeserver.yaml` by using the `matrix_synapse_configuration_extension_yaml` variable. See `roles/matrix-synapse/defaults/main.yml`.

If you're customizing the code, you can build your own Synapse Docker image and point the playbook to it (see the `matrix_synapse_docker_image` variable).

Alternatively, you can:
- fork the [Synapse repository](https://github.com/matrix-org/synapse)
- apply your changes to your own repository
- enable self-building (`matrix_synapse_container_image_self_build: true`) and point the playbook to your own repository URL by adjusting the `matrix_synapse_container_image_self_build_repo` variable (see `roles/matrix-synapse/defaults/main.yml`)

-------------

It's a similar story for changing things for Element. You have the `matrix_client_element_configuration_extension_json` variable for changing custom settings (besides the settings already exposed as dedicated variables by the playbook).

You can also use your own custom Docker image, or point it to your own fork (`matrix_client_element_container_image_self_build_repo`) and enable self-building (`matrix_client_element_container_image_self_build: true`).

It's also possible to mount files on top of the original Docker image files as a way of replacing them. You can do this via `matrix_client_element_container_extra_arguments`. This is probably a less clean solution, but it may be easier, depending on what you need to do.

**Comment by MPTA** [comment]
thanks a lot dear Slavi for matrix-docker-ansible-deploy and perfect explanation and support.

**Comment by MPTA** [comment]
Dear Slavi , following to you alternative ,  fork git of Element-web created on release-v1.9.4 and i have done some very small changes in the code. also i used vscode and docker package to make image of the project to my docker repository , i had tried many times that but i got error , can you help me how can i solve the problem to craete docker image?


<img width="1792" alt="Screen Shot 1400-08-22 at 15 33 04" src="https://user-images.githubusercontent.com/40070445/141643459-47ad3d0e-dbf9-452c-81c8-173f0eff9fab.png">
<img width="1792" alt="Screen Shot 1400-08-22 at 15 33 10" src="https://user-images.githubusercontent.com/40070445/141643462-e98354ac-97ac-412d-9b29-72d4c4c7f2b5.png">
<img width="848" alt="Screen Shot 1400-08-22 at 15 41 43" src="https://user-images.githubusercontent.com/40070445/141643465-4de44934-cf2b-4348-980d-9792bbb5804c.png">

**Comment by spantaleev** [comment]
Looks like you're hitting some error during building. Try just cloning the official git repository, switching to a stable branch/tag and building that (without your modifications).

You don't actually need to build anything on your Mac, however. If it can build in the server, that's good enough. Pointing the playbook to your own Element fork and enabling self-building should be enough.

**Comment by MPTA** [comment]
thanks for your response, so is that fine if i just update  following 2 fields as below in mail.yaml ? 
<img width="1538" alt="Screen Shot 1400-08-23 at 11 43 17" src="https://user-images.githubusercontent.com/40070445/141673232-10ab1a55-2c52-4215-8e14-6d6b58a35610.png">

**Comment by spantaleev** [comment]
Yes, but it's important to change `matrix_client_element_version` too, as that specifies the git branch that will be built.

Looking at your repository, you'd probably wish to set `matrix_client_element_version: develop`

**Comment by MPTA** [comment]
Thanks Slavi, i have searched and problem solved by [https://stackoverflow.com/questions/26913110/allow-more-memory-when-docker-build-a-dockerfile](url)
kindest thanks again
