### ISSUE TITLE
Synapse Admin Reactivcate user

### ISSUE THREAD

**Issue by vvvilife** [spantaleev/matrix-docker-ansible-deploy#1391]
Not sure if this is appropriate here, but every time i try and reactivate a user i get 'Bad Request' in the synapse admin web ui. As an aside to this issue, is there a way to manage this outside of this?

**Comment by skepticalwaves** [comment]
Probably a question for https://github.com/Awesome-Technologies/synapse-admin/ not this ansible deployment script.
