### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by McL0v1n** [spantaleev/matrix-docker-ansible-deploy#140]
Is there anyway to get this working with IPv6? The reasoning behind it is I would like to run this on various mesh protocols (CJDNS, yggdrasil, etc).

**Comment by jdreichmann** [comment]
Yes, you need to make sure that all AAAA records point to your server. LE does support IPv6 aswell (afaik), and since all traffic terminates at the reverse nginx proxy (which should listen on :80 and :443, both IPv4 and IPv6), that should work.
