### ISSUE TITLE
Ios push notification 

### ISSUE THREAD

**Issue by MPTA** [spantaleev/matrix-docker-ansible-deploy#1413]
Hello 
i have installed own server by matrix-docker-ansible and everything works well ,every android and webapp notifications works well but only the problem ios app push notification is not working , i checked sygnal  documention , i want to know is it required to setup and config sygnal to solve this issue or any other config need to do?
thanks for your help in advance

**Comment by MPTA** [comment]
thanks for your response , i run my element ios app in my own developer appstore, so need to install sygnal and config it ?

**Comment by aaronraimist** [comment]
Yes https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-sygnal.md

**Comment by MPTA** [comment]
thank you , so if i need a developer to support me for configuration how can i find that ? i tried to find via freelancer by nobody can help.

**Comment by aaronraimist** [comment]
You can post in [#jobs:matrix.org](https://matrix.to/#/#jobs:matrix.org). I could help you but I'm quite busy through the end of the year.

**Comment by MPTA** [comment]
thanks for  your help
