### ISSUE TITLE
Replace goofys with s3fs

### ISSUE THREAD

**Issue by skepticalwaves** [spantaleev/matrix-docker-ansible-deploy#1415]
goofys seems to be dead (https://github.com/kahing/goofys/issues/662), while s3fs is very active

goofys is also missing some very nice features

Current blocker is I can't find a maintained s3fs docker container. Help wanted.

**Comment by spantaleev** [comment]
Both are very hacky and slow. From what I remember, Goofys was somewhat better, but still generally unusable.


If someone has interest in maintaining S3 support in the playbook (and figuring out if it can be optimized), that'd be great.

**Comment by skepticalwaves** [comment]
> Goofys was somewhat better, but still generally unusable.

My reading says goofys less-posix-but-faster, but there's been a lot of intervening development for s3fs-fuse, and goofys has features reported which don't actually work, in particular sse encryption which I want.

Right now I'm testing a bare-metal s3fs-fuse mount to see if its even usable. Will report back.

**Comment by spantaleev** [comment]
Wasn't s3fs trying to store file ownership (user/group) and permission mode information as S3 file metadata?

This makes it difficult to use `aws s3 sync` to sync a local directory to S3, which you can then mount with s3fs, because the files that you upload this way do not have this custom metadata.

Or is there a way to make it not do such stuff and just expose the raw files as owned by whatever user/group you tell it to?

**Comment by skepticalwaves** [comment]
> Wasn't s3fs trying to store file ownership (user/group) and permission mode information as S3 file metadata?

Yes it does do that

> This makes it difficult to use aws s3 sync to sync a local directory to S3, which you can then mount with s3fs, because the files that you upload this way do not have this custom metadata.

I'm looking into the consequences of how to get the data into S3 to start right now. Hopefully I'll have some details.

> Or is there a way to make it not do such stuff and just expose the raw files as owned by whatever user/group you tell it to?

Not that I can tell.

**Comment by spantaleev** [comment]
> I'm looking into the consequences of how to get the data into S3 to start right now. Hopefully I'll have some details.

You can get s3fs working (having it fuse-mount some directory somewhere), and then `rsync -ar` the data into that directory. If you'll be using a container for this, you'd need to mount the source directory into the container, then `docker exec` into the container, potentially install `rsync` and do the `rsync -ar` thing. It will probably take a long time though.

**Comment by skepticalwaves** [comment]
I can confirm that a s3fs mount point (manually done via fstab) on a new install does work properly without modifying the underlying ansible code.

**Comment by skepticalwaves** [comment]
s3fs was an utter failure after copying 39GB of media into a bucket and swapping the mount points.

synapse hung on start doing *something* and never woke up.

There is this to investigate
https://github.com/matrix-org/synapse-s3-storage-provider

**Comment by pratikbalar** [comment]
Can I suggest something,

Can't we use something like minio client with `mc mirror --remove --watch matrix/data s3/matrix-data-bucket/`? This will continuously mirror local files with a remote bucket back forth.

You can also add `--preserve` 

```log
--preserve, -a    preserve file(s)/object(s) attributes and bucket(s) policy/locking configuration(s) on target bucket(s)
```
---
`$ mc mirror --help`

```log
NAME:
  mc mirror - synchronize object(s) to a remote site

USAGE:
  mc mirror [FLAGS] SOURCE TARGET

FLAGS:
  --overwrite                        overwrite object(s) on target if it differs from source
  --fake                             perform a fake mirror operation
  --watch, -w                        watch and synchronize changes
  --remove                           remove extraneous object(s) on target
  --region value                     specify region when creating new bucket(s) on target (default: "us-east-1")
  --preserve, -a                     preserve file(s)/object(s) attributes and bucket(s) policy/locking configuration(s) on target bucket(s)
  --md5                              force all upload(s) to calculate md5sum checksum
  --active-active                    enable active-active multi-site setup
  --disable-multipart                disable multipart upload feature
  --exclude value                    exclude object(s) that match specified object name pattern
  --older-than value                 filter object(s) older than L days, M hours and N minutes
  --newer-than value                 filter object(s) newer than L days, M hours and N minutes
  --storage-class value, --sc value  specify storage class for new object(s) on target
  --encrypt value                    encrypt/decrypt objects (using server-side encryption with server managed keys)
  --attr value                       add custom metadata for all objects
  --monitoring-address value         if specified, a new prometheus endpoint will be created to report mirroring activity. (eg: localhost:8081)
  --encrypt-key value                encrypt/decrypt objects (using server-side encryption with customer provided keys)
  --config-dir value, -C value       path to configuration folder (default: "/home/pratik/.mc")
  --quiet, -q                        disable progress bar display
  --no-color                         disable color theme
  --json                             enable JSON lines formatted output
  --debug                            enable debug output
  --insecure                         disable SSL certificate verification
  --help, -h                         show help
  
ENVIRONMENT VARIABLES:
   MC_ENCRYPT:      list of comma delimited prefixes
   MC_ENCRYPT_KEY:  list of comma delimited prefix=secret values

EXAMPLES:
  01. Mirror a bucket recursively from MinIO cloud storage to a bucket on Amazon S3 cloud storage.
      $ mc mirror play/photos/2014 s3/backup-photos

  02. Mirror a local folder recursively to Amazon S3 cloud storage.
      $ mc mirror backup/ s3/archive

  03. Only mirror files that are newer than 7 days, 10 hours and 30 minutes to Amazon S3 cloud storage.
      $ mc mirror --newer-than "7d10h30m" backup/ s3/archive

  04. Mirror a bucket from aliased Amazon S3 cloud storage to a folder on Windows.
      $ mc mirror s3\documents\2014\ C:\backup\2014

  05. Mirror a bucket from aliased Amazon S3 cloud storage to a local folder use '--overwrite' to overwrite destination.
      $ mc mirror --overwrite s3/miniocloud miniocloud-backup

  06. Mirror a bucket from MinIO cloud storage to a bucket on Amazon S3 cloud storage and remove any extraneous
      files on Amazon S3 cloud storage.
      $ mc mirror --remove play/photos/2014 s3/backup-photos/2014

  07. Continuously mirror a local folder recursively to MinIO cloud storage. '--watch' continuously watches for
      new objects, uploads and removes extraneous files on Amazon S3 cloud storage.
      $ mc mirror --remove --watch /var/lib/backups play/backups

  08. Continuously mirror all buckets and objects from site 1 to site 2, removed buckets and objects will be reflected as well.
      $ mc mirror --remove --watch site1-alias/ site2-alias/

  09. Mirror a bucket from aliased Amazon S3 cloud storage to a local folder.
      Exclude all .* files and *.temp files when mirroring.
      $ mc mirror --exclude ".*" --exclude "*.temp" s3/test ~/test

  10. Mirror objects newer than 10 days from bucket test to a local folder.
      $ mc mirror --newer-than 10d s3/test ~/localfolder

  11. Mirror objects older than 30 days from Amazon S3 bucket test to a local folder.
      $ mc mirror --older-than 30d s3/test ~/test

  12. Mirror server encrypted objects from MinIO cloud storage to a bucket on Amazon S3 cloud storage
      $ mc mirror --encrypt-key "minio/photos=32byteslongsecretkeymustbegiven1,s3/archive=32byteslongsecretkeymustbegiven2" minio/photos/ s3/archive/

  13. Mirror server encrypted objects from MinIO cloud storage to a bucket on Amazon S3 cloud storage. In case the encryption key contains
      non-printable character like tab, pass the base64 encoded string as key.
      $ mc mirror --encrypt-key "s3/photos/=32byteslongsecretkeymustbegiven1,play/archive/=MzJieXRlc2xvbmdzZWNyZXRrZQltdXN0YmVnaXZlbjE=" s3/photos/ play/archive/

  14. Update 'Cache-Control' header on all existing objects recursively.
      $ mc mirror --attr "Cache-Control=max-age=90000,min-fresh=9000" myminio/video-files myminio/video-files

  15. Mirror a local folder recursively to Amazon S3 cloud storage and preserve all local file attributes.
      $ mc mirror -a backup/ s3/archive

  16. Cross mirror between sites in a active-active deployment.
      Site-A: $ mc mirror --active-active siteA siteB
      Site-B: $ mc mirror --active-active siteB siteA
```

I don't know how architecturally relevant this is but just a suggestion.

**Comment by spantaleev** [comment]
This seems like a way to mirror files to S3, but mirroring does not solve the problem that I think most people are trying to use S3 to solve.

I think most people are reaching for an object store, because they'd like to use a cheap VPS with little storage combined with some "unlimited" object storage for their media store. These people want all files to be stored in the object store, without a local copy existing on disk (since they don't have enough disk space for all that).

Ideally, Synapse would have native support for object stores, so we wouldn't have to rely on hacks (Synapse supporting only the local filesystem, and us faking a local filesystem, which is backed by object storage).

From what I remember, [synapse-s3-storage-provider](https://github.com/matrix-org/synapse-s3-storage-provider) insisted on saving files locally and then copying that content to S3 - thus storing the same file twice (for backup reasons?). Perhaps with `store_local: False` and `store_remote: True`, it could be made to run with S3 as the single storage backend?

Next problem becomes, how do we easily run `synapse-s3-storage-provider`. It's not part of the Synapse container image and just mounting its code into the Synapse container will not be enough, since it requires `boto3` and a bunch of other dependencies: https://github.com/matrix-org/synapse-s3-storage-provider/blob/8926b4e4178edcda1a32fdb39bd36cef1a1a9d40/setup.py#L23-L31

**Comment by pratikbalar** [comment]
> (since they don't have enough disk space for all that).

Ahh, totally slipped from my mind
