### ISSUE TITLE
Increase max file size upload

### ISSUE THREAD

**Issue by jonesthesubmarine** [spantaleev/matrix-docker-ansible-deploy#142]
Hello, ansible and docker beginner here. Is there an easy way to increase file size from 10M to something bigger? I followed the guide and it's all working but I'm not real sure how to edit this setting. Maybe in the homeserver.yaml or the nginx config?

**Comment by aaronraimist** [comment]
Yes, you would set `matrix_synapse_max_upload_size_mb` to the size you want in your `vars.yml` file. So if you want 100 MB as the limit, set `matrix_synapse_max_upload_size_mb: 100`.

Using this setup you'll want to avoid changing the `homeserver.yaml` or nginx config individually and instead change these variables, which in this case will change both for you.

The way you would find what the variables name is would be to look at https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/templates/synapse/homeserver.yaml.j2 or the nginx config, or whatever you want to change, and more than likely there is already a variable setup to change that.

**Comment by aaronraimist** [comment]
In the future, it is probably easier and quicker to get help in our #matrix-docker-ansible-deploy:devture.com room rather than on GitHub issues :)

**Comment by jonesthesubmarine** [comment]
Hey thanks for the help.

One last thing; since I started my services, created users and rooms I'll have to backup my database and media folder, reconfigure and restore the data?

**Comment by aaronraimist** [comment]
Nope! That would be annoying if you had to do that 😄. You can change almost any setting and all you need to do is rerun the setup-all and start tags. The only things you can't change now would be things like `matrix_synapse_macaroon_secret_key` or `matrix_synapse_password_config_pepper`.

As it says https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/installing.md#installing 
> Feel free to re-run this any time

and you will want to continually do this over time to make sure you stay up to date with the latest software, see https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md on how to do that.

**Comment by SlayerOFWrly** [comment]
> Yes, you would set `matrix_synapse_max_upload_size_mb` to the size you want in your `vars.yml` file. So if you want 100 MB as the limit, set `matrix_synapse_max_upload_size_mb: 100`.
> 
> Using this setup you'll want to avoid changing the `homeserver.yaml` or nginx config individually and instead change these variables, which in this case will change both for you.
> 
> For other settings you might want to change: The way you would find what the variables name is, would be to look at https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/templates/synapse/homeserver.yaml.j2 or the nginx config, or whatever you want to change, and more than likely there is already a variable setup to change that.

I don't mean to harp on an old thread but this doesn't seem to be working for me. I set the max upload size in the vars.yml config, matrix_synapse_max_upload_size_mb: 2 but I can still upload files beyond the specified 2 at a default user power level. Any ideas why this would be? I do use the playbook auto configured Traefik setup so maybe there is some further config required there? Thanks
