### ISSUE TITLE
homeserver is not sending email anymore

### ISSUE THREAD

**Issue by nebocamin** [spantaleev/matrix-docker-ansible-deploy#1421]
Hi,

I am using email relay and it stopped working. turning it of by commenting out the matrix-mailer-relay* doesn't helped either. Something outside my config changed that broke it. On the side of the mail server is silence. It is not even trying to reach it.

Here is an example from matrix-synapse as I tried to register myself on the server:

`

> Nov 26 22:38:43 v2202102141459143382 matrix-synapse[486281]: 2021-11-26 21:38:43,296 - synapse.rest.client.register - 540 - WARNING - POST-353 - Ignoring initial_device_display_name without password
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: 2021-11-26 21:39:01,109 - synapse.handlers.identity - 414 - ERROR - POST-390 - Error sending threepid validation email to iamnew@wonderfullmatrix.org
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: Traceback (most recent call last):
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/identity.py", line 412, in send_threepid_validation
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:     await send_email_func(email_address, token, client_secret, session_id)
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:   File "/usr/local/lib/python3.8/site-packages/synapse/push/mailer.py", line 170, in send_registration_mail
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:     await self.send_email(
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:   File "/usr/local/lib/python3.8/site-packages/synapse/push/mailer.py", line 318, in send_email
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:     await self.send_email_handler.send_email(
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/send_email.py", line 180, in send_email
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:     await self._sendmail(
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/send_email.py", line 116, in _sendmail
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]:     await make_deferred_yieldable(d)
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: twisted.mail._except.AUTHRequiredError: 502 Server does not support Client Authentication schemes [CRAM-MD5, LOGIN, PLAIN]
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: <<< 250-PIPE_CONNECT
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: <<< 250-CHUNKING
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: <<< 250-PRDR
> Nov 26 22:39:01 v2202102141459143382 matrix-synapse[486281]: <<< 250 HELP

`

in the vars.yml I have those as related settings:

matrix_ma1sd_enabled: false

matrix_synapse_registrations_require_3pid: ['email']

matrix_mailer_sender_address: "matrix@ourdomain"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "mail.ourdomain"
matrix_mailer_relay_host_port: 25
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "matrix"

**Comment by nebocamin** [comment]
a user mentioned this commit as a possible cause: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/d41e9230da30a5f12beac49ad4d66c53d8750f2d

**Comment by nebocamin** [comment]
i switched from matrix_mailer_relay* to matrix_synapse_email*

```

> matrix_synapse_email_smtp_user: "matrix"
> matrix_synapse_email_smtp_pass: "verystrongpasswd"
> matrix_synapse_email_enabled: true
> matrix_synapse_email_smtp_host: "mail.ourdomain"
> matrix_synapse_email_smtp_port: 25

```

**Comment by skepticalwaves** [comment]
Yes, it looks to me like this commit failed to use an if statement to fill in these values.
