### ISSUE TITLE
Unable to move the media_store directory

### ISSUE THREAD

**Issue by MattieX** [spantaleev/matrix-docker-ansible-deploy#1428]
I'm currently using LVM On Linux and considering the largest part of a Matrix Server tends to be the `media_store` directory - I'd like to move it to an LVM location so that I can easily increase the space over time rather than increasing the space for the rest of the system.

I have tried modifying the following variables in the `vars.yml`
```
matrix_synapse_media_store_path: "/mnt/media_store_lv/storage/media_store"
matrix_synapse_storage_path: "/mnt/media_store_lv/storage"
```

I have copied my current `media_store` directory to this new location and created the appropriate directory structure

After running `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start --ask-pass` and uploading any media to my matrix server, I get a `500` error returned with an 'upload failed' message.

Any help would be appreciated.

**Comment by aaronraimist** [comment]
What is the error in the Synapse logs? It could be a permissions issue.

`sudo journalctl -fu matrix-synapse`

**Comment by MattieX** [comment]
> What is the error in the Synapse logs? It could be a permissions issue.
> 
> `sudo journalctl -fu matrix-synapse`

Ah good point, I forgot to check that - it was a permissions issue.

![image](https://user-images.githubusercontent.com/21284075/144292781-bd37a2c5-a8af-46bd-83f3-d611f24d6ed2.png)

Above was what was in the logs, I fixed it by chowning recursively the storage directory to the owner and group of `matrix`.

Thanks for the suggestion.
