### ISSUE TITLE
Integrate matrix-registration

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#143]
https://github.com/zeratax/matrix-registration

**Comment by jdreichmann** [comment]
Looks interesting, but from what i see, we'd need to put that in a container first.. putting it in the riot-web container seems kinda hacky, so we would either need to build our own public container or build it in the playbook

**Comment by spantaleev** [comment]
Contributing a `Dockerfile` to the [matrix-registration](https://github.com/zeratax/matrix-registration) repository sounds better than making it and keeping that file only here.

I'm guessing @ZerataX might be happy to accept a `Dockerfile` contribution and to build/push a Docker image as part of the release process.

----------

We could then proceed to make the playbook install it.

An important decision would probably be to figure out which domain to use for serving matrix-registration (when reverse-proxying from `matrix-nginx-proxy`).

Only `matrix.DOMAIN` is guaranteed to be available. `riot.DOMAIN` may not be (if `matrix_riot_web_enabled: false`).

However, serving it from `matrix.DOMAIN` sounds more dangerous for the same reason riot-web warns against it in its [Important Security Notice](https://github.com/vector-im/riot-web#important-security-note).

Using yet another domain (`matrix-registration.DOMAIN`) might be possible, but I worry we'd be introducing too many domains that need to be set up and maintained (especially for people who manage their certificates manually, etc.)

**Comment by emiliogon** [comment]
I hope progress will be made on this request, or any other solution that would avoid manual account creation _and_ open registration for a private server:

- Generate invitation links
- Send email invitations
- New account review & approval queue

**Comment by ZerataX** [comment]
fwiw: there is a dockerfile that I haven't tested https://github.com/henry-nicolas/docker-mxreg

I've been pretty busy so nothing has really progressed, but I would really love to contribute to this project.

> - Generate invitation links
> - Send email invitations

Is probably both pretty easily doable with matrix-registration (though sending email is not yet a thing, but probably will be)
Account review & approval isn't really what I had in mind when I made this, so I'm not sure how much sense it makes to have tokens + review?

Probably makes more sense to look at https://github.com/krombel/matrix-register-bot for that?

**Comment by ZerataX** [comment]
>  putting it in the riot-web container seems kinda hacky,

the one good reason to do that would be so you could overwrite `/#/register` on your riot instance.
I know for sure that someone integrated matrix-registration for riot-web, but I sadly can not find the fork

**Comment by prasket** [comment]
What is the latest on adding a user self-registration option to this project?

**Comment by tctovsli** [comment]
I see that there is a Dockerfile available there now: https://github.com/ZerataX/matrix-registration/blob/master/Dockerfile

**Comment by spantaleev** [comment]
I've built an unofficial image here: [devture/zeratax-matrix-registration](https://hub.docker.com/r/devture/zeratax-matrix-registration) and added support to the playbook via da38a7869f91f01.

See our [Setting up matrix-registration](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-matrix-registration.md) documentation page to get started.
