### ISSUE TITLE
matrix-synapse isn't starting after install with ansible

### ISSUE THREAD

**Issue by tardar** [spantaleev/matrix-docker-ansible-deploy#1435]
Hi guys,

i installed matrix with ansible and some services are running:

But matrix-synapse isn't running because he can't find the ssl certificate i think.
Are anyone here who got a idea how to fix that?
thanks a lot :)

PS: I installed with an extra user (not root) - the setup with ansible runs normally through without an error.

This is the journal of the matrix-synapse service.

> Dez 04 00:25:32 matrix matrix-synapse[30486]: This server is configured to use 'matrix.org' as its trusted key server via the
Dez 04 00:25:32 matrix matrix-synapse[30486]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Dez 04 00:25:32 matrix matrix-synapse[30486]: server since it is long-lived, stable and trusted. However, some admins may
Dez 04 00:25:32 matrix matrix-synapse[30486]: wish to use another server for this purpose.
Dez 04 00:25:32 matrix matrix-synapse[30486]: To suppress this warning and continue using 'matrix.org', admins should set
Dez 04 00:25:32 matrix matrix-synapse[30486]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Dez 04 00:25:32 matrix matrix-synapse[30486]: --------------------------------------------------------------------------------
Dez 04 00:25:32 matrix matrix-synapse[30486]: This server is using a spam checker module that is implementing the deprecated spam
Dez 04 00:25:32 matrix matrix-synapse[30486]: checker interface. Please check with the module's maintainer to see if a new version
Dez 04 00:25:32 matrix matrix-synapse[30486]: supporting Synapse's generic modules system is available.
Dez 04 00:25:32 matrix matrix-synapse[30486]: For more information, please see https://matrix-org.github.io/synapse/latest/modules.html
Dez 04 00:25:32 matrix matrix-synapse[30486]: ---------------------------------------------------------------------------------------
Dez 04 00:25:32 matrix matrix-synapse[30486]: 2021-12-03 23:25:32,946 - root - 345 - WARNING - main - ***** STARTING SERVER *****
Dez 04 00:25:32 matrix matrix-synapse[30486]: 2021-12-03 23:25:32,946 - root - 346 - WARNING - main - Server /usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py version 1.48.0
Dez 04 00:25:33 matrix matrix-synapse[30486]: 2021-12-03 23:25:33,056 - synapse.app._base - 241 - CRITICAL - sentinel - Error during startup
Dez 04 00:25:33 matrix matrix-synapse[30486]: Traceback (most recent call last):
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 891, in read_file
Dez 04 00:25:33 matrix matrix-synapse[30486]:     os.stat(file_path)
Dez 04 00:25:33 matrix matrix-synapse[30486]: FileNotFoundError: [Errno 2] No such file or directory: '/data/matrix.xyz.tld.tls.key'
Dez 04 00:25:33 matrix matrix-synapse[30486]: The above exception was the direct cause of the following exception:
Dez 04 00:25:33 matrix matrix-synapse[30486]: Traceback (most recent call last):
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/app/_base.py", line 226, in wrapper
Dez 04 00:25:33 matrix matrix-synapse[30486]:     await cb(*args, **kwargs)
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 388, in start
Dez 04 00:25:33 matrix matrix-synapse[30486]:     await _base.start(hs)
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/app/_base.py", line 428, in start
Dez 04 00:25:33 matrix matrix-synapse[30486]:     refresh_certificate(hs)
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/app/_base.py", line 350, in refresh_certificate
Dez 04 00:25:33 matrix matrix-synapse[30486]:     hs.config.tls.read_certificate_from_disk()
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/tls.py", line 139, in read_certificate_from_disk
Dez 04 00:25:33 matrix matrix-synapse[30486]:     self.tls_private_key = self.read_tls_private_key()
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/tls.py", line 260, in read_tls_private_key
Dez 04 00:25:33 matrix matrix-synapse[30486]:     private_key_pem = self.read_file(private_key_path, "tls_private_key_path")
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 207, in read_file
Dez 04 00:25:33 matrix matrix-synapse[30486]:     return read_file(file_path, (config_name,))
Dez 04 00:25:33 matrix matrix-synapse[30486]:   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 895, in read_file
Dez 04 00:25:33 matrix matrix-synapse[30486]:     raise ConfigError("Error accessing file %r" % (file_path,), config_path) from e
Dez 04 00:25:33 matrix matrix-synapse[30486]: synapse.config._base.ConfigError: ("Error accessing file '/data/matrix.xyz.tld.tls.key'", ('tls_private_key_path',))
Dez 04 00:25:33 matrix systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE

Thanks and have a nice day :)
If any more infos are needed please tell me ;)

**Comment by tardar** [comment]
no one has an idea?

**Comment by aaronraimist** [comment]
Can you post your `vars.yml` file? Make sure to redact the secret keys.

**Comment by tardar** [comment]
Yes,

here is my vars.yml attached to this comment
[vars_anonymisiert.yml.zip](https://github.com/spantaleev/matrix-docker-ansible-deploy/files/7683012/vars_anonymisiert.yml.zip)
.


Thanks a lot :)

**Comment by aaronraimist** [comment]
Wow that's a large one. I'm not sure why you have so much stuff in there. It looks to me like at least 70% of that is just the default values (many of which are for services you have disabled). You only need to add something to your `vars.yml` when you need to customize an option. If you are happy with the default then it shouldn't be in your `vars.yml` file.

Try to install with a basic setup using only these five options https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/examples/vars.yml. Once it is installed you can work on customizing it as you see fit. I'm not going to read through all 2000 lines of your config file but I'm guessing you have made some misconfiguration in there.
