### ISSUE TITLE
Postgres Version changed from 14 to 13.3 after git pull making files incompatible

### ISSUE THREAD

**Issue by jalemann** [spantaleev/matrix-docker-ansible-deploy#1448]
Hi, I just pulled the latest commits and tried to update my by running `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all` and `ansible-playbook -i inventory/hosts setup.yml --tags=start`.

However the setup-all failed with:
```
TASK [matrix-postgres : Execute Postgres additional database initialization SQL file for synapse] *****************************************
fatal: [matrix.alemann.dev]: FAILED! => changed=true 
  cmd:
  - /usr/bin/env
  - docker
  - run
  - --rm
  - --user=997:1000
  - --cap-drop=ALL
  - --env-file=/matrix/postgres/env-postgres-psql
  - --network
  - matrix
  - --mount
  - type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro
  - --entrypoint=/bin/sh
  - docker.io/postgres:13.3-alpine
  - -c
  - psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql
  delta: '0:00:06.939004'
  end: '2021-12-09 17:56:25.786556'
  msg: non-zero return code
  rc: 2
  start: '2021-12-09 17:56:18.847552'
  stderr: 'psql: error: could not translate host name "matrix-postgres" to address: Try again'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
  
When running the command with `--tags=start` it tells me to check if `matrix-postgres` is running and further inspecting via `journalctl -fu matrix-postgres.service` reveals the following:

```
ec 09 17:59:09 815598B systemd[1]: matrix-postgres.service: Scheduled restart job, restart counter is at 146.
Dec 09 17:59:09 815598B systemd[1]: Stopped Matrix Postgres server.
Dec 09 17:59:09 815598B systemd[1]: Starting Matrix Postgres server...
Dec 09 17:59:09 815598B systemd[1]: Started Matrix Postgres server.
Dec 09 17:59:10 815598B matrix-postgres[63803]: chmod: /var/run/postgresql: Operation not permitted
Dec 09 17:59:10 815598B matrix-postgres[63803]: PostgreSQL Database directory appears to contain a database; Skipping initialization
Dec 09 17:59:10 815598B matrix-postgres[63803]: 2021-12-09 17:59:10.909 UTC [1] FATAL:  database files are incompatible with server
Dec 09 17:59:10 815598B matrix-postgres[63803]: 2021-12-09 17:59:10.909 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 13.3.
Dec 09 17:59:11 815598B systemd[1]: matrix-postgres.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 17:59:11 815598B systemd[1]: matrix-postgres.service: Failed with result 'exit-code'.
```

So for me the expected PostgreSQL version seems to have changed from 14 to 13.3 after the latest `git pull`.

Running `ansible-playbook -i inventory/hosts setup.yml --tags=upgrade-postgres` returns/fails with the following message:
```
TASK [matrix-postgres : Abort, if already at latest Postgres version] *********************************************************************
fatal: [matrix.alemann.dev]: FAILED! => changed=false 
  msg: You are already running the latest Postgres version supported (docker.io/postgres:13.3-alpine). Nothing to do
```

How can I use PostgreSQL 14 again?

**Comment by spantaleev** [comment]
It does appear that `matrix_postgres_docker_image_latest` is set to `docker.io/postgres:13.3-alpine` for you.

This doesn't sound right. Check the `matrix_postgres_docker_image_latest` definition in `roles/matrix-postgres/defaults/main.yml`.

Our source code is currently like this: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/fc55df9318efb28d17295293adf3a6edf7ab4b84/roles/matrix-postgres/defaults/main.yml#L26

We're pointing `_latest` to `_v14`, which is usually `docker.io/postgres:14.1-alpine`.

-----

I'm guessing you "pulled the latest source code" incorrectly somehow, or you're redefining `matrix_postgres_docker_image_latest` somewhere in your `vars.yml` file.

**Comment by jalemann** [comment]
Thank you! This line was in deed the cause of the problem. I will review my git settings.

**Comment by jalemann** [comment]
Update: I was quite stupid, linked to some fork instead of this repo and didn't notice.
