### ISSUE TITLE
Appservices should go via nginx?

### ISSUE THREAD

**Issue by HarHarLinks** [spantaleev/matrix-docker-ansible-deploy#1449]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/a9e222d5238af3a76e8d77e2ef7801a05662dbdc/roles/matrix-bridge-appservice-webhooks/templates/config.yaml.j2#L5

I'm debugging this appservice on my synapse with one-of-each workers, that means especially media repo worker.
It ends up doing
```
POST http://matrix-synapse:8008/_matrix/media/r0/upload (AS) HTTP 404 Error
```
because that is all it knows about via the above config, there isn't an extra setting for the media repo url.

I am advised in https://matrix.to/#/#synapse:matrix.org that appservices are supposed to connect via reverse proxy in worker setups, "just like all other clients". I think that would be `matrix-nginx-proxy:12080` (`matrix_nginx_proxy_proxy_matrix_client_api_addr_with_container`, but you probably want to copy that to a "global" variable) rather than `matrix-synapse:8008`, which indeed works for me. This should probably be done for all bridges then?

**Comment by spantaleev** [comment]
You're right! I've fixed this. I believe most bridges were already using this. It was just appservice-slack and appservice-webhooks that were trying to talk to Synapse directly. Using `matrix_homeserver_container_url` is better and more future-proof (in the future, it may even go to different homeserver software, other than Synapse).

Thank you for bringing this up!
