### ISSUE TITLE
Is it possible to run one role ?

### ISSUE THREAD

**Issue by MPTA** [spantaleev/matrix-docker-ansible-deploy#1453]
i want to know is it possible to run only one specific role to setup or update the app ?
if yes how can do it , thanks

**Comment by aaronraimist** [comment]
There are tags to configure the individual services such as `setup-synapse` and `setup-nginx-proxy`. Just remember that some things that may seem to only affect a single service actually require configuration changes across multiple services, such as `matrix_synapse_max_upload_size_mb`.

There are no tags to restart individual services though, you would have to do that on the server with `systemctl`.
