### ISSUE TITLE
Element version: !!UNSET!!

### ISSUE THREAD

**Issue by drasbeck** [spantaleev/matrix-docker-ansible-deploy#1454]
For about a week I've been seeing the following error:

![image](https://user-images.githubusercontent.com/8578706/145719470-f5d7b13e-7b91-4e89-b6d6-fc85e55135a6.png)

The issue is with element-web and is discussed [here](https://github.com/vector-im/element-web/issues/20074)
Furthermore it should fixed according according to these PRs: [#20077](https://github.com/vector-im/element-web/pull/20077) and [#20078](https://github.com/vector-im/element-web/pull/20078)

Looking into our repository it sure looks like we pull the correct version for a fix. However I don't see the change in my relatively vanilla use of our Ansible playbook.

The error "only" causes a frequent "update Element" prompt, which is vaguely annoying to look at/dismiss. But I think it deserves a fix nonetheless if possible.

**Comment by spantaleev** [comment]
Are you self-building Element using the playbook or are you using the pre-built image?

Are you running your Matrix server on a non-`amd64` server by any chance (which would automatically enable self-building)?

**Comment by drasbeck** [comment]
I am using vanilla settings with regards to element-web, so I am not sure if I am self-building or not.

But my architecture is amd64.

**Comment by Pihrra** [comment]
I'm having the same issue, using the pre-built image on a amd64 vps.

**Comment by spantaleev** [comment]
If you're observing this with the pre-built image, then it's not the playbook's fault. We're using the official image produced by the Element team. You can report the bug there: https://github.com/vector-im/element-web/

**Comment by Pihrra** [comment]
Looking at https://github.com/vector-im/element-web/issues/20074 it seems the fixed image was reissued with the same version number. Manually pulling the image again fixed the issue.
`docker pull vectorim/element-web:v1.9.6`

**Comment by drasbeck** [comment]
Thanks for your help, both. Pulling the image again did the trick. So I am satisfied, but other users might still be experiencing this issue.

I guess the problem lies with the reissue. Can we somehow improve the playbook to take such instances into account?

**Comment by aaronraimist** [comment]
It's a super rare thing for the image to be messed up and then uploaded again with the exact same tag. Element is about to release a new version in 30 minutes anyway so it probably doesn't need to be addressed.

**Comment by drasbeck** [comment]
Fair enough. My suggestion would be to just pull the image again as part of running the playbook, as the action is rather quickly resolved if nothing has changed.

I am, however, not used to working in Ansible, and don't know best practice yet. So I respect your answer. 😊

**Comment by drasbeck** [comment]
This issue can be marked as resolved and closed.

And thanks for the great work with the playbook.
