### ISSUE TITLE
Please advise users to update immediately if they are using matrix-mautrix-signal

### ISSUE THREAD

**Issue by theCalcaholic** [spantaleev/matrix-docker-ansible-deploy#1459]
It is currently hard to determine if any of the services in matrix-docker-ansible-deploy is affected by the log4j CVE. It would be great to have that information more accessible (maybe a pinned issue)?

**Comment by theCalcaholic** [comment]
See #1452

**Comment by spantaleev** [comment]
Fixed in a8fc4fe

**Comment by theCalcaholic** [comment]
That's great, thank you. I should join that room :)

**Comment by theCalcaholic** [comment]
@spantaleev I seem to have no permissions to list rooms on your server and thus, can't join that room. Is this intended?

**Comment by spantaleev** [comment]
I'm running with default configuration for which (`matrix_synapse_allow_public_rooms_over_federation: false`), so you probably can't list the (public) room directory for my server.

Still, I believe that you should be able to join the `#matrix-docker-ansible-deploy:devture.com` room, given that you know the address. Try `/join #matrix-docker-ansible-deploy:devture.com` in Element

**Comment by theCalcaholic** [comment]
Thanks, Joining actually worked after some time (although I received an error message at first).
