### ISSUE TITLE
the federation is not working anymore using caddy v2

### ISSUE THREAD

**Issue by GodGoldfish** [spantaleev/matrix-docker-ansible-deploy#1484]
Hi,
i recently edited my vars.yml so i could use my caddy proxy (2.4.6) at the place of the default nginx proxy so i could get certs with caddy but since that the matrix federation doesn't work anymore

my caddy config :
```
example.abc,
matrix.example.abc,
element.example.abc,
jitsi.example.abc,
dimension.example.abc {
 reverse_proxy 127.0.0.1:8080
}
```

my vars.yml config :
```
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: '127.0.0.1:8080'
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_nginx_proxy_trust_forwarded_proto: true
matrix_nginx_proxy_ssl_protocols: "TLSv1.3"
```

**Comment by spantaleev** [comment]
We have Caddy v1 and v2 examples here: https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/examples

**Comment by GodGoldfish** [comment]
my problem is that i don't know what to add to my configuration even if i read those examples.
it would be nice to tell me what's worng with my configuration.

**Comment by spantaleev** [comment]
In short, you're not handling port `8448` (`matrix.DOMAIN:8448`) which is used for federation.

You'll need this at least: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/94a8af58cc6ca3ab5ab9e93cad01f03598e2f0d1/examples/caddy2/Caddyfile#L98-L110

**Comment by GodGoldfish** [comment]
> In short, you're not handling port `8448` (`matrix.DOMAIN:8448`) which is used for federation.
> 
> You'll need this at least:
> 
> https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/94a8af58cc6ca3ab5ab9e93cad01f03598e2f0d1/examples/caddy2/Caddyfile#L98-L110

by adding :
```
matrix.DOMAIN.tld:8448 { 
     handle { 
         encode zstd gzip 
  
         reverse_proxy 127.0.0.1:8048 { 
                header_up X-Forwarded-Port {http.request.port} 
                header_up X-Forwarded-Proto {http.request.scheme} 
                header_up X-Forwarded-TlsProto {tls_protocol} 
                header_up X-Forwarded-TlsCipher {tls_cipher} 
                header_up X-Forwarded-HttpsProto {proto} 
         } 
     } 
 } 
```

i still get the same error like before adding it with the https://federationtester.matrix.org/ 
```
Connection Errors
Get "https://IPV4:8448/_matrix/key/v2/server": http: server gave HTTP response to HTTPS clientGet "https://IPV6:8448/_matrix/key/v2/server": dial tcp [IVP6]:8448: connect: connection refused
```

and also when i tried to use federation functionalities it's not working
(none of my ports are blocked)

**Comment by francislavoie** [comment]
Since `:8448` doesn't look like an HTTPS port, you might need to specify `https://` in front to make sure Caddy actually serves HTTPS for that site.

```
https://matrix.example.com:8448 { 
	...
}
```

**Comment by GodGoldfish** [comment]
> Since `:8448` doesn't look like an HTTPS port, you might need to specify `https://` in front to make sure Caddy actually serves HTTPS for that site.
> 
> ```
> https://matrix.example.com:8448 { 
> 	...
> }
> ```

this has fixed 
```
Connection Errors
Get "https://IPV4:8448/_matrix/key/v2/server": http: server gave HTTP response to HTTPS clientGet "https://IPV6:8448/_matrix/key/v2/server": dial tcp [IVP6]:8448: connect: connection refused
```
but now i have :
```
dial tcp [IVP4]:8448: connect: connection refused
dial tcp [IVP6]:8448: connect: connection refused
```
my SRV is good and i didn't change it since i changed from nginx (SRV | _matrix-identity._tcp | 10 | 0 | 443 matrix.domain.tld).

**Comment by GodGoldfish** [comment]
adding "https://" fixed the error 
`http: server gave HTTP response to HTTPS client`
but sill can't use the federation.

(this is the json report from the federation tester).
here is my json report :
```
{
  "WellKnownResult": {
    "m.server": "matrix..example.tld:8448",
    "CacheExpiresAt": 1640702559
  },
  "DNSResult": {
    "SRVSkipped": true,
    "SRVCName": "",
    "SRVRecords": null,
    "SRVError": null,
    "Hosts": {
      "matrix..example.tld": {
        "CName": "example.tld.",
        "Addrs": [
          "IPV6",
          "IPV4"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "[IPV6]:8448",
      "IPV4:8448"
    ]
  },
  "ConnectionReports": {},
  "ConnectionErrors": {
    "IPV4:8448": {
      "Message": "Non-200 response 502 from remote server"
    },
    "[IPV6]:8448": {
      "Message": "Non-200 response 502 from remote server"
    }
  },
  "Version": {
    "error": "contents=[] msg=Failed to GET JSON (hostname \"matrix.example.tld:8448\" path \"/_matrix/federation/v1/version\"):  code=502 wrapped="
  },
  "FederationOK": false
}
```
i changed my vars.yml in the hope to fix something but it doesn't seems to help.
(all my ports are open)
my vars.yml :
```
matrix_nginx_proxy_enabled: true
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_ssl_protocols: "TLSv1.3"
matrix_nginx_proxy_container_http_host_bind_port: '127.0.0.1:81'
matrix_nginx_proxy_container_federation_host_bind_port: '127.0.0.1:8449'
matrix_synapse_federation_enabled: true
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_nginx_proxy_trust_forwarded_proto: true
matrix_nginx_proxy_x_forwarded_for: '$proxy_add_x_forwarded_for'
```
my Caddyfile :
```
https://example.tld,
https://matrix.example.tld,
https://element.example.tld
https://hydrogen.example.tld,
https://jitsi.example.tld,
https://dimension.example.tld {
 reverse_proxy 127.0.0.1:81
}

https://matrix.example.tld:8448 {
 reverse_proxy 127.0.0.1:8048
}
```
my dns records :
```
;; A Records
example.tld.	1	IN	A	IPV4

;; AAAA Records
example.tld.	1	IN	AAAA	IPV6

;; CNAME Records
dimension.example.tld.	1	IN	CNAME	matrix.example.tld.
element.example.tld.	1	IN	CNAME	matrix.example.tld.
hydrogen.example.tld.	1	IN	CNAME	matrix.example.tld.
jitsi.example.tld.	1	IN	CNAME	matrix.example.tld.
matrix.example.tld.	1	IN	CNAME	example.tld.

;; SRV Records
_matrix-identity._tcp.example.tld.	1	IN	SRV	10 0 443 matrix.example.tld.

```

**Comment by GodGoldfish** [comment]
ok i found out i was just stupidly making a typo on the caddyfile :
```
https://matrix.example.tld:8448 {
 reverse_proxy 127.0.0.1:8048
}
```
at the place of :
```
https://matrix.example.tld:8448 {
 reverse_proxy 127.0.0.1:8449
}
```

Thanks to everyone that gave help !
