### ISSUE TITLE
Unable to allow user registration

### ISSUE THREAD

**Issue by parth-choudhary** [spantaleev/matrix-docker-ansible-deploy#150]
I have added `matrix_synapse_enable_registration: true` in my `inventory/host_vars/matrix{{domain}}/vars.yml` but when I run `docker exec -it matrix-synapse cat /data/homeserver.yaml | grep enable_registration` I get `enable_registration: false`

So somehow the configuration is not passing to the docker. Any idea whats the issue?

**Comment by spantaleev** [comment]
I haven't been able to reproduce this.

----------

For changes to get applied to configuration files, you need to re-run the playbook: `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all`

Furthermore, for changes to actually take effect, you need to restart services: `ansible-playbook -i inventory/hosts setup.yml --tags=start`

.. or you could do both things in one go like this: `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start`
