### ISSUE TITLE
Appservice webhooks failed

### ISSUE THREAD

**Issue by rdaries** [spantaleev/matrix-docker-ansible-deploy#1501]
TASK [matrix-bridge-appservice-webhooks : Ensure Appservice webhooks Docker image is built] *****************************************************************************************************
fatal: [matrix.domain.tld]: FAILED! => changed=false 
  msg: 'Error building localhost/redoonetworks/matrix-appservice-webhooks - code: 1, message: The command ''/bin/sh -c npm install'' returned a non-zero code: 1, logs: [''Step 1/29 : FROM node:12-alpine AS base'', '''', ''Pulling from library/node'', ''Digest: sha256:8fad09b7620b2bc715cbba92e3313c64a797e453f560118576f1740a44584d5d'', ''Status: Image is up to date for node:12-alpine'', '' ---> ce1b097ce235'', ''Step 2/29 : RUN apk upgrade --no-cache'', '''', '' ---> Using cache'', '' ---> 2fe5f1f8c559'', ''Step 3/29 : RUN apk add --no-cache ca-certificates'', '''', '' ---> Using cache'', '' ---> a36a11510350'', ''Step 4/29 : FROM base AS build'', '''', '' ---> a36a11510350'', ''Step 5/29 : ENV NODE_ENV=development'', '''', '' ---> Using cache'', '' ---> c85d26511eef'', ''Step 6/29 : RUN apk add --no-cache     make gcc g++ python3 libc-dev wget git dos2unix'', '''', '' ---> Using cache'', '' ---> d3d841eebaee'', ''Step 7/29 : WORKDIR /srv/matrix-appservice-webhooks'', '''', '' ---> Using cache'',
    '' ---> 1847f30ade30'', ''Step 8/29 : COPY package.json ./'', '''', '' ---> Using cache'', '' ---> 9940376c6ffd'', ''Step 9/29 : COPY package-lock.json ./'', '''', '' ---> Using cache'', '' ---> 406f64b6b4e4'', ''Step 10/29 : COPY index.js ./'', '''', '' ---> Using cache'', '' ---> 6215439beb89'', ''Step 11/29 : COPY src ./src'', '''', '' ---> Using cache'', '' ---> fa4566d62fa7'', ''Step 12/29 : COPY config ./config'', '''', '' ---> Using cache'', '' ---> 531382ee2fad'', ''Step 13/29 : COPY migrations ./migrations'', '''', '' ---> Using cache'', '' ---> b89eb7741841'', ''Step 14/29 : RUN npm install'', '''', '' ---> Running in 6cd95286d3fe'', '''', ''> sqlite3@4.2.0 install /srv/matrix-appservice-webhooks/node_modules/sqlite3'', ''> node-pre-gyp install --fallback-to-build'', '''', ''\x1b[91mnode-pre-gyp\x1b[0m'', ''\x1b[91m WARN Using request for node-pre-gyp https download '', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp \x1b[0m'', ''\x1b[91mWARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v72-linux-arm64.tar.gz
    '', ''node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@12.22.8 (node-v72 ABI, musl) (falling back to source compile with node-gyp) '', ''\x1b[0m'', "make: Entering directory ''/srv/matrix-appservice-webhooks/node_modules/sqlite3/build''", ''  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c'', ''\x1b[91m/bin/sh: python: not found'', ''\x1b[0m'', ''\x1b[91mmake: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127'', ''\x1b[0m'', "make: Leaving directory ''/srv/matrix-appservice-webhooks/node_modules/sqlite3/build''", ''\x1b[91mgyp\x1b[0m'', ''\x1b[91m ERR! build error '', ''\x1b[0m'', ''\x1b[91mgyp ERR! \x1b[0m'', ''\x1b[91mstack\x1b[0m'', ''\x1b[91m Error: `make` failed with exit code: 2'', ''\x1b[0m'', ''\x1b[91mgyp\x1b[0m'', ''\x1b[91m \x1b[0m'', ''\x1b[91mERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)'',
    ''gyp ERR! stack     at ChildProcess.emit (events.js:314:20)'', ''\x1b[0m'', ''\x1b[91mgyp ERR!\x1b[0m'', ''\x1b[91m stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)'', ''\x1b[0m'', ''\x1b[91mgyp ERR! \x1b[0m'', ''\x1b[91mSystem Linux 5.11.0-1021-oracle'', ''\x1b[0m'', ''\x1b[91mgyp \x1b[0m'', ''\x1b[91mERR! \x1b[0m'', ''\x1b[91mcommand\x1b[0m'', ''\x1b[91m "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/srv/matrix-appservice-webhooks/node_modules/sqlite3/lib/binding/node-v72-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/srv/matrix-appservice-webhooks/node_modules/sqlite3/lib/binding/node-v72-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"'', ''gyp ERR! \x1b[0m'', ''\x1b[91mcwd /srv/matrix-appservice-webhooks/node_modules/sqlite3'', ''gyp\x1b[0m'', ''\x1b[91m ERR! node -v v12.22.8'',
    ''gyp ERR! node-gyp -v v5.1.0'', ''\x1b[0m'', ''\x1b[91mgyp ERR! not ok '', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp\x1b[0m'', ''\x1b[91m ERR! build error '', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp ERR! stack\x1b[0m'', "\x1b[91m Error: Failed to execute ''/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/matrix-appservice-webhooks/node_modules/sqlite3/lib/binding/node-v72-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/srv/matrix-appservice-webhooks/node_modules/sqlite3/lib/binding/node-v72-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72'' (1)", ''node-pre-gyp \x1b[0m'', ''\x1b[91mERR! stack     at ChildProcess.<anonymous> (/srv/matrix-appservice-webhooks/node_modules/node-pre-gyp/lib/util/compile.js:83:29)'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp ERR!\x1b[0m'', ''\x1b[91m stack     at ChildProcess.emit (events.js:314:20)'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp
    ERR! stack     at maybeClose (internal/child_process.js:1022:16)'', ''node-pre-gyp ERR!\x1b[0m'', ''\x1b[91m stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp ERR!\x1b[0m'', ''\x1b[91m System Linux 5.11.0-1021-oracle'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp ERR! command "/usr/local/bin/node" "/srv/matrix-appservice-webhooks/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp\x1b[0m'', ''\x1b[91m ERR! cwd /srv/matrix-appservice-webhooks/node_modules/sqlite3'', ''node-pre-gyp ERR! \x1b[0m'', ''\x1b[91mnode -v v12.22.8'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp\x1b[0m'', ''\x1b[91m ERR! node-pre-gyp -v v0.11.0'', ''\x1b[0m'', ''\x1b[91mnode-pre-gyp ERR!\x1b[0m'', ''\x1b[91m not ok '', ''\x1b[0m'', "Failed to execute ''/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/matrix-appservice-webhooks/node_modules/sqlite3/lib/binding/node-v72-linux-arm64/node_sqlite3.node
    --module_name=node_sqlite3 --module_path=/srv/matrix-appservice-webhooks/node_modules/sqlite3/lib/binding/node-v72-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72'' (1)", ''\x1b[91mnpm ERR! code ELIFECYCLE'', ''npm ERR! errno 1'', ''\x1b[0m'', ''\x1b[91mnpm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`'', ''npm ERR! Exit status 1'', ''npm ERR!\x1b[0m'', ''\x1b[91m '', ''npm ERR! Failed at the sqlite3@4.2.0 install script.'', ''npm ERR! This is probably not a problem with npm. There is likely additional logging output above.'', ''\x1b[0m'', ''\x1b[91m'', ''npm ERR!\x1b[0m'', ''\x1b[91m A complete log of this run can be found in:'', ''npm ERR!\x1b[0m'', ''\x1b[91m     /root/.npm/_logs/2022-01-02T07_25_46_402Z-debug.log'', ''\x1b[0m'', ''Removing intermediate container 6cd95286d3fe'']'

PLAY RECAP **************************************************************************************************************************************************************************************
matrix.domain.tld           : ok=111  changed=38   unreachable=0    failed=1    skipped=200  rescued=0    ignored=0

**Comment by redoo-networks** [comment]
We will check ARM compatiblity later today. Please give us some hours.

**Comment by redoo-networks** [comment]
The image was updated to support ARM64 compilation on a AWS ARM Server. 
Because we don't have a production ARM based Matrix installation, we would be happy to hear your feedback.

When image is used as default image in this project, we will update some dependencies, until a replacement was established. (In the meantime there are some better implementations of webhooks, which looks like to be in test case at the moment) 
Simple to keep it safe for users.

**Comment by rdaries** [comment]
Thanks for the quick response, everything works perfectly now on ARM64
