### ISSUE TITLE
route dimension mediaUrl internally

### ISSUE THREAD

**Issue by HarHarLinks** [spantaleev/matrix-docker-ansible-deploy#1516]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/4e4fb98a65474fd058c61a838db6ac312a09e7df/roles/matrix-dimension/templates/config.yaml.j2#L25

similar to #1449, should mediaUrl go through `matrix_homeserver_container_url` instead of "outside"?

**Comment by spantaleev** [comment]
I think not.

The comment says:

> The URL that Dimension will redirect media requests to for downloading media such as
> stickers. If not supplied or left empty Dimension will use the clientServerUrl.

This sounds like some URL that will not be used internally, but rather passed over to clients. Such remote clients cannot access internal container URLs and need the public homeserver URL.
