### ISSUE TITLE
.well-known/matrix/ reutrns 403

### ISSUE THREAD

**Issue by cristiioan** [spantaleev/matrix-docker-ansible-deploy#1526]
I just configured matrix using this book to work with my external nginx proxy. The user www-data (debian has it as default user for nginx) is in matrix group and loading element.domain.tdl works.

What should I do?

**Comment by spantaleev** [comment]
Try rebooting the server. Perhaps the new group membership hasn't kicked in.

You may also get better and quicker help by joining our Matrix room: https://github.com/spantaleev/matrix-docker-ansible-deploy#support
