### ISSUE TITLE
[Feature Request] Adding matrix-appservice-mattermost

### ISSUE THREAD

**Issue by GoliathLabs** [spantaleev/matrix-docker-ansible-deploy#1545]
Hello,
I'm using mattermost quite often at the moment and thus came across matterbridge which looks promising. But I also noticed matrix-appservice-mattermost, which could be added to this deployment instead. The repository itself is currently mostly dependency updates, with no actual development going on there. But nonetheless, it would be a great addition to the project, I think. What are your thoughts on this? Should we add it to the deployment or should we use something else instead (e.g. matterbridge)?

https://github.com/dalcde/matrix-appservice-mattermost
https://matrix.org/bridges/#mattermost

**Comment by mxc** [comment]
I know I am trying my luck but really need the mattermost bridge. Pretty please. I don't have the knowledge to do it myself.

**Comment by rltas** [comment]
Matterbridge is actively maintained, has an ansible role and supports a range of additional protocols, si I'd stick with that. See #2142.

**Comment by razzeee** [comment]
There is https://github.com/gabrc52/mattermost-to-matrix now
