### ISSUE TITLE
SRV records?

### ISSUE THREAD

**Issue by ptman** [spantaleev/matrix-docker-ansible-deploy#156]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5be1d50b3ad1f51ed523a1224c8c9ab128aae034/docs/configuring-well-known.md seems to indicate that matrix is deprecating SRV record support, but https://matrix.org/docs/spec/server_server/r0.1.1.html#resolving-server-names says nothing about deprecations. People get the wrong idea.

**Comment by spantaleev** [comment]
The playbook favors installing to a `matrix.` subdomain, separate from your base domain.

The playbook's documentation is aligned with that and mostly discusses this most-common use case.

Sometimes we provide options or mention alternatives. I guess we could tone down the language in that document and mention that SRV is still useful in other setups, just not in the default scenario assumed by us.

**Comment by spantaleev** [comment]
I've done some documentation changes which hopefully make it clearer.

Thanks for bringing this up! :+1:
