### ISSUE TITLE
A couple weird problems

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1564]
So I'm running into a couple bugs (I think they're bugs), one related to the identity server and one related to Matrix itself. The first occurs during registration. I have email verification enabled, and when a user registers, they're sent a verification email. When they click on the link, however, they're sent right back to the sign up page as though their account hadn't been created and they need to re-enter their details again. The second bug is after a user signs in for the first time. They don't see any of my public spaces. I have a couple spaces, and one is named general, but according to some new users who have joined my server, they don't see the general space, just home and create a space, even though the general space is public. Is there a reason for this? And how do I solve my first issue for registration?

**Comment by skepticalwaves** [comment]
> they don't see the general space

There is no browse UI for spaces yet.

**Comment by ethindp** [comment]
Oh okay, thanks.
