### ISSUE TITLE
CORS Issues between `matrix.<domain>/.well-known/matrix` and `element.<domain>`

### ISSUE THREAD

**Issue by lunaisnotaboy** [spantaleev/matrix-docker-ansible-deploy#1569]
Hi there,

I run the Matrix server for [mint.lgbt](https://mint.lgbt) using this playbook, and we think it's wonderful! It has saved us a lot of time and effort in maintaining our Matrix server.

However, when we upgraded around a month ago, we began to notice problems with our CORS headers when Element was interacting with anything under the `/.well-known/matrix` path.

We have followed the guide and we confirmed that we were proxying the `/.well-known/matrix` correctly, and we even tried rewriting the headers so that our main server (the one that runs the root domain) would add the headers for them, but it did not work.

I would really like to figure something out, as we've been trying _everything_ to fix this, and we're at our wit's end.

Thank you!

**Comment by aaronraimist** [comment]
Can you share your Nginx config for mint.lgbt? I think the problem must be in there since https://matrix.mint.lgbt/.well-known/matrix/client has the correct header.

**Comment by lunaisnotaboy** [comment]
@aaronraimist the following gist has the NGINX configuration for the root domain. It has some other things in there unrelated to the Matrix server, but it's what's in the file:

https://gist.github.com/lunaisnotaboy/dd5ec613fb4d112de42c8923001c1dbc

**Comment by lunaisnotaboy** [comment]
Please keep in mind that we were experiencing the same problem without the added lines for `/.well-known/matrix`

**Comment by lunaisnotaboy** [comment]
Hmm, I'll check.

**Comment by lunaisnotaboy** [comment]
It shows a `403 Forbidden` error.

**Comment by aaronraimist** [comment]
If it still shows 403 after editing the config and reloading/restarting nginx then I'm guessing that means you are editing some config file that is not actually being read by nginx.

Usually the stuff in `/etc/nginx/sites-available/` is symlinked into `/etc/nginx/sites-enabled/` but sometimes people copy the files over instead. Make sure the file you are editing is the one that gets included in the `site-enabled` folder.

**Comment by lunaisnotaboy** [comment]
I can confirm that this is the file in `sites-enabled`.

**Comment by aaronraimist** [comment]
I'm not sure what is going wrong.

**Comment by lunaisnotaboy** [comment]
I'm not sure either. I'll look at the rest of the configuration files, and I'll let you know if I find something.

**Comment by GoliathLabs** [comment]
Can you post your nginx site configuration down below (omitting sensitive values)?

**Comment by lunaisnotaboy** [comment]
@GoliathLabs for NGINX or the playbook?

**Comment by GoliathLabs** [comment]
Both so we can see if there's any misconfiguration

**Comment by lunaisnotaboy** [comment]
Will do. Give me a minute

**Comment by lunaisnotaboy** [comment]
Well, it seems the server is down. I'm currently busy, so it'll be a few hours before I can get the configuration from my personal laptop. Sorry.

**Comment by lunaisnotaboy** [comment]
@GoliathLabs here's the configuration file, sorry it took so long! (the NGINX config is near the beginning of this thread)

https://gist.github.com/lunaisnotaboy/87d7a3b5c1a423cf9c844c02653ef8a6

**Comment by lunaisnotaboy** [comment]
Sorry to bother you, but have you found anything @GoliathLabs? I appreciate your assistance.

**Comment by GoliathLabs** [comment]
What do the includes do in your config? They might cause the problem you're experiencing.

My plain config looks something like this (Using Traefik for TLS traffic):
```
server {
    listen 80 default_server;
    server_name mydomain.com

    client_max_body_size 100M;

    root /usr/share/nginx/html;
    index index.html index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location /.well-known/matrix {
        proxy_pass https://matrix.mydomain.com/.well-known/matrix;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

**Comment by lunaisnotaboy** [comment]
As I said before, my NGINX config is in the following Gist:

https://gist.github.com/lunaisnotaboy/dd5ec613fb4d112de42c8923001c1dbc

**Comment by GoliathLabs** [comment]
I know that. But your gist is still missing the files you include with `include`. Namely:
```
    include /etc/nginx/templates/misc.tmpl;
    include /etc/nginx/templates/iredadmin.tmpl;
    include /etc/nginx/templates/roundcube.tmpl;
    include /etc/nginx/templates/sogo.tmpl;
    include /etc/nginx/templates/netdata.tmpl;
    include /etc/nginx/templates/php-catchall.tmpl;
    include /etc/nginx/templates/stub_status.tmpl;
```

**Comment by lunaisnotaboy** [comment]
> I know that. But your gist is still missing the files you include with `include`.

Sorry about that. Here's a gist with the files (some are not included due to security):

https://gist.github.com/lunaisnotaboy/fc12f4aec2035e946d9660383249d7e0

**Comment by GoliathLabs** [comment]
Hmm, okay. I don't see anything suspicious there as well. Maybe it has something todo with the options-ssl thing from certbot. Maybe commenting it out helps? Just guessing rn.

**Comment by lunaisnotaboy** [comment]
Hm, I'll try.

**Comment by aaronraimist** [comment]
The fact that https://mint.lgbt/.less-well-known/matrix/client 403s despite https://gist.github.com/lunaisnotaboy/fc12f4aec2035e946d9660383249d7e0#file-nginx-conf-L28 existing still makes me think this isn't the active config file

**Comment by lunaisnotaboy** [comment]
We're not sure what's causing this, so we've decided to just serve the base domain from the playbook. Closing.
