### ISSUE TITLE
How do you add a custom app service using this flow?

### ISSUE THREAD

**Issue by bjladner** [spantaleev/matrix-docker-ansible-deploy#1574]
How can I add a custom appservice to matrix if I am using this method of install?  I have synapse and element working and I want to add Cactus Comments to my blog using this matrix app service:

https://cactus.chat/docs/self-hosting/howto/

Can I just run the cactus container on the same machine and add the app service to the homeserver.yaml, or is there a more official way of installing an appservice using ansible?

Thanks - Brian

**Comment by aaronraimist** [comment]
Yeah that sounds right. I don't personally use any appservices that aren't included with the playbook so I'm not 100% sure but other people have seemed to have success with https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/313#issuecomment-1008252548. Documentation hasn't been written up about how to do this but if you get it working, you could write some.
