### ISSUE TITLE
Running docker containers on different hosts (Question)

### ISSUE THREAD

**Issue by razerrazer** [spantaleev/matrix-docker-ansible-deploy#1579]
Hi,

I would like to know if it is possible to add a different server (container) to a different host.

Let's say you have 3 docker-nodes, and you want to run jitsi and PostgreSQL on node#2 and element,prosody on node#3

To allocate resources and risks and not have everything in one basket.

Is this possible to do with your ansible script ?

**Comment by spantaleev** [comment]
This is not currently possible, nor planned. All services must be on the same host.

You may be able to target 2 hosts with Ansible and enable/disable installation of various services in each host's `vars.yml` file, and somehow achieve this. YMMV.
