### ISSUE TITLE
Troubles getting the SSL certificate.

### ISSUE THREAD

**Issue by iambeingtracked** [spantaleev/matrix-docker-ansible-deploy#1608]
So, i'm currently trying to execute `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all -K` everything works fine until the point of getting Lets Encrypt's SSL certificates.
Here's the output of that command: `TASK [matrix-nginx-proxy : Wait some time, so that the required service for obtaining can start] **********************************************************
skipping: [matrix.wherelinux.xyz]

TASK [matrix-nginx-proxy : Attempt initial SSL certificate retrieval with standalone authenticator (directly)] ********************************************
fatal: [matrix.wherelinux.xyz]: FAILED! => changed=true
  cmd: /usr/bin/env docker run --rm --name=matrix-certbot --user=998:1001 --cap-drop=ALL -p 80:8080 --mount type=bind,src=/matrix/ssl/config,dst=/etc/letsencrypt --mount type=bind,src=/matrix/ssl/log,dst=/var/log/letsencrypt docker.io/certbot/certbot:amd64-v1.22.0 certonly --non-interactive --work-dir=/tmp --http-01-port 8080   --standalone --preferred-challenges http --agree-tos --email=w33bspirit@disroot.org -d matrix.wherelinux.xyz
  delta: '0:00:07.434585'
  end: '2022-02-06 19:59:35.686197'
  msg: non-zero return code
  rc: 1
  start: '2022-02-06 19:59:28.251612'
  stderr: |-
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Some challenges have failed.
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with-v for more details.
  stderr_lines: <omitted>
  stdout: |-
    Requesting a certificate for matrix.wherelinux.xyz

    Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
      Domain: matrix.wherelinux.xyz
      Type:   unauthorized
      Detail: Invalid response from http://matrix.wherelinux.xyz/.well-known/acme-challenge/2rDavLW7NV_R4Qi0KtqhNkWSOU8xhgWYkYA6Np2DUIo [my.public.ip.address]: 503

    Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 8080. Ensurethat the listed domains point to this machine and that it can accept inbound connections from the internet.
  stdout_lines: <omitted>
...ignoring

TASK [matrix-nginx-proxy : Attempt initial SSL certificate retrieval with standalone authenticator (via proxy)] *******************************************
fatal: [matrix.wherelinux.xyz]: FAILED! => changed=true
  cmd: /usr/bin/env docker run --rm --name=matrix-certbot --user=998:1001 --cap-drop=ALL -p 127.0.0.1:2402:8080 --network=matrix --mount type=bind,src=/matrix/ssl/config,dst=/etc/letsencrypt --mount type=bind,src=/matrix/ssl/log,dst=/var/log/letsencrypt docker.io/certbot/certbot:amd64-v1.22.0 certonly --non-interactive --work-dir=/tmp --http-01-port 8080   --standalone --preferred-challenges http --agree-tos --email=w33bspirit@disroot.org -d matrix.wherelinux.xyz
  delta: '0:00:03.629124'
  end: '2022-02-06 19:59:39.848991'
  msg: non-zero return code
  rc: 1
  start: '2022-02-06 19:59:36.219867'
  stderr: |-
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Some challenges have failed.
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with-v for more details.
  stderr_lines: <omitted>
  stdout: |-
    Requesting a certificate for matrix.wherelinux.xyz

    Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
      Domain: matrix.wherelinux.xyz
      Type:   unauthorized
      Detail: Invalid response from http://matrix.wherelinux.xyz/.well-known/acme-challenge/_HqBsmCZEmIOA8a_Y3mohLnAkaEA8dXUP31t8j9D_Os [my.public.ip.address]: 503

    Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 8080. Ensurethat the listed domains point to this machine and that it can accept inbound connections from the internet.
  stdout_lines: <omitted>
...ignoring

TASK [matrix-nginx-proxy : Fail if all SSL certificate retrieval attempts failed] *************************************************************************
fatal: [matrix.wherelinux.xyz]: FAILED! => changed=false
  msg: |-
    Failed to obtain a certificate directly (by listening on port 80)
    and also failed to obtain by relying on the server at port 80 to proxy the request.
    See above for details.
    You may wish to set up proxying of /.well-known/acme-challenge to 2402 or,
    more easily, stop the server on port 80 while this playbook runs.

PLAY RECAP ************************************************************************************************************************************************
matrix.wherelinux.xyz      : ok=188  changed=12   unreachable=0    failed=1    skipped=1593 rescued=0    ignored=2`

I thought that the problem might be happening because i edited inventory/hosts and put a local ip address here. Because if i put a public one it tries to ssh using that one, which doesn't work. I tried disabling coturn, just to check if it was because of it or no but i get the same error even with it.
/var/log/letsencrypt/letsencrypt.log appears to be a non-existing file and /var/log/letsencrypt is a non-existing directory. Neither on my machine or the server one. I'm hosting this on a single vmware esxi so loadbalancer could be a problem. Please reply back soon.

**Comment by Arthegor** [comment]
Same Problem here

**Comment by spantaleev** [comment]
`/var/log/letsencrypt` is the path inside the `certbot` container. See the `/matrix/ssl/log` directory on the host to see the logs.

As the error message says, ensure that you've got port 80 open in your firewall and that you have no other webserver running at the time you first run the playbook.

**Comment by iambeingtracked** [comment]
It seems that problem happens because of this
2022-02-09 17:00:29,971:INFO:certbot._internal.auth_handler:http-01 challenge for matrix.wherelinux.xyz
2022-02-09 17:00:29,975:DEBUG:acme.standalone:Successfully bound to :8080 using IPv6
2022-02-09 17:00:29,976:DEBUG:acme.standalone:Certbot wasn't able to bind to :8080 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.

@spantaleev Could you please help me solve this issue?

**Comment by encrosafe** [comment]
Hello, i have the same error with my installation.

**Comment by iambeingtracked** [comment]
I had to install certbot manually via debian's repositories and get the certs from there because lb configuration didn't let me install it via built into playbook certbot. So i have to manually manage it all. Closing the issue
