### ISSUE TITLE
whatsapp bridge: Failed to initialize database: unsupported database version

### ISSUE THREAD

**Issue by jan-bruckner** [spantaleev/matrix-docker-ansible-deploy#1609]
I want to report on an issue I just faced during upgrading. I was able to solve it on my own, but maybe someone else runs into something similar. Or it might prevent similar issues in the future :)

I performed an upgrade as described in: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md
followed by an upgrade of the postgres databse as described here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-postgres.md
Both of these worked fine, but afterwards the whatsapp bridge did not start anymore and repeatedly gave the error:
```
Feb 06 20:41:57 <hostname> systemd[1]: Starting Matrix Mautrix Whatsapp bridge...
Feb 06 20:42:02 <hostname> systemd[1]: Started Matrix Mautrix Whatsapp bridge.
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [INFO] Initializing mautrix-whatsapp 0.2.3 (Jan 16 2022, 18:24:56)
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [DEBUG] Initializing database connection
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [DEBUG] Initializing state store
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [DEBUG] Initializing Matrix event processor
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [DEBUG] Initializing Matrix event handler
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [DEBUG] Bridge built with end-to-bridge encryption, but disabled in config
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [INFO] Bridge initialization complete, starting...
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [DEBUG] Running database upgrades

--- note the following line ---
Feb 06 20:42:03 <hostname> matrix-mautrix-whatsapp[32000]: [Feb  6, 2022 19:42:03] [FATAL] Failed to initialize database: unsupported database version
---
Feb 06 20:42:03 <hostname> systemd[1]: matrix-mautrix-whatsapp.service: Main process exited, code=exited, status=15/n/a
Feb 06 20:42:03 <hostname> systemd[1]: matrix-mautrix-whatsapp.service: Failed with result 'exit-code'.
Feb 06 20:42:33 <hostname> systemd[1]: matrix-mautrix-whatsapp.service: Scheduled restart job, restart counter is at 70.
Feb 06 20:42:33 <hostname> systemd[1]: Stopped Matrix Mautrix Whatsapp bridge.
```
I traced the error back to its origin here: https://github.com/mautrix/whatsapp/blob/e8c77c7ec6247436e1f11d7990445b0aa835893d/database/upgrades/upgrades.go#L99
In my case the `version` was `36` and for some reason larger than `NumberOfUpgrades` which lead to the error.
I was able to fix it manually in the database as follows:
```
# connect to database
docker container exec --interactive --tty matrix-postgres psql -d matrix_mautrix_whatsapp --username matrix_mautrix_whatsapp
# revert migration that lead to version 36 (https://github.com/mautrix/whatsapp/blob/master/database/upgrades/2022-01-24-phone-last-seen-ts.go)
matrix_mautrix_whatsapp=> ALTER TABLE "user" DROP COLUMN phone_last_seen;
# set version 35
matrix_mautrix_whatsapp=> UPDATE version SET version = 35;
```

Then the bridge finally started again and gave me this:
```
Feb 06 21:03:03 <hostname> matrix-mautrix-whatsapp[45088]: [Feb  6, 2022 20:03:03] [Database/Upgrade/INFO] Database currently on v35, latest: v35
```
So for some reason the `version` was incremented to `36` at some point while `NumberOfUpgrades` was afterwards reset to `35`.

I guess this was caused by #1559: the docker image was updated to `latest` after the release of `v0.2.3` which caused the database version to increase to `36` and afterwards, when the image was downgraded to `v0.2.3` the `NumberOfUpgrades` was now back to `35` and the described issue occured.

**Comment by spantaleev** [comment]
Good investigation skills! Thanks for reporting this! If it happens to others, we can refer them to this issue.

Looks like you may have been on a `latest` version, which is newer than the one we pin to (`v0.2.3`). It may be that you may have recently used an older version of the playbook (which did not use to pin the bridge version and used `latest`) to install services and you ended up on a newer version than `v0.2.3`.

There were a few other potential workarounds for your situation:

- continue using `latest` by putting `matrix_mautrix_whatsapp_version: latest` in your `vars.yml`. Then wait for the next mautrix-whatsapp release (`v0.2.4` or `v0.3.0` or whatever it is), submit a PR and remove your version override from `vars.yml`

- downgrade the database version manually. Looks like [2022-01-24-phone-last-seen-ts.go](https://github.com/mautrix/whatsapp/blob/b240eb94d8a755a0893110dcdb607b4d460d3d4d/database/upgrades/2022-01-24-phone-last-seen-ts.go) is the only migration that exists (as of me writing this) on top of what `v0.2.3` contains. So reverting that migration will bring your database back to a state that the bridge is happy with. To revert `ALTER TABLE "user" ADD COLUMN phone_last_seen BIGINT`, you likely need something like `ALTER TABLE "user" DROP COLUMN phone_last_seen` and then one more SQL statement to mark the database as an older version (`36` -> `35`) -- not sure which database table mautrix-whatsapp uses to keep that number
