### ISSUE TITLE
Input extra_hosts to hosts-files

### ISSUE THREAD

**Issue by PelleHanses** [spantaleev/matrix-docker-ansible-deploy#1636]
Hi,
how can I input lines to /etc/hosts files in the docker files with the ansible playbook? extra_hosts would be a nice way to import it but where should I put the extra_hosts lines?

/Pelle

**Comment by spantaleev** [comment]
We don't manage (touch) `/etc/hosts` at all. The playbook tries to "contaminate" the server as little as possible.

So, doing this is out of scope. You can:

- fork the playbook and add this yourself
- invoke the playbook's roles by including them in your own playbook (which can do other things)
- manage the `/etc/hosts` file manually, without Ansible
