### ISSUE TITLE
Does it have recaptcha preinstalled? Does it force users to enter an email address by default? And if it does, how to disable it?

### ISSUE THREAD

**Issue by iambeingtracked** [spantaleev/matrix-docker-ansible-deploy#1637]
This is more of a question than an issue. I'm just curious if it uses all those things like recaptcha and forcing users to have an email linked. If it does, is it possible to configure/disable through changing this playbook's settings?

**Comment by array-in-a-matrix** [comment]
Recaptcha is not preinstalled you have to explicitly add it to your [config](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1fb54a37cba126235b1688bb5e96226a65b4fe80/docs/configuring-captcha.md) to use it. You can require users to link an email to when signing up but its not on by default. Everything can be configured in the playbook afaik.
