### ISSUE TITLE
Why is this playbook so unstable?

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1656]
It seems as though the setup that this playbook installs can't run constantly for longer than a week or two. After that, things break to the point where Element can no longer function. I seriously can't make sense of this. Matrix should not be so unstable like this. I should be able to get it running and it should run for months and months. Is there a reason that Matrix is such a maintenance headache? Is there any way I can prevent things from breaking practically every time I turn my back to go focus on something else?

**Comment by ethindp** [comment]
I don't mean to blame the playbook in particular, I'm just extremely frustrated is all. Apologies if I come off as rude or harsh.

**Comment by FPVogel** [comment]
for me it works just fine, even on an arm system, can you provide any further details?

**Comment by ethindp** [comment]
For me random things break for no reason. Like right now, postgresql randomly stopped and trying to restart it doesn't work -- synapse claims it can't connect to the matrix-postgres container. Even though its running. This has happened at least 5 times since I created my matrix instance. Postgresql is never, ever this unstable. The only reason I don't run an instance outside docker is because it won't go over TLS.

**Comment by ethindp** [comment]
And the only fix I've found is to reboot the entire server. And I can't keep doing that just because matrix decides to not work properly.

**Comment by altsalt** [comment]
Sounds like your server may be under-powered. Have you tried [tuning postgresql](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-postgres.md#tuning-postgresql)? I suspect something is summoning the OOM reaper, leaving the remaining processes in a dirty state. I've got a fairly low powered VPS that's been using this playbook for around a year with no serious hiccups. Sorry you're having such a rough go!

**Comment by spantaleev** [comment]
This definitely sounds like an underpowered server for what you're trying to do with it. You should check `dmesg` and see if the OOM killer gets triggered.

Our deployment method (and using containers in general) should not introduce any overhead or instability. If you're having issues with performance/stability, it's likely that you'll have these same issues *with* or *without* the playbook.

There's thousands of people powering their Matrix server using our deployment method and we certainly don't hear complaints about anyone being unable to run services for more than a week.

You can try to:

- switch to more powerful hardware
- leave some large Matrix rooms
- [disable Synapse presence](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-synapse.md#make-synapse-faster)
- clear some old history and media - see [Purging old data with the Purge History API](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-synapse.md#purging-old-data-with-the-purge-history-api)
- compress Synapse state - see [Compressing state with rust-synapse-compress-state](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-synapse.md#compressing-state-with-rust-synapse-compress-state)
- `VACUUM` your PostgreSQL server - see [Vacuuming PostgreSQL](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-postgres.md#vacuuming-postgresql)
- tune your server to disable Matrix and non-Matrix services to decrease RAM usage
- tune PostgreSQL, as advised above - see [Tuning PostgreSQL](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-postgres.md#tuning-postgresql)
- report your performance troubles upstream (likely at [Synapse](https://github.com/matrix-org/synapse))
- consider rebuilding your Matrix server using a more performant homeserver implementation like Dendrite - see [Dendrite support](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#dendrite-support) in our changelog (**requires starting over and is not a great idea just yet**)

**Comment by ethindp** [comment]
I mean, I've tried tuning pgsql and it doesn't like how I tune it, but I might be asking it to use too much RAM.

**Comment by altsalt** [comment]
Yeah, if you tune it to use more RAM than you have, it could very well summon the reaper.
