### ISSUE TITLE
CONTRIBUTING.md, Issue, and PR templates

### ISSUE THREAD

**Issue by array-in-a-matrix** [spantaleev/matrix-docker-ansible-deploy#1657]
This project is pretty big and I think it would benefit from having its issues/PRs organized better using templates maybe? 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by luixxiul** [comment]
@spantaleev if this project does not require contributing.md, then let's close this as completed for good :)

**Comment by spantaleev** [comment]
Okay, let's close it! I think we can always revisit this later if it's necessary.
