### ISSUE TITLE
matrix_homeserver_generic_secret_key

### ISSUE THREAD

**Issue by lemyoo** [spantaleev/matrix-docker-ansible-deploy#1659]
fatal: [matrix.messaging.strheme.com]: FAILED! => changed=false
  msg: |-
    The `matrix_homeserver_generic_secret_key` variable must be defined and have a non-null and non-empty value.

    If you're observing this error on a new installation, you should ensure that the `matrix_homeserver_generic_secret_key` is defined.

    If you're observing this error on an existing homeserver installation, you can fix it easily and in a backward-compatible way by adding
    `matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"`
    to your `vars.yml` file. Using another secret value for the new variable is also possible and shouldn't cause any trouble.

Please check if there's an error because I have been working on your project for some time now and I never got this error

**Comment by spantaleev** [comment]
This looks like trolling. You seem to know enough English to be able to say:

> Please check if there's an error because I have been working on your project for some time now and I never got this error

.. but not enough to read the error message that very clearly tells you what needs to be done.

**Comment by kevin-liu15** [comment]
same problem with same error , but adding  `matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }} ` or changing another secret value is doesn't work

**Comment by lemyoo** [comment]
I got the error because I didn't name my folder or directory well.
After correcting it it worked fine.
Check the spellings well.

**Comment by moan0s** [comment]
Could you elaborate which directory this was?

**Comment by lemyoo** [comment]
The matrix.something directory
