### ISSUE TITLE
Video Preview Thumbnails in Apps not showing on bridges?

### ISSUE THREAD

**Issue by XTREEMMAK** [spantaleev/matrix-docker-ansible-deploy#1661]
So,
Considering the bridges are under the same umbrella, I guess I'm posting this in the right place.

After connecting any of the bridges (WhatsApp, Instagram, etc.) when you view on Desktop and Web, everything looks fine. However when you open up the same content on Android clients (any actually...I've tried 4 already with the same result), video content specifically has no image for video preview. The videos work fine themselves, but you have no idea what you're playing.

Is this an Android specific problem?

**Comment by spantaleev** [comment]
I don't think this is the right place. It sounds like an [element-android](https://github.com/vector-im/element-android) bug if other clients can do it.

Even if it's not an element-android bug, it might be that what's sending these videos (the specific bridge) is not sending a proper thumbnail. This would make it a bridge bug.

We're just a silly deployment system that deploys what's upstream. There might be a bug in our deployment method (wrong configuration, etc.), but that's likely rare. Looking upstream is usually more productive.
