### ISSUE TITLE
psql: error: connection to server at "matrix-postgres" (172.18.0.2), port 5432 failed: FATAL:  no pg_hba.conf entry for host "172.18.0.3", user "matrix", database "matrix", no encryption

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1675]
**Describe the bug**
When deploying matrix, I receive this error.

**To Reproduce**

I'm trying to move a matrix installation to a new server. When starting postgres and setting it up, this error is generated.

**Expected behavior**
This error should not occur. The playbook should automatically configure postgres with no problems.

**Matrix Server:**
 - OS: Fedora 35 (the playbook doesn't appear to be "directly" compatible with it, but its close enough to RHEL/CentOS that it can work)
 - Architecture: AMD-64

**Comment by ethindp** [comment]
Any update? I'm still getting this error. Sorry if I seem impatient.

**Comment by ToeiRei** [comment]
This looks like the postgres server has a prefilled pg_hba.conf file in /matrix - can you search for that one?

**Comment by ethindp** [comment]
Oddly, this issue just vanished and hasn't happened since I last posted an update here. Talk about weird.
