### ISSUE TITLE
Hookshot - Generic webhooks will be routed to /webhook

### ISSUE THREAD

**Issue by Half-Shot** [spantaleev/matrix-docker-ansible-deploy#1681]
Currently hookshot generic webhooks get routed to `/:hookId` on the webhooks listener, but https://github.com/matrix-org/matrix-hookshot/pull/227 is chaging things so we now prefer them to be routed to `/webhook/:hookId`. While previous setups still work, it's deprecated behavior.

**Comment by HarHarLinks** [comment]
I'll work on this

**Comment by spantaleev** [comment]
Fixed by [4704a60](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/4704a60718946fd469aeee7fc3ae8127c633bb6b)
