### ISSUE TITLE
здравеи ако си българин да станем приятели.

### ISSUE THREAD

**Issue by bgman111111** [spantaleev/matrix-docker-ansible-deploy#1708]
От неколко дни съ опитвъм да инсталиръм  matrix. Имъм 2 виртуални машини, на пъвият е  apache2, на вторият е матрих. Използвъ  nginx. Как да свържъ пъвият apache  със вторят. Искъм първият сървър да е чист. Не съм спа от ммого дни 
Имъм mastodon.bgzashtita.es използвъ ама и тои маи не ръботи. . Америкамците и деугите хоръ не искъм да ми помогнут. Малии ако си българин. Радвъм съ че има и хора като теб. Мерди

**Comment by TomBraun02** [comment]
Трябва само да настроите тази конфигурация и да я оставите да показва IP на сървъра на Matrix.
https://raw.githubusercontent.com/spantaleev/matrix-docker-ansible-deploy/master/examples/apache/matrix-client-element.conf
Надявам се това да ви помогне
