### ISSUE TITLE
fix hookshot public urls in non-https scenarios

### ISSUE THREAD

**Issue by HarHarLinks** [spantaleev/matrix-docker-ansible-deploy#1724]
configuration such as

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/999c717cf452efc94ef72f125ec6c2aa1a7c43f4/roles/matrix-bridge-hookshot/defaults/main.yml#L55

and

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/999c717cf452efc94ef72f125ec6c2aa1a7c43f4/roles/matrix-bridge-hookshot/defaults/main.yml#L105

etc needs to be updated similar to this method

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/999c717cf452efc94ef72f125ec6c2aa1a7c43f4/group_vars/matrix_servers#L698-L700

to support non-https setups and setups with nonstandard http(s) ports.

the above approach can be refactored to generate a common denominator  and then used in the applicable cases to set public urls

**Comment by Ersonusaini** [comment]
Contact me Full setup any matrix server setup using Ansible and Docker 
https://www.fiverr.com/sonusainibhadra/setup-matrix-chat-server-with-android-app
Hire me on Fiverr and Upwork 
Skype:ersonusaini
https://wa.me/+919782533298

**Comment by spantaleev** [comment]
This has likely already been fixed by 78912688734589d67a9213201dbae45d231fad84
