### ISSUE TITLE
Fix git 2.35.2 safe directory errors

### ISSUE THREAD

**Issue by ptman** [spantaleev/matrix-docker-ansible-deploy#1749]
**Describe the bug**

https://github.blog/2022-04-12-git-security-vulnerability-announced/

```
FAILED! => {
"changed": false,
"msg": "Failed to set a new url https://github.com/vector-im/hydrogen-web.git for origin:
fatal: unsafe repository ('/matrix/client-hydrogen/docker-src' is owned by someone else)
To add an exception for this directory, call:

    git config --global --add safe.directory /matrix/client-hydrogen/docker-src"
}
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_client_hydrogen_enabled: true
```

**Expected behavior**

No failure

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture: amd64

**Comment by spantaleev** [comment]
> This version changes Git’s behavior when looking for a top-level .git directory to stop when its directory traversal changes ownership from the current user. (If you wish to make an exception to this behavior, you can use the new multi-valued [safe.directory](https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory) configuration).

Perhaps instead of using the `safe.directory` workaround, we should try to ensure that the user that `git` is started with, and the user of the directory we operate on (e.g. `/matrix/client-hydrogen/docker-src`) are the same. We may be mixing `root` and `matrix` somehow.

**Comment by lucianolacurcia** [comment]
I am getting similar error here:
```
TASK [matrix-client-element : Ensure Element Docker image is pulled] ************************************************************************************************************************************************
skipping: [matrix.***]

TASK [matrix-client-element : Ensure Element repository is present on self-build] ***********************************************************************************************************************************
fatal: [matrix.***]: FAILED! => changed=false
  msg: |-
    Failed to set a new url https://github.com/vector-im/riot-web.git for origin:  fatal: unsafe repository ('/matrix/client-element/docker-src' is owned by someone else)
    To add an exception for this directory, call:

            git config --global --add safe.directory /matrix/client-element/docker-src

PLAY RECAP **********************************************************************************************************************************************************************************************************
matrix.*** : ok=137  changed=3    unreachable=0    failed=1    skipped=1374 rescued=0    ignored=0
```

**Comment by spantaleev** [comment]
Form now on, we'll `git clone` (into `/matrix/SERVICE/docker-src` for self-building purposes) using the `matrix` user, instead of mixing `root` and `matrix`.

-------

For those affected by this issue, you'll need to pull the latest commit of the playbook, as well as run this command on the Matrix server: `find /matrix -maxdepth 2 -name 'docker-src' | xargs rm -rf`

To learn more, see the changelog entry [(Compatibility Break) Changes to docker-src permissions necessitating manual action](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#compatibility-break-changes-to-docker-src-permissions-necessitating-manual-action)

**Comment by ewonchang** [comment]
For me (Aarch64 Ubuntu server), the symptom was something related to git command permission error. Took me a while to find this solution. Thanks @spantaleev the method works like a charm
