### ISSUE TITLE
mautrix-signal: Allow contact list names

### ISSUE THREAD

**Issue by Zepmann** [spantaleev/matrix-docker-ansible-deploy#1773]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to configure automated propagation of Signal (group) names from within Ansible. Within the file:

roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2

The YAML option bridge.contact_list_names is a hard-coded 'disallow'.

**Describe the solution you'd like**
I'd like to be able to control the noted configuration option from an Ansible playbook, to switch it from 'disallow' to 'allow' or 'prefer'.

**Describe alternatives you've considered**
The option can be adjusted manually within Docker (and this works!), but that is not really scalable or requires an ugly workaround.

**Additional context**
I know that there are situations in which contact_list_names is undesirable (multi-user instances in which names can conflict). Therefore, I think the default should still be to disallow it. It would be nice to have an option to enable it, though.

**Comment by spantaleev** [comment]
You can override any `config.yaml.j2` setting using `matrix_mautrix_signal_configuration_extension_yaml`:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/dd83d88cb04791a19f343fd3750f974a3a19c64b/roles/matrix-bridge-mautrix-signal/defaults/main.yml#L109-L116
