### ISSUE TITLE
borg_storage_encryption_passphrase is not decrypted when using ansible vault.

### ISSUE THREAD

**Issue by linuskr** [spantaleev/matrix-docker-ansible-deploy#1791]
When using borg backup and encrypting the password with ansible vault, the encrypted password is put into the config.yaml, leading to a syntax error.
Adding `|string` in the template fixes the issue, but i don't know if that is the correct solution:
```
+++ b/roles/matrix-backup-borg/templates/config.yaml.j2
@@ -10,7 +10,7 @@ storage:
   compression: {{ matrix_backup_borg_storage_compression|to_json }}
   ssh_command: {{ matrix_backup_borg_storage_ssh_command|to_json }}
   archive_name_format: {{ matrix_backup_borg_storage_archive_name_format|to_json }}
-  encryption_passphrase: {{ matrix_backup_borg_storage_encryption_passphrase|to_json }}
+  encryption_passphrase: {{ matrix_backup_borg_storage_encryption_passphrase|string|to_json }}
   unknown_unencrypted_repo_access_is_ok: {{ matrix_backup_borg_unknown_unencrypted_repo_access_is_ok|to_json }}
 
```

**Comment by spantaleev** [comment]
You may be able to define `matrix_backup_borg_storage_encryption_passphrase` in `vars.yml` like this:

```yaml
matrix_backup_borg_storage_encryption_passphrase: "{{ vault_matrix_backup_borg_storage_encryption_passphrase }}"
```

And then define `vault_matrix_backup_borg_storage_encryption_passphrase` in your vault.

Perhaps that is a better workaround for you?

**Comment by linuskr** [comment]
That is indeed a much cleaner workaround, thank you.
