### ISSUE TITLE
Is git installation needed on a server beforehand?

### ISSUE THREAD

**Issue by sernik** [spantaleev/matrix-docker-ansible-deploy#1792]
I added to `vars.yml`:

```yaml
matrix_client_hydrogen_enabled: true
```
and tried to update existing installation with `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all`:

```
TASK [matrix-client-hydrogen : Ensure Hydrogen repository is present on self-build]
fatal: [matrix.DOMAIN]: FAILED! => changed=false 
  msg: 'Failed to find required executable "git" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

It went fine after `apt install git` on server.

**Matrix Server:**
 - OS: Debian 10.12
 - Architecture amd64

**Ansible:**
- Ansible 2.12.4 on Fedora 36

**Comment by aaronraimist** [comment]
Yes it is required for self building from a git repo. I have documented that in https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1827.
