### ISSUE TITLE
The `matrix_homeserver_generic_secret_key` variable must be defined and have a non-null and non-empty value.

### ISSUE THREAD

**Issue by cosmin-vasu** [spantaleev/matrix-docker-ansible-deploy#1794]
Need to mention this is my firs interaction with ansible 

the playbook fails with error:

"The `matrix_homeserver_generic_secret_key` variable must be defined and have a non-null and non-empty value." 

for new installation when running : 

ansible-playbook -i inventory/hosts setup.yml --tags=setup-all

matrix_homeserver_generic_secret_key has been defined in vars.yml as per example  using  `pwgen -s 64 1`

matrix_homeserver_generic_secret_key: 'xxxx...'

I've tried with single quotes, double quotes, no quotes and same error every time 

I don't know what I'm doing wrong here. 

Please help

**Comment by cosmin-vasu** [comment]
forgot to mention the server OS

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

 and is running on Oracle ARM instance VM.Standard.A1.Flex

**Comment by spantaleev** [comment]
You likely have a typo in the domain name in `inventory/hosts` or in the path to the `vars.yml` file (it needs to be `inventory/host_vars/matrix.DOMAIN/vars.yml`. Try following the guide again and beware of typos.

**Comment by cosmin-vasu** [comment]
spot on, mate!
it was a domain name typo.  d'oh! 
Thank you!
