### ISSUE TITLE
matrix-registration.service: Failed ImportError

### ISSUE THREAD

**Issue by sLevasseur** [spantaleev/matrix-docker-ansible-deploy#1798]
Helllo guys,

When setting up matrix-registration i'm having this issue :
**To Reproduce**
Setting up matrix-registration [https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-matrix-registration.md](url)

`May 03 19:20:04 raspberrypi systemd[1]: matrix-registration.service: Scheduled restart job, restart counter is at 71.
May 03 19:20:04 raspberrypi systemd[1]: Stopped matrix-registration.
May 03 19:20:04 raspberrypi systemd[1]: Starting matrix-registration...
May 03 19:20:04 raspberrypi systemd[1]: Started matrix-registration.
May 03 19:20:07 raspberrypi matrix-registration[29736]: Traceback (most recent call last):
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/bin/matrix-registration", line 5, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from matrix_registration.app import cli
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/matrix_registration/__init__.py", line 1, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from . import api
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/matrix_registration/api.py", line 9, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from flask import (
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from jinja2 import escape
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from .environment import Environment
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from .defaults import BLOCK_END_STRING
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
May 03 19:20:07 raspberrypi matrix-registration[29736]:   File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
May 03 19:20:07 raspberrypi matrix-registration[29736]:     from markupsafe import soft_unicode
May 03 19:20:07 raspberrypi matrix-registration[29736]: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)
May 03 19:20:08 raspberrypi systemd[1]: matrix-registration.service: Main process exited, code=exited, status=1/FAILURE
May 03 19:20:08 raspberrypi systemd[1]: matrix-registration.service: Failed with result 'exit-code'.`

uname -a result : Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

ansible --version : ansible 2.10.8
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

Any idea for a workaround ? I could not find which library of matrix-registration if having a dependency with markupsafe.

Thanks !

**Comment by wibbene** [comment]
Are you on the latest commit?
