### ISSUE TITLE
Feature request for enable the user directory

### ISSUE THREAD

**Issue by XiotSamuel** [spantaleev/matrix-docker-ansible-deploy#1799]
Feature request for enable the user directory

change the homeserver.yaml.j2 to following

`# User Directory configuration
#
user_directory:
    # Defines whether users can search the user directory. If false then
    # empty responses are returned to all queries. Defaults to true.
    #
    # Uncomment to disable the user directory.
    #
    enabled: {{ matrix_synapse_user_directory|to_json }}

    # Defines whether to search all users visible to your HS when searching
    # the user directory. If false, search results will only contain users
    # visible in public rooms and users sharing a room with the requester.
    # Defaults to false.
    #
    # NB. If you set this to true, and the last time the user_directory search
    # indexes were (re)built was before Synapse 1.44, you'll have to
    # rebuild the indexes in order to search through all known users.
    # These indexes are built the first time Synapse starts; admins can
    # manually trigger a rebuild via API following the instructions at
    #     https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/background_updates.html#run
    #
    # Uncomment to return search results containing all known users, even if that
    # user does not share a room with the requester.
    #
    search_all_users: {{ matrix_synapse_user_directory|to_json }}

    # Defines whether to prefer local users in search query results.
    # If True, local users are more likely to appear above remote users
    # when searching the user directory. Defaults to false.
    #
    # Uncomment to prefer local over remote users in user directory search
    # results.
    #
    #prefer_local_users: true`

Is it ok?

**Comment by spantaleev** [comment]
You can override any value in `homeserver.yaml`  by using `matrix_synapse_configuration_extension_yaml`. There's no need for changing our default configuration or for introducing new playbook variables.
