### ISSUE TITLE
Make the matrix domain's homepage useful

### ISSUE THREAD

**Issue by spantaleev** [spantaleev/matrix-docker-ansible-deploy#18]
As proposed by @anadahz, we should make the homepage at `matrix.DOMAIN` show something useful or redirect somewhere else, instead of being a 404 page.

Redirecting to `riot.DOMAIN` is one option, but also an option that would fail if `matrix_riot_web_enabled: false`.

It would probably be ideal if we have our own simple HTML page there, which contains an introduction to Matrix and possibly a link to this playbook.

**Comment by aaronraimist** [comment]
Synapse v0.34.0rc2 adds this page where the old webclient used to be https://matrix.raim.ist/_matrix/static/, could redirect `matrix.DOMAIN` to this

**Comment by spantaleev** [comment]
matrix-org/synapse#4289 says:

> We'll redirect to it from / if we have nothing better to display there.

.. but I'm not sure if it does it already or it will be something that's done in the future.
If they don't do it by default, we may be able to set up proxying ourselves too.
