### ISSUE TITLE
Use upstream mx-puppet-discord

### ISSUE THREAD

**Issue by dsonck92** [spantaleev/matrix-docker-ansible-deploy#1801]
**Is your feature request related to a problem? Please describe.**
Some weeks ago, a decision was made to switch from the official mx-puppet-bridge to the beeper maintained fork. This was done as the build of the Dockerfile was failing due to NPM + Github shenanigans. Meanwhile, I've migrated the official project over to gitlab (https://gitlab.com/mx-puppet/discord/mx-puppet-discord) and set-up proper CI pipelines to automatically build new releases, alleviating the need for manual building through the Dockerfile (even though this also still works).

Therefore I propose that it's reverted back, also because in the support channel for mx-puppet-bridge, some beeper specific issues have been cropping up (which, obviously, the upstream project does not want to deal with).

**Describe the solution you'd like**
Revert back to the original mx-puppet-bridge, which can now be found at `registry.gitlab.com/mx-puppet/discord/mx-puppet-discord`. Tags exist for versions (`vX.Y.Z`), specific branches (`main`) and of course `latest`.

NOTE: I cannot say whether shifting between the beeper and original version can be done without ill effects. Potentially the database needs to be fixed manually if any migrations happened on beepers fork.

**Comment by dsonck92** [comment]
Needless to say, I would really like this to go through, since I've had to mention "we don't support the ansible deployment, it's not **the** mx-puppet-discord we develop" a few times.

**Comment by dsonck92** [comment]
Also, the tracking issue there is: https://gitlab.com/mx-puppet/skype/mx-puppet-skype/-/issues/17

**Comment by spantaleev** [comment]
Good to hear that you've made so many improvements! We're happy to get back on the upstream train!

I've migrated my installation from the Beeper fork to yours (via #1802) and (so far) it appears to work well.

Thank you! :+1:
