### ISSUE TITLE
Nginx Hijack

### ISSUE THREAD

**Issue by Rein1n** [spantaleev/matrix-docker-ansible-deploy#1807]
Hello everyone, I was recently able to successfully install synapse using the ansible playbook, but it uses nginx in docker to host the webserver, meaning that my other services no longer work. I was wondering if there was a way to either manually config nginx without docker or how to have docker use a different port for nginx.

**Comment by aaronraimist** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#method-1-disabling-the-integrated-nginx-reverse-proxy-webserver

**Comment by Reinin-dev** [comment]
Thanks!
