### ISSUE TITLE
Reverse proxy example code for well-known for Apache2 is incorrect

### ISSUE THREAD

**Issue by brush** [spantaleev/matrix-docker-ansible-deploy#1815]
**Describe the bug**

Installation appears to work correctly. Services including synapse are working. However, self check fails with this error:

-----------
TASK [matrix-synapse : Check Matrix Client API] ********************************************************************************************

fatal: [matrix.example.com]: FAILED! => changed=false 
  connection: close
  content_length: '153'
  content_type: text/html
  date: Wed, 11 May 2022 01:58:26 GMT
  elapsed: 0
  msg: 'Status code was 404 and not [200]: HTTP Error 404: Not Found'
  permissions_policy: interest-cohort=()
  redirected: false
  server: nginx
  status: 404
  strict_transport_security: max-age=31536000; includeSubDomains
  url: https://matrix.example.com/_matrix/client/versions
...ignoring

TASK [matrix-synapse : Fail if Matrix Client API not working] 
fatal: [matrix.example.com]: FAILED! => changed=false 
  msg: 'Failed checking Matrix Client API is up at `matrix.example.com` (checked endpoint: `https://matrix.example.com/_matrix/client/versions`). Is Synapse running? Is port 443 open in your firewall? Full error: {''redirected'': False, ''url'': ''https://matrix.example.com/_matrix/client/versions'', ''status'': 404, ''date'': ''Wed, 11 May 2022 01:58:26 GMT'', ''server'': ''nginx'', ''content_type'': ''text/html'', ''content_length'': ''153'', ''strict_transport_security'': ''max-age=31536000; includeSubDomains'', ''permissions_policy'': ''interest-cohort=()'', ''connection'': ''close'', ''elapsed'': 0, ''changed'': False, ''failed'': True, ''msg'': ''Status code was 404 and not [200]: HTTP Error 404: Not Found''}'
-----------

Element runs, but results in this error:

`
There was a problem communicating with the homeserver, please try again later. (HTTP 404)
Cannot reach homeserver
Ensure you have a stable internet connection, or get in touch with the server admin
`

In addition, debug logging from synapse includes this:

`
matrix-synapse[192282]: 2022-05-11 01:18:29,846 - synapse.util.httpresourcetree - 47 - INFO - sentinel - Attaching <synapse.rest.ClientRestResource object at 0x7fa917fdad60> to path b'/_matrix/client'
`

... and many like it, mapping various files to urls I believe -- and I'm wondering if that "b" in front of all of them is spurious.

**To Reproduce**
My `vars.yml` file looks like this:

--------
matrix_domain: example.com
matrix_homeserver_generic_secret_key: 'SECRET'
matrix_ssl_lets_encrypt_support_email: 'web@example.com'
matrix_postgres_connection_password: 'PASSWORD'

#matrix_synapse_admin_enabled: true

#matrix_mautrix_signal_enabled: true
#matrix_mautrix_signal_relaybot_enabled: true

#matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
#matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: SECRET

#matrix_appservice_discord_enabled: true
#matrix_appservice_discord_client_id: "CLIENTID"
#matrix_appservice_discord_bot_token: "SECRET"

#matrix_appservice_discord_bridge_enableSelfServiceBridging: true

matrix_synapse_log_level: "INFO"
matrix_synapse_storage_sql_log_level: "INFO"
matrix_synapse_root_log_level: "INFO"
--------------------

Run ansible per instructions. Firewalls are open to required ports, DNS and SSL appear to be working.

**Expected behavior**

No self-test errors.

**Matrix Server:**
 - OS: 
 
 Ubuntu 22.04 running both ansible and the matrix server (same device)
 
 - Architecture
 
 amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)

Ansible run on same server, standard install- not containerized.

- what version of Ansible you're running (see `ansible --version`)

2.10.8

**Additional context**

I hope this is the right place to get installation support? If not, please point me. Thanks!

**Comment by brush** [comment]
quick update: i went to #synapse:matrix.org to see if it might be something synapse-specific they could help me with. they suggested https://matrix-org.github.io/synapse/latest/reverse_proxy.html -- ie. might be an issue with reverse proxy. i remembered the reverse proxy i installed on the main server to point to the matrix.* server, which is apache, and revised the config to have "nocanon" flag, but that didn't help.

then i entered the docker holding nginx, and looked at its config -- which is a reverse proxy based on, but quite a bit more complex than, the one in the ref file above.

how can i try to trace how a request for a  .../_matrix/... file flows through the various redirects, and where it is dropping? any ideas? thanks a ton!

**Comment by brush** [comment]
i think these excerpts from the syslog indicate the heart of the problem.

`May 13 00:32:21 hostname matrix-client-element[1913]: 2022/05/13 07:32:21 [error] 23#23: *63 open() "/usr/share/nginx/html/config.192.168.1.186.json" failed (2: No such file or directory), client: 172.18.0.2, server: localhost, request: "GET /config.192.168.1.186.json?cachebuster=1652427141183 HTTP/1.0", host: "192.168.1.186"
May 13 00:32:22 hostname matrix-client-element[1913]: 2022/05/13 07:32:22 [error] 23#23: *74 open() "/usr/share/nginx/html/_matrix/client/versions" failed (2: No such file or directory), client: 172.18.0.2, server: localhost, request: "GET /_matrix/client/versions HTTP/1.0", host: "192.168.1.186"
May 13 00:32:22 hostname matrix-client-element[1913]: 2022/05/13 07:32:22 [error] 23#23: *77 open() "/usr/share/nginx/html/_matrix/client/versions" failed (2: No such file or directory), client: 172.18.0.2, server: localhost, request: "GET /_matrix/client/versions HTTP/1.0", host: "192.168.1.186"
May 13 00:32:22 hostname matrix-client-element[1913]: 2022/05/13 07:32:22 [error] 23#23: *81 open() "/usr/share/nginx/html/_matrix/client/r0/login" failed (2: No such file or directory), client: 172.18.0.2, server: localhost, request: "GET /_matrix/client/r0/login HTTP/1.0", host: "192.168.1.186"
May 13 00:32:33 hostname matrix-client-element[1913]: 2022/05/13 07:32:33 [error] 23#23: *83 open() "/usr/share/nginx/html/_matrix/client/versions" failed (2: No such file or directory), client: 172.18.0.2, server: localhost, request: "GET /_matrix/client/versions HTTP/1.0", host: "192.168.1.186"
May 13 00:32:33 hostname matrix-client-element[1913]: 2022/05/13 07:32:33 [error] 23#23: *85 open() "/usr/share/nginx/html/_matrix/client/r0/login" failed (2: No such file or directory), client: 172.18.0.2, server: localhost, request: "GET /_matrix/client/r0/login HTTP/1.0", host: "192.168.1.186"
`

the IP addresses are original -- 192.168.1.2 is the TLD server; 192.168.1.186 is the non-docker IP of the matrix.TLD server, and the 172.* are docker IPs.

i believe i've set up the reverse proxy from the TLD server correctly.

**Comment by brush** [comment]
i've resolved this issue, i believe. partly the result of a complex DNS situation behind a firewall; however, was hamstrung by the fact that the instructions in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md for a reverse proxy on Apache2 appear to be incorrect.

should be rather something like:
        SSLProxyEngine on
#        <Location /.well-known/matrix>
#                ProxyPass "https://matrix.cedarmoon.us/.well-known/matrix" nocanon
#        </Location>

        ProxyPass /.well-known/matrix https://matrix.cedarmoon.us/.well-known/matrix nocanon
        ProxyPassReverse /.well-known/matrix https://matrix.cedarmoon.us/.well-known/matrix nocanon
`

i recommend the doc file gets changed promptly.

**Comment by brush** [comment]
above comment looks terrible. the code suggestion is in https://pastebin.com/6xBNgT8Q

**Comment by spantaleev** [comment]
PRs are welcome

**Comment by brush** [comment]
done!

**Comment by spantaleev** [comment]
Fixed by #1820
