### ISSUE TITLE
Matrix Registration Bot- Attempting to pull docker image that doesn't exist

### ISSUE THREAD

**Issue by wibbene** [spantaleev/matrix-docker-ansible-deploy#1847]
Commit 0c741e8d166bcc73792cbb44810be59e7031c330 pulls a docker image with a tag that does not exist. [See the DockerHub](https://hub.docker.com/r/moanos/matrix-registration-bot/tags) to see that the tag does not exist. This commit breaks the playbook, giving out a manifest unknown error while using the tag of setup-all.

It looks @GoliathLabs was trying to bump to the latest version on the [Matrix Registration GitHub Repo](https://github.com/moan0s/matrix-registration-bot), but the DockerHub is unclear on which version it's on. I am going to submit a Pull Request reverting the change in 0c741e8d166bcc73792cbb44810be59e7031c330 as a hot fix to master/main.

**Comment by GoliathLabs** [comment]
@wibbene Thanks for the fix. I went through a few image updates that day and may have thought there was a proper version tag if there was also a release on Github. I will do better in the future.
