### ISSUE TITLE
mautrix-whatsapp bridge missing config to enable spaces creation

### ISSUE THREAD

**Issue by roughnecks** [spantaleev/matrix-docker-ansible-deploy#1855]
**Matrix Server:**
 - OS: Debian 11
 - Architecture amd64

**Problem description**:
Hello, I wanted to automatically create a space for my logged user in mautrix whatsapp bridge (something like heisenbridge does), so I asked over their Matrix room and they told me to check config.yaml, because it could be enabled that way.
I browsed mautrix-wa's github, found the example-config.yaml and these lines:

https://github.com/mautrix/whatsapp/blob/master/example-config.yaml#L98-L100

Problem is, there's not trace of this config line in my `roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2`
Can I still enable it?

**Additional context**
This is the release where spaces first appeared in mautrix:
https://github.com/mautrix/whatsapp/releases/tag/v0.2.3

I'm running:
mautrix-whatsapp 0.4.0 (May 16 2022, 17:36:06)

Thanks

**Comment by aaronraimist** [comment]
Yes you can still enable it using `matrix_mautrix_whatsapp_configuration_extension_yaml`.

If you would like to you can submit a PR to bring `roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2` up to date with the current sample config but it is not necessary.

**Comment by roughnecks** [comment]
> Yes you can still enable it using `matrix_mautrix_whatsapp_configuration_extension_yaml`.

Alright! Thanks :)

> If you would like to you can submit a PR to bring `roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2` up to date with the current sample config but it is not necessary.

Oh, I could do that but I guess I'm not able to.. Never done a PR before. Sorry
