### ISSUE TITLE
Failed - Download matrix-synapse-shared-secret-auth

### ISSUE THREAD

**Issue by benguichard** [spantaleev/matrix-docker-ansible-deploy#1857]
**Describe the bug**

When I'm enabling the variable `matrix_synapse_ext_password_provider_shared_secret_auth_enabled` to activate shared secret auth, it's returning the following error before crash:
FAILED - RETRYING: Download matrix-synapse-shared-secret-auth (X retries left).

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "my_secret"
```

**Expected behavior**
Supposed to download a script and enable the shared secret auth functionality

**Matrix Server:**
 - OS:Ubuntu 22.04
 - Architectur: amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible:  on the Matrix server itself;
- what version of Ansible you're running: 2.10.8

**Additional context**
N/A

**Comment by spantaleev** [comment]
Maybe Github was down or you're having some Docker-related networking issues. Try rebooting the server or checking your firewall.
