### ISSUE TITLE
Invalid example AWS policy for configuring S3 media_store

### ISSUE THREAD

**Issue by jakecoppinger** [spantaleev/matrix-docker-ansible-deploy#1869]
The example S3 policy at https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-s3.md appears invalid. This is the error returned from the `Edit bucket policy` form in the AWS Console:

```
Unknown Error
An unexpected error occurred.
API response
Missing required field Principal
```

I'm not sure what the value of `Principal` should be. I really don't want to get this wrong as I believe this allows public access to the bucket if configured incorrectly.

The AWS docs are at https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html

Should `"Principal": { "AWS": "..." }` be added where `...` is the user's account ID? (in the dropdown under the username in the top right of the AWS Console).

**Comment by spantaleev** [comment]
> You cannot use the Principal element in an identity-based policy. Identity-based policies are permissions policies that you attach to IAM identities (users, groups, or roles). In those cases, the principal is implicitly the identity where the policy is attached.

You're adding this policy using **Edit bucket policy**, which is incorrect. You should create a new IAM user and attach the policy there. Doing that, the Principal is implicitly specified.

`docs/configuring-playbook-s3.md` says:

> You'll need an Amazon S3 bucket and some IAM user credentials (access key + secret key) with full write access to the bucket

.. so I believe it made it clear, but I've nevertheless improved our docs in 337016d.
