### ISSUE TITLE
Telegram web login not working with separate webserver

### ISSUE THREAD

**Issue by timo95** [spantaleev/matrix-docker-ansible-deploy#189]
Trying to use the external Telegram-Bridge login gives me a 404. The chat based login works as expected. I use nginx as webserver. The self-check gives no errors and everything else works.

**Comment by aaronraimist** [comment]
What do you mean by external telegram bridge? You are hosting https://github.com/tulir/mautrix-telegram seperately?

**Comment by aaronraimist** [comment]
`#matrix-docker-ansible-deploy:devture.com` is a better place to get support than GitHub issues by the way.

**Comment by timo95** [comment]
Sorry, that wasn't clear. I mean the web based external login feature of the included telegram bridge.

**Comment by timo95** [comment]
It seems to me like `/matrix/nginx-proxy/conf.d/matrix-synapse.conf` isn't forwarding me to the login page. Using the included nginx works, but not so with my own nginx.

**Comment by timo95** [comment]
I am using mautrix-telegram v0.5.2: `matrix_mautrix_telegram_docker_image: "tulir/mautrix-telegram:v0.5.2"`

**Comment by spantaleev** [comment]
You're right! This was never implemented to begin with.

Hopefully fixed in 7379968a3c7cb7

**Comment by timo95** [comment]
Not yet. I got it working for http by setting `matrix_mautrix_telegram_container_http_host_bind_port` to a port without ip and setting `matrix_mautrix_telegram_appservice_public_external` accordingly. The port was missing and i had to use http.

Trying this with https (the default) returned `SSL_ERROR_RX_RECORD_TOO_LONG`.

**Comment by spantaleev** [comment]
You're right, there was another bug.

When `matrix_nginx_proxy_enabled: false`, the bridge setup code would not inject the configuration into the `matrix-synapse.conf` vhost.

I've fixed that in 5361d3a.

----------

With your workaround, you were not going through your nginx server at `https://matrix.DOMAIN`, but rather accessing the Telegram container's endpoint directly (without HTTPS, at something like `http://matrix.DOMAIN:9006/uuid-here`).

With the new fixes, you should be able to access Telegram's login endpoint at `https://matrix.DOMAIN/uuid-here`, as expected.

**Comment by timo95** [comment]
Thank you! It works now.
