### ISSUE TITLE
Support the new location of the Synapse admin APIs

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#191]
See https://github.com/matrix-org/synapse/pull/5119, they moved from /_matrix to /_synapse

**Comment by spantaleev** [comment]
I was looking at this as something that needs to be done for [matrix-corporal](https://github.com/devture/matrix-corporal) (see https://github.com/devture/matrix-corporal/issues/2), but I completely forgot that we need to add support for reverse-proxying here.

Done now! Thanks for bringing it up! :+1:
