### ISSUE TITLE
Hookshot update referenced before it is published

### ISSUE THREAD

**Issue by derhagen** [spantaleev/matrix-docker-ansible-deploy#1952]
As of right now, commit 05ccee9f6f436c0b6f1e84b8f74fa002f205ef67 leads to the error `msg: 'Error pulling image docker.io/halfshot/matrix-hookshot:1.8.1 - 404 Client Error: Not Found ("manifest for halfshot/matrix-hookshot:1.8.1 not found: manifest unknown: manifest unknown")'`

As @etkecc notes in the commit message, the respective docker tag hasn't been published, yet.

This issue will probably fix itself as soon as the tag is public, however, I think there should be a test in place to avoid such an issue in the first place.

**Comment by etkecc** [comment]
Looks like the https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1949 was accidentally merged before tag was published
