### ISSUE TITLE
arm64 matrix-dimension self build error

### ISSUE THREAD

**Issue by DUCKCHI** [spantaleev/matrix-docker-ansible-deploy#2008]
**Describe the bug**

There was a problem restarting playbook using the following command:
**ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start**

TASK [matrix-dimension : Ensure dimension repository is present on self-build] ***
fatal: [matrix.domain]: FAILED! => changed=false
  msg: |-
    Failed to set a new url https://github.com/turt2live/matrix-dimension.git for origin:  fatal: detected dubious ownership in repository at '/matrix/docker-src/dimension'
    To add an exception for this directory, call:

            git config --global --add safe.directory /matrix/docker-src/dimension

I ran the following command as shown in the error, but the same error continues to occur.
**git config --global --add safe.directory /matrix/docker-src/dimension**

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
Paste your vars.yml file here.
Make sure to remove any secret values before posting your vars.yml file publicly.
```

**Expected behavior**

**Matrix Server:**
 - OS: [e.g. Ubuntu 21.04]
 - Architecture [e.g. amd64, arm32, arm64]

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Client:**

**Additional context**

**Comment by spantaleev** [comment]
Have you seen this?

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#compatibility-break-changes-to-docker-src-permissions-necessitating-manual-action

**Comment by DUCKCHI** [comment]
As a result of executing the find command, an existing error is resolved, but a new error occurs.

failed: [matrix.domain.com] (item=matrix-synapse.service) => changed=false
  ansible_loop_var: item
  item: matrix-synapse.service
  msg: matrix-synapse.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-synapse.service` and `journalctl -fu matrix-synapse.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.

failed: [matrix.domain.com] (item=matrix-dimension.service) => changed=false
  ansible_loop_var: item
  item: matrix-dimension.service
  msg: matrix-dimension.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-dimension.service` and `journalctl -fu matrix-dimension.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `matrix_common_after_systemd_service_start_wait_for_timeout_seconds` variable. See `roles/matrix-common-after/defaults/main.yml` for more details about that.


Errors occur in matrix-synapse and matrix-dimension that were previously operating.

**Comment by DUCKCHI** [comment]
Problem solved. Thank you for your reply :)
