### ISSUE TITLE
Fetching Appservice Discord docker image returns error due to typo

### ISSUE THREAD

**Issue by blotree** [spantaleev/matrix-docker-ansible-deploy#2022]
As of commit 69dce034b1190e65088a30ba276ece252cbde743 the variable in /roles/matrix-bridge-appservice-discord/defaults/main.yml `matrix_appservice_discord_docker_image_name_prefix: "{{ 'localhost/' if matrix_appservice_discord_container_image_self_build else 'ghcr.io' }}"` results in an internal server error when the playbook attemtps to fetch the image as it looks for the address ghcr.iomatrix-org%2Fmatrix-appservice-discord if the image is not self-built.

It is missing a trailing / after ghcr.io and I believe the variable ought to read: 
`matrix_appservice_discord_docker_image_name_prefix: "{{ 'localhost/' if matrix_appservice_discord_container_image_self_build else 'ghcr.io/' }}"`

The addition of the forward slash makes everything work correctly again.

**Comment by spantaleev** [comment]
Thanks! Should be fixed now!
