### ISSUE TITLE
Adding Cactus Comments as a service to this playbook

### ISSUE THREAD

**Issue by N07070** [spantaleev/matrix-docker-ansible-deploy#2024]
Hello everyone,

I've been pondering on using Cactus comments for my blog for a while, and as I've found time to reinstall this playbook on my servers, I was working on installing Cactus Comments too. 

Now, it seems that a role to install Cactus Comments via Ansible doesn't exist yet. As such, I wanted to create one. Would anyone be interested in working on one together ? 

I would also very much like for the role to be included in this playbook, as it would make it much much easier for me to manage all of it. Would there be interest in it ? Or at least, does anyone oppose it ? 

Cheers,

**Comment by spantaleev** [comment]
I haven't heard of anyone working on a Cactus Comments role. It sounds like a nice addition to the playbook though! If you'd like to work on a PR, that'd be great! If you need any guidance, feel free to ask here or in [our support room](https://github.com/spantaleev/matrix-docker-ansible-deploy#support).

**Comment by N07070** [comment]
Thank for your answer ! I'm already in the support room :) 

I'll let you know there ( and here ) when I make progress on the role.

**Comment by moan0s** [comment]
I also use Cactus Comments and would love to bring this to life. Feel free to drop a DM to @moanos:hyteck.de if you need help

**Comment by moan0s** [comment]
I started working on it here: https://github.com/moan0s/matrix-docker-ansible-deploy/tree/cactus-comments
Help or advice welcome (and don't expect fast progress, I am on vacation)
