### ISSUE TITLE
Installing issuse

### ISSUE THREAD

**Issue by elohffa** [spantaleev/matrix-docker-ansible-deploy#203]
When I run the command  ansible-playbook -i inventory/hosts setup.yml --tags=setup-all
to do the initial setup. It report is fail . 
FAILED! => {"ansible_facts": {}, "changed": false, "msg": "The following modules failed to execute: setup\n  setup: MODULE FAILURE\nSee stdout/stderr for the exact error\n"}

**Comment by spantaleev** [comment]
The above error doesn't say too much, so it's hard to say what's wrong.
It might be that there's no Python interpreter on the server, but I'm not sure.
Try installing python on the target server.

Also.. try running the above command in verbose mode. Example:

```
ansible-playbook -vvv -i inventory/hosts setup.yml --tags=setup-all
```

.. and see if there's a more meaningful error.

**Comment by elohffa** [comment]
When I get this error message  :    "msg": "Failed to import docker or docker-py (Docker SDK for Python) - No module named ssl_match_hostname. Try `pip install docker` or `pip install docker-py` (Python 2.6)."
Then I install pip install docker and re-run again, I also get this error message
.

**Comment by spantaleev** [comment]
Which distro is this on?

You don't need to install `docker` or `docker-py` via `pip`.
Just start from an empty server (no Docker or anything). Only ssh & Python are necessary.

The playbook installs `docker-py` and other such stuff by itself.
.. unless you are on an unsupported distribution.. which will likely cause additional issues as well.

**Comment by spantaleev** [comment]
It might be faster to get help if you join the support room.
See here: https://github.com/spantaleev/matrix-docker-ansible-deploy#support

**Comment by elohffa** [comment]
My distro isDISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

I run dpkg -l | grep -i docker

ii  golang-docker-credential-helpers           0.6.1-1                                            amd64        Use native stores to safeguard Docker credentials
ii  python-docker                              3.4.1-2                                            all          Python wrapper to access docker.io's control socket
ii  python-dockerpty                           0.4.1-1                                            all          Pseudo-tty handler for docker Python client (Python 2.x)
ii  python-dockerpycreds                       0.2.2-1                                            all          Python bindings for the docker credentials store API

**Comment by elohffa** [comment]
This error message only happened when it was at TASK [matrix-mailer : Ensure mailer image is pulled]

**Comment by spantaleev** [comment]
Oh, so you managed to move further than the initial error you've reported (`The following modules failed to execute: setup\n setup: MODULE FAILURE\nSee stdout/stderr for the exact error\n`)

**Comment by elohffa** [comment]
Yes . I fix it by add ansible_password=mypasswod  and ansible_sudo_pass=mypassword to the hosts file .

**Comment by elohffa** [comment]
Yeah , I fixed 

I type : sudo cp -r /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports

then run ansible-playbook -vvv -i inventory/hosts setup.yml --tags=setup-all

**Comment by spantaleev** [comment]
I'm not sure why you had to do this, but.. okay.
Good to know that you got it running!
