### ISSUE TITLE
Typing makes CPU skyrockets

### ISSUE THREAD

**Issue by roughnecks** [spantaleev/matrix-docker-ansible-deploy#2040]
I recorded this video to show you: https://youtu.be/gE0z6NgzJ8Q

It looks like it's happening only on a room outside my homeserver; all local rooms are fine.

**Comment by spantaleev** [comment]
Seems like Synapse may be handling typing notifications (over federation) inefficiently.. Or there's just too much work to send it to all servers.

This is unlikely to be a problem with our deployment method and likely to be a problem with [Synapse](https://github.com/matrix-org/synapse) itself. Consider opening this issue there.
