### ISSUE TITLE
matrix-dendrite-create-account parses arguments incorrectly

### ISSUE THREAD

**Issue by madprogramer** [spantaleev/matrix-docker-ansible-deploy#2057]
**Describe the bug**
Attempting to create an account on the dendrite server with the `matrix-dendrite-create-account` util fails.

**To Reproduce**
Enable Dendrite instead of Synapse:

```yaml
# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: dendrite
```

ssh into your server and attempt to create a new account as follows:

```shell
/usr/local/bin/matrix-dendrite-create-account myaccount weakpassword 0 
```
This input is unrecognised, giving the expected usage of the command as output: 
```shell
Usage: /usr/local/bin/matrix-dendrite-create-account <username> <password> <admin access: 0 or 1>
```

However, if `admin access` is not provided, an account is generated successfully with the following message:
```shell
/usr/local/bin/matrix-dendrite-create-account: line 12: [: : integer expression expected
time="2022-08-25T20:10:04Z" level=info msg="Created account: myaccount (AccessToken: SOMETOKEN)"
```

**Expected behavior**
Without any error message, we should expect to see:
```shell
time="2022-08-25T20:10:04Z" level=info msg="Created account: myaccount (AccessToken: SOMETOKEN)"
```

**Comment by spantaleev** [comment]
Thanks for the report! It should be fixed now!

I wonder what this is about though:

> /usr/local/bin/matrix-dendrite-create-account: line 12: [: : integer expression expected
