### ISSUE TITLE
Serve all subdomains as base domains.

### ISSUE THREAD

**Issue by DUCKCHI** [spantaleev/matrix-docker-ansible-deploy#2058]
SSL was issued for the subdomain using option `matrix_ssl_additional_domains_to_obtain_certificates_for
`, and nginx configuration for the subdomain was added using option `matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:`.

However, there is a problem of serving access to all subdomains as the base domain.
I wonder how I can activate the subdomain service while maintaining the default domain serving.

**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: domain.com
cloud_domain: "cloud.{{ matrix_domain }}"

# The Matrix homeserver software to install.
# See `roles/matrix-base/defaults/main.yml` for valid options.
matrix_homeserver_implementation: synapse
matrix_architecture: arm64
matrix_nginx_proxy_base_domain_serving_enabled : true
matrix_ssl_additional_domains_to_obtain_certificates_for :
          - ' {{ matrix_domain }} '
          - ' {{ cloud_domain }}'

matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    server {
        listen 8080;
        listen [::]:8080;

        server_name {{ cloud_domain }};
        server_tokens off;
        root /dev/null;

        location /.well-known/acme-challenge {
                resolver 127.0.0.11 valid=5s;
                set $backend "matrix-certbot:8080";
                proxy_pass http://$backend;
        }
        location / {
                        return 301 https://$http_host$request_uri;
        }
     }
  - |
    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;


        server_name {{ cloud_domain }};

        server_tokens off;
        root /dev/null;

        ssl_certificate /matrix/ssl/config/live/{{ cloud_domain }}/fullchain.pem;
        ssl_certificate_key /matrix/ssl/config/live/{{ cloud_domain }}/privkey.pem;

        ssl_protocols TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_session_tickets off;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_timeout 1d;

        gzip on;
gzip_types text/plain application/json application/javascript text/css image/x-icon font/ttf image/gif;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Frame-Options SAMEORIGIN;
        add_header Content-Security-Policy "frame-ancestors 'self'";

        add_header Permissions-Policy interest-cohort=() always;

        location / {

            client_max_body_size 150m;
                        resolver 127.0.0.11 valid=5s;
                        set $backend "nextcloud_app_1:6374";
                        proxy_pass http://$backend;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
        }


    }
                            
```

**Matrix Server:**
 - OS: Ubuntu 21.04
 - Architecture  arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

**Additional context**

**Comment by aaronraimist** [comment]
Are you asking whether you can put the services like Element or Synapse on a second level domain rather than subdomain? 

Yes you can. They don't have to be subdomains, they can be any domain. You can set any of these variables in your `vars.yml` file https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/8d96e4755583af5d9056ffec2d325bfaf90b8e38/roles/matrix-base/defaults/main.yml#L42-L78.
