### ISSUE TITLE
Variables for Dendrite registration in vars.yml

### ISSUE THREAD

**Issue by madprogramer** [spantaleev/matrix-docker-ansible-deploy#2059]
Recently, https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/3ff56bff1deb0ce048d8b4919afbd3fb2ffd28d2 changed the default value on `matrix_dendrite_registration_disabled` to false. I know that this is policy to prevent increasing spam on matrix, but I have had a long standing goal of keeping my server as open as possible. 

Better than having the default be hidden in `matrix-dendrite/defaults/main.yml`, it might be a good idea to add this as a var to `vars.yml` as well as the `matrix_dendrite_enable_registration_captcha` family of vars.

**Comment by spantaleev** [comment]
Only a very very very small percentage of people would want to expose their server publicly. We don't (and have never) catered to those.

Adding a bunch of unnecessary stuff to our `vars.yml` example is counter-productive. The playbook is very flexible and there are just too many possibilities to list. You want a public server, someone else wants a non-federating server, yet another wants a Synapse server with workers, yet another wants some LDAP integration, etc., etc.

People are advised to to look at the `defaults/main.yml` file for the various components they care about and tweak them accordingly.
