### ISSUE TITLE
Mautrix Bridge Cannot Instantiate Tempfiles on Dendrite

### ISSUE THREAD

**Issue by madprogramer** [spantaleev/matrix-docker-ansible-deploy#2060]
**Describe the bug**
Mautrix Bridge for Discord installs correctly, but fails at runtime due to misconfigured privileges (file-system write-only).
**This is at least the case on Dendrite**, I'm not sure if Synapse has also broken.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
...
matrix_homeserver_implementation: dendrite
matrix_mautrix_discord_enabled: true
...
```

After installing with `ansible-playbook -i inventory/hosts setup.yml --tags="setup-all, start"` and `ssh`ing into my server:
```shell
journalctl -fu matrix-mautrix-discord.service
-- Logs begin at Fri 2022-08-26 02:29:45 CEST. --
Aug 26 09:26:52 SERVER.NET systemd[1]: Stopping Matrix Mautrix Discord bridge...
Aug 26 09:26:55 SERVER.NET matrix-mautrix-discord[11804]: matrix-mautrix-discord
Aug 26 09:26:55 SERVER.NET systemd[1]: matrix-mautrix-discord.service: Main process exited, code=exited, status=137/n/a
Aug 26 09:26:55 SERVER.NET systemd[1]: matrix-mautrix-discord.service: Failed with result 'exit-code'.
Aug 26 09:26:55 SERVER.NET systemd[1]: Stopped Matrix Mautrix Discord bridge.
Aug 26 09:27:46 SERVER.NET systemd[1]: Starting Matrix Mautrix Discord bridge...
Aug 26 09:27:51 SERVER.NET systemd[1]: Started Matrix Mautrix Discord bridge.
Aug 26 09:27:53 SERVER.NET matrix-mautrix-discord[15034]: Error updating config: failed to create temp file for writing config: open /config/mautrix-config-2789911224.yaml: read-only file system
```

**Expected behavior**
If `matrix-mautrix-discord` is running correctly, `@discordbot:YOURDOMAIN` should be invitable on matrix clients.

**Matrix Server:**
 - OS: Debian GNU/Linux 10 (buster)
 - Architecture: amd64

**Comment by madprogramer** [comment]
Might be relevant to @shalzz

**Comment by spantaleev** [comment]
If the bridge is not working, it may be some incompatibility with Dendrite. I don't know if `mautrix-discord` fully works there.

I've made us pass the `--no-update` option to the bridge, so that it won't try to overwrite its read-only configuration.
