### ISSUE TITLE
Working Cactus Setup without Nginx Proxy

### ISSUE THREAD

**Issue by ralfi** [spantaleev/matrix-docker-ansible-deploy#2101]
**Describe the bug**
Cactus setup task to creating config for nginx proxy crashes if nginx proxy is disabled.

**To Reproduce**
My `vars.yml` file looks like this: 

```yaml
matrix_nginx_proxy_enabled: false
matrix_cactus_comments_enabled: true
```

I am using MaDoAnDe behind a apache reverse proxy and do not use nginx. 

**Expected behavior**
Setup a `var` construct which enable cactus setup whithout nginx

**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64

**Comment by spantaleev** [comment]
It'd be helpful to know where it crashes and with what error.
