### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by roughnecks** [spantaleev/matrix-docker-ansible-deploy#2117]
Hello,
I would like to ask a few questions which weren't answered in the Matrix room.

1. What do I need to do to enable guests access? Should any registration's verification method be disabled?
2. Does any Android client support registration with Google ReCaptcha?
3. Why hydrogen's image gets rebuilt every time I setup-all?

Thanks

**Comment by roughnecks** [comment]
1. Other than `matrix_synapse_allow_guest_access: true` also `matrix_client_element_disable_guests: false` must be set. Then guest access is enable in Element.
2. Yes
3. Still unclear..

**Comment by RoiArthurB** [comment]
@roughnecks For your last point, it's because hydrogen is set as `self_build` by default : 

From file `roles > matrix-client-hydrogen > defaults > main.yaml (l. 6-8)`
```
# Self building is used by default because the `config.json` file is only read at build time.
# The pre-built images also were not functional as of 2021-05-15.
matrix_client_hydrogen_container_image_self_build: true
```

**Comment by roughnecks** [comment]
> ```
> # Self building is used by default because the `config.json` file is only read at build time.
> # The pre-built images also were not functional as of 2021-05-15.
> ```

So is there no other way than this atm?

**Comment by RoiArthurB** [comment]
I'm really not sure, I don't follow Hydrogen dev... Maybe @aaronraimist (who made this comment and modif) can help ? 🤷

**Comment by aaronraimist** [comment]
It is possible this has been partially solved by this PR from April 2022 https://github.com/vector-im/hydrogen-web/pull/723 which suggests the `config.json` is now read at built time. However I just spent an hour trying to make it work and I could not make it work. I feel free to give it a try but I can't put more time in to this.

One remaining issue is that there no one is maintaining pre-built images. So self building will still have to be used even if the other issue is resolved, but it should be able to happen less frequently.

**Comment by roughnecks** [comment]
At this point it doesn't matter, I'll just avoid installing it.

Thanks @RoiArthurB and @aaronraimist
