### ISSUE TITLE
mxisd is EOL

### ISSUE THREAD

**Issue by TheLastProject** [spantaleev/matrix-docker-ansible-deploy#212]
This came pretty out of nowhere to me: https://github.com/kamax-matrix/mxisd/commit/21d9d0fda1590f65f01f0db389b82b7b66ff264d.

A replacement probably needs to be found? :/

**Comment by aaronraimist** [comment]
There is a fork here so we can watch how that progresses https://github.com/ma1uta/mxisd

**Comment by davidmehren** [comment]
That fork has now been renamed to ma1sd and received quite a few updates in the last weeks. Any plans to switch from mxisd to ma1sd?

**Comment by spantaleev** [comment]
If using mxisd is starting to cause us trouble (clients no longer working, etc.) or if there are clear benefits to using ma1sd, we should consider switching.. Or at least adding ma1sd as an option.

**Comment by eMPee584** [comment]
I just duplicated the role and fixed up the strings and the image location... (#333) Have not yet tested it, that's my next step. Just wanted to get somethign out there in 2019 :sweat_smile: 
HAPPY NEW YEAR! #MATRIX :sparkles: :rocket: :four_leaf_clover:

**Comment by eMPee584** [comment]
So question is, should we have an option to use ma1sd, which would be tiny bit more complicated to integrate, or just switch to ma1sd completely which is trivial and I am about to do now..

**Comment by thegcat** [comment]
As mxisd has been end-of-lifed there's imho no need to keep it around.

**Comment by spantaleev** [comment]
Lots of people are still probably using mxisd, likely with some integration attached to it.
If ma1sd is to supersede it, they need to switch to it and check that nothing breaks.

Removing mxisd completely right away (without any transition path) sounds a bit invasive.

**Comment by eMPee584** [comment]
totally, that's what I was also wondering about.. i'll have a look at the existing migration script for var renames.. I'm a slow coder but hope to get it testable tomorrow.. basically just more string replaces i need to get my head around..

**Comment by spantaleev** [comment]
This is now solved by @eMPee584 via #333!

Check the changelog for more information. Basically, people with no special identity server configuration (sticking to defaults) will have the playbook automatically migrate them to ma1sd without manual intervention being necessary.
