### ISSUE TITLE
Update Instagram bridge

### ISSUE THREAD

**Issue by LJAM96** [spantaleev/matrix-docker-ansible-deploy#2156]
#https://github.com/mautrix/instagram/issues/56

The Instagram bridge appears to have an issue in which it allows you to sign in and gives you a confirmation but on pinging the service it states youre not signed in, it appears to be fixed in the latest Instagram bridge commit

**Comment by spantaleev** [comment]
The last stable release is currently `0.2.1`, which we're on. Hopefully upstream will release a new stable version soon.

If you'd like, you can switch yourself to `:latest` now by changing your `vars.yml` file.

**Comment by LJAM96** [comment]
Hi, yes it seems the fix isnt included in build `0.2.1` currently.
Changing to `:latest` has fixed the issue 👍

**Comment by spantaleev** [comment]
I've changed the playbook to default to `latest` for this bridge for now: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/da041bc60c67f674ac9f748e528ee3d42ebafb28
