### ISSUE TITLE
How to setup backup federation and identity server in case the primary homeserver was down 

### ISSUE THREAD

**Issue by elohffa** [spantaleev/matrix-docker-ansible-deploy#217]
According to the idea of matrix was providing a decentralize application , could u let me know how to setup a backup federation and identity server were under the same domain name  of my homeserver , in case the primary homeserver was down .,

**Comment by spantaleev** [comment]
The playbook doesn't help you with anything of this sort. The Synapse server does not support such a thing. You can use workers, but they still need to be controlled by a single master Synapse process. Trying to run multiple master processes at the same time is likely disastrous.

The upcoming [Dendrite](https://github.com/matrix-org/dendrite) server is likely to be better in this regard.
