### ISSUE TITLE
Matrix Coturn Installation Fail

### ISSUE THREAD

**Issue by e-legy** [spantaleev/matrix-docker-ansible-deploy#2172]
**Describe the bug**
TASK [matrix-coturn : Ensure turnserver.conf installed] ***************************************************************
fatal: [matrix.elegymagic.tk]: FAILED! => changed=false
  msg: 'TemplateRuntimeError: no test named ''ne'''

**Comment by whowantsmybigdata** [comment]
> TemplateRuntimeError: no test named ''ne'''

sounds like you changed the template for `turnserver.conf` into something not working properly?

**Comment by NewOcean11** [comment]
> > TemplateRuntimeError: no test named ''ne'''
> 
> sounds like you changed the template for `turnserver.conf` into something not working properly?
> 
> edit: I mean the template in /roles/matrix-coturn/templates/[turnserver.conf.j2](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-coturn/templates/turnserver.conf.j2)
> 
> If so, changes should go in your `vars.yml` file not into the roles itself. What were you trying to change?

me 2，and nothing changed in template...I just wonder set DNS Record of turn in CNAME？

**Comment by bmossavari** [comment]
> > TemplateRuntimeError: no test named ''ne'''
> 
> sounds like you changed the template for `turnserver.conf` into something not working properly?
> 
> edit: I mean the template in /roles/matrix-coturn/templates/[turnserver.conf.j2](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-coturn/templates/turnserver.conf.j2)
> 
> If so, changes should go in your `vars.yml` file not into the roles itself. What were you trying to change?

seems like this line #8 of turnserver.conf.j2 is the source of our problem
`{% for ip in matrix_coturn_turn_external_ip_addresses|select('ne', '') %}`
I change it back to 
`{% for ip in matrix_coturn_turn_external_ip_addresses %}`
and everyting works now

**Comment by e-legy** [comment]
> > > TemplateRuntimeError: no test named ''ne'''
> > 
> > 
> > sounds like you changed the template for `turnserver.conf` into something not working properly?
> > edit: I mean the template in /roles/matrix-coturn/templates/[turnserver.conf.j2](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-coturn/templates/turnserver.conf.j2)
> > If so, changes should go in your `vars.yml` file not into the roles itself. What were you trying to change?
> 
> seems like this line #8 of turnserver.conf.j2 is the source of our problem `{% for ip in matrix_coturn_turn_external_ip_addresses|select('ne', '') %}` I change it back to `{% for ip in matrix_coturn_turn_external_ip_addresses %}` and everyting works now

It works, thanks.
