### ISSUE TITLE
Mautrix iMessage support

### ISSUE THREAD

**Issue by MangoTornado** [spantaleev/matrix-docker-ansible-deploy#2173]
Would it be possible to add support for matrix iMessage and wsproxy, there is a docker image provided I believe but I'm not sure how to add it to the playbook

**Comment by aaronraimist** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1016 is the existing issue for wsproxy. There were a couple of unfinished attempts to add it to the playbook https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1050 https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1523.

**Comment by MMM1150** [comment]
ลบ

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1016. wsproxy has been implemented by https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2261.
