### ISSUE TITLE
Runtime error when trying to set up Appservice Slack with the builtin NGINX reverse proxy disabled

### ISSUE THREAD

**Issue by randomsnowflake** [spantaleev/matrix-docker-ansible-deploy#2177]
**Steps to reproduce:**
- Install the Matrix server but do not use the builtin NGINX reverse proxy (`matrix_nginx_proxy_enabled: false`)
- Enable Appservice Slack as described in the official [documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-appservice-slack.md)
- Try to run the installation: `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all`

**Expected behaviour**
- It installs the slack bridge

**Actual behaviour**
- The following error appears
```
TASK [matrix-bridge-appservice-slack : Warn about reverse-proxying if matrix-nginx-proxy not used] **************************************************************************************************
fatal: [matrix.DOMAIN]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'something' is undefined
  
    The error appears to be in '[..]/matrix-docker-ansible-deploy/roles/matrix-bridge-appservice-slack/tasks/init.yml': line 83, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Warn about reverse-proxying if matrix-nginx-proxy not used
      ^ here
```

**Comment**
- the error message string is referencing a variable that does not exist (`something`). This should be fixed
- the documentation also lacks to describe how to set up the slack bridge when not using the builtin NGINX server. It seems you have to reverse proxy another port / path, but which one?

**Comment by catswithbenefits** [comment]
The build now runs without an error message. 

I don't think this is the expected behaviour though. Shouldn't it warn me when trying to install the bridge without the included NGINX reverse proxy? Or at least tell me what ports / folders to redirect?

In either case, the OAUTH next URL still 404s: https://matrix.DOMAIN/appservice-slack

**Comment by spantaleev** [comment]
It does push a warning message which should be displayed at the end of the playbook run.

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/6480cc36293da31fa58b3aa1f7fe90fffbae87bf/roles/matrix-bridge-appservice-slack/tasks/init.yml#L83-L91

---

As [described here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#using-your-own-webserver-instead-of-this-playbooks-nginx-proxy-optional-advanced), the playbook only runs well with `matrix-nginx-proxy` enabled. When completely disabling the proxy and going for another webserver (especially one that is not `nginx`), you're on your own - manual work and other breakage.

**Comment by catswithbenefits** [comment]
It doesn't show a warning, notice or any hint that something went wrong.

Not sure if it helps, the scripts ends with:

```
PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************
matrix.DOMAIN : ok=305  changed=23   unreachable=0    failed=0    skipped=1986 rescued=0    ignored=0   
```


Either way I will change my configuration to use the included NGINX since I'm not interested in doing all the manual work and dealing with various breakages.
