### ISSUE TITLE
Shared-Secret Registration fails with HMAC error

### ISSUE THREAD

**Issue by jeromecc** [spantaleev/matrix-docker-ansible-deploy#219]
Hello!
I wonder if this bug is linked to the playbook or if I should open an issue in the upstream repository.
I updated my instance to 3a8ed2dd816169357c26bead632733ba42694884 of this playbook (july 12th commit).
I set up a shared secret:
```matrix.example.com/vars.yml:matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "myverylongsharedsecret0Uyhh6776"```
I am using this script: https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/_scripts/register_new_matrix_user.py
to test shared_secret user registration.
It fails, reporting an HMAC error.
It used to work a while back ago.
I also tried various other scripts with slight modifications, they all fail.

Should I pass this on to upstream?

Thanks a lot for your time.

**Comment by spantaleev** [comment]
Hi!

Thanks a lot for raising your concern!

I think you're getting 2 things confused:

- [matrix-synapse-shared-secret-auth](https://github.com/devture/matrix-synapse-shared-secret-auth) - a project that allows you to `/login` to Matrix with any user, by using a shared secret. This shared secret is controlled by the `matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret` playbook variable.

- Synapse's `registration_shared_secret` setting, which allows people who it to create user (and admin) accounts on the Synapse server. This settings is controlled by the `matrix_synapse_registration_shared_secret` playbook variable, which by default has the same value as `matrix_synapse_macaroon_secret_key`

Seems like you are using the secret from the first, as a way to do user registrations for the 2nd.
You don't even need matrix-synapse-shared-secret-auth for registering.
