### ISSUE TITLE
Signal bridge is currenly broken, fix in signald 0.23.0

### ISSUE THREAD

**Issue by jakecoppinger** [spantaleev/matrix-docker-ansible-deploy#2205]
Signal bridge currently broken due to cert error:
```
⚠ Your message was not bridged: InternalError: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException, javax.net.ssl.SSLHandshakeException, sun.security.validator.ValidatorException, sun.security.provider.certpath.SunCertPathBuilderException: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

See https://gitlab.com/signald/signald/-/issues/343

`signald` 0.23.0 will fix the certificate issue.

The mautrix signal package will be updated to use `signald` 0.23.0 in https://github.com/mautrix/signal/issues/314

Once the mautrix Signal package is bumped I think we'll need to bump here.

**Comment by cyber-simon** [comment]
As mentioned in https://github.com/mautrix/signal/issues/314 it seems to necessary to update signald directly in matrix-docker-ansible-deploy. It just seems to be this one line, like in pull request: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2206

**Comment by spantaleev** [comment]
Fixed via https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2207
