### ISSUE TITLE
Support Synapse workers

### ISSUE THREAD

**Issue by enko** [spantaleev/matrix-docker-ansible-deploy#221]
It would be nice if one could enable optional workers defined here:

https://github.com/matrix-org/synapse/blob/master/docs/workers.rst

**Comment by CybotTM** [comment]
> It would be nice if one could enable optional workers defined here:
> 
> https://github.com/matrix-org/synapse/blob/master/docs/workers.rst

new URL is https://github.com/matrix-org/synapse/blob/master/docs/workers.md

**Comment by eMPee584** [comment]
.. and researching this more, I stumbled over something. So it seems there is quite something to build upon, namely this wiki entry https://github.com/matrix-org/synapse/wiki/Workers-setup-with-nginx and the files at https://github.com/matrix-org/synapse/tree/master/contrib/systemd-with-workers ..
Regarding the latter, how do you think about also introducing https://github.com/matrix-org/synapse/blob/master/contrib/systemd-with-workers/system/matrix.target @spantaleev ..?

**Comment by eMPee584** [comment]
Just to mention it: I'm working on it, current patch is at https://github.com/eMPee584/matrix-docker-ansible-deploy/commit/29e7a038e2d99a560efe93b5d5e4bafa13bbd05f pull request coming up..

**Comment by eMPee584** [comment]
PR ready for limited testing: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/456

**Comment by ptman** [comment]
How are workers coming along? I think more installations done using this playbook are growing and in need of workers.

**Comment by eMPee584** [comment]
Yes you're absolutely right; we aim at getting it done with this week. ✊⏩

**Comment by spantaleev** [comment]
Thanks! It'd be great to have it polished and merged!

**Comment by eMPee584** [comment]
Ok, had some progress but finishing is for the next days..

**Comment by ptman** [comment]
Great to see you working on this!

**Comment by uumas** [comment]
Fixed by #456
