### ISSUE TITLE
Unable to execute Borg backup with postgres 15

### ISSUE THREAD

**Issue by ctwelve** [spantaleev/matrix-docker-ansible-deploy#2215]
Hello,

This may be related to issue #2209 but I think it merited its own entry. I have recently rebuilt my server on a brand new VM, and if I attempt to activate Borg backup, I now get this:

```
TASK [matrix-backup-borg : Fail if detected Postgres version is unsupported] *************************************************************************
fatal: [matrix.arkmuse.org]: FAILED! => changed=false 
  msg: 'You cannot use borg backup with such an old version (15) of Postgres. Consider upgrading - link to docs for upgrading Postgres: docs/maintenance-postgres.md#upgrading-postgresql
```

I'm not sure what is doing this or how to fix it, but it should be said that I didn't simply migrate my VM. I backed up the database per instructions, and the media-store, then built a new server and restored the data. Everything works perfectly except the backup scripts.

Wat du?

😺

**Comment by spantaleev** [comment]
To use `latest`, add this to your `vars.yml` file:

```yaml
matrix_backup_borg_version: latest
```

This will make the playbook skip detecting the Postgres version and trying to match it to an [`etke.cc/borgmatic` version](https://gitlab.com/etke.cc/borgmatic/container_registry/2913214).

**Comment by westerguard** [comment]
I can confirm that this solves it. Thanks!

**Comment by ctwelve** [comment]
That seems to fix it, thanks!

**Comment by 1over137** [comment]
I have the same issue now with postgres v16 now. Changing that variable (replacing matrix_backup_borg with backup_borg) doesn't work either. How should I fix it?
