### ISSUE TITLE
no longer able to run playbook 

### ISSUE THREAD

**Issue by maul0r** [spantaleev/matrix-docker-ansible-deploy#2218]
When I last tried to update everything, I noticed that I can no longer run the runbook. 

Even when I completely remove the repository and perform a fresh clone, I cannot run the playbook. With the following error: 

```
/matrix/matrix-docker-ansible-deploy# ansible-playbook -i inventory/hosts setup.yml --tags=setup-all
 [WARNING]: Unable to parse /matrix/matrix-docker-ansible-deploy/inventory/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/matrix/matrix-docker-ansible-deploy/roles/matrix-base/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- ansible.builtin.import_tasks: "{{ role_path }}/tasks/sanity_check.yml"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

I am sure if this was a problem in the playbook, others would complain too. Nobody answered in chat - could somebody point me into the right direction?

**Comment by spantaleev** [comment]
See if the `inventory/hosts` file exiss and if it's readable by your user.

The other issues may indicate that you're on some old version of Ansible.

**Comment by maul0r** [comment]
thanks, I guess the upgrade fixed it? I noticed I was running on way outdated debian, performed a full upgrade, which also came with ansible 2.10 (up from 2.7.7). Its working now, thanks!

**Comment by KyleMiles** [comment]
I ran in to this this morning as well.  I was still running Ubuntu 18.04 because of the 20.04 issues.  I just upgraded to 22.04, reinstalled Ansible, and it's working again.

It might be worth while adding some clarifying language around (or removing if it's no longer relevant) [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blame/master/docs/ansible.md#L14).

**Comment by LovesTha** [comment]
should `inventory/hosts` now be `inventory/host_vars/<domain>/hosts`? 

(As I got a similar error and this was the most similar reported issue)

**Comment by LovesTha** [comment]
I've read things again, I was mis reading things :)

"all good" now. 

Or at least with issues 100% unrelated to this thread.
