### ISSUE TITLE
Trying to build synapse from source fails

### ISSUE THREAD

**Issue by chagai95** [spantaleev/matrix-docker-ansible-deploy#2234]
```
*
fatal: [matrix.chagai.website]: FAILED! => changed=false
  cmd:
  - /bin/git
  - fetch
  - origin
  msg: |-
    Failed to download remote objects and refs:  error: cannot open .git/FETCH_HEAD: Permission denied

```

**Comment by spantaleev** [comment]
You're probably on a a very very very old instance.

Check the changelog from ages ago about git directory permissions. There are some manual commands to run to fix it

**Comment by chagai95** [comment]
I think you mean this:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#2022-04-14

Thx! Unfortunately it didn't work for me...
Any other suggestions? 🙈

**Comment by chagai95** [comment]
I had a symlink on /matrix that's why it didn't work 🤦‍♂️ thx so much Slavi!
