### ISSUE TITLE
Etherpad on arm64

### ISSUE THREAD

**Issue by mjarr** [spantaleev/matrix-docker-ansible-deploy#2236]
**Describe the bug**
The latest tagged version of Etherpad doesn't have an arm64 docker build. Develop builds do support arm, but naive switching didn't work for me.
I think it should be noted in the docs.

**Matrix Server:**
 - OS: Oracle Linux Server 8.6
 - Architecture arm64

**Comment by spantaleev** [comment]
`matrix_etherpad_version: develop` should help.

**Comment by mjarr** [comment]
I tried it, and it resulted in `error: password authentication failed for user "matrix_etherpad"`.

**Comment by spantaleev** [comment]
Did you just do `--tags=setup-etherpad`, instead of `--tags=setup-all`?

It's actually `--tags=setup-postgres` that prepares this database and credentials. Other roles may also want to do work to set up Etherpad. Just doing `--tags=setup-etherpad` will miss on a ton of prep work.

**Comment by mjarr** [comment]
Thanks. That was it.
