### ISSUE TITLE
Role not found 

### ISSUE THREAD

**Issue by GammaG** [spantaleev/matrix-docker-ansible-deploy#2263]
After updating the local repository which is updating the roles using the playbook leads to an error in the role definitions. 

The following error is given:

```
ERROR! the role 'galaxy/com.devture.ansible.role.playbook_help' was not found in /root/Matrix/matrix-docker-ansible-deploy/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root/Matrix/matrix-docker-ansible-deploy

The error appears to be in '/root/Matrix/matrix-docker-ansible-deploy/setup.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Most of the roles below are not distributed with the playbook, but downloaded separately using `ansible-galaxy` via the `make roles` command (see `Makefile`).
    - role: galaxy/com.devture.ansible.role.playbook_help
      ^ here
```

I'm not sure if that is my local setup or something in the framework but before last upgrade it worked well.

Best Regards

**Comment by banym** [comment]
I can reproduce it here, too. 
Best Regards

**Comment by oschmidteu** [comment]
Check the doc about upgrading:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md

"take a look at [the changelog](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md) to see if there have been any backward-incompatible changes that you need to take care of"

And then check the Changelog:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#2022-11-04

**Comment by banym** [comment]
Thx. This prevents to use the playbook in AWX for me.

**Comment by GammaG** [comment]
After applying the hints in the the [maintenance-upgrading-services.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md) it worked well again. Thanks for the fast support
