### ISSUE TITLE
A request will timeout after 10 seconds with many generic workers and nginx will flag the worker as unavailable

### ISSUE THREAD

**Issue by anonfloppa** [spantaleev/matrix-docker-ansible-deploy#2264]
I enable workers in vars.yml like this:
matrix_synapse_workers_enabled: true
matrix_synapse_workers_generic_workers_count: 3

I use 3 generic workers. I used this configuration for months without problems but I noticed today that I have tons of errors similar to this log:

`Nov 14 20:30:35 localhost matrix-nginx-proxy[113694]: 2022/11/15 01:30:35 [error] 23#23: *157819 no live upstreams while connecting to upstream, client: 172.18.0.21, server: matrix-nginx-proxy, request: "GET /_matrix/client/r0/sync?filter=3&timeout=30000&since=s44309503_1215028_1859_49273157_18280905_25395_27412775_39234398_0 HTTP/1.0", upstream: "http://generic_workers_upstream/_matrix/client/r0/sync?filter=3&timeout=30000&since=s44309503_1215028_1859_49273157_18280905_25395_27412775_39234398_0"`

Unfortunately, I don't have more information regarding the consequences of this bug. I noticed this error because I was investigating another issue. I commented the line matrix_synapse_workers_generic_workers_count to remove the error for now.

My complete vars.yml can be found here: https://gist.github.com/anonfloppa/a92ca57b9bb2ee00f6b29354ec87d389
It's old but nothing changed.

Thank you very much.

**Comment by anonfloppa** [comment]
this bug might have been caused by the migration to the new roles or it was fixed in the meantime. It doesn't appear to be there anymore.

**Comment by anonfloppa** [comment]
I'm reopening this issue, it's not exactly a bug but maybe other people can find it useful or maybe an improvement can be made to the playbook.

From my understanding, my problem was caused by the load balancer of the synapse reverse proxy companion.

By default, nginx will have the following defaults for upstream servers when there is more than one (if there is only one generic worker those values are ignored):

max_fails=1
fail_timeout=10s

With these defaults, if a generic worker doesn't respond within 10 seconds to a request, nginx will flag the worker as unavailable. If no workers are available because they are all flagged as unavailable, I will get the error I posted above (`no live upstreams while connecting to upstream`).

That timeout is too short for my server when it is under heavy load so I changed the default values like so in the file `/matrix/synapse/reverse-proxy-companion/conf.d/matrix-synapse-reverse-proxy-companion.conf`:

```
upstream generic_workers_upstream {
        server "matrix-synapse-worker-generic-0:18111" max_fails=0 fail_timeout=30;
        server "matrix-synapse-worker-generic-1:18112" max_fails=0 fail_timeout=30;
        server "matrix-synapse-worker-generic-2:18113" max_fails=0 fail_timeout=30;
}
```

That way, a request to a generic worker will timeout after 30 seconds instead of 10 and if a request timeout, nginx will never flag it as unavailable.

That solved my issue.

More information about the upstream module: https://nginx.org/en/docs/http/ngx_http_upstream_module.html

**Comment by spantaleev** [comment]
Does it consider a stalled `/sync` for many seconds/minutes (due to long-polling) as a failure? I suppose it shouldn't.

**Comment by anonfloppa** [comment]
I didn't investigate the cause but I doubt it. I think it's the federation traffic that is overwhelming my server because I receive a lot of it.

![image](https://user-images.githubusercontent.com/92233267/210653387-23684cec-d438-4d8f-92a2-a4c0586b7d60.png)

I am also testing this new configuration, I'm separating the traffic I receive from the federation and from users. I think it's promising for my use case:

```
 upstream client_generic_workers_upstream {
          hash $http_x_forwarded_for;
          server "matrix-synapse-worker-generic-0:18111" max_fails=0 fail_timeout=60;
          server "matrix-synapse-worker-generic-1:18112" max_fails=0 fail_timeout=60;
  }
  upstream federation_generic_workers_upstream {
          hash $http_x_forwarded_for;
          server "matrix-synapse-worker-generic-2:18113" max_fails=0 fail_timeout=60;
          server "matrix-synapse-worker-generic-3:18114" max_fails=0 fail_timeout=60;
  }
```

**Comment by anonfloppa** [comment]
> Does it consider a stalled `/sync` for many seconds/minutes (due to long-polling) as a failure? I suppose it shouldn't.

I think that /sync might be the problem actually but not because of long-polling. the do_fetch call is killing my database and I think it blocks /sync calls for everyone. All those spikes are do_fetch calls:

![image](https://user-images.githubusercontent.com/92233267/211358007-0dab0c9c-7ef6-45ef-88de-6149df11f514.png)

Closing again because it's unrelated to the playbook.
