### ISSUE TITLE
Depoly synapse-simple-antispam require sudo (run as non-root user)

### ISSUE THREAD

**Issue by Lostsite** [spantaleev/matrix-docker-ansible-deploy#2281]
**Describe the bug**
While running the playbook as root, (1st time), it shows:

```
TASK [custom/matrix-synapse : Clone synapse-simple-antispam git repository] ****
fatal: [matrix.102604.icu]: FAILED! => changed=false
  module_stderr: |-
    /bin/sh: 1: sudo: not found
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 127
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_synapse_ext_spam_checker_synapse_simple_antispam_enabled: true

matrix_synapse_ext_spam_checker_synapse_simple_antispam_config_blocked_homeservers:
- example.com
- another.com
```
(That's the only place in the settings related to spam)
(After I comment this part out, playbook works)

**Expected behavior**
since I already run it with root, it should run without sudo
**Matrix Server:**
 - OS: Debian 11
 - Architecture [e.g. amd64, arm32, arm64]
 - AMD 64

**Ansible:**
- run it locally (in host ansible_connection=local); also use --ask-pass function instead of ssh key
- what version of Ansible you're running (see `ansible --version`):
- ansible 2.10.8
  config file = /home/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

**Comment by spantaleev** [comment]
Maybe you need to install `sudo` on the server, so that the playbook can clone that git repository using another user (not `root`)

**Comment by Lostsite** [comment]
That should work... (and I know run as root is a bad habit)...

However, since all other services can run as root, it will be much easier if this can do the same thing too.

**Comment by spantaleev** [comment]
It doesn't matter which user you run `ansible-playbook` with. This is about the user on the server (`ansible_ssh_user` in your `inventory/hosts` file, usually `root`). The playbook runs its tasks as `root` on the server. Some tasks (like this `git clone ..` task where you found the playbook fail), however, are intentionally executed using another user (e.g. `matrix`), so that the resulting files will be owned by the `matrix` user by default.

**Comment by altsalt** [comment]
You can also change the privilege escalation method by passing `--become-method` during the `ansible-playbook` run.
