### ISSUE TITLE
Ansible error in setup.yml

### ISSUE THREAD

**Issue by mjarr** [spantaleev/matrix-docker-ansible-deploy#2282]
**Describe the bug**
Running the playbook results in an error.

**To Reproduce**
Run `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start`
The result is:
```
ERROR! A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleUnicode'> instead

The error appears to be in '/mnt/c/code/web-other/matrix-docker-ansible-deploy/setup.yml': line 1, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


playbooks/matrix.yml
^ here
```

**Ansible:**
Ansible version: 2.10.8
Python version: 3.9.2
OS: Debian 11 (bullseye) in WSL

**Additional context**
The cause is 84c74136.

**Comment by juergen852** [comment]
Did you start "make roles" before running the playbook?

**Comment by akdk7** [comment]
I had this issue yesterday.
One of the last commits contains a move of the file setup.yml to the playbooks directory. The original file is a symbolic link directing to playbooks/matrix.yml. If you pull the repository on a windows machine the symbolic link cannot be created. I am using a windows subsystem linux (ubuntu) and doing "git pull" from now on instead with git extension from windows.
You have to do a hard reset on your local repo clone to recreate the symbolic link. Unfortunately it only works on a linux system.
But make a backup of your inventory directory to avoid it being deleted before!

**Comment by mjarr** [comment]
@akdk7 Thanks for pointers.
To fix the issue I bit the bullet and upgraded to WSL2 as it has better linux compatibility. However I still couldn't get it to work in the windows filesystem even with metadata enabled. The thing that worked was cloning the repo in the linux filesystem and copying the inventory over.
