### ISSUE TITLE
Ensure Jitsi internal auth users are configured -> failed

### ISSUE THREAD

**Issue by taschenlampe** [spantaleev/matrix-docker-ansible-deploy#2284]
Since yesterday(Nov 20, 2022) I have some issues with jitsi. Meaning I cannot start any session anymore.
Back when it worked, I would start a session, then a popup would appear asking me to login. Now this is not working anymore, I got: 

```
2022-11-20T15:03:13.019Z [modules/xmpp/moderator.js] <6885/Sr.prototype._allocateConferenceFocusError>:  Focus error, retry after 8000 
<iq id="5c248dd2-4a3c-4d5a-bcac-00a43ebc544f:sendIQ" from="focus.meet.jitsi" to="okkejap4x4fbiwpwlo29ucs8@meet.jitsi/8BlRNQ224D9l" xmlns="jabber:client" type="error">
lib-jitsi-meet.min.js:2:573453
2022-11-20T15:03:13.033Z [conference.js] <_onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected focus.meet.jitsi 8 app.bundle.min.js:178:2210185
```

So I told myselft I should maybe re-run the tag=jitsi playbook

My `vars.yml` file looks like this:

```
[...]
#jitsi matrix_jitsi_enabled: true  
matrix_jitsi_jicofo_auth_password: blabla
matrix_jitsi_jvb_auth_password: blibli
matrix_jitsi_jibri_recorder_password: blublu
matrix_jitsi_jibri_xmpp_password: bloblo
matrix_jitsi_enable_auth: true 
matrix_jitsi_enable_guests: true 
matrix_jitsi_prosody_auth_internal_accounts:   
    - username: "_hello_"     
    password: "_word_"  
matrix_jitsi_web_custom_config_extension: |
    config.enableLayerSuspension = true;   
    config.disableAudioLevels = true;   
    # Limit the number of video feeds forwarded to each client   
    config.channelLastN = 4;  
matrix_jitsi_web_config_resolution_width_ideal_and_max: 640 
matrix_jitsi_web_config_resolution_height_ideal_and_max: 360 
[...]
```

The Ansible playbook shows this

```
TASK [custom/matrix-jitsi : Ensure Jitsi internal authentication users are configured] **************************************
failed: [matrix.glowingshadows.net] (item={'username': '_hello_', 'password': '_world_'}) => changed=false 
  ansible_loop_var: item
  cmd: /usr/bin/env docker exec matrix-jitsi-prosody prosodyctl --config /config/prosody.cfg.lua register _hello_ meet.jitsi _world_
  delta: '0:00:02.127487'
  end: '2022-11-21 16:07:37.171620'
  item:
    password: _hello_
    username: _world_
  msg: non-zero return code
  rc: 1
  start: '2022-11-21 16:07:35.044133'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |2-
  
  
    **************************
    Prosody was unable to find the configuration file.
    We looked for: /etc/prosody//config/prosody.cfg.lua
    A sample config file is included in the Prosody download called prosody.cfg.lua.dist
    Copy or rename it to prosody.cfg.lua and edit as necessary.
    More help on configuring Prosody can be found at https://prosody.im/doc/configure
    Good luck!
    **************************
  stdout_lines: <omitted>
```
I have deleted  according to [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md) -> rm -rf /matrix/jitsi before running the playbook,

sudo locate "prosody.cfg"
```
locate prosody.cfg 
/matrix/jitsi/prosody/config/prosody.cfg.lua
/var/lib/docker/overlay2/1298f392718a1ae75c912dde53c88513a7a50bf1d70e269c54f782469b264b20/diff/defaults/prosody.cfg.lua
/var/lib/docker/overlay2/35f16765029b25537a88df319019ad5bab10cfe1163bfd6fa6e50a35cb191fc3/diff/defaults/prosody.cfg.lua
```

What could/should I do now?

**Matrix Server:**
 - OS: debian
 - Architecture: amd64

**Comment by taschenlampe** [comment]
So, I re-ran the playbook with tag=jitsi again, this time (so the 2nd time) the playbook ran through, no complaints (so I´d assume that the 1st-run created something that was re-used by the 2nd run...I´ll  re-analyse it if I have the time to clone my system and "play" with it). But the problem remained, meaning I could not create a working jitsi session.

Now, I ´ ve also reset the internal_user account/password and the 4 *passwords in *vars.yml to something new: 1st run -> mentioned ansible error, 2nd run  nothing failed and guess what? What? All worked fine. I can use  jitsi with authentication again.

So...all in all, unfortunately I cannot really/surely tell how I got this running again and  if I´d be able to reproduce this situation again and resolve this issue. :-/ 

Anyway! Thank you so much for the playbook.

**Comment by spantaleev** [comment]
Did you mean `--tag=setup-jitsi`?

**Comment by taschenlampe** [comment]
Hi!
Yes you are of course right I meant  `--tags=setup-jitsi,start`
