### ISSUE TITLE
Hydrogen image rebuilds every time (not idempotent)

### ISSUE THREAD

**Issue by mattcen** [spantaleev/matrix-docker-ansible-deploy#2294]
Ref:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5c3df22c3568371315585f386ecafc0edf4be714/roles/custom/matrix-client-hydrogen/tasks/setup_install.yml#L27-L69

1. "Ensure Hydrogen repository is present on self-build" has `force: "yes"`, which resets the working tree to the specified commit
2. "Ensure Hydrogen configuration installed" updates the working tree by adding `src/platform/web/assets/config.json`

(2) means that a subsequent run of the playbook *always* runs (1) and returns `changed: true`.

This in turn means that "Ensure Hydrogen Docker image is built" always runs (due to `force_source: "{{ matrix_client_hydrogen_git_pull_results.changed }}"`), taking up needless build time.

I'm not sure what the best solution here is.

**Comment by aaronraimist** [comment]
See https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2117#issuecomment-1292939258
