### ISSUE TITLE
Discord Bridge does not work as documented.

### ISSUE THREAD

**Issue by McL0v1n** [spantaleev/matrix-docker-ansible-deploy#230]
The discord bridge does not work as documented. This is due to the fact that DESPITE userStorePath and roomStorePath not beeing needed anymore, the image still looks for it.

The solve is to add:

`userStorePath = /data/user-store.db`
`roomStorePath = /data/room-store.db`

To the config file, no additional configuration required.

This should be adjusted in the main.yml file for this service

**Comment by spantaleev** [comment]
Thanks for the report! It seems like the Discord bridge is really misleading.

If you provide the parameters and start it, it would tell you:

> [DiscordAS] warn: [DEPRECATED] The room store is now part of the SQL database.The config option roomStorePath no longer has any use.
> [DiscordAS] warn: [DEPRECATED] The user store is now part of the SQL database.The config option userStorePath no longer has any use

If you then go ahead and start the bridge without these parameters, it would simply die.

Duh..

--------

I've added these configuration parameters to our configuration.

Unfortunately, this only fixes startup for installations which had the files generated to begin with.

Installations that were migrated over might not have these files there and need manual work to relocate them (or starting fresh).

**Comment by McL0v1n** [comment]
I check and in my installation those files were not there. All I did was change the config file. Half-shot is working on a fix but states "Really this should all become obsolete by 0.6, I've just not had time to finish the port job"

-------- Original Message --------

**Comment by spantaleev** [comment]
If you've used the bridge, you can likely relocate the files manually.

I take it you've never used the bridge though, so.. you can just delete its files (`rm -rf /matrix/appservice-discord`) and rerun the playbook. That would recreate everything correctly.

**Comment by McL0v1n** [comment]
I did that. I had been trying to get this bridge running for months. No .db files were generated. Once I added the deprecated paths everything ran fine except for those warnings. All I did was add the paths; didn't touch any files.

-------- Original Message --------
