### ISSUE TITLE
Running setup on upgrading encounters error msg: '''dict object'' has no attribute ''priority,name'''

### ISSUE THREAD

**Issue by javierwonghf** [spantaleev/matrix-docker-ansible-deploy#2300]
**Describe the bug**
When upgrading to the latest version, running `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start` encounters the following error 

```
TASK [galaxy/com.devture.ansible.role.systemd_service_manager : Ensure systemd services are stopped] ********************************
fatal: [matrix.strellagroup.com]: FAILED! =>
  msg: '''dict object'' has no attribute ''priority,name'''

```

**Expected behavior**
Upgrading to happen successfully.

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- on matrix server itself
- what version of Ansible you're running: core 2.12.7

**Comment by spantaleev** [comment]
ansible-core `2.11.7` works, but maybe only when it's pair with a modern Jinja version (such as `3.1.2`, in my tests).

You're probably on an older Jinja version

**Comment by foxcris** [comment]
Same error on my site.

```
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vbo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/vbo/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```
i am using ubuntu lts on windows with wsl2

**Comment by dysm4s** [comment]
Same error here too

```
ansible [core 2.12.10]
  config file = /home/stoner/Documents/Matrix/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/home/stoner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/stoner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

I am on ubuntu 20.04 server on a cloud host

**Comment by javierwonghf** [comment]
> ansible-core `2.11.7` works, but maybe only when it's pair with a modern Jinja version (such as `3.1.2`, in my tests).
> 
> You're probably on an older Jinja version

was on 2.10.1 similar to @foxcris and @dysm4s.

I can confirm that upgrading Jinja2 to 3.1.2 works. Just ran `pip install -U Jinja2` and reran the upgrade command `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start`.

Thanks @spantaleev.

**Comment by dysm4s** [comment]
@javierwonghf  Thanks! I just did that as well and also had success. Appreciate you posting the fix

**Comment by foxcris** [comment]
The solution from @javierwonghf is working for me. Thx.
