### ISSUE TITLE
unable to update due to recent updates

### ISSUE THREAD

**Issue by 0spinboson** [spantaleev/matrix-docker-ansible-deploy#2302]
**Describe the bug**
Since the changes to the playbook made in the past week or so, I can no longer just run setup-all,start on both my arm64 (ubuntu 22.04) and amd64 (ubuntu 22.04) instances. It seems either the requirements have changed wrt ansible, or the playbook is not pulling in the required dependencies (getting errors related to a bunch of roles in /galaxy: geerlingguy.docker, com.devture.ansible.role.playbook_help and docker_sdk_for_python not being found)

**To Reproduce**
My `vars.yml` file looks like this:
[vars.yml.txt](https://github.com/spantaleev/matrix-docker-ansible-deploy/files/10112314/vars.yml.txt)

**Comment by spantaleev** [comment]
Have you read the changelog since 2022-11-04, specifically the [The playbook now uses external roles for some things](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#the-playbook-now-uses-external-roles-for-some-things) part?

**Comment by 0spinboson** [comment]
no, I hadn't. Okay, thanks.
