### ISSUE TITLE
Cannot run setup on Arch, ntpd

### ISSUE THREAD

**Issue by Nicba1010** [spantaleev/matrix-docker-ansible-deploy#235]
Setup fails with following error "Could not find the requested service ntp: host"
I suspect the cause is that arch uses the ntpd.service file and not ntp

**Comment by spantaleev** [comment]
Even if we fix this, it may fail in a few other places after that.

We don't support installing on Arch Linux right now.

See the list of supported operating systems here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/prerequisites.md

If you would like to work on Arch Linux support, a pull request would be welcome!
