### ISSUE TITLE
A way for stopping and (re)starting all services in a controlled manner

### ISSUE THREAD

**Issue by kuikka** [spantaleev/matrix-docker-ansible-deploy#2367]
I could not find a way to stop and then start all the related services (containers) in a controlled manner.

My use case has to do with system reconfiguration. I need to move `/matrix` into another volume and for that I need to stop everything, do the move and then re-start.

Same would be useful for taking backups.

**Comment by spantaleev** [comment]
1. `--tags=stop`
2. Do your thing
3. `--tags=start`

If migrating to another server, check the "migrating services" doc file

**Comment by kuikka** [comment]
Thank you! Great work on this, it was so easy to set up!
