### ISSUE TITLE
Allow to define TRUSTED_THIRD_PARTY_ID_SERVERS

### ISSUE THREAD

**Issue by ralfi** [spantaleev/matrix-docker-ansible-deploy#237]
Please append the role set for define TRUSTED_THIRD_PARTY_ID_SERVERS like described here ...

https://github.com/matrix-org/synapse/issues/5194

**Comment by spantaleev** [comment]
You already can via the `matrix_synapse_trusted_third_party_id_servers` variable.

I just found and fixed a bug (see 99f5baa7bb50d) that caused `matrix_synapse_trusted_third_party_id_servers` to refer to an undefined variable (`matrix_synapse_id_servers_public`) if mxisd is disabled (`matrix_mxisd_enabled: false`).
