### ISSUE TITLE
Setting up mxisd defaults matrix_mxisd_enable: false do not work

### ISSUE THREAD

**Issue by ralfi** [spantaleev/matrix-docker-ansible-deploy#238]
Setting up this to false seems to me should not install and activate kamax/mxisd but do so.

Also i am a little bit confused about the mxisd state because the development is closed and some people tells me why this happens. BTW the selfhoster should be able to use vector.im or matrix.org as ID server if he needed.

**Comment by spantaleev** [comment]
`matrix_mxisd_enable: false` is wrong. There's a typo in it (`enable` -> `enabled`).

Using mxisd, even though discontinued, is still very much compatible and works well. It's a much much much better choice for your privacy than using vector.im/matrix.org.

See details here:
- https://gist.github.com/maxidorius/5736fd09c9194b7a6dc03b6b8d7220d0
- and here: https://github.com/libremonde-org/paper-research-privacy-matrix.org/tree/master/part2

**Comment by aaronraimist** [comment]
Just to add on to that, even if you do setup an identity server there is nothing stopping one of your users from signing in using vector.im/matrix.org as their identify server. Accounts are not tied to identity servers so we don’t need to build in an option to “be able to use vector.im or matrix.org as ID server if he needed“. You can always use any identity server you want.

Also we should probably consider switching to https://github.com/ma1uta/ma1sd which is the active form of mxisd.
