### ISSUE TITLE
External Coturn Setup

### ISSUE THREAD

**Issue by roughnecks** [spantaleev/matrix-docker-ansible-deploy#2389]
Hello, I just installed coturn on Debian and am trying to use it as external turn server in the playbook (atm only in plain, not tls).
I installed coturn externally because I'd like to use it in prosody too.. Now I have tried with prosodyctl to test it and this is the result:

```
prosodyctl check turn -v --ping=stun.conversations.im
Identified 1 TURN services.

Testing TURN service turn.woodpeckersnest.space:3478...
External IP: 51.195.43.203
Relayed address 1: 51.195.43.203:61883
TURN external address: 51.195.43.203:61883
Success!

All checks passed, congratulations!
```
Then I tried with https://test.voip.librepush.net/ but website seems to have issues, since it returns errors when trying to test (can anyone confirm?)
Lastly I tried calling a friend from my home to his and the connection never happens, even if phone rings. Then he came by and we tested on my home network and phone call was successful, so there's definitely something wrong with external coturn, but what?

My vars.yml looks like this:

```
matrix_coturn_enabled: false
# Point Synapse to your other Coturn server
matrix_synapse_turn_uris:
- turn:woodpeckersnest.space?transport=udp
- turn:woodpeckersnest.space?transport=tcp
```
Any hint?

**Matrix Server:**
 - OS: Debian 11
 - Architecture: amd64

**Client (please complete the following information):**
 - Device: iPhone12, Redmi 6A Android 9

**Additional context**

shouldn't be a way to specify the auth_secret too? Or can I use this?
`matrix_coturn_turn_static_auth_secret:`

**Comment by roughnecks** [comment]
> @roughnecks
> 
> You can either force populate the `turn_shared_secret` with a _<random_static_turn_shared_secret>_ or let the playbook generate one for you by adding the following to your `vars.yml`.
> 
> ```yaml
> matrix_synapse_turn_shared_secret: "{{ matrix_coturn_turn_static_auth_secret }}"
> ```
> 
> Then copy the `static-auth-secret` (your own, or the generated one from `/matrix/synapse/config/homeserver.yaml`) to coturn's config file `turnserver.conf` and try again.

I'm trying right now, thanks.

> > Then I tried with https://test.voip.librepush.net/ but website seems to have issues, since it returns errors when trying to test (can anyone confirm?)
> 
> Had a similar problem with this test using Chrome/Chromium, but everything was _Excellent_ with Firefox. So, your issue might be the browser. Just try another one and compare the results (See this [bug](https://github.com/matrix-org/voip-tester/issues/20)). Btw. the [synapse's docs](https://matrix-org.github.io/synapse/latest/turn-howto.html#troubleshooting) also state that _**this test is not fully reliable yet**_ ...
> 

If I use firefox I get the same errors, like:

Error occurred during test: TypeError: NetworkError when attempting to fetch resource.
Error occurred during test: TypeError: resp_obj.uris is undefined

> And to be sure, also test with: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

I also tried this one but I believe it needs a user/pwd from turn, not from matrix as I get authentication failures.

**Comment by krassle** [comment]
>>And to be sure, also test with: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
>I also tried this one but I believe it needs a user/pwd from turn, not from matrix as I get authentication failures.

You can generate one time credentials valid for 1h by following the docs describing how to [troubleshoot your turn server](https://matrix-org.github.io/synapse/latest/turn-howto.html#troubleshooting). Read it carefully and try again!

>BIG THANK YOU!!

No problem!
