### ISSUE TITLE
Add support for running Mjölnir as appservice

### ISSUE THREAD

**Issue by MichaelSasser** [spantaleev/matrix-docker-ansible-deploy#2390]
#### Is your feature request related to a problem? Please describe.

A while ago I've created the issue #2115 "Multiple instances of mjolnir" which proposed to make it possible to deploy multiple instances of Mjölnir. A little while later, I noticed Mjölnir is moving towards to resolve the issue by themselves. So, I closed #2115. Since the feature has landed, I'm opening a new issue proposing to adding appservice support for Mjölnir to this playbook.

#### Describe the solution you'd like
By adding Mjölnir appservice support to this playbook, multiple communities can use the same instance (one container).

#### Additional context
Mjölnir appservice:
- Docs: https://github.com/matrix-org/mjolnir/blob/main/docs/appservice.md
- Config: https://github.com/matrix-org/mjolnir/tree/main/src/appservice/config

**Comment by austinhuang0131** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-appservice-draupnir-for-all.md
