### ISSUE TITLE
No CHANGELOG around what "just" command is that is now used for upgrades. 

### ISSUE THREAD

**Issue by prasket** [spantaleev/matrix-docker-ansible-deploy#2391]
Today we went to upgrade our services and was greeted with something new about running "just" commands. See https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md 

I do not see anything in the https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md about what this is either.

**Comment by prasket** [comment]
Digging into the project I can now see what `just` is but not having that info in the CHANGELOG to warn everyone is the open issue. 

I personally do not want to install 'just' on my machine but it does appear the old commands still work fine for others that come across it. Hopefully something can be added into CHANGELOG for other users.

**Comment by spantaleev** [comment]
Fixed in https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/fb60ba67f646288b40818a555bb716405e144956
