### ISSUE TITLE
Postgres Galaxy Role Fails to Stop Service 

### ISSUE THREAD

**Issue by mxc** [spantaleev/matrix-docker-ansible-deploy#2407]
After updating vars to accommodate the new postgres galaxy role matrix-docker ansible will not start due to missing variable. I get the following error when running  "ansible-playbook -i inventory/hosts setup.yml --tags=start "

TASK [galaxy/com.devture.ansible.role.systemd_service_manager : Ensure systemd services are stopped] *******************************************************************
fatal: [matrix.abc.co.za]: FAILED! => 
  msg: '''dict object'' has no attribute ''priority,name'''

**Comment by spantaleev** [comment]
This has been reported many times before. You need to upgrade Ansible and Jinja2

**Comment by mxc** [comment]
Thanks. Will upgrade.
