### ISSUE TITLE
 Securely host other web services along side Synapse and Element

### ISSUE THREAD

**Issue by tecoruo** [spantaleev/matrix-docker-ansible-deploy#2412]
Does this ansible deploy suffer from the potential attack vector described in the Synapse repo's [security note](https://github.com/matrix-org/synapse#security-note)? Does someone have insight if it would be relatively safe to host other services _if_ open registration is disabled and not interacting with public rooms? All communication is private rooms that can be trust.

**Comment by aaronraimist** [comment]
> Does this ansible deploy suffer from the potential attack vector described in the Synapse repo's [security note](https://github.com/matrix-org/synapse#security-note)?

By default, yes. The default setup is to use separate subdomains for each service but you are more than welcome to use   separate registered domains for each service if you want to.

> Does someone have insight if it would be relatively safe to host other services if open registration is disabled and not interacting with public rooms? All communication is private rooms that can be trust.

Our default setup is relatively safe even if you have registration open and interact with public rooms, so yes it would also be relatively safe in that scenario.

**Comment by tecoruo** [comment]
Thank you for the insight. I need to run other services on the same domain and server since they're the only ones that I have. With this info I feel more confident to do so.

**Comment by aaronraimist** [comment]
>  is it better to integrate the other services to this ansible play book or host them completely separately?

If they are Matrix bridges or bots or things like that, sure.

If they are not Matrix related, you probably don't want to integrate them with this playbook. You'll either want to install them manually or you could write your own Ansible playbook to manage those services.

> I s it even possible to use the provided nginx to serve other services without messing up the matrix setup?

It is possible to use the built in Nginx for custom stuff but I would personally recommend using your own Nginx server. The Nginx configs that the playbook generates for the Matrix services are still usable in your own Nginx instance https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#using-your-own-external-nginx-webserver.

**Comment by tecoruo** [comment]
Thank you for the information
