### ISSUE TITLE
apache2 reverse proxy: The page isn’t redirecting properly

### ISSUE THREAD

**Issue by dreamflasher** [spantaleev/matrix-docker-ansible-deploy#244]
I am using the following apache config file:

```
<VirtualHost *:443>
        ServerName riot.mydomain.com

        SSLEngine On

        SSLCertificateFile /etc/letsencrypt/live/mydomain.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem

        SSLProxyEngine on
        SSLProxyProtocol +TLSv1.1 +TLSv1.2
        SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH

        ProxyPreserveHost On
        ProxyRequests Off
        ProxyVia On

        ProxyPass / http://127.0.0.1:8765/
        ProxyPassReverse / http://127.0.0.1:8765/

        ErrorLog ${APACHE_LOG_DIR}/riot.mydomain.com-error.log
        CustomLog ${APACHE_LOG_DIR}/riot.mydomain.com-access.log combined
</VirtualHost>
```

I had to remove `+TLSv1.3` because else apache is not starting. When opening the domain in the browser I get `The page isn’t redirecting properly`. I'd highly appreciate your help. I looked in the log files, but they are empty.

The certificates are working with other reverse proxies, also I have two other reverse proxies running on the same instance and they work fine.

**Comment by dreamflasher** [comment]
Figured out the problem. The documentation here is wrong: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md
riot.example.com and dimension.example.com should not point to matrix.example.com, but to the IP of the server.

**Comment by spantaleev** [comment]
`matrix.example.com` is pointed to the IP of the server (as per those instructions), so it's the same.
Or have you pointed it elsewhere?

**Comment by dreamflasher** [comment]
When I set it up as described with `CNAME` then apache only sees `matrix.example.com` and thus does not apply the correct `ServerName` rule.

**Comment by spantaleev** [comment]
I don't think it matters whether it's an `A` record or a `CNAME`.
I haven't seen that cause any difference in processing. It's also described here: https://stackoverflow.com/questions/21559491/should-virtual-hosts-be-defined-as-cname-in-dns-server

It's probably something else that have caused the issue for you.

If you can point us to something reproducible or some documentation that says otherwise, we can reconsider and update the instructions though.
