### ISSUE TITLE
Element Image Self Build Failure ("unknown flag: --tag")

### ISSUE THREAD

**Issue by rltas** [spantaleev/matrix-docker-ansible-deploy#2455]
I'm not even using my own repo yet, just set `matrix_client_element_container_image_self_build: true`.

```
fatal: [matrix.bhv-test.ki-on.net]: FAILED! => changed=true
  cmd:
  - /usr/bin/env
  - docker
  - buildx
  - build
  - --tag=localhost/vectorim/element-web:v1.11.22
  - --file=/matrix/client-element/docker-src/Dockerfile
  - /matrix/client-element/docker-src
  delta: '0:00:00.055237'
  end: '2023-02-09 21:06:44.249664'
  msg: non-zero return code
  rc: 125
  start: '2023-02-09 21:06:44.194427'
  stderr: |-
    unknown flag: --tag
```

Ubuntu 22.04.1 LTS amd64
Docker 23.0.0, build e92dd87

**Comment by spantaleev** [comment]
Does running something like `/usr/bin/env docker buildx build --tag=test .` after SSH-ing to the server produce the same error?

For me, it doesn't. I'm getting this (which is expected):

> ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount...../Dockerfile: no such file or directory

**Comment by rltas** [comment]
I'm using the playbook locally (`ansible_connection=local`), but that shouldn't matter here I guess - yes indeed, same result:

```
:~# /usr/bin/env docker buildx build --tag=test .
unknown flag: --tag
´´´

But I just figured out that the message is misleading, the actual problem is this:

```
~# docker buildx build
docker: 'buildx' is not a docker command.
```

On my other hosts, where I installed Docker manually, I'm getting

```
~# docker buildx build
error: "docker buildx build" requires exactly 1 argument.
```

as expected.

**Comment by rltas** [comment]
Package `docker-buildx-plugin` isn't installed by the playbook. After installing it manually, it works.
