### ISSUE TITLE
Model doesnt exist for ChatGPT

### ISSUE THREAD

**Issue by Happyfeet01** [spantaleev/matrix-docker-ansible-deploy#2459]
Hello,

looks like Open AI limited the access to the Text Model. The currently (since 10/02/23) is 只有text-davinci-003可以

https://github.com/waylaidwanderer/node-chatgpt-api/issues/46

**Comment by Happyfeet01** [comment]
There is an Update. How can we update this for Matrix? @spantaleev https://github.com/waylaidwanderer/node-chatgpt-api/blob/a99a727ae7f276b226037a321b9c4177be34c25c/README.md#using-a-reverse-proxy

**Comment by spantaleev** [comment]
If someone makes a PR, maybe.

However, it may be added to the upstream project too https://github.com/matrixgpt/matrix-chatgpt-bot, not here directly. Whenever that receives a new release, we'll get it updated.

Personally, I don't use ChatGPT and am not working on any fixes myself. I don't follow this stuff at all.

PRs are welcome.

**Comment by Happyfeet01** [comment]
okay thanks for the Info

**Comment by Madchristian** [comment]
you can set this variable in your vars.yml:

`matrix_bot_chatgpt_environment_variables_extension: 'CHATGPT_MODEL=text-davinci-003'`

**Comment by Happyfeet01** [comment]
solved with: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bot-chatgpt.md
