### ISSUE TITLE
git pull this morning breaks my synapse connection between element client and matrix server

### ISSUE THREAD

**Issue by ralfi** [spantaleev/matrix-docker-ansible-deploy#2474]
**Describe the bug**
After git pull this morning setup tells me i have to change a previous defined var to

`matrix_well_known_matrix_client_io_element_e2ee_default: false` 

and so i do so. 

After this ansible setup/start completed whithout errors but the connection between element client and matrix synapse breaks. Looking a little bit around i found this:

The matrix-client-element service does not expose the port 8765 so my apache reverse proxy could not connect to the element web-interface. So i set this explicit via the `vars.yml` and the connection to the element web interface works but element tells me there is no connection to the matrix-server.

Then i try to check federation but this fails. IMHO this could be only related to the changes at these day because everything works until this morning. Could it be related to commit `2be5ba45db7f37e8f838d14c6cdfdde2a8e0bad2` or is there another problem? I need my synapse server and any help is welcome.

BTW: How can i replay the repo to the version that works, i mean yesterday evening or discard changes of `2be5ba45db7f37e8f838d14c6cdfdde2a8e0bad2`

Thanks a lot!

**Matrix Server:**
 - OS: Debian 11
 - Architecture amd64

**Client:**
 - Device: Linux
 - OS: Debian 11
 - Browser Chrome, FF

**Comment by spantaleev** [comment]
What's your configuration like?

See the [Traefik support announcement in the changelog](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#reverse-proxy-configuration-changes-and-initial-traefik-support). Maybe this is some regression caused by it.

You may wish to try adding: `matrix_playbook_reverse_proxy_type: other-on-same-host` to your configuration.

If that doesn't work, please show us your (cleaned up of sensitive data) `vars.yml` and your Apache config.

**Comment by ralfi** [comment]
Huhu Slavi,
let me try this...

**Comment by ralfi** [comment]
Okay, setting

`matrix_playbook_reverse_proxy_type: other-on-same-host`

fails playbook setup to this ...


![image](https://user-images.githubusercontent.com/294423/218459520-0d3f649e-025d-4c35-a181-0493499e5605.png)

**Comment by ralfi** [comment]
my vars.yml without secrets:


matrix_domain: hasihome.ddnss.de

matrix_ssl_lets_encrypt_support_email: <mailaddress>
matrix_ssl_retrieval_method: manually-managed

matrix_synapse_macaroon_secret_key: "<key>"
matrix_synapse_workers_enabled: false
matrix_synapse_enable_registration: true
matrix_synapse_report_stats: false
matrix_synapse_presence_enabled: false

allow_public_rooms_over_federation: true
allow_public_rooms_without_auth: true
matrix_federation_public_port: 8448

matrix_awx_enabled: false
matrix_well_known_matrix_client_io_element_e2ee_default: false
matrix_client_element_container_http_host_bind_port: '127.0.0.1:8765'
matrix_playbook_reverse_proxy_type: 'other-on-same-host'
matrix_common_after_systemd_service_start_wait_for_timeout_seconds: 30
matrix_nginx_proxy_enabled: false

devture_postgres_connection_password: "<key>"

matrix_mailer_hostname: "<name>"
matrix_mailer_sender_address: "<senderaddress>"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "<smtprelayhost>"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "<mailaddress>"
matrix_mailer_relay_auth_password: "<mailboxpassword>"

matrix_heisenbridge_enabled: true

matrix_coturn_enabled: false

matrix_homeserver_generic_secret_key: "<key>"

matrix_playbook_docker_installation_enabled: false

matrix_ma1sd_enabled: true
matrix_ma1sd_matrixorg_forwarding_enabled: false
matrix_synapse_registrations_require_3pid: ['email']

matrix_dimension_enabled: true
matrix_dimension_access_token: "<token>"
matrix_dimension_admins: ['<dimensionadmin>']

matrix_client_element_disable_guests: false
matrix_client_element_integrations_ui_url: "<URL>/element"
matrix_client_element_integrations_rest_url: "<URL>/api/v1/scalar"
matrix_client_element_integrations_widgets_urls: ["<URL>/widgets"]
matrix_client_element_integrations_jitsi_widget_url: ["<URL>/widgets/jitsi"]

matrix_synapse_admin_enabled: true
matrix_synapse_admin_container_http_host_bind_port: 192.168.178.21:8766

matrix_bot_postmoogle_enabled: true
matrix_bot_postmoogle_password: "<postmooglepassword>"
matrix_bot_postmoogle_maxsize: '48'
matrix_bot_postmoogle_loglevel: 'DEBUG'
matrix_bot_postmoogle_admins: 'postmoogle'
matrix_cactus_comments_enabled: true

matrix_bot_chatgpt_matrix_bot_username: 'bot.chat-opengpt'
matrix_bot_chatgpt_matrix_access_token: '<token>'
matrix_bot_chatgpt_openai_api_key: '<apikey>'

**Comment by ralfi** [comment]
my synapse apache reverse proxy conf

`<IfModule mod_ssl.c>`
`<VirtualHost *:443>`

    ServerName matrix.<MATRIX-DOMAIN>

    SSLEngine On
    SSLProxyProtocol +TLSv1.2 +TLSv1.3
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH

	ProxyPreserveHost On
	RequestHeader set "X-Forwarded-Proto"expr=%{REQUEST_SCHEME}

	# Keep some URIs free for different proxy/location
	ProxyPassMatch ^/.well-known/matrix/client !
	ProxyPassMatch ^/.well-known/matrix/server !

	# Proxy all remaining _matrix traffic to Synapse
	AllowEncodedSlashes NoDecode

	ProxyPass /_matrix/identity http://127.0.0.1:8090/_matrix/identity nocanon
	ProxyPassReverse /_matrix/identity http://127.0.0.1:8090/_matrix/identity

	ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
	ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix

	ProxyPass /_synapse http://127.0.0.1:8008/_synapse nocanon
	ProxyPassReverse /_synapse http://127.0.0.1:8008/_synapse

	Loglevel Info
	ErrorLog ${APACHE_LOG_DIR}/<MATRIX-DOMAIN>-error.log
	CustomLog ${APACHE_LOG_DIR}/<MATRIX-DOMAIN>-access.log combined

	Include /etc/letsencrypt/options-ssl-apache.conf

	SSLCertificateFile /etc/letsencrypt/live/matrix.<MATRIX-DOMAIN>/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/matrix.<MATRIX-DOMAIN>/privkey.pem
`</VirtualHost>`

`Listen 8448`
`<VirtualHost *:8448>`

	SSLEngine On

	# MUST BE SET FOR PROXY DELEGATION TO HTTPS
	ProxyPreserveHost On
	RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
	AllowEncodedSlashes NoDecode

	# Keep some URIs free for different proxy/location
	ProxyPassMatch ^/.well-known/matrix/client !
	ProxyPassMatch ^/.well-known/matrix/server !

	# Proxy all remaining federation traffic to the Synapse traffic port

	ProxyPass /_matrix http://127.0.0.1:8048/_matrix nocanon
	ProxyPassReverse /_matrix http://127.0.0.1:8048/_matrix

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/matrix.<MATRIX-DOMAIN>/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/matrix.<MATRIX-DOMAIN>/privkey.pem

`</VirtualHost>`
`</IfModule>`

**Comment by ralfi** [comment]
Hope that helps.

Friendly regards!

**Comment by ralfi** [comment]
![image](https://user-images.githubusercontent.com/294423/218470989-be53e991-63e0-4656-b908-23a61a366929.png)

simple syntax mistake?

**Comment by ralfi** [comment]
Same (invalid ip 127.0.0.1 colum...) with ma1sd service

**Comment by ralfi** [comment]
Thanks Slavi, everything okay. 

BTW, great idea to change to traefik and set a complete homeserver environment playbook with vaultwarden and nextcloud! Should be extended with pihole or adguard-home and you need nothing more as this playbook anytime in life.

**Comment by spantaleev** [comment]
You're welcome to try switching this playbook to Traefik and potentially trying out the other playbooks. Check their interoperability file in the `docs/` directory for details. It's easiest if the Matrix playbook is the one that installs and manages Traefik, with all other playbook using a reverse-proxy of type `other-traefik-container`
