### ISSUE TITLE
Support deploying the Sliding Sync proxy

### ISSUE THREAD

**Issue by ripdog** [spantaleev/matrix-docker-ansible-deploy#2478]
Sliding sync is the future of the Matrix sync api, and might finally give matrix a vaguely okay new-device experience. Sadly, there are no plans for implementing it in Synapse yet, even as the SS-only Element X nears a first public release. The official word from Matthew himself is "install the proxy".

I would install it manually, but I'm unsure how to integrate it with the docker-based setup that this playbook installs, so it seems that the best solution would be for it to be installed by this playbook.

It seems the proxy is installed on it's own URL, which is then referenced in the .well-known file. See https://github.com/matrix-org/sliding-sync/blob/main/docs/Landing.md

https://github.com/matrix-org/sliding-sync

**Comment by spantaleev** [comment]
Someone in our Matrix room recently expressed interest in contributing support for this feature.

**Comment by gnunicorn** [comment]
yeah, that was me ... still need to wrap my head around ansible playbooks :) .
