### ISSUE TITLE
Mounting additional volumes (as opposed to bind mounts) into coturn fails

### ISSUE THREAD

**Issue by mattcen** [spantaleev/matrix-docker-ansible-deploy#2482]
**Describe the bug**
Since the alteration of [this line](https://github.com/spantaleev/matrix-docker-ansible-deploy/blame/d44d4b637f1d01b1957c451e1bf90339e9f7f3bb/roles/custom/matrix-coturn/templates/systemd/matrix-coturn.service.j2#L38), it's no longer possible to add a mount of `type=volume` to the coturn container.

**Additional context**

This  line:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/d44d4b637f1d01b1957c451e1bf90339e9f7f3bb/roles/custom/matrix-coturn/templates/systemd/matrix-coturn.service.j2#L38

makes the unreasonable assumption that all intended additional volumes are bind mounts rather than volumes, which broke things for me. In my `vars.yml` I have the following:

```yaml
  matrix_coturn_container_additional_volumes: [ {"src": "proxy_exported_certs", "dst": "/tls", "options": "ro" } ]
```

Because I have *also* been using a workaround for several months to use Traefik (albeit on *top* of `matrix-nginx-proxy`) and give coturn access to its certs.

This line broke because I'm using a volume and not a bind mount for that particular mount.

**Comment by mattcen** [comment]
(That said, now that Traefik support is built in, I'll likely try switching to that once I've more time to debug any potential issues, but this is still a bug regardless.)

**Comment by spantaleev** [comment]
Perhaps we should add a required `type` field there that you need to specify.

We were previously using `-v` for mounting instead of `--mount`, but we no longer use `-v` for this, because it's too magical. Other instances of `-v` in the playbook shall be migrated to `--mount` as well.

**Comment by mattcen** [comment]
That would definitely solve the problem. As would having a *default* `type` which can be overridden.

Would it be too magical to infer the type from the string (i.e. set either `type=volume` or `type=bind` based on whether or not it contains slashes)?

**Comment by mattcen** [comment]
How would you feel about this change? It's less likely to break things for people who are already using bind mounts via this method:

```diff
diff --git i/roles/custom/matrix-coturn/templates/systemd/matrix-coturn.service.j2 w/roles/custom/matrix-coturn/templates/systemd/matrix-coturn.service.j2
index 523ad1cc..e1b1a427 100644
--- i/roles/custom/matrix-coturn/templates/systemd/matrix-coturn.service.j2
+++ w/roles/custom/matrix-coturn/templates/systemd/matrix-coturn.service.j2
@@ -35,7 +35,7 @@ ExecStart={{ devture_systemd_docker_base_host_command_docker }} run --rm --name
                        {% endif %}
                        --mount type=bind,src={{ matrix_coturn_config_path }},dst=/turnserver.conf,ro \
                        {% for volume in matrix_coturn_container_additional_volumes %}
-                       --mount type=bind,src={{ volume.src }},dst={{ volume.dst }}{{ (',' + volume.options) if volume.options else '' }} \
+                       --mount type={{ volume.type if volume.type else 'bind' }},src={{ volume.src }},dst={{ volume.dst }}{{ (',' + volume.options) if volume.options else '' }} \
                        {% endfor %}
                        {% for arg in matrix_coturn_container_extra_arguments %}
                        {{ arg }} \
```

**Comment by spantaleev** [comment]
Auto-switching based on whether it can find a `/` sounds good. One can also specify the `type` explicitly now.

It should be noted that `options` can be a little different than what was supported with `-v`. Previously, you could use `rw`, but not anymore. `ro` is still a valid option. The `--mount` documentation for `docker run` (`man docker-run`) contains more information.

**Comment by mattcen** [comment]
Oh, elegant! Thanks!
