### ISSUE TITLE
Ability to input multiple 

### ISSUE THREAD

**Issue by gitayam** [spantaleev/matrix-docker-ansible-deploy#2496]
**Is your feature request related to a problem? Please describe.**
Related to chatgpt bot not working for many. It does seem to work with `matrix_bot_chatgpt_environment_variables_extension: 'CHATGPT_MODEL=text-davinci-003'` 

Need the ability to use multiple `matrix_bot_chatgpt_environment_variables_extension` to deal with the issues it currently has with encryption and eventually to impact the temperature and length.

The yml only accepts one `matrix_bot_chatgpt_environment_variables_extension` and accepts only the last one so it was defaulting to #matrix_bot_chatgpt_environment_variables_extension: 'MATRIX_ENCRYPTION=false'
 for me.

**Comment by spantaleev** [comment]
Search for "multiline YAML strings"

**Comment by gitayam** [comment]
This works and chatgpt is working well now. Might be worth including some of these variables in multi line string
