### ISSUE TITLE
Recent upgrade broke the matrix server

### ISSUE THREAD

**Issue by mail02ankit** [spantaleev/matrix-docker-ansible-deploy#2498]
Hi,

I recently upgraded the server using 
`git pull; just roles; just setup-all` . There was no error during the upgrade. But, after the upgrade my server gives "502 Bad Gateway" error.

Nginx log says
```
2023/02/16 21:12:59 [error] 22#22: *926 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, 
server: , request: "GET /_matrix/client/versions HTTP/1.0", upstream: "http://127.0.0.1:8008/_matrix/client/versions", host: "matrix.aa,aa"
```

The self-check script  `ansible-playbook -i inventory/hosts setup.yml --tags=self-check` gives the following error

```
TASK [custom/matrix-synapse : Check Matrix Client API] *********************************************************************************************************************
fatal: [matrix.aa.aa -> 127.0.0.1]: FAILED! => changed=false 
  connection: close
  content_length: '150'
  content_type: text/html
  date: Thu, 16 Feb 2023 21:11:39 GMT
  elapsed: 0
  msg: 'Status code was 502 and not [200]: HTTP Error 502: Bad Gateway'
```
Can someone help me here please?

Thanks

**Comment by mail02ankit** [comment]
Changed `matrix_nginx_proxy_enabled: false` to `matrix_playbook_reverse_proxy_type: other-on-same-host` and it fixed the issue.

**Comment by Happyfeet01** [comment]
Thanks, i searching for an solution. This works!
