### ISSUE TITLE
Broken on Fedora Linux

### ISSUE THREAD

**Issue by array-in-a-matrix** [spantaleev/matrix-docker-ansible-deploy#2522]
**Describe the bug**
Running the playbook on a fresh Fedora Linux 36 does not work as the playbook tries to install the `epel-release` package which is not available for Fedora Linux.

**To Reproduce**
Run ansible-playbook setup on a fresh Fedora Linux 36 install.

**Expected behavior**
Playbook installs matrix on server.

**Matrix Server:**
 - OS: Fedora Linux 36
 - Architecture: amd64
 
**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible:
 Ansible was ran on target server.

- what version of Ansible you're running (see `ansible --version`)
```
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fedora/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/fedora/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
  jinja version = 3.0.3
  libyaml = True
```

**Additional context**
Ansible error:
```
TASK [galaxy/com.devture.ansible.role.docker_sdk_for_python : Ensure epel-release is installed on RedHat > 7] *************************
fatal: [matrix.chatinamatrix.xyz]: FAILED! => changed=false 
  failures:
  - No package epel-release available.
  msg: Failed to install some of the specified packages
  rc: 1
  results: []
```

**Comment by spantaleev** [comment]
Should be fixed by https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python/commit/129c8590e106b83e6f4c259649a613c6279e937a
