### ISSUE TITLE
Additional code blocks for nginx no longer works with Traefik

### ISSUE THREAD

**Issue by FulytheFox** [spantaleev/matrix-docker-ansible-deploy#2563]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
# A list of strings containing additional configuration blocks to add to Element's server configuration (matrix-client-element.conf).
matrix_nginx_proxy_proxy_element_additional_server_configuration_blocks: [
    "	location = /robots.txt {",
    "		add_header Content-Type text/plain;",
    "		return 200 \"User-agent: *\\nDisallow: /\";",
    "	}"
    ]
```

**Matrix Server:**
 - OS: Ubuntu 22.04.2
 - Architecture: amd64

**Problem description**:

Hello, I used the variable `matrix_nginx_proxy_proxy_element_additional_server_configuration_blocks` in my vars.yml to add additional configuration to the nginx config file, wich is located in `/matrix/nginx-proxy/conf.d/matrix-client-element.conf`. Unfortunately, this no longer works with Traefik, as a different config file is now used, wich is located in `/matrix/client-element/nginx.conf`.

Is there a variable to still add additional configurations in the other nginx config, as unfortunately I couldn't find any in the docs. I am very grateful for any help!

**Comment by spantaleev** [comment]
This variable only does something if nginx is used, not Traefik.

**Comment by FulytheFox** [comment]
I understand. I used the variable to add additional code blocks to the nginx configuration, but since the project is slowly switching to Traefik I would like to know if I can add additional configuration like in nginx also with Traefik.

I have seen that when I use Traefik, a local nginx proxy is used inside the Element container. So I thought that maybe now there is a variable to add code block to this config file.

**Comment by rltas** [comment]
Traefik is a reverse proxy, not a webserver. Requests on the element subdomain are directly passed to the respective container. Self-building a fork for this purpose is surely overkill, what one could do is running the tiniest possible container which does nothing but serve that robots.txt, attaching it to the trafik network and using a label like `traefik.http.routers.matrix-client-element-robots.rule=Host(``element.yourdomain.tld``) && Path(``/robots\.txt``)` plus the others that are needed, see the [labels template](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-client-element/templates/labels.j2).
You could also insert the location you're using now into the nginx-proxy config and use the above traefik rule to divert requests from the Element container to nginx-proxy, but imo that's pointless when nginx-proxy will be removed partially or entirely at some point which just silently break that rule.

**Comment by smargold476** [comment]
I have a related issue with additional docker-containers hosting webservices.
I changed the network of the container to traefik and attached the following template with specific URL, appname, Port etc.:

```
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.<appname>-add-headers.headers.customresponseheaders.Content-Security-Policy=frame-ancestors 'self'"
      - "traefik.http.middlewares.<appname>-add-headers.headers.customresponseheaders.Permission-Policy=interest-cohort=()"
      - "traefik.http.middlewares.<appname>-add-headers.headers.customresponseheaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"
      - "traefik.http.middlewares.<appname>-add-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.<appname>-add-headers.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.<appname>-add-headers.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.routers.<appname>.rule=Host(`<URL>`)"
      - "traefik.http.routers.<appname>.entrypoints=web-secure"
      - "traefik.http.routers.<appname>.middlewares=<appname>-add-headers"
      - "traefik.http.routers.<appname>.service=<appname>"
      - "traefik.http.routers.<appname>.tls=true"
      - "traefik.http.routers.<appname>.certResolver=default"
      - "traefik.http.services.<appname>.loadbalancer.server.port=<PORT>"
      - "traefik.docker.network=traefik"
```

my expectation was that these routers, services and middlewares are discovered by the docker provider and then visible in the traefik-dashboard, instead i do only see file-configs like this (I don't understand where they come from):

```
      <appname>.<mydomain>-dummy:
        rule: Host(`<URL>`)
        service: noop@internal
        entryPoints: "web-secure"
        tls:
          certResolver: "default"
```

I tried to delete the entries in `/matrix/traefik/config/provider.yml`and restart traefik and the tested service, but no change except the deleted router from file-provider is missing in the dashboard now.

I'm pretty sure i do not see something here...
Any help would be very welcome :)

**Comment by smargold476** [comment]
Thanks for your response!
Deleted to old certificate-part.
Network and lables are set correctly.
Found the issue in the logs, i used 
`      - "traefik.http.routers.<appname>.certResolver=default"`
instead of
`      - "traefik.http.routers.<appname>.tls.certResolver=default"`

Works now, thanks!

**Comment by luixxiul** [comment]
Closing as resolved.
