### ISSUE TITLE
Dendrite v0.12.0 fails to start

### ISSUE THREAD

**Issue by array-in-a-matrix** [spantaleev/matrix-docker-ansible-deploy#2571]
**Describe the bug**
Dendrite fails to start due to a configuration error:
`msg="Configuration error= missing config key \"relay_api.database.connection_string\""`

**To Reproduce**
Add `matrix_dendrite_docker_image_tag: "v0.12.0"` or git pull latest.

**Expected behavior**
Dendrite starts up successfully.

**Matrix Server:**
 - OS: Ubuntu 22.04 LTS
 - Architecture: amd64
 
**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
On server itself

- what version of Ansible you're running (see `ansible --version`)
Ansible core 2.14.3

**Additional context**
#2567

**Comment by spantaleev** [comment]
Looks like the relay API is something new that we should add.. Perhaps a new database is necessary as well? You can see how the databases are created in `group_vars/matrix_servers`.
