### ISSUE TITLE
Deploy containers in a kubernetes env

### ISSUE THREAD

**Issue by nicop311** [spantaleev/matrix-docker-ansible-deploy#259]
Hi all,
**First, well done for this playbook!** I tested it to deploy a Riot and Matrix servers for some tests. It works fine and the customization options are great.

## How to deploy the containers in a Kubernetes environment?

For the moment (as of august 2019), the `matrix-docker-ansible-deploy` playbook will install `docker-ce` on the target host defined in the inventory, if it is not already installed. The target host is a conventional server (VM or bare metal). See the [Prerequisites](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/prerequisites.md).

And if `docker-ce` is already installed on the target host, the playbook continues with the deployment of the containers that you picked up by configuring the services you need.

## What changes to this playbook would be required if you want to deploy the different containers on a `kubernetes` environment instead of a traditional VM?

Maybe this is a silly idea.

Imagine you have a working `kubernetes` environment as a prerequisite. Then you configure your playbook and xN containers need to be deployed.

Could we deploy these xN containers on, for example, one `kubernetes` **pod** and use one method of **shared file system** which would be used to create the same shared directory than the `/matrix` one when deploying on a standard VM (See "[a Kubernetes Volumes Guide](https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-volumes-example-nfs-persistent-volume.html)")?
I assume we could plug all the containers of this `kubernetes` pod on the same subnetwork. Then you could decide if you use the embedded reverse-proxy or use a custom one.

However, I don't really know if this is the right way to do it. 

In this repository, I could not find any mention of `kubernetes` or `docker swarm`. Maybe it would be enough to adapt the target host in the inventory and adapt to a `kubernetes` environment. Maybe it would require more changes elsewhere, like for the creation of a shared directory.

Did you though about this? Or is this playbook only intended to be used like it is currently working?

Thank you!
nicop311

**Comment by spantaleev** [comment]
I don't think it would be easy to adapt this to deploy onto Kubernetes.

Most services (like Synapse) also don't lend themselves nicely to scaling horizontally, so the benefits of running on such a platform are further diminished.

Still, there are other projects whose aim is to deploy to Kubernetes. See [ananace/matrix-synapse](https://github.com/ananace/matrix-synapse)

**Comment by nicop311** [comment]
Thank you for your answer. In your opinion, what is the tricky part here? Is it the fact that you need to use some kind of Ansible plugin that handles the requests that you need to do to on `Kubernetes` to configure and deploy the containers which will be running on the pod?

> Most services (like Synapse) also don't lend themselves nicely to scaling horizontally

This is true. The benefit I saw is that, if you have a working `Kubernetes` env, you may want to run all your containers / all your applications in it, even if you are not using all the functionalities like scaling, self healing, HA....

TY for the link. However, the configuration option in your playbook seems (without trying the link) more robust than the configuration in `ananace/matrix-synapse`.

**Comment by spantaleev** [comment]
The goal of this project is to have something self-contained that people can easily install on any regular server.

Kubernetes is a beast that's hard to install, requires multiple servers to run correctly, etc.

It's also a completely different and distributed deployment mechanism compared to what we have here -- a single server with systemd services and Docker. Translating what we have to Kubernetes would be hard. Especially if we need to do it at the same time as supporting the current way of doing things (simple VM..).

Not only would it be hard to do, but it would also:
- not be useful to many, as most of us running this playbook operate small homeservers on a single small/cheap machine. Deploying to multiple servers running Kubernetes is usually overkill in terms of cost and complexity.
- not very useful, as most services can't take advantage of the scalability that Kubernetes promises

I also like the promise of setting up a Kubernetes environment for myself, throwing all my services there (Matrix, Gitlab, Nextcloud, other things, ..) and [dealing with cattle, not pets](https://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/). The thing is, such an environment is hard to set up, more expensive to run and none of these services easily deploys to Kubernetes. It's a pain on multiple fronts for little gain (as of right now, at least).

**Comment by nicop311** [comment]
Many thanks for your answer!

You are not wrong in your analysis and your goal of a _self-contained_ solution to deploy Matrix, Riot, etc.

> Kubernetes is a beast that's hard to install,

Maybe it was not clear, but I was thinking that `Kubernetes` could have been a requirement, therefore you do not have to install/deploy Kube with your playbook. And you could have imagine in the playbook a default install/deployment that works the same than today (single server + self-contained installation/config/deployment) and a second method where you deploy with `Kubernetes`.

But if you tell me that you believe, even with this in mind, that it would be hard to use the same current method for the containers/systemd/etc in the single server and transpose it for `Kubernetes`, I believe you!

Still a great tool though!
**You can close this thread if you want :-)**
