### ISSUE TITLE
coturn: Lower DDoS amplification/reflection factor from 2.8 to 1.6

### ISSUE THREAD

**Issue by AndersTrier** [spantaleev/matrix-docker-ansible-deploy#2592]
In the default configuration, this project sets up a coturn instance that is useful for DDoS amplification. This is the report we got:
```
Transaction_id : 000000000000000000000000
Magic_cookie : 2112a442
Message_length : 36
Message_type : 0101
Xor_mapped_family : 01
Xor_mapped_address : 1.2.3.4
Xor_mapped_port : 51181
Software : 
Fingerprint : 
Amplification : 2.80
Response_size : 56
```

This is the settings I think this project should enable in the default install:
```
no-rfc5780
no-stun-backward-compatibility
response-origin-only-with-rfc5780
```
See the relevant comments: https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf

This lowers the amplification factor to 1.6.
```
Transaction_id : 000000000000000000000000
Magic_cookie : 2112a442
Message_length : 12
Message_type : 0101
Xor_mapped_family : 01
Xor_mapped_address : 1.2.3.4
Xor_mapped_port : 22824
Software : 
Fingerprint : 
Amplification : 1.60
Response_size : 32
```

On a related note: I'm a bit surprised that it is even possible to make the server return a large response, given that the following settings for coturn are also enabled:
```
use-auth-secret
static-auth-secret=<secret>
```

**Comment by spantaleev** [comment]
Thanks a lot for your testing and investigation!

I've enabled the recommended options by default. They're all controllable via variables, so if anyone hits trouble with any of these new options, they can easily disable them.

**Comment by LeonWilzer** [comment]
> In the default configuration, this project sets up a coturn instance that is useful for DDoS amplification. This is the report we got:

How did you generate the report?
