### ISSUE TITLE
Error enabling dimension - Could not find the requested service matrix-dimension: host

### ISSUE THREAD

**Issue by maltokyo** [spantaleev/matrix-docker-ansible-deploy#262]
After everything setup well, and confirmed to work (including federation on stippy.com), I tried to start dimension, and get an error I cannot overcome. 

Setup dimension by adding this into vars.yml file

```
matrix_dimension_enabled: true
matrix_dimension_admins: ['@mal:matrix.stippy.com']
matrix_dimension_access_token: "removed this - but i got it as in the guide and inseted"
```

Run this:

`ansible-playbook -i inventory/hosts setup.yml --tags=start`

Error:
`failed: [matrix.stippy.com] (item=matrix-dimension) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-dimension", "msg": "Could not find the requested service matrix-dimension: host"}`

Please let me know what I could be doing wrong.  The message above doesn't help me.

**Comment by spantaleev** [comment]
It looks like you're trying to start services, but you haven't installed them yet.

You need to run `--tags=setup-all` first, before running the start tag.
