### ISSUE TITLE
Support multiple matrix server instances on one physical host

### ISSUE THREAD

**Issue by samip5** [spantaleev/matrix-docker-ansible-deploy#2630]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when most of the ansible roles I find want to install it non-dockerised.

**Describe the solution you'd like**
I would love to be able to deploy one bridge per synapse instance for namespacing reasons.

**Describe alternatives you've considered**
Make own Ansible role alltogether, which I might actually end up doing.

**Comment by spantaleev** [comment]
This is literally the Issue right below yours - #2620.

As for installing non-Dockerized, you should look into another project. We only care about containers.

**Comment by samip5** [comment]
> As for installing non-Dockerized, you should look into another project. We only care about containers.

I did mean to say dockerized and somehow missed that issue...
