### ISSUE TITLE
Disable email notifications for each message from Backend

### ISSUE THREAD

**Issue by ToddCrimson** [spantaleev/matrix-docker-ansible-deploy#2660]
**Is your feature request related to a problem? Please describe.**
Running an instance, added users, we all get email notifications that XYZ sent an encrypted message. I know users can go in their app and turn off email notifications for message, but every time a new user is added, this creates an issue. Would love to see an option to do it from backend

**Describe the solution you'd like**
A simple method from backend to disable server wide email notifications only for messages.

**Describe alternatives you've considered**
Well for now, I am just removing everyone's email address from their account and telling new users NOT to add an email address.

**Additional context**
Since we already get push notifications, we don't feel that we need emails, so for our use case, we'd love flexibility to disable for new messages. If that is not available, then maybe a way to completely disable the email relay service.

**Comment by Wave6677** [comment]
Is there a solution for this issue yet? I have to pay for SMTP forwarding and would prefer not to have to pay more than I need to.

**Comment by spantaleev** [comment]
You can disable email functionality for Synapse completely with `matrix_synapse_email_enabled: false`.

Or you can disable it for all services of the playbook (Synapse and potentially others now or in the future that may try to send email) with: `exim_relay_enabled: false`.

**Comment by spantaleev** [comment]
To add to this, it sounds like you need some smarter way to suppress email notifications when the user has already read the message.

As far as I remember from reading Synapse release announcements, Synapse recently started behaving this way by default. I may be wrong or misremembering though, so feel free to verify.

In any case, requests for such functionality should be done against the [Synapse repository](https://github.com/element-hq/synapse), not ours. The playbook is just an installer, not the actual software.
