### ISSUE TITLE
Own traefik proxy: syslog flooded with sync calls (10 GB per day)

### ISSUE THREAD

**Issue by sophonet** [spantaleev/matrix-docker-ansible-deploy#2664]
**Describe the bug**

I am using the current version of the playbook with an own traefik frontend, configuration has been done according to the guidelines in this repo. However, after some time, my system's syslog messages start filling up with "circular" sync calls between the matrix-nginx-proxy (which I have understood is still there) and the matrix-synapse-reverse-proxy-companion. They fill up about at least 10 GB per day, so currently I have to manually delete them and reboot my server in order not to fill up the hard disk. 

**To Reproduce**
My `vars.yml` file looks like this:

```yaml

matrix_domain: <my domain name, hidden here, has worked before>

matrix_homeserver_implementation: synapse

matrix_homeserver_generic_secret_key: < Secret key, hidden here >
devture_postgres_connection_password: < password, hidden here >
matrix_server_fqn_element: < element fqn >
matrix_server_fqn_matrix: < matrix fqn >
matrix_synapse_admin_enabled: true
matrix_playbook_docker_installation_enabled: false
matrix_ma1sd_enabled: false

matrix_mautrix_signal_enabled: true
matrix_mautrix_whatsapp_enabled: true

matrix_base_data_path: /srv/data/services/matrix/matrix

matrix_ssl_retrieval_method: none

matrix_playbook_reverse_proxy_type: other-traefik-container
matrix_playbook_reverse_proxyable_services_additional_network: 'matrix'
devture_traefik_certs_dumper_ssl_dir_path: /srv/data/services/reverseproxy
matrix_coturn_enabled: false
matrix_docker_network: 'matrix'
```

**Expected behavior**

Earlier, my matrix installation was running as expected, without gigabytes of log messages containing apparent "circular" calls.

**Matrix Server:**
 - OS: Docker 23.0.3 on Debian Bullseye (running in promox lxc container)
 - Architecture: amd64

**Ansible:**
(not the issue)

**Client:**
(probably not the issue, has worked flawlessly before the move to traefik)

**Additional context**

/var/log/syslog and /var/log/daemon.log look like (small snippet, this fills up gigabytes - with a few other messages obviously):

```
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-nginx-proxy[38635]: 172.24.0.11 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.1" 200 205 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
Apr 28 17:49:40 myhost matrix-synapse-reverse-proxy-companion[37725]: 172.24.0.7 - - [28/Apr/2023:17:49:40 +0000] "GET /_matrix/client/v3/sync?timeout=30000&since=s15404_424384_8_10141_15562_3_183_59_0_1&filter=1&set_presence=offline HTTP/1.0" 200 256 "-" "mautrix-signal/0.4.2 mautrix-python/0.18.8 aiohttp/3.8.3 Python/3.10.8" "-"
```

**Comment by jpfulton248** [comment]
I'm having the same issue. Also using traefik but this is my first deploy. I'm having issues with ssl cert on my root domain. I'm trying to solve that first to see if that solves the sync issue. After including the root domain in the "additional domains" variable, I'm not getting a 418 error on my root domain (I'm a teapot). Didn't have time yesterday to look at the reverse proxy config. I'll try to find time to do that today.

**Comment by rltas** [comment]
> I'm having the same issue

Are you using mautrix-signal too?

**Comment by jpfulton248** [comment]
> 

No. matrix-sms-bridge

I requested a new cert without the additional domains directive and now the root domain simply shows 404 not found but the certificate shows valid.

**Comment by rltas** [comment]
Please let's not confuse probably unrelated issues.

> "circular" sync calls

You mean a loop? Requests are passed from proxy to proxy companion, could also be massive spam from mautrix-signal, although all requests looking exactly the same surely looks fishy. Does it disappear if you stop just mautrix-signal?

**Comment by jpfulton248** [comment]
> Please let's not confuse probably unrelated issues.
> 
> > "circular" sync calls
> 
> You mean a loop? Requests are passed from proxy to proxy companion, could also be massive spam from mautrix-signal, although all requests looking exactly the same surely looks fishy. Does it disappear if you stop just mautrix-signal?

You're right... I looked more closely at OP's logs. I too have the GET requests to /sync failing but with different specifics. Also, as I noted above (now deleted), my issues are not related to mautrix-signal. Sorry for the consuion.

**Comment by watzfatz** [comment]
havin the same issue. server gets stuck every few hours due to extreme logfile flooding, looks the same as OP

**Comment by sophonet** [comment]
> Please let's not confuse probably unrelated issues.
> 
> > "circular" sync calls
> 
> You mean a loop? Requests are passed from proxy to proxy companion, could also be massive spam from mautrix-signal, although all requests looking exactly the same surely looks fishy. Does it disappear if you stop just mautrix-signal?

Indeed, the heavy log files seem to be related to using mautrix-signal in my setup. If I stop two signal containers (matrix-mautrix-signal and matrix-mautrix-signal-daemon), the error messages stop appearing. They appear again when the services are automatically relaunched. Not sure 100% though though whether the calls are indeed recursive...

As a temporary workaround, I have disabled the log messages from these two services in /etc/rsyslog.d/matrix.conf:

```
:programname, isequal, "matrix-synapse-reverse-proxy-companion" stop
:programname, isequal, "matrix-nginx-proxy"     stop
```

Nevertheless, the problem is not solved and leads to client applications (e.g. MacOS element) to hang (probably due to countless queued backend calls) after having run for some time such that they need to be killed and restarted in order to work again.

**Comment by geoidwalker** [comment]
I am having this issue as well. I upgraded to the latest version of the playbook today and upgraded postgres. I also increased the number of max connections as per the link from QEDed. I disabled all bridges (slack, whatsapp, discord) but the issue remains. The logs indicate that it is Element itself that is causing the issue. 


Here is a snippet that pretty much repeats until the log is full. 

Aug  8 09:55:47 nexus matrix-nginx-proxy[1072]: 172.23.0.6 - - [08/Aug/2023:16:55:47 +0000] "GET /_matrix/client/r0/sync?filter=2&timeout=30000&set_presence=unavailable&since=s84643_10284901_124_84868_139470_169_45704_972_0_1 HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.37 Chrome/114.0.5735.199 Electron/25.3.0 Safari/537.36" "192.168.200.1"
Aug  8 09:55:47 nexus matrix-traefik[1166]: 192.168.200.1 - - [08/Aug/2023:16:55:47 +0000] "GET /_matrix/client/r0/sync?filter=2&timeout=30000&set_presence=unavailable&since=s84643_10284901_124_84868_139470_169_45704_972_0_1 HTTP/1.1" 200 286 "-" "-" 13864908 "matrix-nginx-proxy-matrix-client@docker" "http://172.23.0.4:8080" 50ms
Aug  8 09:55:47 nexus matrix-nginx-proxy[1072]: 172.18.0.5 - - [08/Aug/2023:16:55:47 +0000] "GET /_matrix/client/r0/sync?filter=5&timeout=30000&since=s84643_10284902_124_84868_139470_169_45704_972_0_1 HTTP/1.0" 200 391 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" "192.168.200.1, 172.23.0.6"
Aug  8 09:55:47 nexus matrix-nginx-proxy[1072]: 172.23.0.6 - - [08/Aug/2023:16:55:47 +0000] "GET /_matrix/client/r0/sync?filter=5&timeout=30000&since=s84643_10284902_124_84868_139470_169_45704_972_0_1 HTTP/1.1" 200 264 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" "192.168.200.1"
Aug  8 09:55:47 nexus matrix-synapse-reverse-proxy-companion[1020]: 172.18.0.5 - - [08/Aug/2023:16:55:47 +0000] "GET /_matrix/client/r0/sync?filter=5&timeout=30000&since=s84643_10284902_124_84868_139470_169_45704_972_0_1 HTTP/1.0" 200 391 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" "192.168.200.1, 172.23.0.6"
Aug  8 09:55:47 nexus matrix-traefik[1166]: 192.168.200.1 - - [08/Aug/2023:16:55:47 +0000] "GET /_matrix/client/r0/sync?filter=5&timeout=30000&since=s84643_10284902_124_84868_139470_169_45704_972_0_1 HTTP/1.1" 200 253 "-" "-" 13864907 "matrix-nginx-proxy-matrix-client@docker" "http://172.23.0.4:8080" 64ms
Aug  8 09:55:47 nexus matrix-nginx-proxy[1072]: 172.18.0.5 - - [08/Aug/2023:16:55:47 +0000] "OPTIONS /_matrix/client/r0/sync?filter=2&timeout=30000&set_presence=unavailable&since=s84643_10284903_124_84868_139470_169_45704_972_0_1 HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.37 Chrome/114.0.5735.199 Electron/25.3.0 Safari/537.36" "192.168.200.1, 172.23.0.6"

Here you can see different clients accessing via different browsers and the app as well. Everything works normally until the logs fill up and there's no more space on the server. 
Jonathan

**Comment by geoidwalker** [comment]
[logs.txt](https://github.com/spantaleev/matrix-docker-ansible-deploy/files/12294361/logs.txt)

**Comment by sophonet** [comment]
> @geoidwalker that looks like presence spam caused by [matrix-org/synapse#16039](https://github.com/matrix-org/synapse/issues/16039) [matrix-org/synapse#16057](https://github.com/matrix-org/synapse/issues/16057) They reverted the change, but old clients will keep causing the problem.

Indeed, this might have been the case - strange that the two issues describing the presence spam have been created months later after my observation. I have just enabled syslog logging again and log messages seem to be fine now. If this persists for the next week or so, I am going to close this issue. Thanks for the info!

**Comment by ristein** [comment]
I'm using this playbook reverse-proxied behind apache.
I get 10M lines from matrix in syslog daily.
Most of them look like an internal access log

**Comment by sophonet** [comment]
There was no more activity - in my case, the presence spam was the reason, updating to newer clients solved this issue

**Comment by emiliogon** [comment]
An old client can still cause this issue?  So...  they didn't actually fix it, did they?

**Comment by sophonet** [comment]
See above, it has been fixed, this issue is closed
