### ISSUE TITLE
Element App crashing

### ISSUE THREAD

**Issue by Siam-1998** [spantaleev/matrix-docker-ansible-deploy#2665]
operating system: Ubuntu22.04 server
Synapse: 1.8.1
Element app: 1.10.11
Iphone12 
ios version: 16.4.1

while making audio and video calls, element app crashes.

**Comment by spantaleev** [comment]
This is not related to the playbook. Feel free to report this issue [here](https://github.com/vector-im/element-ios/).

**Comment by Siam-1998** [comment]
Spantaleev, Thanks for your Reply.
 please let me know, how to check active users in matrix server and its database.
