### ISSUE TITLE
'import-synapse-sqlite-db' not working anymore (or ever)?

### ISSUE THREAD

**Issue by phtmgt** [spantaleev/matrix-docker-ansible-deploy#2669]
**Describe the bug**
Well, this one here - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-synapse-sqlite.md - appears to no longer be functioning.

**To Reproduce**
Just follow the instructions and try to run `ansible-playbook -i inventory/hosts setup.yml --extra-vars='server_path_homeserver_db=<server-path-to-homeserver.db>' --tags=import-synapse-sqlite-db`. It doesn't do anything (unlike, for example, `ansible-playbook -i inventory/hosts setup.yml --extra-vars='server_path_media_store=<server-path-to-media_store>' --tags=import-synapse-media-store`).

I tried looking for any mention of 'import-synapse-sqlite-db' in the codebase, no luck (unlike 'import-synapse-media-store', which is mentioned in 'roles/custom/matrix-synapse/tasks/main.yml'). Has this function ever worked? Is it only the docs being completed? This makes no sene.

**Expected behavior**
Well, it should work.

**Matrix Server:**
 - OS: [e.g. Ubuntu 22.04]
 - Architecture [e.g. arm64]

**Additional context**

**Comment by spantaleev** [comment]
This has been broken for quite a long time (~6 months)!

Thank you for bringing it up! It seems like no one else has reported it in all this time.

Please update your playbook and try following the guide here again: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-synapse-sqlite.md

**Comment by plamenh** [comment]
I can confirm it now works.
