### ISSUE TITLE
Error when bridging a previously bridged Signal chat room

### ISSUE THREAD

**Issue by gitayam** [spantaleev/matrix-docker-ansible-deploy#2683]
open ticket exist on mautrix_signal .  https://github.com/mautrix/signal/issues/329

Steps to Reproduce:
1. Bridge a Signal chat room.
2. Attempt to bridge the same Signal chat room using the options to delete the portal completely and continue bridging.

Expected Behavior:
The Signal chat room should be successfully bridged without encountering any errors.

Actual Behavior:
An unhandled error occurs with the traceback indicating a "ValueError: too many values to unpack (expected 5)".

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 495, in confirm_bridge
    await _locked_confirm_bridge(
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 521, in _locked_confirm_bridge
    (
ValueError: too many values to unpack (expected 5)

```

Additional Information:
- This issue occurs specifically when using the delete-and-continue option to clean up a previously bridged Signal chat room.
- The error is observed in the `mautrix_signal` module.

Environment:
- Matrix-Docker-Ansible-Deploy version: master
- mautrix_singal: mautrix-signal 0.4.2
- Operating System: Debian 5.10.178-3

Please let me know if you need any further information. Thank you!

**Comment by spantaleev** [comment]
Why report it here? What can we do about it, if it's reported upstream already?

**Comment by gitayam** [comment]
> Why report it here? What can we do about it, if it's reported upstream already?

As people are searching for this error or issue.
