### ISSUE TITLE
inventory/hosts has a syntax error

### ISSUE THREAD

**Issue by Velensky** [spantaleev/matrix-docker-ansible-deploy#2737]
Currently, my hosts file looks like this 
[matrix_servers]
matrix.[my website]
ansible_host=[the public ip of my server] 
ansible_ssh_user=opc
become=true
become_user=root
However, this causes a syntax issue. I am using the ansible package on Arch

**Comment by spantaleev** [comment]
The host definition should be on a single line beneath the `[matrix_servers]` heading.

```
[matrix_servers]
matrix.[my website] ansible_host=[the public ip of my server] ansible_ssh_user=opc become=true become_user=root
```
