### ISSUE TITLE
Cannot install role "ansible-role-aux" when using NTFS

### ISSUE THREAD

**Issue by SapuSeven** [spantaleev/matrix-docker-ansible-deploy#2738]
**Describe the bug**
When running `just roles`, the first requirement named "aux" fails to install with the error "Invalid argument".

**To Reproduce**
1. Clone the repo to a directory on an NTFS-formatted disk
2. Run `just roles`

**Expected behavior**
The roles should install without issues.

**Logs**
```
Starting galaxy role install process
- extracting aux to /some/path/matrix-docker-ansible-deploy/roles/galaxy/aux
[WARNING]: - aux was NOT installed successfully: Could not update files in /some/path/matrix-docker-ansible-deploy/roles/galaxy/aux: [Errno 22] Invalid argument: '/some/path/matrix-docker-ansible-deploy/roles/galaxy/aux'
```

**Matrix Server:**
 - OS: Linux 6.3.6
 - Architecture: x86_64

**Additional context**
The issue seems to be that "aux" is a reserved name on NTFS.
As the requirement is specified with `name: aux`, this tries to create `roles/galaxy/aux`, which fails like described above.

You can also reproduce this by navigating to an NTFS-formatted disk and executing `mkdir aux` - this will also fail.

**Comment by spantaleev** [comment]
Related to https://github.com/mother-of-all-self-hosting/mash-playbook/pull/40 which affected mash-playbook.

Looks like it's not just the documentation file name, but also the role's directory name. We can rename it in requirements.yaml (which installs the role) and then in setup.yml (which invokes the role in the playbook).

Would you like to do a PR for this?

**Comment by SapuSeven** [comment]
Sure!
I'll create it shortly.
