### ISSUE TITLE
Unable to run: docker logs ContainerID

### ISSUE THREAD

**Issue by Archehandoro** [spantaleev/matrix-docker-ansible-deploy#274]
Hello,

I am running the playbook on a DigitalOcean VPS, Debian 10, and when I try to see the logs of the several containers the playbook creates I always get:

`Error response from daemon: configured logging driver does not support reading`

Checking the logdriver with docker info returns the Logging Driver is json-file, which is the default.
If I run the command: docker inspect ContainerID I get the variables LogPath and LogConfig empty, as follows:

"LogPath": "",

"LogConfig": {
                "Type": "none",
                "Config": {}
            },

All the info I see on the internet is mainly related to AWS Task Definitions, for example, last comment on this thread here: https://forums.docker.com/t/configured-logging-driver-does-not-support-reading/33042/5

Would that error be related to the one I am facing? Is it possible to change the log driver config it anywhere on the playbook to fix the issue?

Thanks!

**Comment by Archehandoro** [comment]
In the matrix-docker-ansible-deploy/roles/matrix-bridge-rolenamec/templates/systemd/matrix-rolename.service.j2 file, the configuration reads:

`ExecStart=/usr/bin/docker run --rm --name matrix-appservice-irc \
			--log-driver=none \
			--user={{ matrix_user_uid }}:{{ matrix_user_gid }} \
			--cap-drop=ALL \
			--network={{ matrix_docker_network }} \
			{% if matrix_appservice_irc_container_http_host_bind_port %}
			-p {{ matrix_appservice_irc_container_http_host_bind_port }}:9999 \
			{% endif %}
			-v {{ matrix_appservice_irc_config_path }}:/config:z \
			-v {{ matrix_appservice_irc_data_path }}:/data:z \
			{% for arg in matrix_appservice_irc_container_extra_arguments %}
			{{ arg }} \
			{% endfor %}
			{{ matrix_appservice_irc_docker_image }} \
			-c /config/config.yaml -f /config/registration.yaml -p 9999
`
I believe if the parameter --log-driver=none is changed to --log-driver=json-file would solve the issue. Will make the changes on my setup and if it works do a PR.

**Comment by spantaleev** [comment]
See [this comment](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/272#issuecomment-535319561) in another issue, explaining the logs situation.

**Comment by Archehandoro** [comment]
Oh, thanks, that's great. Then we can close the issue.
