### ISSUE TITLE
Update configuring-playbook-email.md

### ISSUE THREAD

**Issue by Beerdy1** [spantaleev/matrix-docker-ansible-deploy#2747]
The free Oracle Cloud tier blocks SMTP on port 25 on accounts created after 06/25/2021: https://support.oracle.com/knowledge/Oracle%20Cloud/2787393_1.html

Request to update the the documentation to indicate this.

**Comment by spantaleev** [comment]
What does this have to do with this playbook?

It seems like we don't mention Oracle anywhere in the playbook and its documentation.

If you're referring to some other guide elsewhere, then you may wish to look into updating that guide.
