### ISSUE TITLE
Support Schildichat-web cilent

### ISSUE THREAD

**Issue by extremelyonline** [spantaleev/matrix-docker-ansible-deploy#2755]
**Is your feature request related to a problem? Please describe.**
Please add support for the Schildichat-web cilent

**Describe the solution you'd like**
Schildichat-web is a fork of Element. The web client would work by simply swapping the Element docker image with [the Schildichat-web image](https://github.com/SchildiChat/element-web/pkgs/container/schildichat-web).

I wonder if a toggle like matrix_client_schildichat_enabled: true can be added.

**Describe alternatives you've considered**
Can also offer the option to build the image.

**Additional context**
https://github.com/SchildiChat/schildichat-desktop
https://github.com/SchildiChat/element-web

**Comment by wuast94** [comment]
@etkecc many thanks, now after i see alls the files changed i would never had get this done, many many thanks 😊
