### ISSUE TITLE
Add matrix-postgres-cli to docs

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#28]

**Comment by spantaleev** [comment]
Sounds like this, along with #29 may go into a new documentation page, likely called `docs/maintenance-and-troubleshooting.md`.

.. Unless we decide we have enough Postgres stuff to make its own dedicated `docs/maintenance-postgres.md` document which:
- mentions the `/usr/local/bin/matrix-postgres-cli` tool
- links to the upgrading Postgres document too (`docs/maintenance-upgrading-postgres.md`)
- gives some additional pointers about server performance, tools for purging data, etc.
