### ISSUE TITLE
Add DKIM signing to email

### ISSUE THREAD

**Issue by tablador** [spantaleev/matrix-docker-ansible-deploy#280]
It would be nice to add a way to add DKIM signatures and DMARC to email to help with spam filtering.

**Comment by spantaleev** [comment]
I think that'd be something one would do at the SMTP server though..

And then `matrix-mailer` would be set up as a smarthost, relaying through that other SMTP server.

Adding DKIM support and other such things to `matrix-mailer` seems like a complication we'd better not have to deal with in this project.
Well, if you have a proposal for how to do it simply and possibly a pull request, we might add it.

In any case, I've found delivery to work quite well even without DKIM.

**Comment by aaronraimist** [comment]
Emails from my server were getting marked as spam by Gmail but setting up https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-email.md#relaying-email-through-another-smtp-server got them to be delivered to the inbox with passing SPF and DKIM

**Comment by spantaleev** [comment]
I'll close this.. It seems out of scope for us.
