### ISSUE TITLE
Guide to updating matrix domain

### ISSUE THREAD

**Issue by akshaylive** [spantaleev/matrix-docker-ansible-deploy#2835]
I've been running matrix for more than a year on DomainA. I would like to switch to DomainB without losing messages (mainly between participants on the same server). Is there a way to port the messages without having to perform a reinstall?

**Describe the solution you'd like**
Ideally, I want to be able to update the host_vars and hosts files with the new domain everywhere and rerun `step-all,start` to achieve this.

**Describe alternatives you've considered**
Maybe re-setup the domain after uninstall and port the database somehow?

Any help is appreciated here.

**Comment by spantaleev** [comment]
The Matrix protocol does not support changing the name of the server subsequently. If you do, you need to start from scratch with an empty database.
