### ISSUE TITLE
Max filesize

### ISSUE THREAD

**Issue by Saik0Shinigami** [spantaleev/matrix-docker-ansible-deploy#284]
Maybe I'm retarded, but hopefully someone can set me straight...

Is there no built in way to set the max_filesize in this script? 

I've already went in to /matrix/synapse/config/homeserver.yaml and changed it there... after a reboot... no dice.

10MB is a bit small for my usage and would prefer upping it to 25 or something like that.

**Comment by spantaleev** [comment]
See the `matrix_synapse_max_upload_size_mb` setting.

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/3bf7a7a85ec5439dba8f71f71fadfecb275cf4f2/roles/matrix-synapse/defaults/main.yml#L74

Override that variable in your `vars.yml` file, run the playbook with `--tags=setup-all,start` and you're done.

**Comment by aaronraimist** [comment]
To be clear when using this setup you should never edit `/matrix/...` directly.

**Comment by Saik0Shinigami** [comment]
@aaronraimist I can understand that, however I was unaware of another method. So I tried it anyway just to see as I rather try things and possibly break them myself so I can learn rather than bother others. I understood that the setting can be reverted or throw other issues. Thanks for the concern.

As far as the resolution proposed by @spantaleev, that did not work for me. I've placed the line and ran the command to no avail. I still receive 

"Upload Error
This file is too large to upload. The file size limit is 10 MB but this file is <larger> MB."

I can confirm that the homeserver.yaml in the same location I mentioned before reflects the new value(which was different than what I set it to manually, so it has changed), but does not appear to function.

**Comment by spantaleev** [comment]
@Saik0Shinigami, this sounds like an error message coming from riot-web or something.

From what I remember, there was some media API endpoint which clients could use to find the maximum allowed file size. I'm guessing your riot-web instance had the 10MB value cached and continued using it, even after it got changed.

Perhaps restarting riot-web or clearing its cache might help.

**Comment by Saik0Shinigami** [comment]
After a few days of letting the problem sit on the back-burner and then trying it again, it not functions as intended. Could have been a cache somewhere I suppose. thanks for the assistance.
