### ISSUE TITLE
The ntfy behind traefik proxy doesn't work.

### ISSUE THREAD

**Issue by Aquilamason** [spantaleev/matrix-docker-ansible-deploy#2846]
**Playbook Configuration**:

My `vars.yml` file looks like this:

ntfy_enabled: true
ntfy_configuration_extension_yaml: |
  listen-http: ':8080'
  behind-proxy: true

**Matrix Server:**
 - OS: CentOS 7
 - Architecture: amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:
When I run ansible for self-check and it reports errors:

TASK [galaxy/ntfy : Check ntfy] ****************************************************************************************************************************
fatal: [matrix.autodevops.link -> 127.0.0.1]: FAILED! => changed=false
  connection: close
  content_length: '11'
  content_type: text/plain; charset=utf-8
  date: Sat, 26 Aug 2023 01:15:55 GMT
  elapsed: 0
  msg: 'Status code was 502 and not [200]: HTTP Error 502: Bad Gateway'
  redirected: false
  status: 502
  url: https://ntfy.autodevops.link/upSELFCHECK123/json?poll=1&since=1s
...ignoring

TASK [galaxy/ntfy : Fail if ntfy not working] **************************************************************************************************************
fatal: [matrix.autodevops.link]: FAILED! => changed=false
  msg: 'Failed checking ntfy is up at `https://ntfy.autodevops.link` (checked endpoint: `https://ntfy.autodevops.link/upSELFCHECK123/json?poll=1&since=1s`). Is ntfy running? Is port 443 open in your firewall? Full error: {''redirected'': False, ''url'': ''https://ntfy.autodevops.link/upSELFCHECK123/json?poll=1&since=1s'', ''status'': 502, ''date'': ''Sat, 26 Aug 2023 01:15:55 GMT'', ''content_length'': ''11'', ''content_type'': ''text/plain; charset=utf-8'', ''connection'': ''close'', ''elapsed'': 0, ''changed'': False, ''failed'': True, ''msg'': ''Status code was 502 and not [200]: HTTP Error 502: Bad Gateway''}'

I've set up ntfy's DNS ntfy.autodevops.link correctly.
Am I overlooking some configurations please? Do I need to add any configuration in traefik?

**Comment by spantaleev** [comment]
Why are you messing with the port inside the container by overriding it via `ntfy_configuration_extension_yaml`?

The only thing you should need is `ntfy_enabled: true` and `ntfy_hostname: ...` and it should all work automatically.

Check if `mash-ntfy` is up via `systemctl status mash-ntfy` and see logs for `mash-ntfy` and `mash-traefik` via `journalctl -fu SERVICE_NAME`

**Comment by Aquilamason** [comment]
@spantaleev Thanks for your reply.
I changed the port because the matrix-ntfy service can't be started and reports such errors:
matrix-ntfy: 2023/08/25 14:20:56 FATAL listen tcp :80: bind: permission denied (exit_code=1)
matrix-ntfy: listen tcp :80: bind: permission denied

Since the traefik proxy is already listening to port 80, how should I properly resolve their conflict?

**Comment by spantaleev** [comment]
I see! The problem is that you're on an old distro which likely uses an old version of Docker, which does not like it when contianers use [privileged ports](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html).

One either needs to pass an additional `CAP_NET_ADMIN` privilege to the container or to avoid using privileged ports (among other potential workarounds).

No one else has reported this issue, so you're in the minority of trying to run ntfy on such an old distro and Docker version. I recommend upgrading to Rockylinux 9.

Nevertheless, I have updated the ntfy role (`v2.7.0-0` -> `v2.7.0-2`) so that it uses port 8080 internally. Reverse-proxies (like Traefik and the deprecated matrix-nginx-proxy) now use port `8080` to follow suit.

**Comment by Aquilamason** [comment]
> Nevertheless, I have updated the ntfy role (`v2.7.0-0` -> `v2.7.0-2`) so that it uses port 8080 internally. Reverse-proxies (like Traefik and the deprecated matrix-nginx-proxy) now use port `8080` to follow suit.
> 
> Update the playbook (likely `git pull`) and run `just roles` (or `make roles`) to get the updated code.

It works now, thanks a lot!
