### ISSUE TITLE
synapse warnings flood logfile

### ISSUE THREAD

**Issue by nowatbuer** [spantaleev/matrix-docker-ansible-deploy#2849]
I have a pretty small matrix installation for some time. Since a few days my system logfiles are flooded with tons of entries like:
Aug 30 11:33:45 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:45,947 - synapse.federation.sender.per_destination_queue - 399 - WARNING - federation_transaction_transmission_loop-38753 - TX [mail.wuast24.de] Received 404 response to transaction: 404: Not Found
Aug 30 11:33:45 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:45,954 - synapse.replication.tcp.handler - 733 - WARNING - store_retry_timings-37401 - Dropping command as not connected: 'REMOTE_SERVER_UP'
Aug 30 11:33:45 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:45,968 - synapse.http.matrixfederationclient - 805 - WARNING - federation_transaction_transmission_loop-38754 - {PUT-O-38475} [bridge.tachchef.de] Request failed: PUT matrix-federation://bridge.tachchef.de/_matrix/federation/v1/send/1693386856505: HttpResponseException('401: Unauthorized')
Aug 30 11:33:45 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:45,969 - synapse.federation.sender.per_destination_queue - 399 - WARNING - federation_transaction_transmission_loop-38754 - TX [bridge.tachchef.de] Received 401 response to transaction: 401: Unauthorized
Aug 30 11:33:45 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:45,976 - synapse.replication.tcp.handler - 733 - WARNING - store_retry_timings-37402 - Dropping command as not connected: 'REMOTE_SERVER_UP'
Aug 30 11:33:46 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:46,002 - synapse.http.matrixfederationclient - 805 - WARNING - federation_transaction_transmission_loop-38755 - {PUT-O-38476} [mail.wuast24.de] Request failed: PUT matrix-federation://mail.wuast24.de/_matrix/federation/v1/send/1693386856506: HttpResponseException('404: Not Found')
Aug 30 11:33:46 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:46,003 - synapse.federation.sender.per_destination_queue - 399 - WARNING - federation_transaction_transmission_loop-38755 - TX [mail.wuast24.de] Received 404 response to transaction: 404: Not Found
Aug 30 11:33:46 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:46,012 - synapse.replication.tcp.handler - 733 - WARNING - store_retry_timings-37403 - Dropping command as not connected: 'REMOTE_SERVER_UP'
Aug 30 11:33:46 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:46,016 - synapse.http.matrixfederationclient - 805 - WARNING - federation_transaction_transmission_loop-38756 - {PUT-O-38477} [bridge.tachchef.de] Request failed: PUT matrix-federation://bridge.tachchef.de/_matrix/federation/v1/send/1693386856507: HttpResponseException('401: Unauthorized')
Aug 30 11:33:46 rootsrv matrix-synapse[2733]: 2023-08-30 09:33:46,017 - synapse.federation.sender.per_destination_queue - 399 - WARNING - federation_transaction_transmission_loop-38756 - TX [bridge.tachchef.de] Received 401 response to transaction: 401: Unauthorized

The vars.yml is:
matrix_domain: 466buer.de
matrix_ssl_lets_encrypt_support_email: *******************
matrix_coturn_turn_static_auth_secret: "*****************************"
matrix_synapse_macaroon_secret_key: "*****************************"
devture_postgres_connection_password: '__pass__'
matrix_nginx_proxy_base_domain_serving_enabled: true
jitsi_enabled: true
jitsi_jicofo_component_secret: *****************************
jitsi_jicofo_auth_password: *****************************
jitsi_jvb_auth_password: *****************************
jitsi_jibri_recorder_password: *****************************
jitsi_jibri_xmpp_password: *****************************
matrix_registration_enabled: true
matrix_registration_admin_secret: "*****************************"
matrix_server_fqn_jitsi: **********************
matrix_mautrix_signal_enabled: true
matrix_mautrix_whatsapp_enabled: true
matrix_synapse_admin_enabled: true
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: *******************

Thanks for any idea
Norbert

**Comment by spantaleev** [comment]
Sounds like: https://github.com/matrix-org/synapse/issues/16208

There was (and still is?) a similar issue too: https://github.com/matrix-org/synapse/issues/16101

I've pushed some changes which should make Synapse quieter by default.

**Comment by nowatbuer** [comment]
Thanks, that helped.
Norbert
