### ISSUE TITLE
start matrix-synapse.service: Unit not found

### ISSUE THREAD

**Issue by xsq0718** [spantaleev/matrix-docker-ansible-deploy#285]
I follow the steps to install
![image](https://user-images.githubusercontent.com/26321450/67271679-996d1480-f4ed-11e9-8bce-581f9520b742.png)

**Comment by spantaleev** [comment]
Are you using the whole playbook or are you plugging its roles into some other playbook of yours?

What is your `vars.yml` file like?

**Comment by xsq0718** [comment]
![image](https://user-images.githubusercontent.com/26321450/67367993-1c9f7080-f5a9-11e9-984f-318218df5bea.png)
/matrix-docker-ansible-deploy/inventory/host_vars/matrix.basswaf.space
![image](https://user-images.githubusercontent.com/26321450/67368347-bebf5880-f5a9-11e9-9f55-b99c3157758a.png)
/matrix-docker-ansible-deploy/inventory/hosts

me using the while playbook

**Comment by spantaleev** [comment]
Hmm.. It's weird that it's not finding a `matrix-synapse.service` unit file.

Perhaps it died during Synapse installation?
If you log in to the server manually and run `systemctl daemon-reload`, the problem might go away.

**Comment by xsq0718** [comment]
`systemctl daemon-reload` and ![image](https://user-images.githubusercontent.com/26321450/67370140-c3394080-f5ac-11e9-9173-1f3ef6012078.png)

still "Unable to start service matrix-synapse: Failed to start matrix-synapse.service: Unit not found"

this ` ansible-playbook -i inventory/hosts setup.yml --tags=setup-all` problem？

**Comment by spantaleev** [comment]
I'm not sure, but "Job invalid" sounds like there might be some syntax error in `/etc/systemd/system/matrix-synapse.service` or something else that your version of systemd does not like in that file.

Which distro is this on? Which version of systemd? Do you see anything irregular in `/etc/systemd/system/matrix-synapse.service`?

**Comment by xsq0718** [comment]
i found
![image](https://user-images.githubusercontent.com/26321450/67372487-9129dd80-f5b0-11e9-9f55-fa79ac43417d.png)

`OS: CentOS Linux release 7.2.1511 (Core) `

![image](https://user-images.githubusercontent.com/26321450/67372772-03022700-f5b1-11e9-9644-2fa9fdc6eb62.png)

**Comment by spantaleev** [comment]
"CentOS Linux release 7.2.1511 (Core)" is quite old, given that CentOS 7.7 is available now.

Maybe it's a compatibility problem with it.

I suggest that you do some system updates (`yum update`) and see if that solves the problem.

**Comment by xsq0718** [comment]
using CentOS 7.7 can run successfully.
thank you^_^
