### ISSUE TITLE
matrix federation not working

### ISSUE THREAD

**Issue by Siam-1998** [spantaleev/matrix-docker-ansible-deploy#2862]
**Subject:** I want to communicate with two different matrix servers using federation but not working. When I check it is configured correctly, the error shows 

**Error:** It is possible that the MatchingServerName error below is caused by you entering the wrong URL in the federation tester, not because there is an actual issue with your federation. You should enter the server name into the Federation Tester, not the location where your server is. The server name is the public facing name of your server that appears at the end of usernames and room aliases 

**DNS results** server name/.well-known result contains explicit port number: no SRV lookup done

- Server Details:
- Ubuntu Server 22.04 LTS
 
 Homeserver version: Synapse 1.90.0
 
 vars.yml File

#Example value: example.com
matrix_domain: domain1.com
#The Matrix homeserver software to install.
matrix_homeserver_implementation: synapse
#You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: '#######'
#For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
#Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: 'admin@domain1.com'
#using this superuser account.
devture_postgres_connection_password: '#####'
matrix_synapse_federation_domain_whitelist:
- domain1.com
- domain2.com
matrix_synapse_allow_public_rooms_over_federation: true
matrix_synapse_admin_enabled: true
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_ma1sd_enabled: true
matrix_well_known_matrix_server_enabled: true

DNS Record 

Used by component  Type:SRV  Host:_matrix-identity._tcp  Priority:10  Weight:0  Port:8448  Target:matrix.domain1.com

**Comment by Virkkunen** [comment]
In my case, I think this issue happens because my main domain (domain.tld) is managed under github pages, while matrix.domain.tld is managed by this playbook, which causes issues.

**Comment by aaronraimist** [comment]
@Virkkunen there's no reason that can't work. You just need to make sure the .well-known files are being served on domain.tld which may require some manual jekyll configuration.

**Comment by aaronraimist** [comment]
@Siam-1998 What domain are you putting into the federation tester?

**Comment by Siam-1998** [comment]
I am putting into the federation tester
matrix.domain1.com and domain1.com

**Comment by aaronraimist** [comment]
@Siam-1998 as the error message is trying to tell you, entering matrix.domain1.com into the federation tester is almost certainly incorrect. You should be putting your server name into the federation tester (that's `matrix_domain` in your `vars.yml` file).

**Comment by Siam-1998** [comment]
@aaronraimist Thanks, yes it is working. There is no errors showing, but DNS results

server name/.well-known result contains explicit port number: no SRV lookup done

**Comment by aaronraimist** [comment]
@Siam-1998 That's just information for you. Not an issue.

As long the connection reports show success, federation should work.

**Comment by Siam-1998** [comment]
@aaronraimist Yes it working Thank You
