### ISSUE TITLE
Why Traefik? Sliding Sync Proxy on existing nginx proxy or other webservers

### ISSUE THREAD

**Issue by 0x416c69** [spantaleev/matrix-docker-ansible-deploy#2881]
We care a lot about performance and the performance of Traefik is not good enough for us. It's sad that you're no longer gonna maintain nginx, is this decision reversible? If not, is there a guide to setting up sliding sync proxy for either the existing nginx or other better high performance web servers such as OpenLiteSpeed?

**Comment by 4censord** [comment]
Maybe https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#another-webserver sufficient for you?
That should allow you to use any other server, with the downside that you need to configure it yourself.

**Comment by 0x416c69** [comment]
@4censord I know that page exists but, does this setup also work for [sliding proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-sliding-sync-proxy.md)?

**Comment by 4censord** [comment]
Well, on the project page itself it lists a snippet for using nginx: https://github.com/matrix-org/sliding-sync#same-hostname

**Comment by 0x416c69** [comment]
Could it be incompatible with future updates from this repo? Honestly I was afraid to use this big docker ansible deploy project, I guess it's time to move on from it and configure it all by myself, that'd be the safest and best option

**Comment by 4censord** [comment]
If you use the external reverse proxy option, as far as i can tell that should not happen.

**Comment by satoshinotdead** [comment]
So, using Nginx like reverse proxy with the Ansible script should be safe for future updates or it's not a good deal at all?

I'm with the OP on this, Traefik seems to be not better choice than Nginx but I assume there are cons and pros that I don't mind in the evaluation.

Thanks for sharing this fantastic work, by the way!

**Comment by Happyfeet01** [comment]
@satoshinotdead i tried this but Element x still at the First sync

**Comment by 0x416c69** [comment]
@spantaleev Thanks for not giving a s***, I'm sure you have your _reasons_

**Comment by satoshinotdead** [comment]
Someone can share a working template with Nginx as reverse proxy?

**Comment by Happyfeet01** [comment]
I don't know what you have. It works perfectly for me with an Nginx RP on the host. Traefik takes care of everything. Nginx only forwards to the external port of Traefik.

**Comment by 4censord** [comment]
Well have you looked at the [nginx template included with the sliding sync proxy](https://github.com/matrix-org/sliding-sync?tab=readme-ov-file#same-hostname)?

Happyfeet: Their original concern was that traffic is not performant enough for their usecase.

**Comment by satoshinotdead** [comment]
> I don't know what you have. It works perfectly for me with an Nginx RP on the host. Traefik takes care of everything. Nginx only forwards to the external port of Traefik. 

Hello, that's my actual configuration. I just want to use Nginx for having Matrix with other services and I only need to redirect Matrix subdomains to the services.

Can you share your template?

**Comment by 0x416c69** [comment]
Since the author of the project does not care about our saying in the project (cuz why should he? he's doing it for free/out of fun, _some open source contributors☕_), I'll probably make my own docker ansible deploy with nginx and openlitespeed and share the repository link if anyone's interested.

**Comment by Happyfeet01** [comment]
> > I don't know what you have. It works perfectly for me with an Nginx RP on the host. Traefik takes care of everything. Nginx only forwards to the external port of Traefik. 
> 
> Hello, that's my actual configuration. I just want to use Nginx for having Matrix with other services and I only need to redirect Matrix subdomains to the services.
> 
> Can you share your template?

Sure, but later this Day.
