### ISSUE TITLE
How to import the certificate from another installation?

### ISSUE THREAD

**Issue by Aquilamason** [spantaleev/matrix-docker-ansible-deploy#2889]
**Matrix Server:**
 - OS: Rocky Linux 9
 - Architecture: amd64

**Problem description**:

I set up a server on AWS EC2 with the latest Ansible script and now I want to migrate it to another server and with the same domain. 
I followed the below guides and imported both Postgres and media files successfully and then changed DNS to the new server.
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-postgres.md
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-synapse-media-store.md

However, when I started the new server and ran self-check, I found that the SSL certificate validation failed. So I suspect that I need to import the original SSL certificates from the old server into the new server. 
Is there any guide on how to import the certificate from the old installation?

**Comment by spantaleev** [comment]
If Traefik is failing to obtain SSL certificates, you should check your incoming port 80 and restart `matrix-traefik` (`systemctl restart matrix-traefik`).

You don't need to import SSL certificates from your previous installation. Traefik will fetch new ones.

-----

On a related note: If you were running another installation under the same Synapse `server_name`, you may wish to migrate its `.signing.key` file. On the new installation, the file is at `/matrix/synapse/config/matrix.DOMAIN.signing.key`. You can paste in the contents of your previous signing key there.

**Comment by Aquilamason** [comment]
Thanks, I copied the .signing.key file and it works now!
