### ISSUE TITLE
Empty Room, display name is raw user id for Dendrite setup

### ISSUE THREAD

**Issue by starascendin** [spantaleev/matrix-docker-ansible-deploy#2895]
**Describe the bug**
Hi all, i've successfully ran the playbook with dendrite as the matrix server. Things look good except for these issues:
* Empty Room -- messages from the bridges (whatsapp, imessage, etc) are showing up as "Empty Room" and does not auto accept the room. Is this a dendrite issue or a config issue? Using synapse things worked fine, and after switching to dendrite these started to appear
* Display name is raw user_ids -- with synapse, I was able to get display name from whatsapp and imessage bridges and they show up as they do in the native apps. However, when i switched to dendrite, i've been getting display names like `imessage_39781 and imessage_39781 (@imessagebot:xxx.com)` . Does anyone know what is causing this? 

Thanks!

**Comment by spantaleev** [comment]
I'm not sure about your specific issues, but.. Dendrite is known to be broken in various ways when it comes to bridge compatibility.

**Comment by starascendin** [comment]
> I'm not sure about your specific issues, but.. Dendrite is known to be broken in various ways when it comes to bridge compatibility.

ok didn't know and thanks for pointing that out... i'll switch back to synapse for the time being then

**Comment by starascendin** [comment]
gonna close the issue
