### ISSUE TITLE
Install docker-compose plugin does not work under ArchLinux

### ISSUE THREAD

**Issue by dev-da77** [spantaleev/matrix-docker-ansible-deploy#2924]
**Describe the bug**

File geerlingguy.docker/defaults/main.yml was changed since my last update. Change triggers to install docker-compose-plugin.

**Package docker-compose-plugin not available under archlinux**, which is my server OS!

--

Error message when running: ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start -K

```
TASK [galaxy/geerlingguy.docker : Install docker-compose plugin.] *************************************
fatal: [matrix.xxx.xx]: FAILED! => changed=false 
  cmd:
  - /usr/bin/pacman
  - --upgrade
  - --print-format
  - '%n'
  - docker-compose-plugin
  msg: Failed to list package docker-compose-plugin
  rc: 1
  stderr: |-
    error: 'docker-compose-plugin': could not find or read package
  stderr_lines: <omitted>
  stdout: |-
    loading packages...
  stdout_lines: <omitted>
```

What changed since last successful run:

../matrix-docker-ansible-deploy/roles/galaxy/geerlingguy.docker/defaults/main.yml

```
# Docker Compose Plugin options.
docker_install_compose_plugin: false   <<< CHANGED TO TRUE
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present

# Docker Compose options.
docker_install_compose: true   <<< CHANGED TO FALSE
docker_compose_version: "v2.11.1"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ docker_compose_arch }}"
docker_compose_path: /usr/local/bin/docker-compose
```

Package docker-compose-plugin not available under archlinux!

**Matrix Server:**
 - OS: ArchLinux
 - Architecture: amd64

**Comment by spantaleev** [comment]
I've disabled installing of the docker compose plugin by default for us. Thank you for reporting this.

The Arch issue seems to have already been reported upstream [here](https://github.com/geerlingguy/ansible-role-docker/issues/427)
