### ISSUE TITLE
Set Heisenbridge media URL

### ISSUE THREAD

**Issue by Firefishy** [spantaleev/matrix-docker-ansible-deploy#2932]
**Describe the bug**
Heisenbridge by default uses the `matrix_heisenbridge_homeserver_url` as the media url which is set to `matrix_homeserver_container_url` (`matrix-nginx-proxy:12080`). The ansible code should set a correct media URL, as heisenbridge [now supports setting](https://github.com/hifi/heisenbridge/commit/9298988dc7453490cb2a96ecd93d053145f78fc4) a separate media url.

**To Reproduce**
* Install Heisenbridge
* Attach an image in an IRC channel supported by Heisenbridge
* Heisenbridge sends a media URL to IRC: https://matrix-nginx-proxy:12080/...

**Expected behavior**
Expectation the url is the external https://matrix.example.com/...

**Comment by Firefishy** [comment]
A workaround for the moment is to override the MEDIAURL within matrix by sending private messaging to the heisenbridge bot with a command: `mediaurl https://matrix.example.com/`. 

Ideally heisenbridge should be supplied with the correct mediaurl out-the-box by ansible.

**Comment by signaleleven** [comment]
If you mean the domain used when you post media in a bridged chat

`matrix_heisenbridge_homeserver_url: "example.tld"` 

does what you need

**Comment by spantaleev** [comment]
For my setup, I didn't find this to be necessary, because it was auto-detecting the media URL by itself:

> matrix-heisenbridge[1127966]: Trying to detect homeserver public endpoint, this might take a while...
> matrix-heisenbridge[1127966]: Homeserver is publicly available at https://matrix.DOMAIN

Nevertheless, given that we know the value, there's no need for this guessing game.

The playbook now configures the `media_url` explicitly, using `matrix_homeserver_url`.

**Comment by Firefishy** [comment]
Rockstars! Thank you for being awesome. :-)
