### ISSUE TITLE
passlib missing for traefik dashboard

### ISSUE THREAD

**Issue by gnunicorn** [spantaleev/matrix-docker-ansible-deploy#2967]
I tried enabling the traefik dashboard by adding:

```
devture_traefik_dashboard_enabled: true
devture_traefik_dashboard_hostname: "{{ matrix_server_fqn_matrix }}"
devture_traefik_dashboard_basicauth_enabled: true
devture_traefik_dashboard_basicauth_user: SOMETHING
devture_traefik_dashboard_basicauth_password: PASSWORD
```

but it fails on my Arch Linux with:

```

TASK [galaxy/com.devture.ansible.role.traefik : Generate basic auth file locally] **********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'passlib'
fatal: [matrix.SERVER -> 127.0.0.1]: FAILED! => changed=false 
  msg: Failed to import the required Python library (passlib) on laptops's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter

```

Rerunning `just roles` before didn't do anything to it. Looks like dependency is missing ensuring I have passlib for python available on the runner-system...

Running `pamac install python-passlib` fixed it for me here, but if maybe that is something to define in some dependencies?

**Comment by spantaleev** [comment]
Previous Ansible versions could do some hashing/crypto stuff from the standard Python library, but newer ones deprecated this and require the `passlib` module.

`passlib` is mentioned as a prerequisite in `docs/prerequisites.md`.

`just roles` only installs Ansible roles (YAML configuration files).
