### ISSUE TITLE
Twitter bridge anyone?

### ISSUE THREAD

**Issue by xme** [spantaleev/matrix-docker-ansible-deploy#298]
I see that a Twitter bridge exists (https://half-shot.github.io/matrix-appservice-twitter/) and I would like to deploy it via ansible like other well-known bridges. Anybody could help?

**Comment by aaronraimist** [comment]
That Twitter bridge *used to exist*. Twitter shutdown the API that it used.

**Comment by frankgerhardt** [comment]
https://github.com/Sorunome/mx-puppet-twitter

**Comment by ptman** [comment]
I use a bot to follow twitter via matrix: https://github.com/vranki/hemppa

**Comment by luixxiul** [comment]
Closing as answered.
