### ISSUE TITLE
Code-review: location regexp matching working?

### ISSUE THREAD

**Issue by jolly-jump** [spantaleev/matrix-docker-ansible-deploy#2986]
Hi Stani,

based on #2954, where I am very sure (from the specs and the tests) that `^~` does not do any regexp matching, I came across two more lines where this is (probably) the intention:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ad230555e9a612b3e3a775f4aaf1f98c742e0779/roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2#L122

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ad230555e9a612b3e3a775f4aaf1f98c742e0779/roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2#L145

I could find that you introduced these lines 4 months ago for the matrix-media-repo. I cannot test this and I could not find who has this running to check if my suspicion (that these lines above do not match and thus do not work) is right.

**Comment by spantaleev** [comment]
Good catch!

Looks like various people are copy-pasting `location` blocks and do not really look into (or remember) what the `^~` prefix does. I've supposedly fixed it now.
