### ISSUE TITLE
Installation fail on raspberry pi 4

### ISSUE THREAD

**Issue by ariko861** [spantaleev/matrix-docker-ansible-deploy#299]
TASK [matrix-synapse : Generate initial Synapse config and signing key] ********************************************************************************************************************
fatal: [matrix.example.com]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=991:991", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=991", "-e", "GID=991", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=matrix.example.com", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.5.1", "generate"], "delta": "0:00:02.137538", "end": "2019-11-07 11:14:39.293929", "msg": "non-zero return code", "rc": 1, "start": "2019-11-07 11:14:37.156391", "stderr": "standard_init_linux.go:211: exec user process caused \"exec format error\"", "stderr_lines": ["standard_init_linux.go:211: exec user process caused \"exec format error\""], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************************************************************************************************************************
matrix.example.com      : ok=72   changed=0    unreachable=0    failed=1  

This is what I get when I run "ansible-playbook -i inventory/hosts setup.yml --tags=start"
Any clue of how to fix this ?

**Comment by spantaleev** [comment]
ARM is not supported (yet).

Most components do not have an ARM Docker image..
The error you're seeing (`standard_init_linux.go:211: exec user process caused "exec format error`) indicates that this is a Docker image for a different architecture, which you can't execute on your ARM hardware.

For some components (like the Synapse server), there are multi-arch images which support ARM.
It may be possible to use those non-official images, but.. they may be different enough to not work.

Your best bet would be disabling most playbook components and only enabling the minimum (Postgres, Synapse). And then trying some alternative Docker image for Synapse. The Postgres image seems to have an ARM version and may work by default.

**Comment by ariko861** [comment]
Thanks !
I'll try that !

On November 7, 2019 1:51:56 PM GMT+01:00, Slavi Pantaleev <notifications@github.com> wrote:
>ARM is not supported (yet).
>
>Most components do not have an ARM Docker image..
>The error you're seeing (`standard_init_linux.go:211: exec user process
>caused "exec format error`) indicates that this is a Docker image for a
>different architecture, which you can't execute on your ARM hardware.
>
>For some components (like the Synapse server), there are multi-arch
>images which support ARM.
>It may be possible to use those non-official images, but.. they may be
>different enough to not work.
>
>Your best bet would be disabling most playbook components and only
>enabling the minimum (Postgres, Synapse). And then trying some
>alternative Docker image for Synapse. The Postgres image seems to have
>an ARM version and may work by default.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/299#issuecomment-551066402

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
