### ISSUE TITLE
just roles ntfy broken

### ISSUE THREAD

**Issue by darksnakezero** [spantaleev/matrix-docker-ansible-deploy#3004]
**Describe the bug**
"just roles" fails to install ntfy. 
`just roles
Starting galaxy role install process
- extracting auxiliary to /root/matrix-docker-ansible-deploy/roles/galaxy/auxiliary
- auxiliary (v1.0.0-1) was installed successfully
- extracting backup_borg to /root/matrix-docker-ansible-deploy/roles/galaxy/backup_borg
- backup_borg (v1.2.6-1.8.4-0) was installed successfully
- extracting container_socket_proxy to /root/matrix-docker-ansible-deploy/roles/galaxy/container_socket_proxy
- container_socket_proxy (v0.1.1-2) was installed successfully
- extracting docker_sdk_for_python to /root/matrix-docker-ansible-deploy/roles/galaxy/docker_sdk_for_python
- docker_sdk_for_python (129c8590e106b83e6f4c259649a613c6279e937a) was installed successfully
- extracting playbook_help to /root/matrix-docker-ansible-deploy/roles/galaxy/playbook_help
- playbook_help (c1f40e82b4d6b072b6f0e885239322bdaaaf554f) was installed successfully
- extracting playbook_runtime_messages to /root/matrix-docker-ansible-deploy/roles/galaxy/playbook_runtime_messages
- playbook_runtime_messages (9b4b088c62b528b73a9a7c93d3109b091dd42ec6) was installed successfully
- extracting playbook_state_preserver to /root/matrix-docker-ansible-deploy/roles/galaxy/playbook_state_preserver
- playbook_state_preserver (ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16) was installed successfully
- extracting postgres to /root/matrix-docker-ansible-deploy/roles/galaxy/postgres
- postgres (v16.1-0) was installed successfully
- extracting postgres_backup to /root/matrix-docker-ansible-deploy/roles/galaxy/postgres_backup
- postgres_backup (5dd334c0b7f0a2795023ec9ece747c3ea3da06f2) was installed successfully
- extracting systemd_docker_base to /root/matrix-docker-ansible-deploy/roles/galaxy/systemd_docker_base
- systemd_docker_base (v1.0.0-0) was installed successfully
- extracting systemd_service_manager to /root/matrix-docker-ansible-deploy/roles/galaxy/systemd_service_manager
- systemd_service_manager (v1.0.0-1) was installed successfully
- extracting timesync to /root/matrix-docker-ansible-deploy/roles/galaxy/timesync
- timesync (v1.0.0-0) was installed successfully
- extracting traefik to /root/matrix-docker-ansible-deploy/roles/galaxy/traefik
- traefik (v2.10.5-2) was installed successfully
- extracting traefik_certs_dumper to /root/matrix-docker-ansible-deploy/roles/galaxy/traefik_certs_dumper
- traefik_certs_dumper (v2.8.1-0) was installed successfully
- extracting etherpad to /root/matrix-docker-ansible-deploy/roles/galaxy/etherpad
- etherpad (v1.9.3-0) was installed successfully
- extracting docker to /root/matrix-docker-ansible-deploy/roles/galaxy/docker
- docker (7.0.2) was installed successfully
- extracting grafana to /root/matrix-docker-ansible-deploy/roles/galaxy/grafana
- grafana (v10.2.1-0) was installed successfully
- extracting jitsi to /root/matrix-docker-ansible-deploy/roles/galaxy/jitsi
- jitsi (v9078-1) was installed successfully
[WARNING]: - ntfy was NOT installed successfully: - command /usr/bin/git checkout v2.8.0-0 failed in directory /root/.ansible/tmp/ansible-local-5104w8zzkw23/tmpfm0rigmw/ntfy (rc=1) - error: pathspec 'v2.8.0-0'
did not match any file(s) known to git
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
error: Recipe `roles` failed with exit code 1`

The suggested workaround flag does not work either:
`just --ignore-errors roles
error: Found argument '--ignore-errors' which wasn't expected, or isn't valid in this context

USAGE:
    just [FLAGS] [OPTIONS] [--] [ARGUMENTS]...

For more information try --help`

**To Reproduce**
My `vars.yml` file looks like this:

```vars.yaml
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: [DOMAIN].com

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: '[EMAIL]'

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: '[LONG STRING OF CHARACTERS AND NUMERS]'

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: '[LONG STRING OF CHARACTERS AND NUMERS]'

# All secrets keys are now derived from `matrix_homeserver_generic_secret_key`, not from `matrix_synapse_macaroon_secret_key`.
# To keep them all the same, define `matrix_homeserver_generic_secret_key` in terms of `matrix_synapse_macaroon_secret_key`.
# Using a new secret value for this configuration key is also possible and should not cause any problems.
#
# Fun fact: new installations (based on the new `examples/vars.yml` file) do this in reverse.
# That is, the Synapse macaroon secret is derived from `matrix_homeserver_generic_secret_key`.
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: '[LONG STRING OF CHARACTERS AND NUMERS]'

matrix_playbook_reverse_proxy_type: playbook-managed-nginx
matrix_nginx_proxy_enabled: true

#Base domain is provided by nginx
matrix_nginx_proxy_base_domain_serving_enabled: true
#Get valid SSL Cert for nextcloud
matrix_ssl_additional_domains_to_obtain_certificates_for:
- [DOMAIN]

#readable version in separate file
#Setup nginx to relay traffic for nextcloud
matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
- "server {\r\n        listen 8080;\r\n        listen [::]:8080;\r\n\r\n        server_name [OTHERSERVER];\r\n        server_tokens off;\r\n\r\n                location /.well-known/acme-challenge {\>

#enable nginx status webpanel
matrix_nginx_proxy_proxy_matrix_nginx_status_enabled: true

#allow access to status webpanel for pc .30
matrix_nginx_proxy_proxy_matrix_nginx_status_allowed_addresses:
- [LOCAL IP ADRESS]

#enable synapse admin interface
matrix_synapse_admin_enabled: true

#activate shared secret auth
#enables automatic pupeteering
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: '[LONG STRING OF CHARACTERS AND NUMERS]'

#enable mautrix-telegram
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: [API ID]
matrix_mautrix_telegram_api_hash: [HASH]

#enable mautrix-whatsapp
matrix_mautrix_whatsapp_enabled: true

#enable mx-puppet-discord
matrix_mx_puppet_discord_enabled: true

#enable mautrix-discord
matrix_mautrix_discord_enabled: true

#enable matrix reminder bot
matrix_bot_matrix_reminder_bot_enabled: true

# Adjust this to whatever password you chose when registering the bot user
matrix_bot_matrix_reminder_bot_matrix_user_password: [LONG STRING OF CHARACTERS AND NUMERS]

# Adjust this to your timezone
matrix_bot_matrix_reminder_bot_reminders_timezone: Europe/London

#compress the state table periodically -> Less Memory usage
matrix_synapse_auto_compressor_enabled: true
```

1) do a git pull
2) adjust vars.yaml
3) do a "just roles"
4) observe the error and be unable to update/restart anything

**Expected behavior**
No error in just roles.

**Matrix Server:**
 - debian 11
 - amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- ansible is run on the server itself
- ansible version: 2.10.8, python version: 3.9.2

**Additional context**
If this should be reported somewhere else, please kindly tell me.

If there is any way to exclude the ntfy role, please also tell me, as I dont want to use the ntfy service.

**Comment by darksnakezero** [comment]
Additional information:
This seems to be due to the change in line 58 of requirements.yml:
https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/ef3f3741c9e355282f975d5e2ccb5ae81c26d1fd

Reverting this change fixes the problem. This is probably caused by the missing tag of Aines newest commit. THe reference vby version number might need the tag.

Going to report this with the Ntfy repo now

**Comment by spantaleev** [comment]
It should be fixed now
