### ISSUE TITLE
Setup fails on Raspbian

### ISSUE THREAD

**Issue by emiliogon** [spantaleev/matrix-docker-ansible-deploy#301]
Setup fails at the step "Generate initial Synapse config and signing key" with an "exec format error".  This appears to be an architecture mismatch when attempting to launch the actual Synapse docker image.  This is on Raspbian 10.

Here is the full error:
`TASK [matrix-synapse : Generate initial Synapse config and signing key] ************************************************
fatal: [matrix.neurostyle.net]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=991:991", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=991", "-e", "GID=991", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=matrix.neurostyle.net", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.5.1", "generate"], "delta": "0:00:39.109225", "end": "2019-11-08 06:33:39.780808", "msg": "non-zero return code", "rc": 1, "start": "2019-11-08 06:33:00.671583", "stderr": "standard_init_linux.go:211: exec user process caused \"exec format error\"", "stderr_lines": ["standard_init_linux.go:211: exec user process caused \"exec format error\""], "stdout": "", "stdout_lines": []}`

Thank you for assembling this playbook!  I hope I can get it to work.

**Comment by aaronraimist** [comment]
No it isn’t supported. See https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/299#issuecomment-551066402 for something you could try.

**Comment by emiliogon** [comment]
Aha, thank you; I didn't run across that issue before filing this.
