### ISSUE TITLE
 matrix-traefik missing acme.json

### ISSUE THREAD

**Issue by vengefulpunk** [spantaleev/matrix-docker-ansible-deploy#3026]
**Playbook Configuration**:
```
  GNU nano 6.2                                                                                                                                                          vars.yml                                                                                                                                                                    ---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: redacted

# The Matrix homeserver software to install.
# See:
#  - `roles/custom/matrix-base/defaults/main.yml` for valid options
# - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
matrix_homeserver_implementation: synapse

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_homeserver_generic_secret_key: 'redacted'

# By default, the playbook manages its own Traefik (https://doc.traefik.io/traefik/) reverse-proxy server.
# It will retrieve SSL certificates for you on-demand and forward requests to all other components.
# For alternatives, see `docs/configuring-playbook-own-webserver.md`.
matrix_playbook_reverse_proxy_type: playbook-managed-traefik

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
devture_traefik_config_certificatesResolvers_acme_email: redacted

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: 'redacted'

# By default, we configure Coturn's external IP address using the value specified for `ansible_host` in your `inventory/hosts` file.
# If this value is an external IP address, you can skip this section.
#
# If `ansible_host` is not the server's external IP address, you have 2 choices:
# 1. Uncomment the line below, to allow IP address auto-detection to happen (more on this below)
# 2. Uncomment and adjust the line below to specify an IP address manually
#
# By default, auto-detection will be attempted using the `https://ifconfig.co/json` API.
# Default values for this are specified in `matrix_coturn_turn_external_ip_address_auto_detection_*` variables in the Coturn role
# (see `roles/custom/matrix-coturn/defaults/main.yml`).
#
# If your server has multiple IP addresses, you may define them in another variable which allows a list of addresses.
# Example: `matrix_coturn_turn_external_ip_addresses: ['1.2.3.4', '4.5.6.7']`
#
# matrix_coturn_turn_external_ip_address: ''

```

**Matrix Server:**
 - OS: ubuntu 22.04
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
ansible [core 2.16.0]
  config file = /home/ansible/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

I am installing matrix and running ansible-playbook -i inventory/hosts setup.yml --tags=install-all,ensure-matrix-users-created,start when I receive the error below

failed: [redacted] (item={'name': 'matrix-coturn.service', 'priority': 4000, 'groups': ['matrix', 'coturn']}) => changed=false
  ansible_loop_var: item
  item:
    groups:
    - matrix
    - coturn
    name: matrix-coturn.service
    priority: 4000
  msg: |-
    Unable to start service matrix-coturn.service: A dependency job for matrix-coturn.service failed. See 'journalctl -xe' for details.

from journalctl

Dec 06 18:56:07 emerald matrix-traefik-certs-dumper[96288]: /in/acme.json is missing.. Waiting (2331/inf.)

With this being a default traefik setup, I am not sure what, if anything, I should modify for this.

**Comment by vengefulpunk** [comment]
My apologies for the poor formatting. I can't edit it to fix that.

**Comment by aaronraimist** [comment]
@vengefulpunk You can edit it to fix the formatting.

1. Click on this button: <img width="1046" alt="screenshot" src="https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/5855073/0d129bdd-4dfb-420c-8bc1-db4c83220f2e">
1. Click Edit.
1. Add three backticks (```) on their own line before the start of the `vars.yml` contents
2. Add three more on their own line after the end of the `vars.yml` contents.

**Comment by vengefulpunk** [comment]
I fixed it, the container just needed a bit more memory
