### ISSUE TITLE
Vector-im is now Element-hq

### ISSUE THREAD

**Issue by pm-McFly** [spantaleev/matrix-docker-ansible-deploy#3043]
**Describe the bug**
Some components are now unable to be downloaded (e.g. hydrogen-web) due to the recent moving of the vector-im repos.

Please refer to:
https://www.linkedin.com/posts/element-hq_element-activity-7140455403569537024-1dDe?utm_source=share&utm_medium=member_desktop

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_client_hydrogen_enabled: true
```

**Expected behavior**
"Working as usual."
Unfortunately, during the migration, some links got broken - therefore some adaptations are needed on this side.

**Matrix Server:**
N/a

**Ansible:**
N/a

**Client:**
N/a

**Additional context**
A PR. for the hydrogen-web is on the way.
Help needed for the other components :)

**Comment by spantaleev** [comment]
Seems like we're still pulling Element from `vectorim/element-web` on Docker Hub (see `roles/custom/matrix-client-element/defaults/main.yml`), but it doesn't seem like it's mirrored elsewhere yet.. Or at least, I can't find it.

So I guess it continues to live at the same place and we can close this. Perhaps they'll announce an alternate location with the next element-web release and we can switch.
