### ISSUE TITLE
Mautrix-Signal Bridge broken

### ISSUE THREAD

**Issue by whowantsmybigdata** [spantaleev/matrix-docker-ansible-deploy#3054]
As described [here](https://github.com/mautrix/signal/issues/388) using `v0.4.3` (as used by the playbook) will not let new signal-bridge-users link a device.
Upstream advice is to use main branch which would be `:latest` but when I put `matrix_mautrix_signal_version: latest` in my vars.yml (same as I put it directly in the `.../defaults/main.yml` of the mautrix-signal-role) I get this error when starting the `matrix-mautrix-signal.service`:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python3": executable file not found in $PATH: unknown.`

I use arm64 with the latest system-, docker- and playbook updates.

**Comment by ThellraAK** [comment]
Tulir's git repo is not spantaleev's repo.

The default value is

`matrix_mautrix_signal_docker_repo: "https://mau.dev/mautrix/signal.git"`

If you want to use the mainline version, I'd suspect that's where you would set it from.

**Comment by whowantsmybigdata** [comment]
thanks a lot, different git repo makes sense

regarding the #3041: my problem was that I was logged out/thrown out automatically (couldnt figure out why till now) and now I can't log in again because of [this](https://github.com/mautrix/signal/issues/388)

could you maybe point out (a bit more newbie style) what I should change to use the mainline version (to be able to login again) or if the login issue is solved in the go-version how to update

would be very thankful

**Comment by whowantsmybigdata** [comment]
thanks a lot, different git repo makes sense.

I tried setting it to 
```
matrix_mautrix_signal_docker_repo: "https://github.com/mautrix/signal.git"
matrix_mautrix_signal_docker_repo_version: "{{ 'main' if matrix_mautrix_signal_version == 'latest' else matrix_mautrix_signal_version }}"
matrix_mautrix_signal_docker_src_files_path: "{{ matrix_base_data_path }}/mautrix-signal/docker-src"

# renovate: datasource=docker depName=dock.mau.dev/mautrix/signal
matrix_mautrix_signal_version: latest
# renovate: datasource=docker depName=signald/signald
matrix_mautrix_signal_daemon_version: 0.23.2
```
but it didnt work (same error as before)

regarding the #3041: my problem was that I was logged out/thrown out automatically (couldnt figure out why till now) and now I can't log in again because of [this](https://github.com/mautrix/signal/issues/388)

could you maybe please point out (a bit more newbie style) what I could try to change to use the mainline version (to be able to login again) or if the login issue is solved in the go-version and if so how to apply the update you commited?

**Comment by whowantsmybigdata** [comment]
sorry, quite this late reaction: such great news - thanks a lot @pm-McFly for contributing and also for the extra info!
The bridge works flawlessly again with no extra fiddling needed but the re-linking...
