### ISSUE TITLE
Matrix Room "does not exist"

### ISSUE THREAD

**Issue by gitayam** [spantaleev/matrix-docker-ansible-deploy#3072]
[#matrix-docker-ansible-deploy:devture.com](https://matrix.to/#/#matrix-docker-ansible-deploy:devture.com)

This room doesn't seem to exist for me. Can anyone confirm or help ?

Using federated self hosted server

**Comment by spantaleev** [comment]
Perhaps your server does not federate properly. Try the [Matrix Federation Tester](https://federationtester.matrix.org/) and input the base domain there (e.g. `example.com`, not `matrix.example.com`).

**Comment by gitayam** [comment]
Ok, Must be cloudflare blocking certain countries.
