### ISSUE TITLE
WeChat bridge

### ISSUE THREAD

**Issue by Korben57** [spantaleev/matrix-docker-ansible-deploy#3092]
**Is your feature request related to a problem? Please describe.**
Just looking for a built in WeChat bridge 

**Describe the solution you'd like**
A built in WeChat bridge that is as easy to deploy as all other bridges

**Describe alternatives you've considered**
There is an Alpha WeChat bridge built off Mautrix-Go (I assume by the Beeper team)

https://github.com/duo/matrix-wechat

**Comment by tobiasdiez** [comment]
Could you give https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3241 a try?
