### ISSUE TITLE
Rcently getting in element desktop - Your Server is unsupported - Update to V1.5

### ISSUE THREAD

**Issue by Joshndroid** [spantaleev/matrix-docker-ansible-deploy#3113]
I have been using the ansible for a significant period of time and it has been working fantastic... updates here and essentially forget about it.

Recently I have been seeing in the element desktop app (Windows) this warning message (Everything seems to be working okay)

```
Your server is unsupported
This server is using an older version of Matrix. Upgrade to Matrix v1.5 to use Element without errors.
```

I ran an update figuring it would fix it however I still seem to see this error.
On checking here in the github issues section I can't seem to find anything relating to my issue.

I assume I have either need to run a specific command or fix up an entry somewhere.

Anyone got any tips on how to get rid of this error?

Cheers

Ubuntu desktop install.
Ansible playbook
Proxy as configured within playbook

**Comment by spantaleev** [comment]
Try visiting `https://matrix.DOMAIN/_matrix/client/versions` in a browser (or hit it via `curl`) and see if the `versions` list contains `v1.5`.

If you're up to date, the versions list should look like this right now:

```json
["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0","r0.6.1","v1.1","v1.2","v1.3","v1.4","v1.5","v1.6","v1.7","v1.8","v1.9"]
```

If that's what you see, then you're up-to-date indeed. You may also verify that by SSH-ing into the server and running `docker ps | grep matrix-synapse` - you should see it running `v1.99.0` of the container image.

You may also try other clients and see if they work correctly.

Finally, you may check if element-desktop has an update you need to do. If you're up-to-date and everything works fine in other clients, consider reporting an issue to [their repository](https://github.com/element-hq/element-web).

**Comment by spantaleev** [comment]
You're missing `just roles` (or `make roles`), so you're not installing various dependency Ansible roles that this playbook uses.

You may also have some other issues with your `git pull` though, because.. not installing roles would meant that the `setup-all` command should yell at you (failing to find the dependency roles). If `setup-all` completes successfully despite you not installing the roles, then you're on some very old playbook code.

You can confirm where you are by running some commands:
- `git branch`
- `git log`

**Comment by Joshndroid** [comment]
I was on some VERY old playbook code...
nothing was erroring so I had no idea.
I have managed to git pull and get myself up to speed and installed just.
I will close this as I got a few bits of help in the matrix chat group for your project (possibly from you as well).
