### ISSUE TITLE
Removal of NGINX breaks Matrix User Verfication Service functionality

### ISSUE THREAD

**Issue by crapo9000** [spantaleev/matrix-docker-ansible-deploy#3127]
Hello everyone,

the latest changes to the reverse proxy setup of the playbook (removal of NGINX) breaks the functionality of the Matrix User Verification Service in Jitsi calls. From what I've checked so far the issue could be related to the docker network changes. Maybe someone else has already solved the problem and could share their solution.

**Comment by gnouts** [comment]
I'm also experiencing issue with all 3rdparty services, namely : 
- matrix-media-repo, because I had `devture_traefik_config_entrypoint_web_secure_enabled: false` as I'm using my own Caddy as a proxy. I switched to `true` and told caddy to ignore tls errors while proxying. It's more a hack than a fix. And the default config still point to `http://matrix-synapse:8008` which works but I thought it was supposed to steal path on Traefik.
- hookshot
- all mautrix bridges

I haven't investigate the last two. Let me know if more logs are needed and/or if I should create dedicated issues for each.

**Comment by WowSuchRicky** [comment]
I am having the same issue as @gnouts. As you pointed out, almost certainly related to https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/8dadcee4bc9ad87c9c2301ccd4484c5899da2756.

**Comment by venimus** [comment]
> * matrix-media-repo, because I had `devture_traefik_config_entrypoint_web_secure_enabled: false` as I'm using my own Caddy as a proxy. I switched to `true` and told caddy to ignore tls errors while proxying. It's more a hack than a fix. And the default config of media-repo still point to `http://matrix-synapse:8008` which works (but breaks media for bridges)  but I thought it was supposed to steal path on Traefik.

I also have issues with Caddy as proxy  + 'web_secure: false' (I want ssl from Caddy):

Fixed my issues (lots of "invalid entrypoints") with
```
matrix_media_repo_container_labels_traefik_media_entrypoints: "web"
matrix_media_repo_container_labels_traefik_logout_entrypoints: "web"
matrix_media_repo_container_labels_traefik_admin_entrypoints: "web"
matrix_media_repo_container_labels_traefik_t2bot_entrypoints: "web"
```

However registration stopped working
```
# identity server / email login and other
matrix_ma1sd_enabled: true
matrix_ma1sd_verbose_logging: true
#this actually have to be set in the jinja template homeserver.yaml.j2 because there is no var exposed for it
disable_msisdn_registration: true
matrix_synapse_registrations_require_3pid: ['email']
```

**Comment by crapo9000** [comment]
I've played around a bit and found out, that the federation api returns a "404 page not found" error on accessing this URL: https://matrix.domain:8448/_matrix/federation/v1/openid/userinfo?access_token=redacted. (This is what UVS is doing, to check the validity of an access token on joining a jitsi call)

In a working environment (before NGINX removal) there should be a response like "{"errcode":"M_UNKNOWN_TOKEN","error":"Access Token unknown or expired"}"

@spantaleev Have there been any changes regarding the federation API since switch to the traefik only setup?

**Comment by spantaleev** [comment]
Is your server federating? If you're getting "not found", it may be that it's not and that `/_matrix/federation` is not being handled.

For my server, I can see the `{"errcode":"M_UNKNOWN_TOKEN","error":"Access Token unknown or expired"}` response when calling this URL from outside.

If UVS is doing it from a container, there may be some routing issue, so testing it from the outside is a good first step.

If your server is not federating, then that API may still be made available. We supposedly have this variable override which takes care of it (and even takes UVS into account): https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/8a9a700cfca59ee1c9be528960d64c3d222b2cfc/group_vars/matrix_servers#L3948

**Comment by crapo9000** [comment]
> Is your server federating? If you're getting "not found", it may be that it's not and that /_matrix/federation is not being handled.

No, I have explicitly deactivated federation in both instances. (dev -> traefik only  + prod-> with NGINX) 

The variable
 
`matrix_synapse_federation_port_openid_resource_required: "{{ not matrix_synapse_federation_enabled and (matrix_dimension_enabled or matrix_ma1sd_enabled or matrix_user_verification_service_enabled) }}"` 

is  doing what it should and makes the openid available as far as i can tell. But the path `/_matrix/federation/openid` seems not to be handled in the traefik only environment.(at least in my setup) From my understanding matrix-synapse-reverse-proxy-companion was handling these requests before. So is it possible that there are missing configs at the traefik side?
