### ISSUE TITLE
Example to front playbook managed traefik with nginx probably needs an update

### ISSUE THREAD

**Issue by ddogfoodd** [spantaleev/matrix-docker-ansible-deploy#3132]
A while ago I switched to fronting the playbook managed traefik with a nginx reverse-proxy. I also contributed my nginx configuration to the [examples reverse-proxies directory](https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/examples/reverse-proxies/nginx).
I am not too sure, but I think the recent changes to the playbook managed traefik broke something (seemingly federation).
So the example config might need an update to work properly, assuming this is where the error originates from...

**Here is what happened:**
`devture_traefik_additional_entrypoints_auto` was deprecated and the doc for [Fronting the integrated reverse-proxy webserver with another reverse-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#fronting-the-integrated-reverse-proxy-webserver-with-another-reverse-proxy) was updated.

I followed the changelog and the [Fronting the integrated reverse-proxy webserver with another reverse-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#fronting-the-integrated-reverse-proxy-webserver-with-another-reverse-proxy) steps to adjust to the new variables in `vars.yml`.

**Now the federationtester returns the following error:**
`Get "https://[xxxx:xxx:xxxx:xxx::x]:8448/_matrix/key/v2/server": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

Existing rooms seem to work, but I cannot join new rooms. This and the port in the federationtester error make me think the federation broke...

**I have an idea where the problem might originate from but I probably need some help solving it:**
The last two paragraphs in the [Fronting the integrated reverse-proxy webserver with another reverse-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#fronting-the-integrated-reverse-proxy-webserver-with-another-reverse-proxy) doc state:
> It's important that these webservers proxy-pass requests to the correct place and also set the `Host` HTTP header appropriately. If you don't pass the `Host` header correctly, you would get a 404 not found error from Traefik.
> 
> To put it another way, curl `http://127.0.0.1:81` would give you a 404, but `curl -H 'Host: matrix.DOMAIN' http://127.0.0.1:81` should work.

If I don't misunderstand, `curl http://127.0.0.1:81` should **not** return `404 page not found`.
However, it does on my side, whereas `curl -H 'Host: matrix.DOMAIN' http://127.0.0.1:81` returns `Found`.

So there might be something wrong with the `Host` header in the [example nginx config](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/examples/reverse-proxies/nginx/matrix.conf)...
However I don't know what the issue is, it also looks quite similar to the recently added [nginx proxy manager config](https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/examples/reverse-proxies/nginx-proxy-manager) which I assume to work.

Any hint or help is appreciated, and I will update the example nginx configuration accordingly after this is resolved.

**Comment by spantaleev** [comment]
> If I don't misunderstand, curl http://127.0.0.1:81 should not return 404 page not found.
> However, it does on my side, whereas curl -H 'Host: matrix.DOMAIN' http://127.0.0.1:81 returns Found.

You're saing exactly the opposite of what our documentation page says.

Hitting `127.0.0.1:81` without a proper `Host` header is supposed to return 404 not found. It only works if you send a proper `Host` header.

-----

Federation tester is testing everything and currently choking on the federation port (`8448`). Are you sure your own reverse-proxy is handling this port? It's supposed to `proxy_pass` this federation traffic (coming on port `8448`) to `127.0.0.1:8449`, not to `127.0.0.1:81`.

`127.0.0.1:81` is for Matrix Client-Server traffic and other (regular) web requests for the other services (`element.DOMAIN`, etc).

I suggest that you check whether `https://matrix.DOMAIN:8448` works for you and to adjust things until it does.
You may also run the playbook's `self-check` (`just run-tags self-check`).

**Comment by jalemann** [comment]
Thanks for the clarification, I did misunderstand it.
Should `curl -H 'Host: matrix.DOMAIN' http://127.0.0.1:8449` also return `Found` then?

Ah yes, `https://matrix.DOMAIN:8448` returns 404 at the moment, even though it seems to be set in my nginx conf (matrix.DOMAIN:8448 forwarded to localhost:8449).
I will review my nginx and playbook configs.

The self-check returns no errors.

**Comment by jalemann** [comment]
Oh wow, turns out I just needed to reboot.
Maybe something went wrong when trying out the new specialized workers and disabling them again.
If someone runs into the same issue, just reboot. Nginx config in examples should continue to work when fronting the playbook traefik.
