### ISSUE TITLE
mautrix/facebook deprecated in favor of mautrix/meta

### ISSUE THREAD

**Issue by WowSuchRicky** [spantaleev/matrix-docker-ansible-deploy#3138]
**Is your feature request related to a problem? Please describe.**

Per https://github.com/mautrix/facebook/issues/332, the mautrix/facebook bridge is being deprecated soon and likely not receiving further updates in favor of mautrix/meta. 

**Describe the solution you'd like**
This project should integrate the new bridge in. It seems that there are no current plans to create a migration path, but there is a path described to clean existing rooms before moving to the new bridge. 

**Describe alternatives you've considered**
Add a notice that the facebook bridge is deprecated and that folks should use it with caution, especially as it diverges from being up to date and working.

**Comment by ppkhoa** [comment]
mautrix/meta merges Instagram and Facebook bridge as well. Need 2 instances if both are needed. Configuration looks similar to current mautrix/facebook bridge, seems like only minor changes needed for the playbook.

**Comment by Devenda** [comment]
mautrix/facebook looks like it might not be supporting the new E2EE forced by Meta for some messenger chats.
However currently mautrix/meta does seem to support the new E2EE (https://github.com/mautrix/meta/pull/10) making support (even if it's still in beta) important for most users being forced to E2EE.
