### ISSUE TITLE
role galaxy/playbook_help not found

### ISSUE THREAD

**Issue by mrtuxa** [spantaleev/matrix-docker-ansible-deploy#3139]
  mrtuxa   ~/deployment/matrix-docker-ansible-deploy git-[ master]-  ansible-playbook -i inventory/hosts setup.yml --tags=setup-all
ERROR! the role 'galaxy/playbook_help' was not found in /home/mrtuxa/deployment/matrix-docker-ansible-deploy/roles:/home/mrtuxa/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/mrtuxa/deployment/matrix-docker-ansible-deploy

The error appears to be in '/home/mrtuxa/deployment/matrix-docker-ansible-deploy/setup.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Most of the roles below are not distributed with the playbook, but downloaded separately using `ansible-galaxy` via the `just roles` command (see `justfile`).
    - role: galaxy/playbook_help
      ^ here

**Comment by mitexleo** [comment]
What's the solution to this problem?

**Comment by spantaleev** [comment]
Running `just roles` or `make roles` to install the additional Ansible roles that this Ansible playbook depends on. These roles are described in the `requirements.yml` file.

The `just roles` (or `make roles`) step is mentioned at the top of the [Installation documentation page](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/installing.md).

For running `just`, you will need to install the tool. It's documented on the [Prerequisites documentation page](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/prerequisites.md). Alternatively, one can also use `make` (and install the `make` tool).
