### ISSUE TITLE
How to setup default custom themes?

### ISSUE THREAD

**Issue by ZelChief** [spantaleev/matrix-docker-ansible-deploy#3151]
**Playbook Configuration**:

In my `vars.yml` I added next strings:

```yaml
matrix_client_element_themes_enabled: true
matrix_client_element_setting_defaults_custom_themes: [Discord Black]
```

`Discord Black` is the name from file `matrix-client-element/files/scratchpad/themes/Discord/Discord-Black/Discord-Black-Theme.json`

And in web interface appeared a log list of themes:

<img width="1050" alt="Снимок экрана 2024-02-03 в 00 31 40" src="https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/5526126/e939c60d-c6ae-4717-9d13-1d49d95167b3">

But default theme is not `Discord Black`.

**Problem**:
How to setup defaults custom theme?

**Comment by austinhuang0131** [comment]
```yaml
matrix_client_element_default_theme: "Discord Dark"
```
i think

**Comment by ZelChief** [comment]
Nope 😞  Default theme `Light` didn't change.

<img width="1050" alt="Снимок экрана 2024-02-03 в 12 51 56" src="https://github.com/spantaleev/matrix-docker-ansible-deploy/assets/5526126/cbb3f673-8dff-4359-b534-4d2529c4df95">

**Comment by gnouts** [comment]
@ZelChief What was your issue ? How did you solve it ? 😶

**Comment by snowping** [comment]
@gnouts little late but I just used that feature myself now. You need to prefix the default theme setting with 'custom'. So for example `matrix_client_element_default_theme: "custom-Discord Dark"`
