### ISSUE TITLE
How to get a `Photoprism` container to be routed through `matrix-traefik`??

### ISSUE THREAD

**Issue by drelephant** [spantaleev/matrix-docker-ansible-deploy#3179]
I have a working `matrix-docker-ansible-deploy` setup on Ubuntu 20.04.6.

I'm running Photoprism via docker compose which I installed by [following this info](https://docs.photoprism.app/getting-started/docker-compose/) but it only worked on http.

I want to get it to run only on https and through `matrix-traefik`.

I saw [this info](https://docs.photoprism.app/getting-started/proxies/traefik/) on how to get Photoprism to go through traefik but not sure how to edit settings for matrix-traefik.

I saw [this comment](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3140#issuecomment-1936590831) from @elindgren which sort of described what I'm trying to do, so I edited my photoprism `docker-compose.yml`:
I changed
```
      PHOTOPRISM_SITE_URL: "http://myserver.org:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
```
to
```
      PHOTOPRISM_SITE_URL: "https://photos.myserver.org/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
```
and added (info from [here](https://www.photoprism.app/kb/https))
```
      PHOTOPRISM_DISABLE_TLS: "true" 
```
and under photoprism service:
```
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.photoprism.entrypoints=web-secure
      - traefik.http.routers.photoprism.service=photoprism
      - traefik.http.routers.photoprism.rule=Host(`photos.myserver.org`)
      - traefik.http.routers.photoprism.tls=true
      - traefik.http.routers.photoprism.tls.certResolver=default
      - traefik.http.routers.photoprism.tls.domains[0]=myserver.org
      - traefik.http.routers.photoprism.tls.domains[0].sans=photos
      - traefik.http.services.photoprism.loadbalancer.server.port=2342
    networks:
      - traefik
```
and at the end:
```
networks:
  traefik:
    external: true
```
And then ran `sudo docker compose up -d` to get it to restart the photoprism container.

But I get a "Bad Gateway" error when I try to go to https://photos.myserver.org

If I look at `matrix-client-element` container (which is working), by runing `sudo docker inspect matrix-client-element | grep traefik`:
```
                "traefik.docker.network": "traefik",
                "traefik.enable": "true",
                "traefik.http.middlewares.matrix-client-element-add-headers.headers.customresponseheaders.Content-Security-Policy": "frame-ancestors 'self'",
                "traefik.http.middlewares.matrix-client-element-add-headers.headers.customresponseheaders.Permission-Policy": "interest-cohort=()",
                "traefik.http.middlewares.matrix-client-element-add-headers.headers.customresponseheaders.Strict-Transport-Security": "max-age=31536000; includeSubDomains",
                "traefik.http.middlewares.matrix-client-element-add-headers.headers.customresponseheaders.X-Content-Type-Options": "nosniff",
                "traefik.http.middlewares.matrix-client-element-add-headers.headers.customresponseheaders.X-Frame-Options": "SAMEORIGIN",
                "traefik.http.middlewares.matrix-client-element-add-headers.headers.customresponseheaders.X-XSS-Protection": "1; mode=block",
                "traefik.http.routers.matrix-client-element.entrypoints": "web-secure",
                "traefik.http.routers.matrix-client-element.middlewares": "matrix-client-element-add-headers",
                "traefik.http.routers.matrix-client-element.rule": "Host(`element.myserver.org`)",
                "traefik.http.routers.matrix-client-element.service": "matrix-client-element",
                "traefik.http.routers.matrix-client-element.tls": "true",
                "traefik.http.routers.matrix-client-element.tls.certResolver": "default",
                "traefik.http.services.matrix-client-element.loadbalancer.server.port": "8080"
                "traefik": {
```
And run `sudo docker inspect photoprism-photoprism-1 | grep traefik`
```
                "traefik.docker.network": "traefik",
                "traefik.enable": "true",
                "traefik.http.routers.photoprism.entrypoints": "web-secure",
                "traefik.http.routers.photoprism.rule": "Host(`photos.myserver.org`)",
                "traefik.http.routers.photoprism.service": "photoprism",
                "traefik.http.routers.photoprism.tls": "true",
                "traefik.http.routers.photoprism.tls.certResolver": "default",
                "traefik.http.services.photoprism.loadbalancer.server.port": "2342"
                "traefik": {
```
So it looks the same to me except the middleware stuff.

Anyone know how I can get Photoprism to work with matrix-docker-ansible-deploy's traefik?

**Comment by drelephant** [comment]
I got it working, what was needed was to add:
```
    networks:
      - traefik
```
Under mariadb: service as well in the `docker-compose.yml`.

**Comment by tame47** [comment]
I set up a linuxserver.io nextcloud container on the matrix server on a wokring matrix ansible server.  I got the same error as you that I got the same "bad gateway" as yours.  I can find the nextcloud service in the traefik docker network.  Can you show me your full docker compose configuration file.  Much appreciated.

**Comment by drelephant** [comment]
Sorry about the late reply but here it is, had to rename it to txt.

[docker-compose_redacted.txt](https://github.com/user-attachments/files/17054016/docker-compose_redacted.txt)
