### ISSUE TITLE
Firebase Push Notification

### ISSUE THREAD

**Issue by mrtshoot** [spantaleev/matrix-docker-ansible-deploy#319]
how to use firebase push notification?

**Comment by spantaleev** [comment]
This doesn't seem related to the playbook. I don't know what you mean to do. It probably involves modifying [Synapse](https://github.com/matrix-org/synapse) configuration or [Sygnal](https://github.com/matrix-org/sygnal).

The playbook cannot currently install Sygnal for you. If you need it, you should install it separately or possibly add support for that in the playbook (pull requests are welcome!).

As for modifying Synapse configuration, the playbook has variables for certain things (see `roles/matrix-synapse/templates/synapse/homeserver.yaml.j2` and `roles/matrix-synapse/defaults/main.yml`). For every other thing you wish to change in the `homeserver.yaml` file, you can use the `matrix_synapse_configuration_extension_yaml` variable (read about it in `roles/matrix-synapse/defaults/main.yml`).
