### ISSUE TITLE
server_name vs domain_name

### ISSUE THREAD

**Issue by CybotTM** [spantaleev/matrix-docker-ansible-deploy#320]
Hi,

for the domain "netresearch.de" i have set up a matrix service at matrix.netresearch.de.
```
$ cat inventory/host_vars/matrix.netresearch.de/vars.yml
...
matrix_domain: netresearch.de
...
```

i have enabled the `.well-known`: https://matrix.netresearch.de/.well-known/matrix/server which points to matrix.netresearch.de - fine
and synapse server is reachable by :8448

But when looking at https://matrix.netresearch.de:8448/_matrix/key/v2/server/ i find `server_name` is "netresearch.de" - shouldn't this be "matrix.netresearch.de"?

When checking with https://federationtester.matrix.org/api/report?server_name=matrix.netresearch.de it also complains about mismatch in server name:

` "MatchingServerName": false,`

so it seems to me https://matrix.netresearch.de:8448/_matrix/key/v2/server/ `server_name` shows the domain name (netresearch.de), but instead should show the matrix server name (matrix.netresearch.de), or am i wrong?

btw. thanks for your work here!

**Comment by spantaleev** [comment]
The playbook makes some assumptions.

The base server name is `netresearch.de`, while services are actually installed at `matrix.netresearch.de`. To have that working, you're supposed to set up [Server Delegation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/howto-server-delegation.md). For our use case, it's easier to use the "well known" method for Server Delegation.

That is, the end result should be that https://netresearch.de/.well-known/matrix/server (note: this is on the base domain!) should be identical to the "template" file we set up at https://matrix.netresearch.de/.well-known/matrix/server . The **Server Delegation** documentation page suggests multiple ways you can do this.

The DNS SRV record that you currently have for `_matrix._tcp.netresearch.de` should be removed.

When using the Federation Tester, you should input your base domain (netresearch.de) and not your Matrix server's domain (matrix.netresearch.de).

**Comment by CybotTM** [comment]
okay, thank you, 

than i was just confused by *server name*  in `"server_name":"netresearch.de`.

So "server_name" is in fact the domain name - and not name of the server where synapse/matrix is running?

**Comment by spantaleev** [comment]
Indeed! I guess Synapse's configuration key (`server_name`) makes it confusing..

As for the signature, I'm guessing that it is for the base domain.. All rooms and user ids on your server are tied to the base domain, etc, and signed with that key.

**Comment by CybotTM** [comment]
Thank you very much.

I will close the ticket for now, as it seems to me now that providing https://netresearch.de/.well-known/matrix/server will solve my problem.

**Comment by CybotTM** [comment]
Just confirming: https://netresearch.de/.well-known/matrix/server did the trick.
