### ISSUE TITLE
Update SchildiChat to v1.11.36

### ISSUE THREAD

**Issue by luixxiul** [spantaleev/matrix-docker-ansible-deploy#3205]
**Is your feature request related to a problem? Please describe.**
SchildiChat was updated to `v1.11.36`. Please see: https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.36-sc.2

Since the release includes the security fix, the playbook should be updated as soon as possible, including documentation like described here: https://github.com/luixxiul/matrix-docker-ansible-deploy/commit/ba2e31c48d8bb408f558ea610e40f3da4c03094a

**Describe the solution you'd like**
We can just wait for https://gitlab.com/etke.cc/schildichat-web/container_registry to be updated, so that renovate will work as expected?

**Describe alternatives you've considered**

**Additional context**

**Comment by spantaleev** [comment]
An image for `v1.11.36-sc.2` is now available. I've pulled your patch. Thank you!

**Comment by luixxiul** [comment]
Still, please note `v1.11.36-sc.2` is not really usable as it consists errors, reported as here: https://github.com/SchildiChat/schildichat-desktop/issues/233, https://github.com/SchildiChat/schildichat-desktop/issues/234 …
