### ISSUE TITLE
please start and enable {{ matrix_static_files_identifier }}.service if matrix_static_files_container_labels_base_domain_enabled true

### ISSUE THREAD

**Issue by pcfe** [spantaleev/matrix-docker-ansible-deploy#3215]
**Describe the bug**
doing `setup-all` with HEAD at 7c1e5df3e79589c1288f2c5d0d8f406072866007 it would seem that while 

```yaml
"{{ devture_systemd_docker_base_systemd_path }}/{{ matrix_static_files_identifier }}.service"
```
gets deployed by `roles/custom/matrix-static-files`, it is neither started nor enabled.

**To Reproduce**

1. git pull (I tested with HEAD at 7c1e5df3e79589c1288f2c5d0d8f406072866007)
2. set up as per docs/configuring-playbook-base-domain-serving.md#serving-a-static-website-at-the-base-domain
3. set up as per option 2 of docs/configuring-well-known.md
4. `just roles`
5. `ANSIBLE_VAULT_PASSWORD_FILE=.vault_password.sh ansible-playbook --inventory ../[…]/matrix-docker-ansible-deploy-inventory setup.yml --tags=setup-all`

My `vars.yml` file looks like this:

```yaml
[…]
matrix_static_files_file_matrix_server_enabled: true
matrix_static_files_container_labels_base_domain_enabled: true
matrix_static_files_file_index_html_template: |
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
  <html lang="en">
    <head>
[…]
    </body>
  </html>

matrix_static_files_file_matrix_client_property_io_element_e2ee_secure_backup_required: true
matrix_static_files_file_matrix_client_property_io_element_e2ee_secure_backup_setup_methods: []
[…]
```

**Expected behavior**
base domain served, especially .well-known/… so that federation works

**Actual behavior**

1. server and client well-knowns generated
```bash
[root@matrix ~]# ls -l  /matrix/static-files/public/.well-known/matrix/
total 8
-rw-r--r--. 1 matrix matrix 466 Mar  7 19:42 client
-rw-r--r--. 1 matrix matrix  42 Mar  7 20:11 server
```
2. `/etc/systemd/system/matrix-static-files.service` generated
3. **but** `matrix-static-files.service` neither started nor enabled.

**Workaround**

```bash
systemctl status matrix-static-files.service
systemctl enable matrix-static-files.service
```

**Comment by spantaleev** [comment]
`setup-*` (and `install-*`) Ansible tags **do not** start and enable services. That's handled by the `start` tag.

This is well documented on `docs/installing.md`: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7c1e5df3e79589c1288f2c5d0d8f406072866007/docs/installing.md#L16-L24

If you're using [just](https://github.com/casey/just) and running commands via it (e.g. `just setup-all` or `just install-all`), it should be noted that these just recipe shortcuts do include the `start` tag within them.

**Comment by pcfe** [comment]
guess the error I experienced was a side effect of following docs/maintenance-upgrading-services.md
that instructs to `just setup-all`

while I grok why `setup-*` (and `install-*`) Ansible tags do not _start_ I was expecting them to _enable_
:shrug: nvm

**Comment by luixxiul** [comment]
> If you're using [just](https://github.com/casey/just) and running commands via it (e.g. `just setup-all` or `just install-all`), it should be noted that these just recipe shortcuts do include the `start` tag within them.

Does this mean that this description is not quite right?

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/22ef4aed3c75f1ef0febb867edf43f41d61f5754/docs/installing.md?plain=1#L32

**Comment by aine-etke** [comment]
Correct, it's not anymore. Previously, that was true (IIRC, when there was no justfile, only Makefile), but since then, it has been changed along the way.
