### ISSUE TITLE
wrong comment in 'example/hosts'

### ISSUE THREAD

**Issue by nuclear06** [spantaleev/matrix-docker-ansible-deploy#3237]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/a99b57943dbb3de56f0fd3df337cdbc113d496c0/examples/hosts#L6
According to the comments, should add  `become_password` to the host line. But it is wrong and Ansible cant receive password, according to the [Ansible documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#passwords-for-enable-mode) , it should be `ansible_become_password`

**Comment by spantaleev** [comment]
Fixed by [9c01d87](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/9c01d875f31a7da5244c975e209aac26c8b16972)
