### ISSUE TITLE
Option to make Riot Webclient available on matrix subdomain

### ISSUE THREAD

**Issue by Relypete** [spantaleev/matrix-docker-ansible-deploy#324]
Is there an option to make the Riot Webclient available on matrix.domain.org instead of riot.domain.org. Since the default "It works! Synapse is running" isn't really needed on the matrix subdomain, port 80/443 should theoretically be available to be used by Riot, right?

**Comment by aaronraimist** [comment]
Riot should never be run on the same domain as Synapse because it could allow for XSS attacks. https://github.com/vector-im/riot-web/issues/1977
