### ISSUE TITLE
Consider OpenTalk for video conferencing

### ISSUE THREAD

**Issue by bfabio** [spantaleev/matrix-docker-ansible-deploy#3242]
**Is your feature request related to a problem? Please describe.**
Support for OpenTalk.

**Describe the solution you'd like**
It would be nice if this playbook supported the installation of OpenTalk, which was opensourced last year (https://opentalk.eu/en/news/opentalk-now-open-source-under-eu-public-licence). I find it pretty user friendly.

**Additional context**
https://opentalk.eu/en
https://gitlab.opencode.de/opentalk

**Comment by spantaleev** [comment]
How is this related to Matrix? Are there Matrix solutions (widgets, etc.) that make it possible to seamlessly integrate OpenTalk into Matrix? I haven't heard of such things.

Right now, it seems like the Matrix ecosystem is ditching Jitsi and replacing it with Element Call. A bunch of clients already support Element Call and more are on the way to doing so.

**Comment by bfabio** [comment]
@spantaleev it was my understanding that this playbook installed extra components non directly related to Matrix, but still useful within the workflow of decentralized communication. Ignore this if it's out of scope.

A more integrated solution is even better, are you planning to support Element Call?

**Comment by spantaleev** [comment]
The Matrix playbook tries to only deal with Matrix-related services.

The sibling playbook ([mash-playbook](https://github.com/mother-of-all-self-hosting/mash-playbook)) deals with other (non-Matrix) services. For both playbooks, opening an issue just brings a particular service to the community's attention, but does not guarantee that someone will work on it. PRs are welcome!

As for Element Call, I will probably work on it some day, but it's not a high priority.. Someone may also beat me to it by sending a PR. It would involve creating Ansible roles both for the Element Call static websiteand for the LiveKit backend, so it's a bit more involved.
