### ISSUE TITLE
logging to SIEM

### ISSUE THREAD

**Issue by kosherpork** [spantaleev/matrix-docker-ansible-deploy#328]
i like to closely monitor the matrix server and related services. when i had a stand alone installation in the past it defaulted to rather verbose logs so i could map uris to actions (register, login, create channel, unencrypted channel communication, etc) and monitor for exceptions and investigate whether they were security incidents. this resulted in nice graylog dashboards. my new stack from ansible playbooks is much quieter and i can't get enough context to interpret log entries into user actions. 

is modifying /matrix/synapse/config/ all thats needed to improve logs for security monitoring or is there somewhere else? is it ok to make this change directly or will it be lost on upgrades via ansible? thank you.

**Comment by aaronraimist** [comment]
If you have questions, instead of opening issues please come to our Matrix room `#matrix-docker-ansible-deploy:devture.com`

**Comment by kosherpork** [comment]
my apologies. feel free to delete this.
