### ISSUE TITLE
Failed installation when using chrony

### ISSUE THREAD

**Issue by Hedgehog57** [spantaleev/matrix-docker-ansible-deploy#329]
Got an error installing on VM with chrony and ntp installed.
```
[ansible@matrix ~]$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

[ansible@matrix ~]$ rpm -qa|grep -E chrony\|ntp
ntpdate-4.2.6p5-29.el7.centos.x86_64
chrony-3.4-1.el7.x86_64
ntp-4.2.6p5-29.el7.centos.x86_64

[ansible@matrix matrix-docker-ansible-deploy]$ ansible-playbook -v ./setup.yml
```
```
TASK [matrix-base : Ensure Matrix group is created] **********************************************************************************************************************************************************************************
fatal: [matrix.doma.in]: FAILED! => {"changed": false, "msg": "groupadd: GID '991' already exists\n", "name": "matrix"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
```

**Comment by Hedgehog57** [comment]
Looks like I am not fully right. Maybe UID are assigned from 1000 to 1 for services without standart UID/GID. NTP has them and they are 38:38. That is a block from my /etc/group
```
input:x:999:
systemd-journal:x:190:
systemd-network:x:192:
dbus:x:81:
polkitd:x:998:
printadmin:x:997:
libstoragemgmt:x:996:
rpc:x:32:
cgred:x:995:
ssh_keys:x:994:
abrt:x:173:
gluster:x:993:
tss:x:59:
ntp:x:38:
sssd:x:992:
rpcuser:x:29:
nfsnobody:x:65534:
sshd:x:74:
slocate:x:21:
postdrop:x:90:
postfix:x:89:
chrony:x:991:
uuidd:x:990:
screen:x:84:
tcpdump:x:72:
zabbix:x:989:
dockerroot:x:988:
docker:x:987:
matrix:x:900:
```
post-installed after anaconda are
zabbix,docker and now - matrix. I have used 900:900 for my installation here.

**Comment by spantaleev** [comment]
You can overwrite the default user/group values like this in your `vars.yml` file:

```yaml
matrix_user_uid: 900
matrix_user_gid: 900
```

**Comment by Hedgehog57** [comment]
Thanks for a quick answer Slavi.

I already did it.
I have just write this issue if You need to know about this problem. ;)

If You think this is not a problem for most of users You can close this issue.

**Comment by spantaleev** [comment]
We haven't had reports about this. I guess it may happen that we get a similar conflict with various packages for the different distros we support. I'm not sure how we should handle it.

For now, it seems like the `991` default has worked well for most people, so let's stick to that and see what happens. If we get more reports like this, we should probably consider trying to pick a better uid/gid number or even let the system generate it during initial user/group creation.
