### ISSUE TITLE
Missing documentation on how to specify docker port mapping IPs (certbot/nginx)

### ISSUE THREAD

**Issue by digitalkram** [spantaleev/matrix-docker-ansible-deploy#330]
Hi

thank you for providing this convenient playbook to host a matrix server.
I installed it sucessfully on a dedicated host but now tried to migrate it to to another system to consolidate things.

I have multiple dedicated public IPv4s on the target host. On one of the IPs ports 80/443 are explicitly in use.

I thought I could just use another free IP for matrix. But it appears that the certbot container binds the docker port like this: `-p 80:8080` which is basically all IPs/interfaces just like `-p 0.0.0.0:80:8080` and I thought directions on how to make it bind to an IP explicitly using `-p x.y.z.a:80:8080` should be available here:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ssl-certificates.md

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-nginx.md

But there is no indication how to configure it. Any hint is appreciated!

I suspect the same might apply for the nginx container itself but I did not get so far yet.

Cheers.

**Comment by spantaleev** [comment]
We didn't have a way to control which IPs certbot binds to. It was always `0.0.0.0:80`.

You can use the new `matrix_ssl_lets_encrypt_container_standalone_http_host_bind_port` variable to make it use a specific IP address. Example:

```yaml
matrix_ssl_lets_encrypt_container_standalone_http_host_bind_port: "a.b.c.d:80"
```

There's 3 variables that do the same for `matrix-nginx-proxy`:
- `matrix_nginx_proxy_container_http_host_bind_port` (example value: `a.b.c.d:80`)
- `matrix_nginx_proxy_container_https_host_bind_port` (example value: `a.b.c.d:443`)
- `matrix_nginx_proxy_container_federation_host_bind_port` (example value: `a.b.c.d:8448`)

**Comment by spantaleev** [comment]
Thanks for bringing Coturn to my attention as well!

I've added 3 new variables:
- `matrix_coturn_container_stun_plain_host_bind_port` (example value: `a.b.c.d:3478`)
- `matrix_coturn_container_stun_tls_host_bind_port` (example value: `a.b.c.d:5349`)
- `matrix_coturn_container_turn_range_listen_interface` (example value: `a.b.c.d`) -- affects the whole TURN UDP port range (as defined by `matrix_coturn_turn_udp_min_port` and `matrix_coturn_turn_udp_max_port`)

**Comment by digitalkram** [comment]
Great, thank you! Works like a charm :-)
