### ISSUE TITLE
Leftover (failed) `matrix-ssl-nginx-proxy-reload.{service,timer}`

### ISSUE THREAD

**Issue by HarHarLinks** [spantaleev/matrix-docker-ansible-deploy#3307]
**Describe the bug**

I updated from a time where the playbook still used synapse 1.98 and nginx to 1.106 and traefik. systemctl shows a leftover (failed) `matrix-ssl-nginx-proxy-reload.service` and `.timer`.

**To Reproduce**
upgrade

**Expected behavior**
all traces of previous main nginx ingress automatically uninstall

**Matrix Server:**
 - OS: debian
 - Architecture amd64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- another machine, arch linux, pacman ansible
- 2.16.6

**Comment by HarHarLinks** [comment]
@spantaleev thanks for addressing this, what do I do to apply this? after running `--tags=setup-all,ensure-matrix-users-created,start`  these are still in
```
systemctl --failed
  UNIT                                  LOAD      ACTIVE SUB    DESCRIPTION
● matrix-ssl-nginx-proxy-reload.service not-found failed failed matrix-ssl-nginx-proxy-reload.service
● matrix-ssl-nginx-proxy-reload.timer   not-found failed failed matrix-ssl-nginx-proxy-reload.timer
```

**Comment by spantaleev** [comment]
If you're still not seeing these gone, then maybe you can try:

- `systemctl disable matrix-ssl-nginx-proxy-reload.{timer,service}` to ensure symlinks are gone
- `systemctl daemon-reload`, although this should be happening at least once during playbook run (via the `start` playbook tag)
- rebooting to start systemd cleanly and have it possibly forget these old services
