### ISSUE TITLE
Unhandled exception when running the playbook

### ISSUE THREAD

**Issue by z3ky** [spantaleev/matrix-docker-ansible-deploy#3366]
**Describe the bug**
Since about one week, I get this error when running the playbook to update matrix.
The last test was against commit 75f5a1d

```
fatal: [matrix.xxx]: FAILED! => 
  msg: |-
    The conditional check 'devture_systemd_service_manager_services_list_to_work_with | length > 0' failed. The error was: An unhandled exception occurred while templating '{{ devture_systemd_service_manager_services_list }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ devture_systemd_service_manager_services_list_auto + devture_systemd_service_manager_services_list_additional }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ devture_systemd_service_manager_services_list_auto + devture_systemd_service_manager_services_list_additional }}): can only concatenate str (not "list") to str
  
    The error appears to be in '/xxx/matrix-docker-ansible-deploy/roles/galaxy/systemd_service_manager/tasks/restart_specified.yml': line 3, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - when: devture_systemd_service_manager_services_list_to_work_with | length > 0
      ^ here
```

**Matrix Server:**
 - OS: [e.g. Ubuntu 20.04]
 - Architecture amd64

**Ansible:**
ansible --version
ansible [core 2.13.13]
  config file = /xxx/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

**Comment by spantaleev** [comment]
This is usually caused by old Ansible / Jinja. See `docs/ansible.md` for suggestions on how to update Ansible.

See https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3146
