### ISSUE TITLE
Integrate Cortex

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#337]
https://gitlab.com/matrix-cortex/cortex

**Comment by Cadair** [comment]
If we had support for workers in general, it would be easy enough to swap out what endpoints went to what containers, i.e. you could have a container for federation and use cortex over synapse. I think the bigger issue is generic worker support? #221

**Comment by aaronraimist** [comment]
At the moment this is unmaintained so closing for now
