### ISSUE TITLE
msg: 'Error pulling image docker.io/grafana/grafana:11.1.2 - 404 Client Error: Not Found ("manifest for grafana/grafana:11.1.2 not found: manifest unknown: manifest unknown")'

### ISSUE THREAD

**Issue by UehgxEQbFiw4Tlw8** [spantaleev/matrix-docker-ansible-deploy#3445]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
Paste your vars.yml file here.
Make sure to remove any secret values before posting your vars.yml file publicly.
```

**Matrix Server:**
 - OS: [e.g. Ubuntu 21.04]
 - Architecture [e.g. amd64, arm32, arm64]

**Ansible:**
If your problem appears to be with Ansible, tell us:
- where you run Ansible -- e.g. on the Matrix server itself; on another computer (which OS? distro? standard installation or containerized Ansible?)
- what version of Ansible you're running (see `ansible --version`)

**Problem description**:

Describe what you're doing, what you expect to happen and what happens instead here.
Tell us what you've tried and what you're aiming to achieve.

As it seems, there is no tag v11.1.2.0, causing the error message:

TASK [galaxy/grafana : Ensure Grafana image is pulled] ***************************************************************************************************************
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (10 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (9 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (8 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (7 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (6 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (5 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (4 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (3 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (2 retries left).
FAILED - RETRYING: [matrix.xxx.de]: Ensure Grafana image is pulled (1 retries left).
fatal: [matrix.xxx.de]: FAILED! => changed=false 
  attempts: 10
  msg: 'Error pulling image docker.io/grafana/grafana:11.1.2 - 404 Client Error: Not Found ("manifest for grafana/grafana:11.1.2 not found: manifest unknown: manifest unknown")'

PLAY RECAP ***********************************************************************************************************************************************************
matrix.xxx.de            : ok=286  changed=6    unreachable=0    failed=1    skipped=395  rescued=0    ignored=0

If I look at https://hub.docker.com/r/grafana/grafana/ 

go under "Tags" and I use the filter, I find only v.11.1.0 or v11.1.0-ubuntu for v11.1.*

Can you confirm the origin of the error with subsequent broken update process? Or docker image are pulled from another source?

Thank you!

Kind regards,
M.

P.S. This apparently does not affect your MASH, still having there v11.1.0 (see Versions.md)

**Client (please complete the following information):**

**Additional context**

**Comment by Keeberos** [comment]
msg: 'Error pulling image docker.io/grafana/grafana:11.1.2 - 404 Client Error for http+docker://localhost/v1.46/images/create?tag=11.1.2&fromImage=docker.io%2Fgrafana%2Fgrafana: Not Found ("manifest for grafana/grafana:11.1.2 not found: manifest unknown: manifest unknown")'

**Comment by UehgxEQbFiw4Tlw8** [comment]
The source being in requirements.yml placed at:

- src: git+https://gitlab.com/etke.cc/roles/grafana.git

This brings one to https://gitlab.com/etke.cc/roles/grafana/-/blob/main/defaults/main.yml

putting finally in my vars.yml the line

grafana_version: **11.1.0**

fixes the tag to a particular version (I thus downgraded again) and worked fine for me as a simple workaround, waiting for the next update through the usual way.

I think, it can be closed.

Thank you.

Best,
M.

**Comment by UehgxEQbFiw4Tlw8** [comment]
Hello again,

sorry for re-opening this, but same error as above today, but this time with v11.1.3:

fatal: [matrix.xxx.de]: FAILED! => changed=false 
  attempts: 10
  msg: 'Error pulling image docker.io/grafana/grafana:11.1.3 - 404 Client Error: Not Found ("manifest for grafana/grafana:11.1.3 not found: manifest unknown: manifest unknown")'

PLAY RECAP ******************************************************************************************************************************************************************************************************
matrix.xxx.de            : ok=293  changed=6    unreachable=0    failed=1    skipped=398  rescued=0    ignored=0   

Just for Info, I have already my workaround. 
Again, on docker hub, I can tag up to 11.1.1 (it is now there, if fixed in vars.yml it works fine) but not above this latter.

Roles are installed successfully, e.g.:

- extracting grafana to /home/massimo/matrix-docker-ansible-deploy/roles/galaxy/grafana
- grafana (v11.1.3-0) was installed successfully

It is just the pulling the docker image that goes empty. 

Thank you.

Kind regards,
M.
