### ISSUE TITLE
Telegram bridge.login_shared_secret being unset

### ISSUE THREAD

**Issue by paulbdavis** [spantaleev/matrix-docker-ansible-deploy#346]
Looking at the playbook, it seems that the value of `matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret` should be used for `matrix_mautrix_telegram_login_shared_secret` when it's set and `matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true` is specified.

When I run the playbook with `setup-all` I see that this is correctly set in the mautrix telegram config file.

However when I then run the playbook with `start` the line in the config is removed and the bridge starts up without automatic double puppeting

**Comment by paulbdavis** [comment]
Looking into it some more, it seems that the config gets overwritten every time the systemd service restarts.

I manually edited the file at `/matrix/mautrix-telegram/config/config.yaml` to include the shared secret and then restarted the systemd service. Right after the config file had reverted itself.

Making the volume read only spits out some errors in the bridge trying to update the config file, I'll look there to see why that's happening and removing that key

**Comment by paulbdavis** [comment]
Figured it out, the image in the playbook was at 0.6.x, this was added on 0.7.0

I'll get a PR in next week unless you want to grab it, testing it out now.

**Comment by spantaleev** [comment]
Ahh.. So starting the (old) bridge is what discarded configuration keys it didn't recognize. I was wondering how `--tags=start` could be corrupting the configuration, as it wasn't supposed to do anything like that.

It's a bit unfortunate to have the bridge touch the configuration file at all. I wonder if we have a way around this.

I've upgraded the playbook to 0.7.0. I'm assuming all is fine if you've been testing it for a few hours and haven't written back about a potential problem.

**Comment by paulbdavis** [comment]
Yeah, sorry, it was later when I wrote that. Everything seems to be fine using 0.7.0

**Comment by spantaleev** [comment]
Thanks for figuring it out!

**Comment by paulbdavis** [comment]
> It's a bit unfortunate to have the bridge touch the configuration file at all. I wonder if we have a way around this.

It doesn't seem so. From my reading it looks like it always loads the file at startup, parses the valid config keys and then rewrites the validated config back to the file.

**Comment by paulbdavis** [comment]
Sorry for continuing to add, but I only checked the telegram bridge for this, I did not check to see if the other mautrix bridges are on the correct image to support the new shared secret stuff.

**Comment by spantaleev** [comment]
That's a good reminder!

All the other Mautrix bridges use `:latest` for the Docker image (because there are no tagged releases for them.. or at least there weren't at the time it was done), so they should be fine.
