### ISSUE TITLE
FAILED! => {"changed": false, "msg": "Could not find the requested service docker: "}

### ISSUE THREAD

**Issue by DraneLixX** [spantaleev/matrix-docker-ansible-deploy#347]
Hi im trying to get the matrix-docker-ansible-deploy

Host System: Ubuntu 18.04 LTS
Ansible via Docker running on the Host System

> `docker` run -it --rm \
> -w /work \
> -v `pwd`:/work \
> --entrypoint=/bin/sh \
> devture/ansible:2.8.1-r0`

i do not use a SSH Key insted i use a password so i added sshpass and run the playbook command

> `ansible-playbook --ask-pass -i inventory/hosts setup.yml --tags=setup-all`

Afterwards i get an Error:

> /work # ansible-playbook --ask-pass -i inventory/hosts setup.yml --tags=setup-al
> l
> SSH password:
> 
> PLAY [Set up a Matrix server] **************************************************
> 
> TASK [Gathering Facts] *********************************************************
> ok: [matrix.cddt.net]
> 
> TASK [matrix-base : set_fact] **************************************************
> ok: [matrix.cddt.net]
> 
> TASK [matrix-base : Fail if running on Ansible < 2.5] **************************
> skipping: [matrix.cddt.net]
> 
> TASK [matrix-base : Fail if running on Ansible 2.5.x (lower than 2.5.2)] *******
> skipping: [matrix.cddt.net]
> 
> TASK [matrix-base : (Deprecation) Catch and report renamed settings] ***********
> skipping: [matrix.cddt.net] => (item={'old': 'host_specific_hostname_identity',                                                           'new': 'matrix_domain'})
> skipping: [matrix.cddt.net] => (item={'old': 'hostname_identity', 'new': 'matrix                                                          _domain'})
> skipping: [matrix.cddt.net] => (item={'old': 'hostname_matrix', 'new': 'matrix_s                                                          erver_fqn_matrix'})
> skipping: [matrix.cddt.net] => (item={'old': 'hostname_riot', 'new': 'matrix_ser                                                          ver_fqn_riot'})
> 
> TASK [matrix-base : Fail if required variables are undefined] ******************
> skipping: [matrix.cddt.net] => (item=matrix_domain)
> skipping: [matrix.cddt.net] => (item=matrix_server_fqn_matrix)
> skipping: [matrix.cddt.net] => (item=matrix_server_fqn_riot)
> 
> TASK [matrix-base : Fail if uppercase domain used] *****************************
> skipping: [matrix.cddt.net] => (item=cddt.net)
> skipping: [matrix.cddt.net] => (item=matrix.cddt.net)
> skipping: [matrix.cddt.net] => (item=riot.cddt.net)
> 
> TASK [matrix-base : Get rid of old files and directories] **********************
> ok: [matrix.cddt.net] => (item=/matrix/environment-variables)
> ok: [matrix.cddt.net] => (item=/matrix/scratchpad)
> 
> TASK [matrix-base : include_tasks] *********************************************
> skipping: [matrix.cddt.net]
> 
> TASK [matrix-base : include_tasks] *********************************************
> skipping: [matrix.cddt.net]
> 
> TASK [matrix-base : Ensure Docker is started and autoruns] *********************
> fatal: [matrix.cddt.net]: FAILED! => {"changed": false, "msg": "Could not find t                                                          he requested service docker: "}
> 
> PLAY RECAP *********************************************************************
> matrix.cddt.net            : ok=3    changed=0    unreachable=0    failed=1    s                                                          kipped=7    rescued=0    ignored=0

**Comment by spantaleev** [comment]
```
TASK [matrix-base : include_tasks] *********************************************
skipping: [matrix.cddt.net]

TASK [matrix-base : include_tasks] *********************************************
skipping: [matrix.cddt.net]
```

This part is worrisome. It has skipped both import tasks in [roles/matrix-base/tasks/server_base/setup.yml](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/72f6e56fb85cbfd5e6433223114633024a10f8ab/roles/matrix-base/tasks/server_base/setup.yml), indicating that the server OS was detected to be neither CentOS, nor some Debian-based distribution. Thus, important setup tasks were skipped and starting Docker later on fails.

We do support Ubuntu 18.04 for which `ansible_os_family` should be `'Debian'`, so it's strange to have such an error.

Would you run this: `ansible -i inventory/hosts -m setup 'matrix_servers' | grep -E 'ansible_os|ansible_distribution'` and let us know what you get.

**Comment by DraneLixX** [comment]
>  [WARNING]: Platform linux on host matrix.cddt.net is using the discovered
> Python interpreter at /usr/bin/python3.7, but future installation of another
> Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/
> reference_appendices/interpreter_discovery.html for more information.
>         "ansible_distribution": "Alpine",
>         "ansible_distribution_file_parsed": true,
>         "ansible_distribution_file_path": "/etc/alpine-release",
>         "ansible_distribution_file_variety": "Alpine",
>         "ansible_distribution_major_version": "3",
>         "ansible_distribution_release": "NA",
>         "ansible_distribution_version": "3.10.0",
>         "ansible_os_family": "Alpine",

**Comment by spantaleev** [comment]
It looks like you are trying to install to an Alpine Linux server.

I guess you're trying to target the local machine and have `ansible_connection=local` in your `inventory/hosts` file. Unfortunately, this cannot work when done from a container. Stop using a local connection if you'll be running Ansible from a container.. Alternatively, find a way to run Ansible outside of the container or in a container, but on some other machine (so that you won't need `ansible_connection=local` anymore).

**Comment by DraneLixX** [comment]
Now i get

> [WARNING]: Unhandled error in Python interpreter discovery for host matrix.cddt.net: Using a SSH
> password instead of a key is not possible because Host Key checking is enabled and sshpass does
> not support this.  Please add this host's fingerprint to your known_hosts file to manage this
> host.
> 
> fatal: [matrix.cddt.net]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}

i Have a self-hosted server at home running Ubuntu 18.04 LTS there i Installed Ansible thro `pip install ansible ` Normaly i fight me thro this questions but ansible is a completely new thing to me and i just wanna try out first the Matrix chat and mess with the mautrix-whatsapp brige

so the installation of Ansible was flawless and i configured the playbook again without `ansible_connection=local` insed i used the matrix.cddt.net as domain what is pointed on the host Server where the Matrix server should be installed i got the basic playbook config so i would start first barebone ah before i forget to mention about this i also installed ob both the server sshpass so i cloud use my ssh root password i also tryed the same in the docker ansible still not working same error.

**Comment by DraneLixX** [comment]
> Now i get
> 
> > [WARNING]: Unhandled error in Python interpreter discovery for host matrix.cddt.net: Using a SSH
> > password instead of a key is not possible because Host Key checking is enabled and sshpass does
> > not support this.  Please add this host's fingerprint to your known_hosts file to manage this
> > host.
> > fatal: [matrix.cddt.net]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}
> 
> i Have a self-hosted server at home running Ubuntu 18.04 LTS there i Installed Ansible thro `pip install ansible ` Normaly i fight me thro this questions but ansible is a completely new thing to me and i just wanna try out first the Matrix chat and mess with the mautrix-whatsapp brige
> 
> so the installation of Ansible was flawless and i configured the playbook again without `ansible_connection=local` insed i used the matrix.cddt.net as domain what is pointed on the host Server where the Matrix server should be installed i got the basic playbook config so i would start first barebone ah before i forget to mention about this i also installed ob both the server sshpass so i cloud use my ssh root password i also tryed the same in the docker ansible still not working same error.

**Comment by DraneLixX** [comment]
Never mind typed export ANSIBLE_HOST_KEY_CHECKING=False in the cli and now its doing its thing

**Comment by taymur1** [comment]
Hi spantaleev,

After running this command : 
ansible-playbook -i inventory/hosts setup.yml --tags=start

I got this output ....It seems there is something wring at the last..


PLAY [Set up a Matrix server] ***************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host matrix.omxecho.com should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using
 the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [matrix.omxecho.com]

TASK [matrix-base : set_fact] ***************************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-base : Fail if running on Ansible < 2.5] ***************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-base : Fail if running on Ansible 2.5.x (lower than 2.5.2)] ********************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-base : (Deprecation) Catch and report renamed settings] ************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com] => (item={u'new': u'matrix_domain', u'old': u'host_specific_hostname_identity'})
skipping: [matrix.omxecho.com] => (item={u'new': u'matrix_domain', u'old': u'hostname_identity'})
skipping: [matrix.omxecho.com] => (item={u'new': u'matrix_server_fqn_matrix', u'old': u'hostname_matrix'})
skipping: [matrix.omxecho.com] => (item={u'new': u'matrix_server_fqn_riot', u'old': u'hostname_riot'})

TASK [matrix-base : Fail if required variables are undefined] *******************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com] => (item=matrix_domain)
skipping: [matrix.omxecho.com] => (item=matrix_server_fqn_matrix)
skipping: [matrix.omxecho.com] => (item=matrix_server_fqn_riot)

TASK [matrix-base : Fail if uppercase domain used] ******************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com] => (item=omxecho.com)
skipping: [matrix.omxecho.com] => (item=matrix.omxecho.com)
skipping: [matrix.omxecho.com] => (item=riot.omxecho.com)

TASK [matrix-base : Fail if using python2 on Archlinux] *************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-base : Ensure Matrix group is created] *****************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-base : Set Matrix Group GID Variable] ******************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-base : Ensure Matrix user is created] ******************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-base : Set Matrix Group UID Variable] ******************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-mailer : set_fact] *************************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-postgres : set_fact] ***********************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-corporal : set_fact] ***********************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-discord : Fail if matrix-synapse role already executed] ******************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-discord : set_fact] ******************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-discord : set_fact] ******************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : Fail if matrix-synapse role already executed] ********************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : Fail if matrix-synapse role already executed] ********************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : Fail if matrix-nginx-proxy role already executed] ****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : Generate Matrix Appservice Slack proxying configuration for matrix-nginx-proxy] **********************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : Register Slack Appservice proxying configuration with matrix-nginx-proxy] ****************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-slack : Warn about reverse-proxying if matrix-nginx-proxy not used] ******************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : Fail if matrix-synapse role already executed] *****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : set_fact] *****************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : set_fact] *****************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : Fail if matrix-synapse role already executed] *****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : Fail if matrix-nginx-proxy role already executed] *************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : Generate Matrix Appservice webhooks proxying configuration for matrix-nginx-proxy] ****************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : Register webhooks Appservice proxying configuration with matrix-nginx-proxy] **********************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-webhooks : Warn about reverse-proxying if matrix-nginx-proxy not used] ***************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-irc : Fail if matrix-synapse role already executed] **********************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-irc : set_fact] **********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-appservice-irc : set_fact] **********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-facebook : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-facebook : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-facebook : Fail if running on Ansible lower than 2.8 and trying self building] **********************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : Fail if matrix-nginx-proxy role already executed] ****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : Generate Mautrix Hangouts proxying configuration for matrix-nginx-proxy] *****************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : Register Mautrix Hangouts proxying configuration with matrix-nginx-proxy] ****************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : Warn about reverse-proxying if matrix-nginx-proxy not used] ******************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-hangouts : Fail if running on Ansible lower than 2.8 and trying self building] **********************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-telegram : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-telegram : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-telegram : Fail if matrix-nginx-proxy role already executed] ****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-telegram : Generate Mautrix Telegram proxying configuration for matrix-nginx-proxy] *****************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-telegram : Register Mautrix Telegram proxying configuration with matrix-nginx-proxy] ****************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-telegram : Warn about reverse-proxying if matrix-nginx-proxy not used] ******************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-whatsapp : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mautrix-whatsapp : set_fact] ********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-skype : set_fact] *********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-skype : set_fact] *********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-skype : Fail if running on Ansible lower than 2.8 and trying self building] ***********************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : set_fact] *********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : set_fact] *********************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : Fail if matrix-nginx-proxy role already executed] *****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : Generate Matrix MX Puppet Slack proxying configuration for matrix-nginx-proxy] ************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : Register Slack Appservice proxying configuration with matrix-nginx-proxy] *****************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : Warn about reverse-proxying if matrix-nginx-proxy not used] *******************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-mx-puppet-slack : Fail if running on Ansible lower than 2.8 and trying self building] ***********************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-sms : Fail if matrix-synapse role already executed] *********************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-sms : set_fact] *********************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-bridge-sms : set_fact] *********************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-synapse : set_fact] ************************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-synapse : set_fact] ************************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-synapse : Fail if running on Ansible lower than 2.8 and trying self building] **************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-synapse : Mark matrix-synapse role as executed] ********************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-riot-web : set_fact] ***********************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-riot-web : Fail if running on Ansible lower than 2.8 and trying self building] *************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-jitsi : set_fact] **************************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-ma1sd : set_fact] **************************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-ma1sd : Fail if running on Ansible lower than 2.8 and trying self building] ****************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-dimension : set_fact] **********************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-email2matrix : set_fact] *******************************************************************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-nginx-proxy : set_fact] ********************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-nginx-proxy : Mark matrix-nginx-proxy role as executed] ************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-coturn : set_fact] *************************************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-coturn : Fail if running on Ansible lower than 2.8 and trying self building] ***************************************************************************************************************************************************
skipping: [matrix.omxecho.com]

TASK [matrix-common-after : Ensure systemd reloaded] ****************************************************************************************************************************************************************************************
ok: [matrix.omxecho.com]

TASK [matrix-common-after : Ensure Matrix services stopped] *********************************************************************************************************************************************************************************
failed: [matrix.omxecho.com] (item=matrix-mailer) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-mailer", "msg": "Could not find the requested service matrix-mailer: host"}
failed: [matrix.omxecho.com] (item=matrix-postgres) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-postgres", "msg": "Could not find the requested service matrix-postgres: host"}
failed: [matrix.omxecho.com] (item=matrix-synapse) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-synapse", "msg": "Could not find the requested service matrix-synapse: host"}
failed: [matrix.omxecho.com] (item=matrix-riot-web) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-riot-web", "msg": "Could not find the requested service matrix-riot-web: host"}
failed: [matrix.omxecho.com] (item=matrix-ma1sd) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-ma1sd", "msg": "Could not find the requested service matrix-ma1sd: host"}
failed: [matrix.omxecho.com] (item=matrix-nginx-proxy) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-nginx-proxy", "msg": "Could not find the requested service matrix-nginx-proxy: host"}
failed: [matrix.omxecho.com] (item=matrix-coturn) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-coturn", "msg": "Could not find the requested service matrix-coturn: host"}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
matrix.omxecho.com         : ok=16   changed=0    unreachable=0    failed=1    skipped=68   rescued=0    ignored=0

**Comment by spantaleev** [comment]
Are you sure you've ran the `--tags=setup-all` command to completion first?

Looks like these systemd services haven't been created, so it's failing when trying to start them.

You can try:

- running `--tags=setup-all` again, before running `--tags=start`
- executing `systemctl daemon-reload` on the server, to ensure systemd finds the new services (in case it didn't discover them during `--tags=setup-all` for some reason)
- try checking if there are any `matrix-*.service` files in `/etc/systemd/system/` on the server
