### ISSUE TITLE
Change root data folder

### ISSUE THREAD

**Issue by z3ky** [spantaleev/matrix-docker-ansible-deploy#3509]
Can the default data path /matrix be changed on the host system?

**Comment by spantaleev** [comment]
Yes: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/05b79057aa62450c8638831e8d4a4a33138f11b8/roles/custom/matrix-base/defaults/main.yml#L147

Such non-issue questions are better asked in our [support room](https://github.com/spantaleev/matrix-docker-ansible-deploy?tab=readme-ov-file#support).
