### ISSUE TITLE
heisenbridge media_path prefix wrong in traefik

### ISSUE THREAD

**Issue by Firefishy** [spantaleev/matrix-docker-ansible-deploy#3518]
I believe the following line is incorrectly set.

The following with defaults:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/8e5e92321415f4a49bb4a67fed773165a06fbf3b/roles/custom/matrix-bridge-heisenbridge/defaults/main.yml#L49
sets:
```
matrix_heisenbridge_container_labels_traefik_media_path_prefix = /heisenbridge/_heisenbridge/media
```

But heisenbridge still uses the default: /_heisenbridge/media/ url in irc communications which is then not picked up by traefik and routed to heisenbridge. Users on irc get a 404.

---

Simple fix it to set prefix / as follows, but I suspect there is a better fix:
```
matrix_heisenbridge_container_labels_traefik_path_prefix = /
```
This then correctly sets:
```
matrix_heisenbridge_container_labels_traefik_media_path_prefix: /_heisenbridge/media/
```
and then irc users get the correct media via the proxy instead of a 404.

---

@spantaleev Sorry this bug report is vauge. I am new to traefik
Cross reference with: https://github.com/hifi/heisenbridge/issues/294

**Comment by spantaleev** [comment]
Thanks for these pointers! It seems like I've gotten it working now and the path prefix is still configurable.
