### ISSUE TITLE
Add Mjolnir (moderation bot)

### ISSUE THREAD

**Issue by turt2live** [spantaleev/matrix-docker-ansible-deploy#353]
https://github.com/matrix-org/mjolnir is a moderation bot intended for use within individual communities. For those who spin up a homeserver for their community, Mjolnir would be a good fit.

This request is for the bot to be added, not the Synapse module (because that's complicated). Docker images are available on Docker Hub: https://hub.docker.com/r/matrixdotorg/mjolnir

**Comment by Cadair** [comment]
Would also be good to have the synapse module to handle invite spam on personal homesevers etc :smile:

**Comment by aaronraimist** [comment]
> not the Synapse module (because that's complicated) 

How complicated is it? We already have synapse_simple_antispam

**Comment by turt2live** [comment]
managing it can be troublesome, and it apparently doesn't even work right now.

**Comment by P-C-R** [comment]
+1

**Comment by funar** [comment]
> managing it can be troublesome, and it apparently doesn't even work right now.

Is this still the case?  I've been running it in a container alongside the playbook.  It seems to run well.  The only caveat being either requiring the bot to be a server admin, or added to the ```ratelimit_override``` table.  i.e.:

```insert into ratelimit_override values ( '@mjolnir:mymatrix.org', 0, 0 );```

**Comment by turt2live** [comment]
that was with respect to the synapse module.
