### ISSUE TITLE
Latest Commit has an error with Beeper Linkedin + more?

### ISSUE THREAD

**Issue by Handrail9** [spantaleev/matrix-docker-ansible-deploy#3541]
**Describe the bug**
EDIT: I removed LinekdIn Beeper from my vars.yaml, and then the error happened with Twitter Mautrix, which is the next bridge set up in my config file.
When I ran "git pull" and tried to update today I got this error
```
fatal: [my.server.tld]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'devture_systemd_docker_base_container_networks_driver_options' is undefined. 'devture_systemd_docker_base_container_networks_driver_options' is undefined
  
    The error appears to be in '/home/handrail9/matrix-docker-ansible-deploy/roles/custom/matrix-bridge-beeper-linkedin/tasks/setup_install.yml': line 86, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Ensure beeper-linkedin container network is created
      ^ here


```

**Expected behavior**
No error

**Additional context**
If this is somehow user error please let me know. I have been known to misunderstand errors and make issues that are user error because I didn't read an update correctly or overlooked something.

**Comment by spantaleev** [comment]
No typo. You need to run `just roles` / `make roles`.

**Comment by Handrail9** [comment]
> No typo. You need to run `just roles` / `make roles`.

Ah. Thank you, sorry for opening an issue for that. I can be a bit forgetful and stupid sometimes :sweat_smile:
