### ISSUE TITLE
State of KeyDB

### ISSUE THREAD

**Issue by azerbe** [spantaleev/matrix-docker-ansible-deploy#3544]
I was running into https://github.com/Snapchat/KeyDB/issues/802 and had problems to debug the issue, as I was not able to start that specific version (alpine_x86_64_v6.3.4) manually and it crashed without any log-output or other debugging information. Downgrading to 6.3.3 worked.

I then inspected the state of the container images and even the latest release (v6.3.4) is older then a year.  Is it documented why KeyDB was choosen as alternative for Redis? I understand the license implications and I am not too deeply invested into the topic, so I cant bring up alternatives, but I would still like to understand why KeyDB was choosen and if it is considered a stable part of this playbook.

If there is no clear answer, feel free to close this issue. It is primarily intended as a link to the above mentioned issue on the KeyDB repo.

**Comment by spantaleev** [comment]
There have been others (see https://github.com/mother-of-all-self-hosting/mash-playbook/issues/247) reporting that 6.3.4 does not run on some CPUs (missing some instructions). Downgrading to 6.3.3 resolves the issue.

KeyDB was chosen as a popular and fast alternative to Redis as the licensing change was happening. Later on, more options have appeared. If we were to choose now, we may have gone with [Valkey](https://valkey.io/). At some point, we may even switch to it. It will probably be closer to what Redis was doing and will be maintained better than KeyDB is.
