### ISSUE TITLE
Can't allow synapse admin with any servers anymore

### ISSUE THREAD

**Issue by HarHarLinks** [spantaleev/matrix-docker-ansible-deploy#3576]
I have configured

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ec5e379672e118edb2ecbf2e3ef20c5d71d31d0c/CHANGELOG.md?plain=1#L188-L191

This does not work anymore and instead leads to an empty selection box.

This might be a regression in the etkecc/synapse-admin (I hope! CC @aine-etke) or the docs/changelog need updating.

**Comment by aine-etke** [comment]
Cross-linking between issues helps a lot: https://github.com/etkecc/synapse-admin/issues/56

**Comment by aine-etke** [comment]
Fixed in https://github.com/etkecc/synapse-admin/commit/f5d6f24b30bbfa9370ab683d75274132e2fdb67a - will be available soon in `latest` docker image and admin.etke.cc (wait for CI)

Please, close this one

**Comment by HarHarLinks** [comment]
I did not see these as directly related, but regardless thanks for fixing both :)
