### ISSUE TITLE
Issues with hosting on IP

### ISSUE THREAD

**Issue by abmyii** [spantaleev/matrix-docker-ansible-deploy#363]
Firstly thanks for this amazing tool!

I intend to host matrix, but on an IP rather than a domain. It seems that `riot.<ip>` is not a valid URL, so I decided to improvise and instead have `<ip>/riot`. I added the following settings:

```
matrix_server_fqn_riot: "{{ matrix_domain }}/riot"
matrix_server_fqn_matrix: "{{ matrix_domain }}/matrix"
matrix_server_fqn_dimension: "{{ matrix_domain }}/dimension"
```

However that resulted in this error:
```
fatal: [matrix.localhost]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=991:991", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=991", "-e", "GID=991", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=127.0.0.1/matrix", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.9.0", "generate"], "delta": "0:00:03.222582", "end": "2020-01-25 15:42:10.338677", "msg": "non-zero return code", "rc": 1, "start": "2020-01-25 15:42:07.116095", "stderr": "Container running as UserID 991:991, ENV (or defaults) requests 991:991\nWill not perform chmod/su-exec as UserID already matches request\nCreating log config /data/127.0.0.1/matrix.log.config\nTraceback (most recent call last):\n  File \"/start.py\", line 259, in <module>\n    main(sys.argv, os.environ)\n  File \"/start.py\", line 201, in main\n    return run_generate_config(environ, ownership)\n  File \"/start.py\", line 150, in run_generate_config\n    convert(\"/conf/log.config\", log_config_file, environ)\n  File \"/start.py\", line 33, in convert\n    with open(dst, \"w\") as outfile:\nFileNotFoundError: [Errno 2] No such file or directory: '/data/127.0.0.1/matrix.log.config'", "stderr_lines": ["Container running as UserID 991:991, ENV (or defaults) requests 991:991", "Will not perform chmod/su-exec as UserID already matches request", "Creating log config /data/127.0.0.1/matrix.log.config", "Traceback (most recent call last):", "  File \"/start.py\", line 259, in <module>", "    main(sys.argv, os.environ)", "  File \"/start.py\", line 201, in main", "    return run_generate_config(environ, ownership)", "  File \"/start.py\", line 150, in run_generate_config", "    convert(\"/conf/log.config\", log_config_file, environ)", "  File \"/start.py\", line 33, in convert", "    with open(dst, \"w\") as outfile:", "FileNotFoundError: [Errno 2] No such file or directory: '/data/127.0.0.1/matrix.log.config'"], "stdout": "", "stdout_lines": []}                                                        
```

I also saw that you suggested a simple installation method (https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/241#issuecomment-520229493) which was to add these settings:

```
matrix_server_fqn_riot: "{{ matrix_domain }}"
matrix_server_fqn_matrix: "{{ matrix_domain }}"
matrix_server_fqn_dimension: "{{ matrix_domain }}"
```

This is actually more ideal for my use case, but when going to `https://127.0.0.1` (the domain) it simply shows:
```
Hello from 127.0.0.1! 
```

I would be very grateful if you could assist me with this.

**Comment by spantaleev** [comment]
That hello message is usually when you've asked the playbook to serve the base domain for you (`matrix_nginx_proxy_base_domain_serving_enabled: true`). Have you?

In any case, putting paths in any of `matrix_server_fqn_riot`, `matrix_server_fqn_matrix` and `matrix_server_fqn_dimension` will probably not work. We use those to retrieve certificates, etc.

There's probably at least a bunch of other variables to change to make it not choke on IP addresses. And even then, I'm not sure you can get it to work. The nginx proxy, at least, expects different domain names for domain-based virtual hosting.

--------

It might be worth trying to use some domain names (even [xip.io](http://xip.io/) ones). The playbook might even be able to retrieve certificates for them. In any case, you can also go with using self-signed certificates (`matrix_ssl_retrieval_method: self-signed`).

**Comment by abmyii** [comment]
Thank you for your swift response!

> That hello message is usually when you've asked the playbook to serve the base domain for you (matrix_nginx_proxy_base_domain_serving_enabled: true). Have you?

I did indeed!

> It might be worth trying to use some domain names (even xip.io ones). The playbook might even be able to retrieve certificates for them.

Really this all flies above my head and I haven't much time to research how to do it. Perhaps it will be time well-spent, however, so I will give it a look. Thank you for the tip!

> In any case, you can also go with using self-signed certificates (matrix_ssl_retrieval_method: self-signed).

I have already done so, and they work fine!

> There's probably at least a bunch of other variables to change to make it not choke on IP addresses. And even then, I'm not sure you can get it to work. The nginx proxy, at least, expects different domain names for domain-based virtual hosting.

I see. I guess it's nearly impossible to host on an IP then?

**Comment by abmyii** [comment]
I just tested without `matrix_nginx_proxy_base_domain_serving_enabled: true`; it worked, but `https://127.0.0.1/config.127.0.0.1.json?cachebuster=1579969097377` and `https://127.0.0.1/_matrix/client/versions` couldn't be found. Is this what you were referring to?

**Comment by abmyii** [comment]
With regards to xip, I believe you have to set `hosts` on each user's computer? If so then I will not be able to use it, as I cannot do so.

**Comment by spantaleev** [comment]
You can use xip.io without touching the `hosts` file on each computer. Well, I've never tried to setup a Matrix server with such a domain, but .. it might work.

**Comment by abmyii** [comment]
> You can use xip.io without touching the hosts file on each computer. Well, I've never tried to setup a Matrix server with such a domain, but .. it might work.

Do they have to all be in the same LAN?

**Comment by spantaleev** [comment]
Depends on what IP address you put inside the `xip` domain. If it's a local one, then yes, only computers on the LAN would be able to use it. If you use some external IP address, then that would be accessible through the domain name from everywhere.

**Comment by abmyii** [comment]
I see, thanks! I think I shall use `xip` and that should solve the problem. Thanks for your rapid and helpful replies!
