### ISSUE TITLE
MAS is incompatible with Registration bot

### ISSUE THREAD

**Issue by wjbeckett** [spantaleev/matrix-docker-ansible-deploy#3647]
**Describe the bug**
When migrating an existing home server to MAS with the registration bot enabled, the deployment fails when attempting to register the registration bot in MAS.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
# Registration bot
matrix_bot_matrix_registration_bot_enabled: false
matrix_bot_matrix_registration_bot_matrix_user_id_localpart: bot-registration
matrix_bot_matrix_registration_bot_bot_password: REDACTED
```

**Expected behavior**

**Additional context**
TASK [custom/matrix-user-creator : Ensure Matrix Authentication Service user registered - bot-registration] *******************************************************************************************************************
fatal: [matrix.REDACTED.org]: FAILED! => changed=false
  cmd:
  - /usr/bin/env
  - docker
  - exec
  - matrix-authentication-service
  - mas-cli
  - manage
  - register-user
  - -p
  - REDACTED
  - --yes
  - --ignore-password-complexity
  - --admin
  - bot-registration
  delta: '0:00:00.145382'
  end: '2024-10-21 06:17:35.725715'
  failed_when_result: true
  msg: non-zero return code
  rc: 1
  start: '2024-10-21 06:17:35.580333'
  stderr: |-
    2024-10-21T06:17:35.692715Z  WARN db.connect: sqlx_postgres::options::pgpass: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-postgres-0.8.1/src/options/pgpass.rs:46: Failed to open `.pgpass` file: Os { code: 2, kind: NotFound, message: "No such file or directory" } path=/.pgpass
    2024-10-21T06:17:35.711851Z ERROR homeserver.is_localpart_available{matrix.homeserver="REDACTED.org" matrix.localpart="bot-registration"}: mas_matrix_synapse: crates/matrix-synapse/src/lib.rs:216: error=Failed to query localpart availability from Synapse

    Caused by:
        request failed with status 401 Unauthorized: M_UNKNOWN_TOKEN: Invalid access token passed.
    Error: Failed to query localpart availability from Synapse

    Caused by:
        request failed with status 401 Unauthorized: M_UNKNOWN_TOKEN: Invalid access token passed.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by spantaleev** [comment]
Not sure why you closed this issue, but.. it made me think..

If you currently do `install-all` (or `setup-all`) to install MAS, the `matrix-user-creator` Ansible role will automatically try to prepare accounts for various bots used by the playbook.

If you're aiming to do a migration via syn2mas, you would have set `matrix_authentication_service_migration_in_progress: true` as per our instructions, but the `matrix-user-creator` role would still have created these users in the MAS database. If you later run `syn2mas`, you may run into a conflict.

I've made changes to improve the situation - automatic creation of user accounts in the MAS database via the `matrix-user-creator` role would be suppressed when MAS migration is in progress (`matrix_authentication_service_migration_in_progress: true`).

-----

I'm not sure if you were affected by this issue, but if you were and are still having troubles, you could:

- stop `matrix-authentication-service`: `systemctl stop matrix-authentication-service`
- use `/matrix/postgres/bin/cli` and run `DROP DATABASE matrix_authentication_service;` 
- run `install-all` (or `setup-all`) to reinstall
- after the initial MAS installation (which should now result in an empty user database for MAS), continue with the syn2mas migration process as described in `docs/configuring-playbook-matrix-authentication-service.md`
