### ISSUE TITLE
Unable to login to Synapse Admin when MAS is enabled

### ISSUE THREAD

**Issue by wjbeckett** [spantaleev/matrix-docker-ansible-deploy#3659]
**Describe the bug**
It seems like the user created in MAS does not get the "server admin" role even if they were created with admin=yes.
When attempting to login to Synapse Admin, the following error is presented.
`M_FORBIDDEN (403): You are not a server admin`

**Comment by MichaelSasser** [comment]
You probably need the [urn:synapse:admin:*](https://element-hq.github.io/matrix-authentication-service/reference/scopes.html#urnsynapseadmin) scope. One way of doing it would be through the database. There is a column `can_request_admin` in the table `"public"."users"`. If you set that to `t` (true) for the user you want to have access to the admin API, you should be able to use synapse admin again.

It should be something like: `UPDATE "public"."users" SET "can_request_admin" = 't' WHERE "user_id" = 'YOUR_UUID';`. 

I think the table also had a `username` column, which only contained the localpart. In theory, should also be `UNIQUE`. So, you should be able to do something like `UPDATE "public"."users" SET "can_request_admin" = 't' WHERE "username" = 'your_localpart';`.

**Comment by aine-etke** [comment]
Synapse Admin [does not work with MAS directly yet](https://github.com/etkecc/synapse-admin/issues/38), but (that's a different link) [there is a workaround with pre-generated access token](https://github.com/etkecc/synapse-admin/issues/55#issuecomment-2421562004)
