### ISSUE TITLE
matrix-riot-web doesn't start in LXD container

### ISSUE THREAD

**Issue by thugcee** [spantaleev/matrix-docker-ansible-deploy#369]
Host: Ubuntu 16.04.3 with LXD 3.0.3-0ubuntu1~16.04.1
Container: Ubuntu 18.04.3

This is probably caused by default security rules (I didn't changed anything there).

**Problematic configuration:**
In file `/etc/systemd/system/matrix-riot-web.service`, line

```
-v /dev/null:/etc/nginx/conf.d/default.conf:ro \
```

**Log message:**
```
matrix-riot-web[111159]: /usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/dev/null\\\" to rootfs \\\"/var/lib/
docker/vfs/dir/85f4c21f04c5a2a85c12586402f053bf7d472f5dccd84352aff3a8508f325e07\\\" at \\\"/var/lib/docker/vfs/dir/85f4c21f04c5a2a85c12586402f053bf7d472f5dccd84352aff3a8508f325e07/etc/nginx/conf.d/default.conf\\\" caused \\\"operation not permitted\\\"\"": unknown.
```

**Workaround:**

`touch /matrix/null` and change the problematic line to 

```
-v /matrix/null:/etc/nginx/conf.d/default.conf:ro \
```

**Comment by wangnangg** [comment]
I had the same problem. It turns out that my VM's memory is too small.

**Comment by spantaleev** [comment]
How is that related to LXD?

**Comment by stagprom** [comment]
LXD does not allow to mount devices,
so you have to use a fake file.
The workaround works.

**Comment by spantaleev** [comment]
We're no longer mounting `/dev/null` over other files, so this should be fixed now.
