### ISSUE TITLE
Add "Web" to Element and SchildiChat

### ISSUE THREAD

**Issue by luixxiul** [spantaleev/matrix-docker-ansible-deploy#3753]
**Is your feature request related to a problem? Please describe.**
When it comes to Element web client, I think it should be explicitly written as "Element Web", which ~~often~~ sometimes by the company's people is abbreviated as EW. Element Web is distinguished from Element X or Element Android, and without the description it can be confusing what "Element" means concretely, if your are not familiar with their terminology.

The same thing is applied to SchildiChat. SchildiChat Web/Desktop is distinguished from SchildiChat Android or SchildiNext (fork of Element X). This distinction matters as SchildiChat Web, not SchildiChat Android or SchildiNext, often lags from the upstream project, and we have the warning message about the lag on our documentation, while the possibility of confusion has been diminished as the warning message explicitly describes SchildiChat as "SchildiChat Web".

**Describe the solution you'd like**
Write Element as "Element Web", and SchildiChat as "SchildiChat Web", when they mean the web clients.

**Describe alternatives you've considered**

**Additional context**
I think this distinction does not exist for Hydrogen nor Cinny.

**Comment by spantaleev** [comment]
I do not remember seeing the EW abbreviation, but maybe I'm hanging out in the wrong circles.

I think you're right though - we'd better avoid referring to Element/SchildiChat as if they only have 1 product. We should be explicit and add a Web/Desktop suffix.

**Comment by luixxiul** [comment]
> I do not remember seeing the EW abbreviation

I remember I've seen it on a post in the room where clients devs coordinated, though I cannot pinpoint it…
