### ISSUE TITLE
Task "Execute Postgres managed database initialization SQL file for synapse" crashes my matrix server

### ISSUE THREAD

**Issue by ralfi** [spantaleev/matrix-docker-ansible-deploy#3769]
Hi all,

after just update for all and try to setup the play the task above runs in a timeout - i think so...

![Anmerkung 2024-11-14 074350](https://github.com/user-attachments/assets/a921d7b0-00b1-481f-a6e8-560b78284965)

...because matrix-postgres is up and port is open.

If i try `just run-tags run-postgres-vacuum`  it crashes with

![Anmerkung 2024-11-14 075554](https://github.com/user-attachments/assets/cc1e1317-fb04-4047-8475-d0442c49f422)

Any hints?

**Comment by ralfi** [comment]
After this i connect to matrix-postgres container and try to exec

`psql -v ON_ERROR_STOP=1 -c ''VACUUM FULL VERBOSE ANALYZE''`

it fails. What is th syntax to execute on the psql console?

**Comment by spantaleev** [comment]
Your first `ANALYZE;` is executed successfully.

Your second `ANALYZE` is not terminated with `;`, so.. `psql` is waiting for more input.

You're appending `VACUUM VERBOSE;` to it, so it becomes `ANALYZE VACUUM VERBOSE;` which is incorrect.

-----------------

Something odd is going on.. It seems like Postgres is up now, so maybe it was slow the first time around?

If you try `install-all` once again (now that Postgres is known to be up), does it work?

-------

Checking the status of the Postgres service (`systemctl status matrix-postgres.service`) and its logs (`journalctl -fu matrix-postgres.service`) may be helpful.

**Comment by ralfi** [comment]
Thanks a lot but it seem a big problem with networking connectivity after debians d-u yesterday. Many curious network problem, f.i. cannot connect to containers in the same network and so on. Really frustraded...

**Comment by spantaleev** [comment]
You may have done it already, but.. rebooting the server may help reset the iptables/Docker rules and fix networking between services.

**Comment by ralfi** [comment]
Yes, Slavi but reboot do not help in this case...

**Comment by ralfi** [comment]
![image](https://github.com/user-attachments/assets/646ed594-1297-42ce-8a8d-c334380342a9)

Seems to me a great tool but recognize only the fact - i know - that i cannot communicate between container in the same network

**Comment by ralfi** [comment]
it seems to to iptables related...

**Comment by ralfi** [comment]
@spantaleev And yes, iptables/unstable breaks docker networking. From testing it works as expected. No rants please for using unstable... ;-)

**Comment by ralfi** [comment]
Closing
