### ISSUE TITLE
Advice needed: best EC2 instance for running synapse

### ISSUE THREAD

**Issue by vjoomens** [spantaleev/matrix-docker-ansible-deploy#378]
Hi, can someone give some advise on what type of EC2 instance to choose for smoothly running synapse using an RDS database? Should it be memory / compute / storage optimised? We're using matrix for a large closed community, with large rooms (10K+ users). Perhaps using multiple instances using load balancing and auto scaling? Or would a single instance do the trick?

**Comment by aaronraimist** [comment]
matrix-docker-ansible-deploy doesn't support Synapse workers yet which you probably want access to for scaling so you may have to install Synapse manually (without this playbook) unless someone implements that #221. Synapse does not support multiple load balancing across multiple Synapse master processes.

I don't have experience running a server like that so I don't know what kind of specs you need. A random guess would be to start with the equivalent of a couple CPUs and 8 GB of RAM and then tune from there.

**Comment by vjoomens** [comment]
@aaronraimist thank you for answering my question. I'm running synapse now an a ec2 t3.xlarge instance, and its running quite smoothly. Next step is to defer DB to an RDS instance.
One thing I notice though is that there's always 1 python process running, no matter how many requests are being handled, and multiple postgres processes. I have no experience with python, this is normal? A webserver running nginx / php-fpm always shows multiple processes being handled simultaneously...

**Comment by aaronraimist** [comment]
Yes there is just one Synapse master process running unless you setup Synapse workers which can offload specific tasks.
