### ISSUE TITLE
IP unreachable

### ISSUE THREAD

**Issue by aneesimran** [spantaleev/matrix-docker-ansible-deploy#385]
Hi,

I am new to matrix.org and I had some issues in setting up.

I have been following this guide on the official Matrix website 
( https://matrix.org/docs/guides/free-small-matrix-server/#point-domain-at-server )

Which told me to get a domain from service such as freenom which I have.

Also, states to get a VM instance of Ubuntu via Oracle Cloud services which is also running fine. 

Later on the guide (see link above) it tells you to install the ansible playbook and directs to this github and there is also a live demo (after around 14 min mark https://www.youtube.com/watch?v=ubD1QrNegIo)

As seen in the video the demo uses `nslookup matrix.xxxxxxx.net` and copies the ip address under Non-authoritative answer into the hosts file in inventory.

I did the exact same but when I run the following command `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all`

I get the error 

`fatal: [matrix.whatsppmatrix.cf]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"140.238.85.214\". Make sure this host can be reached over ssh: root@140.238.85.214: Permission denied (publickey).\r\n", "unreachable": true}
`

The reason being the VM instance requires a RSA key to connect and that was mentioned in the Matrix tutorial, so then I tried hosting the domain via CloudFlare and tried the nslookup and got a different error

`
fatal: [matrix.whatsppmatrix.cf]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"104.24.116.106\". Make sure this host can be reached over ssh: ssh: connect to host 104.24.116.106 port 22: Connection timed out\r\n", "unreachable": true}
`

Any ideas on what I am doing wrong or suggestions to make it work?

Thanks!

**Comment by spantaleev** [comment]
A RSA public key is fine. It's how most people connect to their servers via SSH/Ansible, I guess.

I wonder why Ansible wouldn't be using your SSH key to connect to the server. Perhaps it's not at a common path (like `~/.ssh/id_rsa`) and it's not loading it..? You can try passing `-vvv` to the `ansible-playbook` commands and check if you see anything interesting about the SSH connection.

If you point the domain to a Cloudflare IP, it probably doesn't forward SSH traffic to your actual server, hence the "Connection timed out" error.. Better not do that.

**Comment by aneesimran** [comment]
> A RSA public key is fine. It's how most people connect to their servers via SSH/Ansible, I guess.
> 
> I wonder why Ansible wouldn't be using your SSH key to connect to the server. Perhaps it's not at a common path (like `~/.ssh/id_rsa`) and it's not loading it..? You can try passing `-vvv` to the `ansible-playbook` commands and check if you see anything interesting about the SSH connection.
> 
> If you point the domain to a Cloudflare IP, it probably doesn't forward SSH traffic to your actual server, hence the "Connection timed out" error.. Better not do that.

Ive tried it and ran it again, this is what i get : 

`
PLAY [Set up a Matrix server] ***************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
[WARNING]: Unhandled error in Python interpreter discovery for host matrix.whatsppmatrix.cf: Failed to connect to
the host via ssh: root@104.238.85.214: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

fatal: [matrix.whatsppmatrix.cf]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"104.238.85.214\". Make sure this host can be reached over ssh: root@104.238.85.214: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

PLAY RECAP **********************************************************************************************************
matrix.whatsppmatrix.cf    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

`

**Comment by thepra** [comment]
[Context] I use ssh with publickey from my windows machine to my linux server and following the guide from my server console.

I'm having the same issue with the same exact error(except domain and root).
I went with not connecting with non-root user, like in the setting in `hosts`:
    
    [matrix_servers]
    matrix.<my-domain> ansible_host=<my-ip> ansible_ssh_user=void become=true become_user=root

And my command also includes `--ask-pass`
My ports are open, and I can ssh with void@<my-ip> from my windows machine without any issue.

Here's my `-vvv` gory log:

> TASK [Gathering Facts] **********************************************************************************************
> task path: /home/void/Matrix/matrix-docker-ansible-deploy/setup.yml:2
> <matrix.**my-domain**> Attempting python interpreter discovery
> **my-ip** ESTABLISH SSH CONNECTION FOR USER: void
> **my-ip** SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="void"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/cca236d24f **my-ip** '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
> **my-ip** (255, b'', b'void@**my-ip**: Permission denied (publickey,password).\r\n')
>  [WARNING]: Unhandled error in Python interpreter discovery for host matrix.**my-domain**: Failed to connect to the
> host via ssh: void@**my-ip**: Permission denied (publickey,password).
> 
> Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
> Pipelining is enabled.
> **my-ip** ESTABLISH SSH CONNECTION FOR USER: void
> **my-ip** SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="void"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/cca236d24f **my-ip** '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-aoszvlgydflvmlguviiyknahhvkpfzfv ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
> fatal: [matrix.**my-domain**]: UNREACHABLE! => {
>     "changed": false,
>     "msg": "Data could not be sent to remote host \"**my-ip**\". Make sure this host can be reached over ssh: void@**my-ip**: Permission denied (publickey,password).\r\n",
>     "unreachable": true
> }

**Comment by aneesimran** [comment]
Hi, I found the error I didnt make the correct changes in the hosts file, after doing so it worked correctly.
