### ISSUE TITLE
Can't define matrix_synapse_container_additional_volumes without options

### ISSUE THREAD

**Issue by razzeee** [spantaleev/matrix-docker-ansible-deploy#3871]
**Describe the bug**
I'm trying to use https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7be14f03a0cc21def307bf982fb72e5ba5dc1c44/roles/custom/matrix-synapse/defaults/main.yml#L696 to mount a certificate into synapse, but it seems, like it might need to be writable.

So I think I need to remove the `options`

These seem to account for that
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7be14f03a0cc21def307bf982fb72e5ba5dc1c44/roles/custom/matrix-synapse/templates/synapse/systemd/matrix-synapse-worker.service.j2#L68

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7be14f03a0cc21def307bf982fb72e5ba5dc1c44/roles/custom/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2#L55

Deploying via `all,start` fails with:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'options'
failed: [matrix.name.com] (item={'src': '/home/matrix-deploy/matrix-docker-ansible-deploy/roles/custom/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2', 'dest': '/etc/systemd/system/matrix-synapse.service', 'mode': '0644'}) => changed=false 
  ansible_loop_var: item
  item:
    dest: /etc/systemd/system/matrix-synapse.service
    mode: '0644'
    src: /home/matrix-deploy/matrix-docker-ansible-deploy/roles/custom/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''options'''


```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
matrix_synapse_container_additional_volumes: [{"src": "/home/matrix-deploy/root-cert/", "dst": "/usr/local/share/ca-certificates/"}]
```

The rest of the config should be irrelevant

**Expected behavior**
I would think, that the `all,start` should finish without error

**Matrix Server:**
Debian 5.10.218-1 (2024-06-01) x86_64

**Comment by razzeee** [comment]
it seems to mount okay and with rw when I do

```
matrix_synapse_container_additional_volumes: [{"src": "/home/matrix-deploy/root-cert/", "dst": "/usr/local/share/ca-certificates/", "options": ""}]
```

which I also tried earlier, but doesn't seem to enrole the cert - so I guess that a different problem

**Comment by spantaleev** [comment]
The `options` key is required, as described in the comment for this Ansible variable:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/2c6dfeadfd5b8bcfe455beecb12fc8eaec49380f/roles/custom/matrix-synapse/defaults/main.yml#L694-L698

It doesn't explicitly say it's required, but it tells you what the shape of the objects should be and gives you an example.

You can use an empty string for the options (`{......, 'options': ''}`) and no options would be used. `rw` works just as well.

As such, I suppose this issue can be closed. If you're having some other problems, then perhaps they are unrelated to this.
