### ISSUE TITLE
Move /matrix or media_files folder to new destination - not S3

### ISSUE THREAD

**Issue by nocci-sl** [spantaleev/matrix-docker-ansible-deploy#390]
Hello everybody,

first: I am quite new to this whole thing (github/ansible/vps etc) so please excuse me if I am writing my issue a bit weird. 

I am running Matrix on a small vm/vps and I am running out of space.
My provider offers me extra storage space wich would be available in the vps on a extra folder like /storagespace1

I would like to tell the playbook to use /storagespace1 instead of /matrix - or at least the media_files.

Is there a simple way to archieve this?

I saw that following line in the host_vars maybe would solve my problem:
`matrix_synapse_media_store_path: "/storagespace1"`
Does this work? I dont want to mess up my exsisting and still great running system.
But what can I do if the database is getting go big so I would have to move it too?

Thank you... and I am happy to use this playbook since it makes everything very simple for beginners.

**Comment by Metzlmane** [comment]
I'm facing the same problem and i was thinking about to just copy the whole directory to /storagespace1 and then mount the directory in fstab as /matrix and if it works to delete the old one. Same as I do with the files for my music nfs share

**Comment by spantaleev** [comment]
Redefining `matrix_synapse_media_store_path` in your `vars.yml` file should work.

Another option is to move `/matrix` to `/storagespace1/matrix` and to set `matrix_base_data_path: /storagespace1/matrix`.

Before you move things around, make sure to stop all services on the server (`ansible-playbook .... --tags=stop`). After making changes, re-run the playbook: `ansible-playbook .... --tags=setup-all,start`

**Comment by nocci-sl** [comment]
Yes. This is what I was searching for. Perfect solution. 
Thank you very much for your help.

**Comment by jalemann** [comment]
Just in case anyone else is trying this in the future.

If modifying `matrix_base_data_path:` make sure to **move** (`mv`) the `\matrix` directory to the new location. Copying using `cp -r` seems to not work the same way as moving.

**Comment by spantaleev** [comment]
Copying with the `-a` (archive) flag may help retain ownership/permission information. A recursive copy is not enough.

`rsync -ar` may also help.
