### ISSUE TITLE
letsencypt certificate via dns challange

### ISSUE THREAD

**Issue by Deanosim** [spantaleev/matrix-docker-ansible-deploy#391]
Would it be possible to get support for obtaining the letsencrypt cert using a dns01 challenge?
I've been using this method on other servers and it works brilliantly if you can't use normal authentication for obtaining the cert (For instance if you're using cloudflare like me)
https://certbot-dns-cloudflare.readthedocs.io/en/stable/

**Comment by Deanosim** [comment]
Okay after more testing with my own external nginx proxy using dns challenge, it doesn't seem to be the only problem, because you can't change the federation port and so it's impossible to get federation to work with cloudflare.

**Comment by spantaleev** [comment]
Supporting the DNS challenge method is somewhat difficult.. Lots of providers, each of which requiring different configuration, etc.

I'm also not sure if each such module is part of the default certbot distribution or if it's necessary to install it separately.

**Comment by Deanosim** [comment]
Yeah it is, I've been using https://github.com/linuxserver/docker-letsencrypt to do it.

Finally got it all to work by manually editing the homeserver.yaml file to make combine the listeners for client and federation into a single listener that looks like this
`listeners:
-   bind_addresses:
    - '::'
    port: 8008
    resources:
    -   compress: false
        names: [client, federation]
    tls: false
    type: http
    x_forwarded: true'

Not sure if that breaks if I run the playbook again.

**Comment by spantaleev** [comment]
All manually-made changes to `homeserver.yaml` will be lost the next time you rerun the playbook.

The proper way to modify this is to define your overrides in your `vars.yml` file, using the `matrix_synapse_configuration_extension_yaml` variable. Check `roles/matrix-synapse/defaults/main.yml` for documentation on how to use this variable.

You'll basically need to define the whole `listeners:` configuration block inside `matrix_synapse_configuration_extension_yaml`.

**Comment by Deanosim** [comment]
Okay I've tried to do that just now, I added 

```matrix_synapse_configuration_extention_yaml: |
  listeners:
    - port: 8008
      tls: false
      type: http
      x_forwarded: true

  resources:
     - names: [client, federation]
       compress: false

auto_join_rooms:
- "#home:explodingpineapple.net"
- "#welcome.explodingpineapple.net"
autocreate_auto_join_rooms: true
```
to my vars.yaml at the bottom, and then ran `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start`
But when i check the homeserver.yaml file it hasn't changed anything, I assume I've not written the matrix_synapse_configuration_extension_yaml section correctly.

**Comment by Deanosim** [comment]
Don't worry got it to run, somehow i ended up with extension spelt wrong XD

**Comment by Deanosim** [comment]
```
matrix_synapse_configuration_extension_yaml: |
    listeners:
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
```
currently looks like that, but the resources part is being put in another part of the homeserver.yaml and now the server doesn't start.

**Comment by spantaleev** [comment]
Indentation is also very important.

Okay, so all is good now?

**Comment by Deanosim** [comment]
Yep everything seems to be working perfectly, Thanks for the help :)
