### ISSUE TITLE
connecting bridges such as whatsapp

### ISSUE THREAD

**Issue by aneesimran** [spantaleev/matrix-docker-ansible-deploy#395]
Hi,

I have got riot running on my domain.

Now I am unsure on how to connect the whatsapp bridge, the only change i made was in 
`/roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml `

and the change was by making `matrix_mautrix_whatsapp_enabled: true`

as stated by a guide on matrix.org 

have reinstalling and restarting my matrix server, i am not sure what is needed to do next.

Could someone point me in the right direction?

Thanks!

**Comment by spantaleev** [comment]
You **never** need to edit anything in the `roles/` directory.

All changes (such as `matrix_mautrix_whatsapp_enabled: true`) are meant to be made in your own `inventory/host_vars/matrix.DOMAIN/vars.yml` file.

We have a guide about the Whatsapp bridge in the `docs/` directory - [Setting up Mautrix Whatsapp (optional)](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-whatsapp.md)

**Comment by aneesimran** [comment]
> You **never** need to edit anything in the `roles/` directory.
> 
> All changes (such as `matrix_mautrix_whatsapp_enabled: true`) are meant to be made in your own `inventory/host_vars/matrix.DOMAIN/vars.yml` file.
> 
> We have a guide about the Whatsapp bridge in the `docs/` directory - [Setting up Mautrix Whatsapp (optional)](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-whatsapp.md)

Hi, 

Thanks for referring me to the guide, I have followed the instructions, but when typing in riot `@whatsappbot:whatsppmatrix.cf`

Nothing comes up and i cant manually add as it says user does not exist.

**Comment by spantaleev** [comment]
After adding `matrix_mautrix_whatsapp_enabled: true` to the correct file, have you re-ran the playbook and restarted services?

`ansible-playbok ...... --tags=setup-all,start`

It's only after this that you'd be able to message the bot.

**Comment by aneesimran** [comment]
> After adding `matrix_mautrix_whatsapp_enabled: true` to the correct file, have you re-ran the playbook and restarted services?
> 
> `ansible-playbok ...... --tags=setup-all,start`
> 
> It's only after this that you'd be able to message the bot.

Yep, I have rerun it again and double checked

**Comment by aneesimran** [comment]
I have tried even facebook bridge even still I am not getting the bot accounts appearing

**Comment by aneesimran** [comment]
> After adding `matrix_mautrix_whatsapp_enabled: true` to the correct file, have you re-ran the playbook and restarted services?
> 
> `ansible-playbok ...... --tags=setup-all,start`
> 
> It's only after this that you'd be able to message the bot.

this is the error i get 

`Unable to find profiles for the Matrix IDs listed below - would you like to invite them anyway?

@whatsappbot:whatsppmatrix.cf: User @whatsappbot:whatsppmatrix.cf does not exist`

**Comment by spantaleev** [comment]
Try inviting them anyway.

**Comment by aneesimran** [comment]
> Try inviting them anyway.

I have and this happens

![Annotation 2020-03-09 092802](https://user-images.githubusercontent.com/35374406/76199823-7c10bc80-61e8-11ea-9a8e-9bb1b9cb79c0.png)

**Comment by spantaleev** [comment]
Got if fixed?
