### ISSUE TITLE
Could not connect to identity server

### ISSUE THREAD

**Issue by blaluc** [spantaleev/matrix-docker-ansible-deploy#399]
I followed the instructions for setting up the system. Everything seems to work fine (very good job indeed) except the identity server. If I connect through Riot.im (v.0.9.10 android) and try to manually set the Identity Server address (Settings->Identity Server->https://matrix.<mydomain.xyz>), I get the message "Could not connect to identity server", while trying to do the same with the official matrix Identity Server (https://matrix.org) everytihing works without any issue.
Looking at the system log I see the following error:

```
GET /_matrix/identity/v2/terms HTTP/2.0" 405 0 "-" "Riot.im/0.9.10 
```
So it seems that the problem is the invocation of this service that returns a "405 Method Not Allowed". Could it be related to the mxsid that is no more aligned to the latest spec? 
If this is the case, perhaps the switching to ma1sd becomes urgent.

**Comment by blaluc** [comment]
Does anyone have a suggestion about this issue?
I saw that there was a PR for ma1sd, but I don't know what's the best way to proceed.
Many thanks.

**Comment by spantaleev** [comment]
It's probably time to make more progress on integrating ma1sd (#333) indeed.

**Comment by enzingerm** [comment]
It would be great if ma1sd could be integrated soon. I have also had problems with using mxisd as a backend for managing eMail invites, returning 405 on specified API calls.

**Comment by spantaleev** [comment]
ma1sd is integrated already, which should resolve this issue. See #333 and #212
