### ISSUE TITLE
Add Prometheus and Grafana to display metrics

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#4]
https://github.com/matrix-org/synapse/blob/67dbe4c89944cf5957f806ad63f60880e2242b23/contrib/grafana/README.md

**Comment by spantaleev** [comment]
Are you thinking the playbook should be made to install Prometheus and Grafana? .. or rather, that we'd just make Synapse expose the metrics, so they can be hooked to an external Prometheus setup?

**Comment by aaronraimist** [comment]
It would be great if it could install it all.

**Comment by spantaleev** [comment]
@aaronraimist, do you have a good Grafana dashboard for Synapse's metrics?

I've tried setting up metrics collection and visualizing it with [this Prometheus console](https://github.com/matrix-org/synapse/tree/master/contrib/prometheus), but:

- a lot of the graphs (especially interesting ones like "Federation") are missing for some reason ("No timeseries returned")

- the graphs that do appear to be there seem kind of useless ("Cache hit ratio" graph having way too many things on it)

I'm not sure if I'm doing something wrong, but.. it doesn't seem like this setup is too useful.
Probably if these other graphs start working or if there's some good Grafana dashboard..

**Comment by aaronraimist** [comment]
I don't but TravisR and I think Half Shot have some pretty good setups so you might be able to contact them.

https://matrix.to/#/!qPNOnUsNsZrToFZqxB:half-shot.uk/$15335863793215gQKyQ:t2l.io

**Comment by spantaleev** [comment]
Seems like there is a Grafana dashboard in the Synapse repository: https://github.com/matrix-org/synapse/tree/master/contrib/grafana

It looks much better and more useful than the Prometheus Console discussed above.

It might have some issues though, looking at this: https://github.com/matrix-org/synapse/issues/3862

**Comment by richvdh** [comment]
(the prometheus console is essentially unmaintained, as you've discovered)

**Comment by ptman** [comment]
I think prometheus and grafana may be a big out-of-scope for this project, but at least exposing prometheus metrics safely would be a nice addition.

**Comment by aaronraimist** [comment]
Looks like we forgot to mention it here but you can expose the metrics like since #86. This is what my config looks like:
```
matrix_synapse_metrics_enabled: true
matrix_nginx_proxy_proxy_synapse_metrics: false
matrix_synapse_metrics_port: 9129
matrix_synapse_container_metrics_api_host_bind_port: "127.0.0.1:9129"
```

**Comment by spantaleev** [comment]
I guess that having the ability to expose metrics to an externally-installed Prometheus/Grafana is good enough as far as the scope of the playbook is concerned.

I'll close this issue, as there are no plans to install Prometheus/Grafana via the playbook at this time.

**Comment by ptman** [comment]
What happened? https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/838

**Comment by spantaleev** [comment]
We may be turning into systemd, sort of ;)

I guess what happened is.. it's nice to be able to monitor your Matrix server and Prometheus/Grafana seem to be popular tools for that (not just with Synapse, but also with various bridges, etc.), so lots of people may wish to be able to monitor the server that way.

Still, installing and configuring Prometheus/Grafana can be difficult and annoying. Doing it separately, just for the sake of your Matrix server (which is the only thing a lot of people may wish to monitor) is not easy. Installing Prometheus/Grafana on the Matrix server (for those who only wish to monitor their Matrix server) can be annoying without it being baked into the playbook (extra certificates and vhosts managed manually, etc.). Although the playbook is flexible enough to allow people to obtain SSL certificates for other domains and to inject extra nginx configuration, it's still a bit of a battle.. Which doesn't seem worth it to most of us. I'm happy to be able to look at some graphs for my server, but I'm also not willing to spend effort to install Prometheus/Grafana neither separately (on another server), nor by hacking away manually on the Matrix server.

Another thing that happened is.. someone actually went through all the trouble to contribute support for Prometheus/Grafana, so me having no plans to work on doing that myself was nicely resolved.
