### ISSUE TITLE
Slack container fails to start

### ISSUE THREAD

**Issue by Metzlmane** [spantaleev/matrix-docker-ansible-deploy#400]
I inserted the two config lines from the manual (with my room ID) and run setup-all, but this keeps failing. Any hints where I can dig for erros?

```matrix systemd[1]: Started Matrix Appservice Slack server. 
matrix matrix-appservice-slack[3718]: /usr/bin/docker: invalid publish opts format (should be name=value but got '127.0.0.1:{{'). 
matrix matrix-appservice-slack[3718]: See '/usr/bin/docker run --help'. 
matrix systemd[1]: matrix-appservice-slack.service: Main process exited, code=exited, status=125/n/a
matrix systemd[1]: matrix-appservice-slack.service: Failed with result 'exit-code'.```

**Comment by Metzlmane** [comment]
somehow the variable for the first port number of the docker container in the ubuntu systemd file is not written

**Comment by spantaleev** [comment]
Is your playbook up to date?

There was a fix for something like this ~2 weeks ago. See 4a06e52660f01

**Comment by Metzlmane** [comment]
yes you are right.. sorry my bad.
