### ISSUE TITLE
Strange folders in home directory

### ISSUE THREAD

**Issue by lxp** [spantaleev/matrix-docker-ansible-deploy#403]
Yesterday I updated the playbook and let it run through. It created some strange folders in my home folder:

```
matrix@matrix01:~$ ls -l
total 4
drwxr-x--- 3 matrix matrix 4096 Mar 16 21:24 '{'\''src'\'': '\'''
```

By correlating the creation time with my syslog, I found the following Ansible module caused this:

```
Mar 16 21:24:38 matrix01 ansible-file: Invoked with directory_mode=None force=False remote_src=None _original_basename=None path={'src': '/matrix/synapse/docker-src', 'when': False} owner=matrix follow=True group=matrix 
unsafe_writes=None state=directory content=NOT_LOGGING_PARAMETER serole=None selevel=None setype=None access_time=None access_time_format=%Y%m%d%H%M.%S modification_time=None regexp=None src=None seuser=None recurse=False _diff_peek=None delimiter=None mode=488 modification_time_format=%Y%m%d%H%M.%S attributes=None backup=None
```

I have traced it back to this line: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/22ce50875a9a5635b0b1771b6c66a35ed8fa88fe/roles/matrix-synapse/tasks/setup_synapse.yml#L14

It seems that this commit introduced it: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/310aa685f94e0c65b960be4f11964f8981c8a77d

I am using ansible 2.9.4. I am not sure how to fix this.

**Comment by lopsided** [comment]
Can confirm, I just installed today and have this issue also. Ansible version 2.9.5

**Comment by spantaleev** [comment]
Thank you for the report! It's fixed now!
