### ISSUE TITLE
Install fails user verification

### ISSUE THREAD

**Issue by xloem** [spantaleev/matrix-docker-ansible-deploy#404]
```
TASK [matrix-base : Ensure Matrix user is created] **********************************************************************************
fatal: [matrix.caringneed.org]: FAILED! => {"changed": false, "msg": "usermod: user matrix is currently used by process 16923\n", "name": "matrix", "rc": 8}
```
Checking the process, it seems it is `/lib/systemd/systemd --user` with a subprocess of `(sd-pam)`

Within about a minute later, the process has closed.

**Comment by spantaleev** [comment]
You should be able to change the user/group ids like this (example):

```yaml
matrix_uid: 1300
matrix_gid: 1300
```

**Comment by xloem** [comment]
I'm just following the setup instructions.  Where do I put that?

**Comment by spantaleev** [comment]
In your `inventory/host_vars/matrix.DOMAIN/vars.yml` file

**Comment by xloem** [comment]
okay, it looks like this was caused by the ssh user being the same as the matrix user
