### ISSUE TITLE
video timeout

### ISSUE THREAD

**Issue by xsq0718** [spantaleev/matrix-docker-ansible-deploy#409]
[root@izbp1czplot2hq98jaybtdz matrix]# journalctl -fu matrix-synapse
-- Logs begin at Wed 2020-03-11 23:37:00 CST. --
Mar 19 14:37:25 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:37:25,106 - synapse.http.site - 203 - WARNING - GET-2613 - Error processing request <XForwardedForRequest at 0x7fbd40b43310 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_333_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 19 14:37:25 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:37:25,115 - synapse.http.server - 465 - WARNING - GET-2613 - Not sending response to request <XForwardedForRequest at 0x7fbd40b43310 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_333_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
Mar 19 14:39:58 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:39:58,940 - synapse.http.site - 203 - WARNING - GET-2642 - Error processing request <XForwardedForRequest at 0x7fbd4093f6d0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_341_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 19 14:39:58 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:39:58,949 - synapse.http.server - 465 - WARNING - GET-2642 - Not sending response to request <XForwardedForRequest at 0x7fbd4093f6d0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_341_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
Mar 19 14:44:49 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:44:49,911 - synapse.http.site - 203 - WARNING - GET-2669 - Error processing request <XForwardedForRequest at 0x7fbd4011dbd0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_349_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 19 14:44:49 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:44:49,919 - synapse.http.server - 465 - WARNING - GET-2669 - Not sending response to request <XForwardedForRequest at 0x7fbd4011dbd0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_349_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
Mar 19 14:45:42 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:45:42,545 - synapse.push.httppusher - 387 - WARNING - httppush.process-91 - Failed to push event $fl4-y-uY3dNQZg9_PZ8cD5pOs_dGtlKs2gFPwBPGnak to @test4:mydomain/im.vector.app.ios.voip.prod/kEias6zIYvjR4fr0YZG2GXiqLnwuRhKGQKxD87PEGV4=: <class 'twisted.internet.error.TimeoutError'> User timeout caused connection failure.

hi
    I want to know what causes this issue

**Comment by spantaleev** [comment]
Maybe it's a temporary problem while connecting to the push server.

If it persists, you may need to investigate it. In any case, it's likely a problem with [Synapse](https://github.com/matrix-org/synapse) and not with the playbook.
