### ISSUE TITLE
Make it more clear that Matrix Corporal is a feature for advanced users

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#41]
I thought it was clear enough that only people who know what they are looking for should setup Matrix Corporal but `@x0n:staubsaugertraum.de` Had a bad experience after setting it up and not being able to find out why he couldn’t set his avatar.

> I just rechecked the github docs. there is no mention of the optional parts being "advanced" and/or "this will fuck up your life because noone will be able to help you". maybe such a warning would suffice

**Comment by spantaleev** [comment]
I've updated the documentation in 733b8068333, which should make it clearer.
