### ISSUE TITLE
Fail if DNS SRV record incorrect

### ISSUE THREAD

**Issue by randomprey** [spantaleev/matrix-docker-ansible-deploy#411]
fatal: [matrix.mtx-me.tk -> 127.0.0.1]: FAILED! => {"changed": false, "msg": "It appears the DNS SRV record for _matrix-identity._tcp on mtx-me.tk. is not set up correctly. Expected it to point to `matrix.mtx-me.tk.` (port 443). Found it pointing to `matrix.mtx-me.tk.mtx-me.tk.` (port 443). See the 'Configuring DNS' documentation for this playbook."}

I've tried two different DNS systems and get the same error on both. Here is my DNS SRV record:

mtx-me.tk | _matrix-identity._tcp | SRV | 1800 | matrix | 10 | 0 | 443

The deployment went good and I'm able to connect and create accounts. Thanks for the help and the cookbook!

**Comment by spantaleev** [comment]
```
dig -t srv _matrix-identity._tcp.mtx-me.tk
```

```
;; ANSWER SECTION:
_matrix-identity._tcp.mtx-me.tk. 1800 IN SRV    10 0 443 matrix.mtx-me.tk
```

It looks okay to me now. Maybe DNS hadn't refreshed before. I'm guessing if you run `--tags=self-check` again, you'll get a good result.

**Comment by randomprey** [comment]
yes indeed! It's always dns isn't it. Thanks for what you are doing for
this project. My first matrix server turns 3 this year and it's been great
watching this project grow.
