### ISSUE TITLE
matrix-jitsi.conf has dimension.DOMAIN as it's ssl server name

### ISSUE THREAD

**Issue by JasonLocklin** [spantaleev/matrix-docker-ansible-deploy#417]
After enabling jitsi, matrix-jitsi.conf is created in /matrix/nginx-proxy/conf.d and the server_name is set to dimension.mydomain instead of jitsi.mydomain.

**Comment by JasonLocklin** [comment]
inside matrix-jitsi.conf:
`
<snip>
server {
        listen 8443 ssl http2;
        listen [::]:8443 ssl http2;

        server_name dimension.locklin.science;
<snip>
`

**Comment by JasonLocklin** [comment]
inside matrix-jitsi.conf
```
<snip>
   server {
        listen 8443 ssl http2;
        listen [::]:8443 ssl http2;

        server_name dimension.locklin.science;
<snip>
```

This leads to a cert rejection in the browser.

**Comment by spantaleev** [comment]
Thanks for reporting this! It's fixed now!
