### ISSUE TITLE
Wrong title or copy and paste error

### ISSUE THREAD

**Issue by christianlupus** [spantaleev/matrix-docker-ansible-deploy#424]
While looking through the whole code, I found [this section](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/ext/synapse-simple-antispam/setup_install.yml#L16-L22). It looks rather counter-intuitive, as it states to install `git` but instead installs `openssl`. The other variant (CentOS) installs really `git`. Thus I assume it was copied over from a location where `openssl` is installed.

I assume this is an overseen bug but wanted to bring it to your awareness to check it once, please.

**Comment by spantaleev** [comment]
Thanks for catching this! :+1:
