### ISSUE TITLE
Feature request : Jitsi language

### ISSUE THREAD

**Issue by anup92k** [spantaleev/matrix-docker-ansible-deploy#427]
Hello (from france),

Unless I'm mistaken, there is no way to set the default language or use the users system language for the Jitsi integration.
I've been looking into `roles/matrix-jitsi/defaults/main.yml` so I can override something but I don't see any relative options.

Is their a way you can make available the setting of `LANG_DETECTION: false` located in
`roles/matrix-jitsi/templates/web/interface_config.js.j2` ?

Or/and maybe make the commented setting `defaultLanguage: 'en',` located in `roles/matrix-jitsi/templates/web/config.js.j2` available ?

Best regards,
Anup

**Comment by spantaleev** [comment]
Hello!

I've made both of these configurable via variables. Example (for your `inventory/host_vars/matrix.DOMAIN/vars.yml`):

```yaml
matrix_jitsi_web_config_defaultLanguage: 'fr'
matrix_jitsi_web_interface_config_lang_detection: true
```

**Comment by anup92k** [comment]
Many thanks for this feature and your quick reply !
