### ISSUE TITLE
New to ansible: how do I connect to ec2 with pem file

### ISSUE THREAD

**Issue by hfgoulding** [spantaleev/matrix-docker-ansible-deploy#430]
I have spent a couple of hours trying to figure out the syntax to connect to my ec2 instance using the pem file. Localmachine is linux. I ssh into the server with .pem file, it is set with permissions,  0400 and i provide a full path. I have tried
matrix.xxxxx.xxxing.com ansible_host=3.21.xxx.xxx ansible_ssh_private_key_file=/home/hfg/.ssh/xxxxxxxxx.pem ansible_ssh_user=ubuntu@ecx-xx-xx-xxx3.us-east-2.compute.amazonaws.com
Thanks for the help

**Comment by spantaleev** [comment]
`ansible_ssh_user` should be something like `ubuntu` only, and not `ubuntu@ecx-xx-xx-xxx3.us-east-2.compute.amazonaws.com`.

Since you're logging in as non-`root`, you'll also need to add `become=true become_user=root`
