### ISSUE TITLE
cannot find vars.yml

### ISSUE THREAD

**Issue by airdogvan** [spantaleev/matrix-docker-ansible-deploy#431]
I must be missing something very obvious because I cannot find the file
inventory/host_vars/matrix.<your-domain>/vars.yml
It seems to be an important file as it defines a certain number of parameters (how many I don't know since I haven't seen the file).
I know at least for setting up  dimension it is.
I git cloned on 2 different servers and the file is definitively not there.
So what is it that I understood wrong?

Thank you

**Comment by anup92k** [comment]
Hello,

This file doesn't exist yet
`inventory/host_vars/matrix.<your-domain>/vars.yml`

You have to built it copying an existing exemple file see [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook.md)

For exemple, if your domain is `airrljdtbp.com` you should do the following :
```bash
$ mkdir inventory/host_vars/matrix.airrljdtbp.com
$ cp examples/host-vars.yml inventory/host_vars/matrix.airrljdtbp.com/vars.yml
```
Then edit the newly created file to override values of differents modules installed. This mean you have to copy the variable name from the default config and add it to the file `inventory/host_vars/matrix.airrljdtbp.com/vars.yml`.

Their default values are located like this :
roles/**ONE_ROLE_OF_THIS_PLAYBOOK**/defaults/main.yml

For exemple, the dimension config is in :
`roles/matrix-dimension/defaults/main.yml`
If you want to change something from this config, add it to you config file.

For exemple, setting `matrix_dimension_enabled: false` to `true` you have to put `matrix_dimension_enabled: true` to your file `inventory/host_vars/matrix.airrljdtbp.com/vars.yml`.

Hope this help !

Regards

**Comment by airdogvan** [comment]
Thanks so much for the explanation.  I guess I misunderstood the docs.
Much appreciated

**Comment by spantaleev** [comment]
Just to clarify some more: defaults come from `roles/ROLE/defaults/main.yml`, but also from `group_vars/matrix_servers`. The latter is what wires all these separate roles together, so it has priority. Ultimately, your own `vars.yml` file has the final say though.

**Comment by airdogvan** [comment]
Thank you again.  You might be interested to know that I did read the directive where it said to copy the file from examples, but I just copied it instead of renaming it, i.e. I copied to host-vars.yml.  What is interesting is that the install worked so I'm guessing your script takes any .yml file present in that directory and makes do with that.

**Comment by spantaleev** [comment]
I'm not sure why that would've worked.

If the `vars.yml` file is missing, Ansible would carry on with whatever defaults these variables have. Still, it's expected to crash at some point, because we have various safety checks, checking whether some critical variables are empty.

**Comment by airdogvan** [comment]
Well nevertheless it did work, configured my domain and I now have a running valid install with voice call and jitsi call working perfectly and I'm positively sure that the only file available to the script was the host-vars.yml configured with the values I changed.
Anyway thank you so much for making this script available, lot of work in there if only for the docs, makes life much easier for lazy people like me :).
Am still struggling with minor issues such as Federation and don't understand why I cannot add phone # or user emails to the profile but I'll figure it out eventually.
Again thanks so much.
