### ISSUE TITLE
Disable ma1sd, only allow external LDAP?

### ISSUE THREAD

**Issue by fooness** [spantaleev/matrix-docker-ansible-deploy#433]
I’m a little bit confused by [Setting up the LDAP authentication password provider module (optional, advanced)](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ldap-auth.md) which says:

> The playbook can install and configure the [matrix-synapse-ldap3](https://github.com/matrix-org/matrix-synapse-ldap3) LDAP Auth password provider for you.

When using the config variables shown in that docs, and setting `matrix_synapse_password_config_localdb_enabled: false`, how would I disable ma1sd (as well as prevent it from being installed)?

**Comment by spantaleev** [comment]
It should be possible via this plugin, yes.

It then depends on what kind of features you need to decide whether this LDAP plugin is enough or you need something more (ma1sd).

**Comment by eMPee584** [comment]
put into your `inventory/host_vars/[HOST]/vars.yml` something like

```
matrix_synapse_ext_password_provider_ldap_enabled: false
matrix_synapse_ext_password_provider_ldap_uri: "ldap://[HOST]:389"
matrix_synapse_ext_password_provider_ldap_start_tls: false
matrix_synapse_ext_password_provider_ldap_base: "ou=users,dc=[SUBDOMAIN],dc=[HOST],dc=[TLD]"
matrix_synapse_ext_password_provider_ldap_attributes_uid: "uid"
matrix_synapse_ext_password_provider_ldap_attributes_mail: "mail"
matrix_synapse_ext_password_provider_ldap_attributes_name: "cn"
matrix_synapse_ext_password_provider_ldap_bind_dn: "cn=admin,dc=[SUBDOMAIN],dc=[HOST],dc=[TLD]"
matrix_synapse_ext_password_provider_ldap_bind_password: "SECRET"
```

.. more documentation in https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/docs/configuring-playbook-ldap-auth.md

**Comment by spantaleev** [comment]
Don't forget to use `matrix_synapse_ext_password_provider_ldap_enabled: true` though ;)

**Comment by eMPee584** [comment]
ah ouch sorry i forgot to switch that back
