### ISSUE TITLE
Jitsi server doesn't work correctly when auth and guests are enabled

### ISSUE THREAD

**Issue by ProjectMoon** [spantaleev/matrix-docker-ansible-deploy#439]
I don't know if this is the right place to report this problem, but I feel like it's a good starting point. I've enabled authentication and guest mode on the Jitsi server. When both are enabled, I think Jitsi Meet goes into the Twilight Zone. When I start a meeting, I"m not given any login prompt or waiting room messaging. Instead, it just sits there. No buttons work, camera is on but not showing any video. If I have only auth on, or turn auth and guest mode off, it works fine.

I did use these settings before doing a `git pull` for today's code, which contains the Jitsi auth stuff. The problem was happening both before and after the pull. Am I doing something wrong/did I break the installation?

**Comment by spantaleev** [comment]
If you had Jitsi installed from before (without authentication), have you made sure to delete the data in `/matrix/jitsi/prosody`, as our docs page says?

A few of us have tested this authenticated Jitsi setup and it seems to work well, so I'm curious as to what problems you might be encountering.

If you set up the Jitsi server without authentication everything works fine (audio/video)?

**Comment by ProjectMoon** [comment]
I delete the directory between every deployment while I'm testing this, yes.

If I turn off auth and guest mode, the meeting works fine. If I turn on authentication, it asks me for a username and password, and works fine if I log in.

**Comment by teutat3s** [comment]
Could you try again with the recent changes to the Jitsi role? It would probably be best to start fresh again by deleting `/matrix/jitsi` on the matrix host once again.

**Comment by ProjectMoon** [comment]
Looks like it is working now. Camera comes up, Jitsi asks if I'm the host, and then I can authenticate. So it looks like whatever changes were made to the settings fixed this issue!
