### ISSUE TITLE
when starting services, error occurs, synapse cant start

### ISSUE THREAD

**Issue by caglar1** [spantaleev/matrix-docker-ansible-deploy#449]
I have tried to start services
`ansible-playbook -i inventory/hosts setup.yml --tags=start`
I see this error
`TASK [matrix-common-after : Fail if service isn't detected to be running] ******
failed: [matrix_servers] (item=matrix-synapse) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-synapse", "msg": "matrix-synapse was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-synapse` and `journalctl -fu matrix-synapse` on the server to investigate."}`

and I see this details 
`root@vmi360245:~# journalctl -fu matrix-synapse
-- Logs begin at Sat 2020-03-21 18:19:30 CET. --
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,579 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/server.py", line 242, in setup
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,579 - twisted - 192 - ERROR -  -     self.datastores = DataStores(self.DATASTORE_CLASS, self)
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,580 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/__init__.py", line 47, in __init__
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,580 - twisted - 192 - ERROR -  -     with make_conn(database_config, engine) as db_conn:
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,580 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 101, in make_conn
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,580 - twisted - 192 - ERROR -  -     db_conn = engine.module.connect(**db_params)
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,580 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,580 - twisted - 192 - ERROR -  -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,581 - twisted - 192 - ERROR -  - psycopg2.OperationalError: local user with ID 991 does not exist
Apr 10 13:36:31 vmi360245.contaboserver.net matrix-synapse[25592]: 2020-04-10 11:36:31,581 - twisted - 192 - ERROR -  -
Apr 10 13:36:32 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 13:36:32 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Apr 10 13:37:02 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Apr 10 13:37:02 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 26.
Apr 10 13:37:02 vmi360245.contaboserver.net systemd[1]: Stopped Synapse server.
Apr 10 13:37:02 vmi360245.contaboserver.net systemd[1]: Starting Synapse server...
Apr 10 13:37:02 vmi360245.contaboserver.net matrix-synapse[25805]: Error response from daemon: Cannot kill container: matrix-synapse: No such container: matrix-synapse
Apr 10 13:37:02 vmi360245.contaboserver.net matrix-synapse[25829]: Error: No such container: matrix-synapse
Apr 10 13:37:02 vmi360245.contaboserver.net systemd[1]: Started Synapse server.
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: This server is configured to use 'matrix.org' as its trusted key server via the
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: server since it is long-lived, stable and trusted. However, some admins may
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: wish to use another server for this purpose.
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: To suppress this warning and continue using 'matrix.org', admins should set
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: --------------------------------------------------------------------------------
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,378 - root - 257 - WARNING - None - ***** STARTING SERVER *****
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,378 - root - 258 - WARNING - None - Server /usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.12.3
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,392 - twisted - 192 - ERROR -  - Traceback (most recent call last):
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,393 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,393 - twisted - 192 - ERROR -  -     "__main__", mod_spec)
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,393 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,394 - twisted - 192 - ERROR -  -     exec(code, run_globals)
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,394 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 651, in <module>
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,394 - twisted - 192 - ERROR -  -     main()
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,394 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 646, in main
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,395 - twisted - 192 - ERROR -  -     hs = setup(sys.argv[1:])
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,395 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 348, in setup
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,396 - twisted - 192 - ERROR -  -     hs.setup()
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,396 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/server.py", line 242, in setup
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,396 - twisted - 192 - ERROR -  -     self.datastores = DataStores(self.DATASTORE_CLASS, self)
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,397 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/__init__.py", line 47, in __init__
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,397 - twisted - 192 - ERROR -  -     with make_conn(database_config, engine) as db_conn:
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,397 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 101, in make_conn
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,397 - twisted - 192 - ERROR -  -     db_conn = engine.module.connect(**db_params)
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,397 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,398 - twisted - 192 - ERROR -  -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,398 - twisted - 192 - ERROR -  - psycopg2.OperationalError: local user with ID 991 does not exist
Apr 10 13:37:06 vmi360245.contaboserver.net matrix-synapse[25838]: 2020-04-10 11:37:06,398 - twisted - 192 - ERROR -  -
Apr 10 13:37:06 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 13:37:06 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Apr 10 13:37:37 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Apr 10 13:37:37 vmi360245.contaboserver.net systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 27.`

what is the problem?

**Comment by spantaleev** [comment]
What's your `vars.yml` like? (excluding secrets, of course)

**Comment by caglar1** [comment]
the vars.yml   like this
`
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# Example value: example.com
matrix_domain: cityshopia.com

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: mcunsal@yahoo.com

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "static-auth-secret"

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "macaron-secret-key"`

**Comment by caglar1** [comment]
the vars.yml file is default one like this,
----------------------------------------------
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# Example value: example.com
matrix_domain: cityshopia.com

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: kaya@yahoo.com

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "static-auth-secret"

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "macaron-secret-key"

**Comment by caglar1** [comment]
Hi
the var.yml is here
https://github.com/caglar1/matrix-ansible-2/blob/master/inventory/host_vars/matrix.cityshopia.com/vars.yml

I use this playbook
https://github.com/caglar1/matrix-ansible-2

**Comment by spantaleev** [comment]
Exposing your variables publicly, especially secrets (like your Gmail password) is not a good idea at all!

As for the "psycopg2.OperationalError: local user with ID 991 does not exist" error, I'm not sure what's causing it. Have you changed the Postgres username/password subsequently?

**Comment by caglar1** [comment]
Thank you for your warning
no problem, all the email and passwords are wrong
you can see the new postgrade username and pass on the var.yml

I have changed postgrade username and password,
 because, when I was setting up the playbook the process failed with the following error

`TASK [matrix-postgres : Fail if required Postgres settings not defined] ********
failed: [matrix_servers] (item=matrix_postgres_connection_hostname) => {"ansible_loop_var": "item", "changed": false, "item": "matrix_postgres_connection_hostname", "msg": "You need to define a required configuration setting (`matrix_postgres_connection_hostname`).\n"}
failed: [matrix_servers] (item=matrix_postgres_connection_username) => {"ansible_loop_var": "item", "changed": false, "item": "matrix_postgres_connection_username", "msg": "You need to define a required configuration setting (`matrix_postgres_connection_username`).\n"}
failed: [matrix_servers] (item=matrix_postgres_connection_password) => {"ansible_loop_var": "item", "changed": false, "item": "matrix_postgres_connection_password", "msg": "You need to define a required configuration setting (`matrix_postgres_connection_password`).\n"}
failed: [matrix_servers] (item=matrix_postgres_db_name) => {"ansible_loop_var": "item", "changed": false, "item": "matrix_postgres_db_name", "msg": "You need to define a required configuration setting (`matrix_postgres_db_name`).\n"}`

so I had to change the postgrade username on the var.yml

**Comment by spantaleev** [comment]
Doing things like [this](https://github.com/caglar1/matrix-ansible-2/commit/158fbed7342aab69d2a425d823b755577d562777) likely makes the playbook not load some important variables from the `group_vars/matrix_servers` file.

This leads to many variables being undefined and you having to define them manually.

If `group_vars/matrix_servers` gets loaded as per normal, you would not get an error like this:
> You need to define a required configuration setting (matrix_postgres_db_name)
.. because we provide a default value.

So I suspect that you doing strange things and modifying files you shouldn't touch has created such problems for you.

If your server hasn't been used yet (no existing data you need to preserve), I'd advise you to start fresh (`systemctl stop matrix*` and `rm -rf /matrix` OR start with an empty server) and follow our guide. The only files you need to touch are `inventory/hosts` and `inventory/host_vars/matrix.DOMAIN/vars.yml`. Changing the Postgres connection details subsequently is going to lead to errors.

**Comment by caglar1** [comment]
@spantaleev Thank you very much for your kindly help
I was using AWX , and didn't setup correctly the extra variables on `group_vars/matrix_servers`
now I set it up correctly and everything is fine
Thanks for the nice playbook
good luck
