### ISSUE TITLE
Please support encryption for bridges

### ISSUE THREAD

**Issue by jgoerzen** [spantaleev/matrix-docker-ansible-deploy#451]
Hi,

In `/matrix/mautrix-facebook/config/config.yaml`, there is a reference to E2EE encryption, which is disabled.  I grepped through the checked out ansible tree and couldn't find this text anywhere in the templates, so I don't know where it's coming from, as that file clearly does have content coming from templates.

The bit I'm talking about is:

```    # End-to-bridge encryption support options. These require matrix-nio to be installed with pip
    # and login_shared_secret to be configured in order to get a device for the bridge bot.
    #
    # Additionally, https://github.com/matrix-org/synapse/pull/5758 is required if using a normal
    # application service.
    encryption:
        # Allow encryption, work in group chat rooms with e2ee enabled
        allow: false
        # Default to encryption, force-enable encryption in all portals the bridge creates
        # This will cause the bridge bot to be in private chats for the encryption to work properly.
        default: false
```

It would also be nice to be able to adjust the things in bridge.permissions, but they are fine with me for now.

**Comment by spantaleev** [comment]
I've updated our default configuration to include these options. The default to being disabled (`false` value), which is inline with the example configuration for the bridges in their own respective repositories.

There's no need for us to define special variables for each and every option like this though. You can enable encryption by extending the default configuration like this:

```yaml
matrix_mautrix_facebook_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true
```
