### ISSUE TITLE
Error with federation

### ISSUE THREAD

**Issue by McL0v1n** [spantaleev/matrix-docker-ansible-deploy#453]
When joining rooms on federated servers, messages can pass outbound but not inbound. Logs show this error:

> Apr 11 19:12:29 matrix1 matrix-synapse: 2020-04-12 02:12:29,377 - synapse.http.site - 203 - WARNING - PUT-157 - Error processing request <XForwardedForRequest at 0x7fe63411c650 method='PUT' uri='/_matrix/federation/v1/send/1585938162909' clientproto='HTTP/1.0' site=8048>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.

I believe I've seen a solve for this somewhere by updating the version of twisted used.

**Comment by spantaleev** [comment]
If there's some problem like this, then it's probably a [Synapse](https://github.com/matrix-org/synapse) issue. Please report it there, if you see it often and believe it to a be a Synapse problem.
