### ISSUE TITLE
Use custom sub-domain 

### ISSUE THREAD

**Issue by raphawa** [spantaleev/matrix-docker-ansible-deploy#458]
Hi
This is not a real issue. I've followed up and my server is set an running.
just wanted to know if I could use custom subdomains like conference.domain.com instead of jitsi.domain.com or mycom.domain.com instead of matrix.domain.com

**Comment by spantaleev** [comment]
It's possible.

You can override various variables, as seen here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7035af87d8d96c9381b47ed65a39e05ead1dc3b5/roles/matrix-base/defaults/main.yml#L10

Redefine them in your own `vars.yml` file as you see fit.

This should preferably be done before the initial install. Changing some things subsequently may lead to breakage. You can give it a try though.
