### ISSUE TITLE
Remove synapse-janitor

### ISSUE THREAD

**Issue by jcgruenhage** [spantaleev/matrix-docker-ansible-deploy#465]
Synapse janitor is buggy and potentially breaking synapse (already happened in the past). It was removed from the matrix.org FAQ (https://github.com/matrix-org/matrix.org/commit/b35fb2f48981c42376773f6046d36c20fdcdf892) and I submitted a PR to their repo to include a notice about that in README (https://github.com/xwiki-labs/synapse_scripts/pull/12).

I therefore propose that you remove the docs and playbooks integrating synapse janitor and shout about it in the room to make sure people don't run into trouble there.

**Comment by aaronraimist** [comment]
Do you have any recent evidence of it messing things up? It is still the only way to ensure some things are deleted since the Synapse API to delete a room is fairly buggy.

It’s probably fine to remove it from the playbook but I think it is still worth pointing people to it, even if you say it is experimental and your mileage may vary.

**Comment by spantaleev** [comment]
I've added a note about it and the playbook now asks people to explicitly submit `--extra-vars='i_know_synapse_janitor_is_dangerous=1'` if they'd like to run it.

We can consider removing it depending on other people's anecdotes about it and on how upstream handles it.

**Comment by jcgruenhage** [comment]
@aaronraimist It came up recently in a NV + alumni channel. I asked the synapse team what they think and they said that it shall not be used, and shall not be recommended at all. Upstream accepted my PR to include a big fat warning on the README, saying they have no real knowledge about synapse too, so I think what I said is fair to say.

**Comment by richvdh** [comment]
> Do you have any recent evidence of it messing things up?

https://github.com/matrix-org/synapse/issues/7305

Ultimately: please don't just delete rows from your database. or if you do, please don't be surprised when it breaks.

**Comment by babolivier** [comment]
Note that this script doesn't seem to be maintained anymore: the repo description says pretty obviously that they're looking for maintainers to take over, and there hasn't been any activity on it since November 2017 apart from merging 3 small external PRs.
