### ISSUE TITLE
Include mx-puppet-instagram and mx-puppet-discord

### ISSUE THREAD

**Issue by Hexalyse** [spantaleev/matrix-docker-ansible-deploy#469]
I just wanted to know if there is any plan to include the https://github.com/Sorunome/mx-puppet-instagram bridge to the playbook ?

And same question for the https://github.com/matrix-discord/mx-puppet-discord instead of the current Discord bridge (this one supports bridging guilds transparently, and also private and group DMs).

If not, I've never used Ansible before using this playbook, so is there a LOT of work to include such a bridge, or just a few variables to configure so that it can be automatically deployed and configured ? In which case, I might try to add mx-puppet-instagram.

**Comment by spantaleev** [comment]
@rbelem said he'd be working on mx-puppet-discord support soon.

For mx-puppet-instagram, I haven't heard of anyone mentioning it. Please go ahead with adding support, if you're interested and would like to jump into Ansible. I guess you can copy some of the other mx-puppet bridge roles and start from there. If you've got any questions or troubles with development, we can provide help in our Matrix room (`#matrix-docker-ansible-deploy:devture.com`).

**Comment by jdreichmann** [comment]
For mx-puppet-instagram, see #551 
I could already test it successfully locally

**Comment by jdreichmann** [comment]
With #540 and #551 being merged and announced, i'd vote to close this issue (ping @spantaleev).

**Comment by spantaleev** [comment]
Thanks for the ping! It's nice to see support for both bridges getting merged within the same week :)
