### ISSUE TITLE
Matrix-corporal installation fails

### ISSUE THREAD

**Issue by rootuser** [spantaleev/matrix-docker-ansible-deploy#477]
Hi,

first of all: your ansible script rocks; it did a great job helping me setting up a working synapse.
But now I need your help, because matrix-corporal installation fails. Although I have tried hard to find the problem, I can't get any further.

Executing the puppet script always ends with

> failed: [matrix.ohoco.de] (item=matrix-corporal) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-corporal", "msg": "matrix-corporal was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-corporal` and `journalctl -fu matrix-corporal` on the server to investigate."}

When I check with journalctl -fu matrix-corporal on the matrix server, it seelm that there is a problem with the docker container:

> Apr 29 15:33:53 matrix matrix-corporal[20049]: Error: No such container: matrix-corporal
Apr 29 15:33:53 matrix systemd[1]: Started Matrix Corporal.
Apr 29 15:33:54 matrix matrix-corporal[20058]: time="2020-04-29T13:33:54Z" level=info msg="Starting HTTP Gateway Server on 127.0.0.1:41080"
Apr 29 15:33:54 matrix matrix-corporal[20058]:                  _        _                                                _
Apr 29 15:33:54 matrix matrix-corporal[20058]:  _ __ ___   __ _| |_ _ __(_)_  __      ___ ___  _ __ _ __   ___  _ __ __ _| |
Apr 29 15:33:54 matrix matrix-corporal[20058]: | '_ \ _ \ / _\ | __| '__| \ \/ /____ / __/ _ \| '__| '_ \ / _ \| '__/ _\ | |
Apr 29 15:33:54 matrix matrix-corporal[20058]: | | | | | | (_| | |_| |  | |>  <_____| (_| (_) | |  | |_) | (_) | | | (_| | |
Apr 29 15:33:54 matrix matrix-corporal[20058]: |_| |_| |_|\__,_|\__|_|  |_/_/\_\     \___\___/|_|  | .__/ \___/|_|  \__,_|_|
Apr 29 15:33:54 matrix matrix-corporal[20058]:                                                     |_|
Apr 29 15:33:54 matrix matrix-corporal[20058]: ---------------------------------------------------------- [ Version: 1.9.0 ]
Apr 29 15:33:54 matrix matrix-corporal[20058]: GitCommit: e8250a9
Apr 29 15:33:54 matrix matrix-corporal[20058]: GitBranch: master
Apr 29 15:33:54 matrix matrix-corporal[20058]: GitState: dirty
Apr 29 15:33:54 matrix matrix-corporal[20058]: GitSummary: 1.9.0-dirty
Apr 29 15:33:54 matrix matrix-corporal[20058]: BuildDate: 2020-04-17T19:22:47Z
Apr 29 15:33:54 matrix matrix-corporal[20058]: panic: HTTP provider is missing a required configuration key: TimeoutMilliseconds
Apr 29 15:33:54 matrix matrix-corporal[20058]: goroutine 1 [running]:
Apr 29 15:33:54 matrix matrix-corporal[20058]: devture-matrix-corporal/corporal/container.BuildContainer.func17(0x8deea0, 0xc00000c760, 0x84889d, 0xf)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /build/corporal/container/container.go:221 +0x20d
Apr 29 15:33:54 matrix matrix-corporal[20058]: github.com/euskadi31/go-service.(*container).Get(0xc00000c760, 0x84889d, 0xf, 0x0, 0x0)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /go/pkg/mod/github.com/euskadi31/go-service@v1.3.2/container.go:90 +0x1a3
Apr 29 15:33:54 matrix matrix-corporal[20058]: devture-matrix-corporal/corporal/container.BuildContainer.func10(0x8deea0, 0xc00000c760, 0x854b9b, 0x29)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /build/corporal/container/container.go:155 +0x8f
Apr 29 15:33:54 matrix matrix-corporal[20058]: github.com/euskadi31/go-service.(*container).Get(0xc00000c760, 0x854b9b, 0x29, 0x0, 0x0)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /go/pkg/mod/github.com/euskadi31/go-service@v1.3.2/container.go:90 +0x1a3
Apr 29 15:33:54 matrix matrix-corporal[20058]: devture-matrix-corporal/corporal/container.BuildContainer.func9(0x8deea0, 0xc00000c760, 0x852101, 0x23)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /build/corporal/container/container.go:147 +0x52
Apr 29 15:33:54 matrix matrix-corporal[20058]: github.com/euskadi31/go-service.(*container).Get(0xc00000c760, 0x852101, 0x23, 0x0, 0x0)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /go/pkg/mod/github.com/euskadi31/go-service@v1.3.2/container.go:90 +0x1a3
Apr 29 15:33:54 matrix matrix-corporal[20058]: devture-matrix-corporal/corporal/container.BuildContainer.func8(0x8deea0, 0xc00000c760, 0x84828c, 0xe)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /build/corporal/container/container.go:134 +0x74
Apr 29 15:33:54 matrix matrix-corporal[20058]: github.com/euskadi31/go-service.(*container).Get(0xc00000c760, 0x84828c, 0xe, 0x0, 0x0)
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /go/pkg/mod/github.com/euskadi31/go-service@v1.3.2/container.go:90 +0x1a3
Apr 29 15:33:54 matrix matrix-corporal[20058]: main.main()
Apr 29 15:33:54 matrix matrix-corporal[20058]:         /build/matrix-corporal.go:94 +0x4a0
Apr 29 15:33:54 matrix systemd[1]: matrix-corporal.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 29 15:33:54 matrix systemd[1]: matrix-corporal.service: Failed with result 'exit-code'.

As far as I can tell I have configured the playbook exactly as demanded in the documentation. 

Do you have any hint perhaps?

Thank you very much!
Best, Tom

**Comment by spantaleev** [comment]
Hi!

Thank you for the kind words!

This is a problem with the example configuration. There's a new `TimeoutMilliseconds` required parameter for matrix-corporal's HTTP policy provider.

Please adjust your `matrix_corporal_policy_provider_config` variable to add the required `TimeoutMilliseconds` value. I've adjusted the example in da90988.

**Comment by rootuser** [comment]
Hey,

thank you very much for your response at light-speed!

Alas, your fix does not seem to solve the problem...
Seems I had "TimeoutMilliseconds" in my config already.
I pulled the script updates, re-checked the config and tried again, but to no avail.

Error output of the installation script stays the same. 

journalctl gives different output though; the TimeoutMilliseconds error is done.
In spite of the installation error message corporal seems to try fetching the profile:

> time="2020-04-29T15:52:09Z" level=info msg="Starting policy provider: http (https://myserver.de/matrix/policy/policy.json)"
Apr 29 17:52:09 matrix matrix-corporal[15979]: time="2020-04-29T15:52:09Z" level=warning msg="Failed loading policy from URL (https://myserver.de/matrix/policy/policy.json): invalid character ']' looking for beginning of value"
Apr 29 17:52:09 matrix matrix-corporal[15979]: panic: Failed loading policy from remote (invalid character ']' looking for beginning of value) and from cache (invalid character ']' looking for beginning of value)

The documentation of matrix-corporal is a bit vague concerning the correct value for matrix_corporal_policy_provider_config / uri parameter.
let'S say I have the file in https://myserver.com/matrix/profiles/profiles.json, would I fill in the complete path or would I omit the file (like https://myserver.com/matrix/profiles)?

I already tried both but only keep getting errors. 

Sorry to bug you with that, but still I hope you can help ;-)

Best, Tom

**Comment by spantaleev** [comment]
`uri` needs to point to the file, not to some parent directory.

Maybe the file is malformed and that's why it fails with this error?

matrix-corporal is also caching the file locally (in `CachePath`), so you can take a look at that and see what data it's working with.
