### ISSUE TITLE
Playbook looking for Docker-Repository. Ubuntu 20.04 Focal does not require Docker Repository anymore

### ISSUE THREAD

**Issue by schwony** [spantaleev/matrix-docker-ansible-deploy#482]
Trying to run the playbook on an upgraded Ubuntu Focal 20.04 installation. It fails looking for Docker-Repository. There are no 'focal' release files in the repository as it is not required anymore. Any chance of fixing this issue?

Thank you very much for your great work.

**Comment by spantaleev** [comment]
You can install Docker manually and set `matrix_docker_installation_enabled: false` in your `vars.yml` file to make the playbook not try to install Docker by itself.

**Comment by SuperSandro2000** [comment]
Just install the docker from Eoan.

**Comment by spantaleev** [comment]
Maybe we should keep an eye on https://github.com/docker/for-linux/issues/992 for a while.

If it doesn't get resolved soon, we should probably consider defaulting `matrix_docker_installation_enabled` to `false` on Ubuntu 20.04, or updating our docs to let people know what to do.

---------

For anyone manually installing Docker on Ubuntu 20.04, note that:
- the package is called `docker.io`, not `docker`
- you also need to install `python3-docker`

That is, you need to do: `apt-get install docker.io python3-docker`

You also need `matrix_docker_installation_enabled: false` in your `vars.yml` file.

**Comment by schwony** [comment]
with the instructions above the playbook gets stuck while the pulling mailer image:

"Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on *server* Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named requests.exceptions"}"

**Comment by spantaleev** [comment]
Probably because there's also Python 2 on the server and that's what Ansible is using.
If you get rid of it, it may work.

Alternatively, you should install `docker-py` somehow. It didn't seem like there's a package, so maybe installing through `pip` is necessary.

**Comment by schwony** [comment]
yep! that worked. I purged all python2 incl. dependencies and the playbook ran through. 

greatly appreciate your help!

**Comment by spantaleev** [comment]
Looks like these hacks shouldn't be required anymore, because https://github.com/docker/for-linux/issues/992 has been resolved.
