### ISSUE TITLE
Defaults for adding rooms to a community?

### ISSUE THREAD

**Issue by jasonkolodziej** [spantaleev/matrix-docker-ansible-deploy#489]
I keep getting an error when I try to add a room to a community is this a configuration issue or a riot issue?

**Comment by spantaleev** [comment]
You're not telling us what the error is, or if there's anything in the Synapse logs (`journalctl -fu matrix-synapse`).

**Comment by jasonkolodziej** [comment]
@spantaleev When I run this no logs will print for synapse.
Basically, I try adding a room on my instance of riot (underneath the community I created).
![image](https://user-images.githubusercontent.com/42076058/81475372-5f393b00-91d1-11ea-91c0-5f334726db68.png)

After doing so the room does not show up in the community, rather it shows up as a room that I created personally. (see below)
![image](https://user-images.githubusercontent.com/42076058/81475394-85f77180-91d1-11ea-8f7c-eaa5f75e9beb.png)


So I navigate to the community settings and click "Add Rooms" and paste the room id into the input bar. This is the error to follow.
![image](https://user-images.githubusercontent.com/42076058/81475316-f6ea5980-91d0-11ea-9b75-edab83f899bd.png)

**Comment by jasonkolodziej** [comment]
I might be doing something incorrectly, as I am new to this... But I would appreciate you or anyone else's feedback  (-:

**Comment by aaronraimist** [comment]
The communities feature of Synapse is fairly broken. I wouldn't use it unless you are willing to deal with weird issues like this. Most likely this is https://github.com/matrix-org/synapse/issues/4891 or a related issue. You would have to look at your Synapse logs.

It isn't an issue with this playbook.
