### ISSUE TITLE
Enable etherpad for jitsi

### ISSUE THREAD

**Issue by tomkel** [spantaleev/matrix-docker-ansible-deploy#493]
See https://github.com/jitsi/docker-jitsi-meet#shared-document-editing-using-etherpad

2. https://github.com/jitsi/jitsi-meet/wiki/Etherpad-addition-example

**Comment by spantaleev** [comment]
If someone would like to work on adding this as an optional service (behind some flag like `matrix_jitsi_etherpad_enabled`, defaulting to `false`), that'd be great!

**Comment by pushytoxin** [comment]
I stumbled upon this open issue, it can be closed since PR #804 has been merged that contains this change.

**Comment by spantaleev** [comment]
Good catch! Thanks!
