### ISSUE TITLE
I got a issue when I install on my Ubuntu 20.04 LTS?

### ISSUE THREAD

**Issue by elohffa** [spantaleev/matrix-docker-ansible-deploy#496]
The full traceback is:
  File "/tmp/ansible_apt_repository_payload_7yyt4ub7/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 591, in update
    raise FetchFailedException(e)
fatal: [matrix.xxxxxxx.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": null,
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable",
            "state": "present",
            "update_cache": true,
            "validate_certs": true
        }

**Comment by pushytoxin** [comment]
This is not a tech support forum, come join us at ﻿#matrix-docker-ansible-deploy:devture.com!

**Comment by spantaleev** [comment]
Also, take a look at #482.
