### ISSUE TITLE
Fail install on Pi4

### ISSUE THREAD

**Issue by elohffa** [spantaleev/matrix-docker-ansible-deploy#501]
Hi , I m using the following setting in my vars.yml , I enable the matrix_architecture  as arm64. 

# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# Example value: example.com
matrix_domain: xxx.com

#matrix_container_images_self_build: true

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: elohffa@gmail.com

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "9SssafaJeAgvtNf3mKTixxMaxOdRS5G0wG9FqCp9zGi7Lo76TI5vJ3hUAxfIW"

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "jqZXmePJ1F8y1b6PulzRIlfasfaiQMtVbXOV71YRojWRzhUCa8vbJjC7hfqbvSYP"

matrix_architecture: "arm64" 

And I shoot a  command " ansible-playbook -vvv -i inventory/hosts setup.yml --tags=setup" to start the batching work, it looks everything is fine, 
: ok=15   changed=0    unreachable=0    failed=0    skipped=65   rescued=0    ignored=0   

So what is the problem, when I shoot a command "ansible-playbook -vvv -i inventory/hosts setup.yml --tags=start" to start the program, then it is telling me something go wrong, the error message 

failed: [matrix.xxx.com] (item=matrix-mailer) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": false, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": "matrix-mailer", 
            "no_block": false, 
            "scope": null, 
            "state": "stopped", 
            "user": null
        }
    }, 
    "item": "matrix-mailer", 
    "msg": "Could not find the requested service matrix-mailer: host"
}
failed: [matrix.xxx.com] (item=matrix-postgres) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": false, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": "matrix-postgres", 
            "no_block": false, 
            "scope": null, 
            "state": "stopped", 
            "user": null
        }
    }, 
    "item": "matrix-postgres", 
    "msg": "Could not find the requested service matrix-postgres: host"
}

failed: [matrix.xxx.com] (item=matrix-synapse) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": false, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": "matrix-synapse", 
            "no_block": false, 
            "scope": null, 
            "state": "stopped", 
            "user": null
        }
    }, 
    "item": "matrix-synapse", 
    "msg": "Could not find the requested service matrix-synapse: host"
}

failed: [matrix.xxx.com] (item=matrix-riot-web) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": false, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": "matrix-riot-web", 
            "no_block": false, 
            "scope": null, 
            "state": "stopped", 
            "user": null
        }
    }, 
    "item": "matrix-riot-web", 
    "msg": "Could not find the requested service matrix-riot-web: host"
}

failed: [matrix.xxx.com] (item=matrix-ma1sd) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": false, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": "matrix-ma1sd", 
            "no_block": false, 
            "scope": null, 
            "state": "stopped", 
            "user": null
        }
    }, 
    "item": "matrix-ma1sd", 
    "msg": "Could not find the requested service matrix-ma1sd: host"
}

failed: [matrix.xxx.com] (item=matrix-coturn) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": false, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": "matrix-coturn", 
            "no_block": false, 
            "scope": null, 
            "state": "stopped", 
            "user": null
        }
    }, 
    "item": "matrix-coturn", 
    "msg": "Could not find the requested service matrix-coturn: host"
}

then i use docker ps to list the installed image, and the list is empty. 
Can u let me know , how can I fix this ? or give me a url  to pull the docker image  in arm64

**Comment by aaronraimist** [comment]
Ok well for one. Do not post those secret keys such as `matrix_synapse_macaroon_secret_key` and `matrix_coturn_turn_static_auth_secret`. You need to change those now since you shared them publicly.

Second, can you please put the config file into a code block? https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by elohffa** [comment]
Ok. Thanks your advice,  I know the key is important, the pair of keys are fake .  for creating better outlook of design of the block , I will take a look and next time I will take care the block in better outlook. So what is the solution u can suggest to help me fix my issue?

**Comment by spantaleev** [comment]
You said you're running some command like this:

```
ansible-playbook -vvv -i inventory/hosts setup.yml --tags=setup
```

There's no `setup` tag in the playbook. The tag we have is called `setup-all`. So you need to run this first:

```
ansible-playbook -vvv -i inventory/hosts setup.yml --tags=setup-all
```

You can then proceed to run `--tags=start`.

**Comment by elohffa** [comment]
new error was happening 

The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_apt_repository_payload_z9H3Zp/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 588, in update
    raise FetchFailedException()
fatal: [matrix.psycrypto.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "codename": null, 
            "filename": null, 
            "install_python_apt": true, 
            "mode": null, 
            "repo": "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable", 
            "state": "present", 
            "update_cache": true, 
            "validate_certs": true
        }
    }, 
    "msg": "apt cache update failed"
}

**Comment by dasTholo** [comment]
I'm not sure, but shouldn't a Pi Distro be "aarch64" or "arm"
` uname -a` will show you like this

> tholo@hassrk:~$ uname -a
Linux hassrk 4.4.213-rk3399 #23 SMP Sat Mar 28 16:58:50 CET 2020 **aarch64** GNU/Linux

I think amd64 is wrong here
