### ISSUE TITLE
Let's Encrypt to deprecate ACME v1 in June 2020

### ISSUE THREAD

**Issue by admrulankor** [spantaleev/matrix-docker-ansible-deploy#504]
Reverse-proxy would not work beyond June, how to fix this?

**Comment by spantaleev** [comment]
Why wouldn't it?

We use [certbot](https://certbot.eff.org/) which should support ACME v2. I think we're fine.

**Comment by aa1874** [comment]
Aaaahh, okay then, I don't know that. Thanks!
