### ISSUE TITLE
3PIDs not shown in user settings / reverse proxy issue?

### ISSUE THREAD

**Issue by rootuser** [spantaleev/matrix-docker-ansible-deploy#505]
Hello,

I am trying to find the reason for an issue I discovered yesterday:
3PIDs are not shown on a users settings page (I have only tried that thoroughly with email addresses though).

At first I posted this error in the riot web issue tracker, so all the details can be found there, if necessary [https://github.com/vector-im/riot-web/issues/13033](url)

In short it's like this: Emails are not shown in user settings in riot web and riotX (Android). In the old riot.im app emails are displayed correctly.
Also, I can successfully request the 3PID list via client-server API.
So I guess riot web and riot x use the identity service API, while riot.im uses client api.

Now I noticed in my browser (with developer tools active) that there seems to be an issue with the identity server; when opening the setings page I get:

> Access to XMLHttpRequest at 'https://matrix.ohoco.de/_matrix/identity/v2/account/register' from origin 'https://riot.ohoco.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The identity server responds with a
> HTTP/1.1 405 Method Not Allowed

The question is now: why is that header not send? In the issue linked above, t3chguy suggests it might be a reverse proxy issue.
I have gone through your installation instructions again, but could not find any error in my configuration.

Do you perhaps have an idea what I could look for?
Thanks for any hint!

Best, Tom

**Comment by ns130291** [comment]
same as #503
