### ISSUE TITLE
to use let's encrypt for all the subdomains but inject an existing crt for the TLD

### ISSUE THREAD

**Issue by TwoTwenty** [spantaleev/matrix-docker-ansible-deploy#506]
use the standard play's Let;s encrypt to get:
matrix.example.com
riot.example.com
jitsi.example.com
dimesnion.example.com
etc.example.com

but provide an option to inject the base domain's certificate
example.com

**Comment by spantaleev** [comment]
We have such an option. See [Obtaining SSL certificates for additional domains](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ssl-certificates.md#obtaining-ssl-certificates-for-additional-domains)

If you're hosting the base domain on the same server and can afford to let the playbook manage it, there's an even easier way. You can just tell the playbook to [serve the base domain](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-base-domain-serving.md) and it will do everything for you (including obtaining the SSL certificate).
