### ISSUE TITLE
default matrix_mautrix_telegram_docker_image doesn't work

### ISSUE THREAD

**Issue by 26fiftysix** [spantaleev/matrix-docker-ansible-deploy#509]
Default variable set for matrix_mautrix_telegram_docker_image doesn't work.

## Error
With the defaults it errors out on:
`TASK [matrix-bridge-mautrix-telegram : Ensure Mautrix Telegram image is pulled] **********
fatal: [example.com]: FAILED! => {"changed": false, "msg": "Error pulling image dock.mau.dev/tulir/mautrix-telegram:v0.7.0 - 404 Client Error: Not Found (\"manifest for dock.mau.dev/tulir/mautrix-telegram:v0.7.0 not found: manifest unknown: manifest unknown\")"}`

## Steps to reproduce
Enable the matrix telegram bridge and run the playbook with the default options for matrix_mautrix_telegram_docker_image:
`matrix_mautrix_telegram_docker_image: "dock.mau.dev/tulir/mautrix-telegram:v0.7.0"`

## Solution:
Change the defaults for matrix_mautrix_telegram_docker_image, removing colon + version number (:v0.7.0)
`matrix_mautrix_telegram_docker_image: "dock.mau.dev/tulir/mautrix-telegram"`

**Comment by spantaleev** [comment]
`docker pull dock.mau.dev/tulir/mautrix-telegram:v0.7.0` works for me.

Changing to just `dock.mau.dev/tulir/mautrix-telegram`, which is equivalent to `dock.mau.dev/tulir/mautrix-telegram:latest` doesn't sound like a good idea. We'd rather use a specific version, when available.

**Comment by 26fiftysix** [comment]
I don't have much knowledge about this. So maybe I'm wrong here. But since `matrix_mautrix_telegram_docker_image_force_pull` looks like this:
`"{{ matrix_mautrix_telegram_docker_image.endswith(':latest') }}"`

Doesn't it try to pull `dock.mau.dev/tulir/mautrix-telegram:v0.7.0:latest`?

**Comment by spantaleev** [comment]
No..

```yaml
matrix_mautrix_telegram_docker_image_force_pull: "{{ matrix_mautrix_telegram_docker_image.endswith(':latest') }}"
```

.. should end up putting a `true` or `false` value in `matrix_mautrix_telegram_docker_image_force_pull`, indicating whether to force-pull or not. We'd like to force-pull when the tag is `:latest`, because that tag is repointed to newer and newer versions. If `:latest` is used, we'd rather ensure we've refetched it each and every time. Other tags (like `v0.7.0`) are supposedly static, so force-fetching them should not be necessary.

**Comment by 26fiftysix** [comment]
Alright, thanks for the explanation. I just know that the playbook gave me that error until I removed `:v0.7.0` from the `default matrix_mautrix_telegram_docker_image`.

Thanks for this project too! I got a matrix server up and running in no time! Documentation was very easy to follow.

**Comment by spantaleev** [comment]
Thank you for the kind words!

Not sure why the Telegram image failed.. You can try with the default again later on.. Or pulling manually on the server (`docker pull dock.mau.dev/tulir/mautrix-telegram:v0.7.0`).
