### ISSUE TITLE
Setup in a LXD ubuntu VM without success

### ISSUE THREAD

**Issue by G-eos** [spantaleev/matrix-docker-ansible-deploy#515]
Hi, I try to setup into a lxd container ubuntu host, ubuntu VM without success.
Unfortunately either in /var/log/syslog or journalctl I found nothing relevant (but I do not know what to search for).
The container has priviledge true and I can run unbuntu docker image into the VM.

docker ps -a is empty :-(

The whole ansible playbook run correcty !  Where are the container :)

PLAY RECAP *************************************************************************************************************************************************************************************
matrix.yyyyy.com        : ok=141  changed=17   unreachable=0    failed=0    skipped=449  rescued=0    ignored=0   

docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
vectorim/riot-web       v1.6.2              876c6abdef20        25 hours ago        42.9MB
matrixdotorg/synapse    v1.13.0             8cae8418a844        4 days ago          261MB
postgres                12.3-alpine         bd3eeea38a5a        7 days ago          151MB
certbot/certbot         amd64-v1.4.0        69f1cc16b9f8        2 weeks ago         163MB
instrumentisto/coturn   4.5.1.2             74a2e7a8c564        2 weeks ago         18.9MB
nginx                   1.17.10-alpine      89ec9da68213        4 weeks ago         19.9MB
ma1uta/ma1sd            2.3.0               691422562f68        3 months ago        130MB
devture/exim-relay      4.92.2-r0-0         87ce1eb229e0        8 months ago        9.28MB

Thanks !

**Comment by spantaleev** [comment]
Containers are only created and started when you start services (running the playbook with `--tags=start`). Containers are started by the `matrix-` systemd services (see `ls /etc/systemd/system/`).

Looks like you've done the `--tags=setup-all` part of [Installing](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/4c4f208613230d652043a334b8645f8e80bfef81/docs/installing.md), but you haven't done the `--tags=start` part yet.

**Comment by G-eos** [comment]
oh yes :-( Thanks a lot to have spend the time to answer to such an issue ! RTFM !!!
