### ISSUE TITLE
no proper video conference, whenever more than two participants are involved ...

### ISSUE THREAD

**Issue by andreas-dc** [spantaleev/matrix-docker-ansible-deploy#519]
Hello,

Once again I need to point out the excellence of the project first. I really like it.

I followed the configuration/installation script to the letter. My Jitsi section of vars.yml is:

matrix_jitsi_enabled: true
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true
matrix_jitsi_jicofo_component_secret: xxx
matrix_jitsi_jicofo_auth_password: xxx
matrix_jitsi_jvb_auth_password: xxx
matrix_jitsi_jibri_recorder_password: xxx
matrix_jitsi_jibri_xmpp_password: xxx

All necessary ports are open. I do arrive at the Jitsi server directly (skipping Matrix) from regular home networks (without port restrictions). Even when I turn off the firewall of the docker host completely, the Jitsi server fails to serve a conference to more than 2 participants. There is no obvious crash, just all video screens (of all conference members) turning black. Whenever I go back to p2p, the session revitalises properly.

Do you have any idea why? Is there any chance to study logs? Since the services are not started normally (s6 is used), I can't find jicofo.log, prosody.log or jvb.log in their usual locations. Probably I simply don't recognise the path of the files being put. Maybe someone can point me into proper directions? Maybe there is some rerouting to any kind of docker logs happening. I'm new to ansible and docker.

Much thx for reading,
Andreas

**Comment by andreas-dc** [comment]
It seems like setting "--log-driver=json-file" within the systemd service description on the docker host does the trick in logging. But so far the messages were unfortunately of no help.

**Comment by spantaleev** [comment]
Logs go straight to journald. Use `journalctl -fu matrix-jitsi-SOMETHING`.

You don't need to do the `--log-driver=json-file` hack :)

If you're trying to use the Jitsi server from the local network of your Matrix server, you may need to take a look at #473.

Also, Jitsi reportedly has some problems on Firefox, so you may wish to try another browser (like Chromium/Chrome)

**Comment by andreas-dc** [comment]
Much thx for your very quick response, spantaleev! "Journalctl" is enough for me, I immediately undid the hack. ;)

Did you mean, if I was trying to access the Jitsi server locally? Clients and server in the same network? This is not the case. The docker host (incl. Matrix and Jitsi containers) is located in a remote data centre, being accessible via public ip.

I've been using Opera, whenever it comes to video conferencing, for a while.

**Comment by spantaleev** [comment]
> Did you mean, if I was trying to access the Jitsi server locally? Clients and server in the same network? This is not the case. The docker host (incl. Matrix and Jitsi containers) is located in a remote data centre, being accessible via public ip.

That's what I mean, yes. If you're accessing it through the public IP, then you don't need to do anything special.

You should probably look at our Prerequisites docs page and see to it that you've whitelisted all ports in your firewall.

**Comment by cnvandijk** [comment]
Depending on how you are doing NAT on your firewall, you may need more than just whitelisting ports. Specifically, jvb uses stun to get the external IP, causing incoming packets to have the external IP of your firewall, and not the jvb server.

**Comment by andreas-dc** [comment]
Much thanks to both of you for your input! I appreciate it very much.

I'm coming to the conclusion, that the firewall set up is fishy. For now I have a rather generous setup, when it comes to allowing access to Matrix and Jitsi:

iptables -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --dport 4443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 4443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --dport 5349 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 5349 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp --dport 5349 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp --sport 5349 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp --dport 10000 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp --sport 10000 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp --dport 49152:49172 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp --sport 49152:49172 -m conntrack --ctstate ESTABLISHED -j ACCEPT

While having no desire to run federation. ;) Cheers, Andreas

PS. While checking passage for Port 10000/UDP into the matrix (docker) network, I've not been successful so far. Busybox and Netcat were my friends in doing the analysis. But to no avail. I didn't get access from the outside. Most likely it's much too obvious. ;) Do you recognise any mistakes in the abovementioned rules?

**Comment by andreas-dc** [comment]
Need to correct myself. Firing up a busybox (attached to the docker network "matrix") and netcat (listening @port 10000/udp) gave me the chance to verify the connection. It works, coming from another public server. Strange ... Cheers, Andreas

**Comment by andreas-dc** [comment]
@cnvandijk: I need to confess, I don't really get it. Do you like to elaborate on this? Where do you see the troubles exactly?

By the way I've experimented in getting rid of the aws harvester, tcp harvester and stun mechanism (to offer the external ip of the docker host to jvb directly) in the meantime as well. I also manually set up "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS". @spantaleev: Guilty as charged, I did a little hacking again. ;) This time it struck ../matrix-docker-ansible-deploy/roles/matrix-jitsi/templates/jvb/sip-communicator.properties.j2. Didn't help with my problem.

But during my excursion through the jvb startup script (/var/run/s6/services/jvb/run@matrix-jitsi-jvb) I stumbled upon the following lines:

if [[ ! -z "$DOCKER_HOST_ADDRESS" ]]; then
    LOCAL_ADDRESS=$(hostname -I | cut -d " " -f1)
    JAVA_SYS_PROPS="$JAVA_SYS_PROPS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$LOCAL_ADDRESS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$DOCKER_HOST_ADDRESS"
fi

Inside of matrix-jitsi-jvb the environment variable docker_host_address does not exist. Where should it come from? Is there any chance, that it is resolved nonetheless during the startup of the script? Surely a beginner's question again. ;)

Cheers
Andreas

**Comment by andreas-dc** [comment]
Figured it out. The variable DOCKER_HOST_ADDRESS is usually set in the appropriate ".env" file. Thus, I couldn't resist but do a hack again. ;) I added "DOCKER_HOST_ADDRESS=xxx" to ../matrix-docker-ansible-deploy/roles/matrix-jitsi/templates/jvb/env.j2. And voila ... the conference is coming up with 3 participants. "journalctl -fu matrix-jitsi-jvb" confirms it, showing lots of activity now.

My ../matrix-docker-ansible-deploy/roles/matrix-jitsi/templates/jvb/sip-communicator.properties.j2 file deactivates aws harvester, tcp harvester and stun. It looks like:
org.jitsi.videobridge.DISABLE_AWS_HARVESTER=true
org.jitsi.videobridge.SINGLE_PORT_HARVESTER_PORT={{ matrix_jitsi_jvb_rtp_udp_port }}
org.jitsi.videobridge.DISABLE_TCP_HARVESTER=true
org.jitsi.videobridge.TCP_HARVESTER_PORT={{ matrix_jitsi_jvb_rtp_tcp_port }}

org.jitsi.videobridge.xmpp.user.shard.HOSTNAME={{ matrix_jitsi_xmpp_server }}
org.jitsi.videobridge.xmpp.user.shard.DOMAIN={{ matrix_jitsi_xmpp_auth_domain }} ... now.

**Comment by spantaleev** [comment]
@andreas-dc, we mention `DOCKER_HOST_ADDRESS` on our Jitsi docs page. There's a way to set it (using `matrix_jitsi_jvb_container_extra_arguments`), without modifying `roles/matrix-jitsi/templates/jvb/env.j2`.

**Comment by andreas-dc** [comment]
Lovely, much thx, Spantaleev. Worked like a charm. No need for a hack anymore. Video conference comes up with more than 2 participants. I'll keep it in mind, whenever similar config necessities arise.

Thus, it seems like your 1st idea was the right one. Although my troubles actually did not relate to the necessity getting access to Jitsi via LAN. For me it seems the setting is essential, whenever you try to inhibit jvb figuring out its location by itself (via aws, tcp harvester / stun). Don't you think, this might become standard? Which might lead to the question .. What do I still need the handbook's coturn server for?

Jitsi meet usually comes with a coturn server as well. Which appears quite lovely in theory (never personally succeeded so far in using it), whenever you try to establish connections to jvb although port 10000/UDP can not be accessed (via corporate firewall etc.). Meaning, the traffic goes through port 443/TCP, which is usually claimed by the web server. But since the basic jitsi meet install comes with an interesting config (using ssl_preread_alpn_protocols in /etc/nginx/modules-enabled/60-jitsi-meet.conf), the webserver is able to differentiate the traffic. As far as I can perceive, your handbook does not apply this module / these settings. So, I repeat myself, what do I need the handbook's coturn server for?

Cheers
Andreas

**Comment by spantaleev** [comment]
Coturn in the playbook serves multiple purposes by default:
- it is used as a STUN server for Jitsi (its web component)
- it is used for normal 1 on 1 VoIP calls in Riot (not Jitsi)
