### ISSUE TITLE
Add a config variable to change the listening port for the federation api

### ISSUE THREAD

**Issue by j027** [spantaleev/matrix-docker-ansible-deploy#523]
This will allow for federation to still work with cloudflare enabled. Currently it is hardcoded to port 8448

**Comment by spantaleev** [comment]
We can introduce a new `matrix_federation_public_port` variable in `roles/matrix-base/defaults/main.yml` and have that control various other things that hardcode `8448`.

I'm guessing the `matrix_federation_public_port` variable should be used as a base (default) value for various other variables. It seems like we currently use `8448` for configuration in `matrix-nginx-proxy`, but also for generating the well-known static files in `matrix-base`. Perhaps people should be able to use a different value for these 2 use-cases?

I'm not sure I can imagine your Cloudflare setup and what exactly you'd like to change.

**Comment by j027** [comment]
Cloudflare only proxies the ports listed here, https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy so any of the other ports get blocked

**Comment by spantaleev** [comment]
I see! Sounds like we should make it configurable anyway.. We've had discussions about it a month ago as well (@jdreichmann).
