### ISSUE TITLE
Add documentation/config examples for Synapse SSO

### ISSUE THREAD

**Issue by tctovsli** [spantaleev/matrix-docker-ansible-deploy#526]
Would be nice with documentation describing setting up SSO.

**Comment by spantaleev** [comment]
This sounds like something that should be documented on the [Synapse](https://github.com/matrix-org/synapse) side.

On our side, you can use the `matrix_synapse_configuration_extension_yaml` variable to inject any settings (into `homeserver.yaml`) for which we don't have a dedicated variable.

**Comment by ptman** [comment]
https://github.com/matrix-org/synapse/issues/5764#issuecomment-625194187

https://github.com/matrix-org/synapse/blob/develop/docs/dev/oidc.md
