### ISSUE TITLE
Pi4 Docker: No such container: matrix-ma1sd

### ISSUE THREAD

**Issue by TheNyneR** [spantaleev/matrix-docker-ansible-deploy#529]
First of all thanks for providing such an easy to use program for setting up synapse.
I am currently trying to set up a synapse server on my Raspberry Pi 4 on which i installed Manjaro ARM (based on ArchLinux).
I followed the install documentation and can run the setup-all tag after I set 
`
matrix_ssl_retrieval_method: maually-managed
`
and
`
matrix_ssl_config_dir_path: /etc/letsencrypt/
`
because there were some problems in obtaining the certificates automatically.

With this the setup-all tag completes successfully but the start tag returns with errors.
`journalctl -fu matrix-ma1sd.service`

> Jun 01 22:46:15 kaze systemd[1]: matrix-ma1sd.service: Failed with result 'exit-code'.
Jun 01 22:46:45 kaze systemd[1]: matrix-ma1sd.service: Scheduled restart job, restart counter is at 122.
Jun 01 22:46:45 kaze systemd[1]: Stopped Matrix ma1sd Identity server.
Jun 01 22:46:45 kaze systemd[1]: Starting Matrix ma1sd Identity server...
Jun 01 22:46:45 kaze matrix-ma1sd[1911952]: Error response from daemon: Cannot kill container: matrix-ma1sd: No such container: matrix-ma1sd
Jun 01 22:46:45 kaze matrix-ma1sd[1911987]: Error: No such container: matrix-ma1sd
Jun 01 22:46:45 kaze systemd[1]: Started Matrix ma1sd Identity server.
Jun 01 22:46:47 kaze matrix-ma1sd[1912021]: standard_init_linux.go:211: exec user process caused "exec format error"
Jun 01 22:46:48 kaze systemd[1]: matrix-ma1sd.service: Main process exited, code=exited, status=1/FAILURE
Jun 01 22:46:48 kaze systemd[1]: matrix-ma1sd.service: Failed with result 'exit-code'.

This occurs for matrix-coturn, matrix-ma1sd, matrix-mailer and matrix-riot-web.

**Comment by spantaleev** [comment]
Have you seen our [Alternative architectures](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/alternative-architectures.md) and [Self-building](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/self-building.md) docs pages?

You should probably use something like this:

```yaml
matrix_architecture = "arm32"
matrix_container_images_self_build: true
```

.. and then run the playbook with `--tags=setup-all` and `--tags=start` again.

**Comment by TheNyneR** [comment]
With the change to `matrix_architecture` I get 

> TASK [matrix-ma1sd : Ensure gradle is installed for self-building (Archlinux)] *************************************************************************
fatal: FAILED! => {"changed": false, "msg": "failed to install gradle: error: target not found: gradle\n"}

during the `--tags=setup-all`.
Also `uname -m` returns `aarm64` so i tried `matrix_architecture: "arm64"` which returned with the same error as above.

**Comment by spantaleev** [comment]
Looks like installing the `gradle` package on ARM-based Archlinux fails. It says there's no such package.

For regular `x86_64` Archlinux, the `gradle` package is part of the `community` repository. Maybe it's not available for ARM though.

I'm not sure why you managed to install manually with `sudo pacman -S gradle` and why Ansible fails to do the same though. Perhaps adding `-vvv` to the `ansible-playbook` command will tell us more.

----------

You can try removing that failing task from the playbook and carrying on to see if something else breaks.

----------------

Another way to solve the problem would be to just disable `ma1sd` by adding `matrix_ma1sd_enabled: false` to your `vars.yml` file.

**Comment by TheNyneR** [comment]
I actually installed the package `gradle-rc` with yay (Yet Another Yaourt).
This one doesn't ship with `gradlew` but just with `gradle` command.

I set `matrix_ma1sd_enabled: false` and `--tags=setup-all` works but i still get the "no such container" message for `matrix-riot-web`, `matrix_mailer` and `matrix-coturn`.

**Comment by spantaleev** [comment]
Have you done `--tags=start` after that?

**Comment by TheNyneR** [comment]
Yes `--tags=start` has errors like 

> "msg": "matrix-coturn was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-coturn` and `journalctl -fu matrix-coturn` on the server to investigate."

for the three containers and `journalctl -fu` returns 

> Jun 02 13:24:29 kaze systemd[1]: matrix-mailer.service: Failed with result 'exit-code'.
Jun 02 13:24:59 kaze systemd[1]: matrix-mailer.service: Scheduled restart job, restart counter is at 3893.
Jun 02 13:24:59 kaze systemd[1]: Stopped Matrix mailer.
Jun 02 13:24:59 kaze systemd[1]: Starting Matrix mailer...
Jun 02 13:24:59 kaze matrix-mailer[3379190]: Error response from daemon: Cannot kill container: matrix-mailer: No such container: matrix-mailer
Jun 02 13:24:59 kaze matrix-mailer[3379198]: Error: No such container: matrix-mailer
Jun 02 13:24:59 kaze systemd[1]: Started Matrix mailer.
Jun 02 13:25:01 kaze matrix-mailer[3379205]: [FATAL tini (6)] exec exim failed: Exec format error
Jun 02 13:25:02 kaze systemd[1]: matrix-mailer.service: Main process exited, code=exited, status=1/FAILURE
Jun 02 13:25:02 kaze systemd[1]: matrix-mailer.service: Failed with result 'exit-code'.

for all of them.

**Comment by spantaleev** [comment]
This indicates that the Docker image it's trying to use is for the wrong architecture.

Maybe it's not building the image, because it already finds one that exists (because you hadn't enabled self-building, etc. before-hand and it pulled down some images for other architectures).

Perhaps you should try deleting said images and you should re-run the playbook again.

Try:

- `systemctl stop matrix*`
- `docker kill $(docker ps -aq)`
- `docker rm $(docker ps -aq)`
- `docker rmi --force $(docker images -aq)`
- re-run the playbook (`--tags=setup-all,start`)

**Comment by TheNyneR** [comment]
`docker ps -aq` returns nothing but the images can be removed.

Re-running `--tags=setup-all,start` results in an error of `matrix-mailer` not being a container, while `matrix-postgres, matrix-mautrix-whatsapp, matrix-synapse, matrix-nginx-proxy, matrix-coturn` are skipped. 
The skipped services also say `no such container` but seem to get started anyways.

> Jun 03 19:26:06 kaze matrix-postgres[1826560]: Error: No such container: matrix-postgres
Jun 03 19:26:06 kaze systemd[1]: Started Matrix Postgres server.
Jun 03 19:26:08 kaze matrix-postgres[1826575]: chmod: /var/run/postgresql: Operation not permitted
Jun 03 19:26:08 kaze matrix-postgres[1826575]: PostgreSQL Database directory appears to contain a database; Skipping initialization
Jun 03 19:26:09 kaze matrix-postgres[1826575]: 2020-06-03 17:26:09.336 UTC [1] LOG:  starting PostgreSQL 12.3 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
Jun 03 19:26:09 kaze matrix-postgres[1826575]: 2020-06-03 17:26:09.336 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Jun 03 19:26:09 kaze matrix-postgres[1826575]: 2020-06-03 17:26:09.336 UTC [1] LOG:  listening on IPv6 address "::", port 5432
Jun 03 19:26:09 kaze matrix-postgres[1826575]: 2020-06-03 17:26:09.338 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Jun 03 19:26:09 kaze matrix-postgres[1826575]: 2020-06-03 17:26:09.378 UTC [14] LOG:  database system was shut down at 2020-06-03 16:45:53 UTC
Jun 03 19:26:09 kaze matrix-postgres[1826575]: 2020-06-03 17:26:09.385 UTC [1] LOG:  database system is ready to accept connections

**Comment by TheNyneR** [comment]
During install of matrix-mailer the tasks 
`Ensure mailer base path exists`, `Ensure mailer environment variables file created`, `Ensure mailer image is pulled`, `Ensure matrix-mailer.service installed` 

are marked as `ok` while 

`Ensure systemd reloaded after matrix-mailer.service installation`, `Check existence of matrix-mailer service`, `Ensure matrix-mailer is stopped`, `Ensure matrix-mailer.service doesn't exist`, `Ensure systemd reloaded after matrix-mailer.service removal`, `Ensure Matrix mailer environment variables path doesn't exist` and `Ensure mailer Docker image doesn't exist` 

are all `skipped`.

Also the error output of the `--tags=start` is:

> "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "ansible_loop_var": "item",
        "changed": false,
        "failed": false,
        "invocation": {
            "module_args": {
                "daemon_reexec": false,
                "daemon_reload": false,
                "enabled": null,
                "force": null,
                "masked": null,
                "name": "matrix-mailer",
                "no_block": false,
                "scope": null,
                "state": null,
                "user": null
            }
        },
        "item": "matrix-mailer",
        "name": "matrix-mailer",
        "status": {
            "ActiveEnterTimestamp": "Fri 2020-06-05 16:34:14 CEST",
            "ActiveEnterTimestampMonotonic": "400592749328",
            "ActiveExitTimestamp": "Fri 2020-06-05 16:34:17 CEST",
            "ActiveExitTimestampMonotonic": "400595653537",
            "ActiveState": "activating",
            "After": "docker.service systemd-journald.socket system.slice basic.target sysinit.target",
            "AllowIsolate": "no",
            "AllowedCPUs": "",
            "AllowedMemoryNodes": "",
            "AmbientCapabilities": "",
            "AssertResult": "yes",
            "AssertTimestamp": "Fri 2020-06-05 16:34:14 CEST",
            "AssertTimestampMonotonic": "400592514743",
            "Before": "multi-user.target shutdown.target",
            "BlockIOAccounting": "no",
            "BlockIOWeight": "[not set]",
            "CPUAccounting": "no",
            "CPUAffinity": "",
            "CPUAffinityFromNUMA": "no",
            "CPUQuotaPerSecUSec": "infinity",
            "CPUQuotaPeriodUSec": "infinity",
            "CPUSchedulingPolicy": "0",
            "CPUSchedulingPriority": "0",
            "CPUSchedulingResetOnFork": "no",
            "CPUShares": "[not set]",
            "CPUUsageNSec": "[not set]",
            "CPUWeight": "[not set]",
            "CacheDirectoryMode": "0755",
            "CanIsolate": "no",
            "CanReload": "no",
            "CanStart": "yes",
            "CanStop": "yes",
            "CapabilityBoundingSet": "cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend cap_audit_read",
            "CleanResult": "success",
            "CollectMode": "inactive",
            "ConditionResult": "yes",
            "ConditionTimestamp": "Fri 2020-06-05 16:34:14 CEST",
            "ConditionTimestampMonotonic": "400592514742",
            "ConfigurationDirectoryMode": "0755",
            "Conflicts": "shutdown.target",
            "ControlPID": "0",
            "DefaultDependencies": "yes",
            "DefaultMemoryLow": "0",
            "DefaultMemoryMin": "0",
            "Delegate": "no",
            "Description": "Matrix mailer",
            "DevicePolicy": "auto",
            "DynamicUser": "no",
            "EffectiveCPUs": "",
            "EffectiveMemoryNodes": "",
            "ExecMainCode": "1",
            "ExecMainExitTimestamp": "Fri 2020-06-05 16:34:17 CEST",
            "ExecMainExitTimestampMonotonic": "400595652855",
            "ExecMainPID": "2476083",
            "ExecMainStartTimestamp": "Fri 2020-06-05 16:34:14 CEST",
            "ExecMainStartTimestampMonotonic": "400592749158",
            "ExecMainStatus": "1",
            "ExecStart": "{ path=/usr/bin/docker ; argv[]=/usr/bin/docker run --rm --name matrix-mailer --log-driver=none --user=100:101 --cap-drop=ALL --read-only --init --tmpfs=/var/spool/exim:rw,noexec,nosuid,size=100m --network=matrix --env-file=/srv/matrix/mailer/env-mailer --hostname=matrix.nyner.de devture/exim-relay:4.92.2-r0-0 ; ignore_errors=no ; start_time=[Fri 2020-06-05 16:34:14 CEST] ; stop_time=[Fri 2020-06-05 16:34:17 CEST] ; pid=2476083 ; code=exited ; status=1 }",
            "ExecStartEx": "{ path=/usr/bin/docker ; argv[]=/usr/bin/docker run --rm --name matrix-mailer --log-driver=none --user=100:101 --cap-drop=ALL --read-only --init --tmpfs=/var/spool/exim:rw,noexec,nosuid,size=100m --network=matrix --env-file=/srv/matrix/mailer/env-mailer --hostname=matrix.nyner.de devture/exim-relay:4.92.2-r0-0 ; flags= ; start_time=[Fri 2020-06-05 16:34:14 CEST] ; stop_time=[Fri 2020-06-05 16:34:17 CEST] ; pid=2476083 ; code=exited ; status=1 }",
            "ExecStartPre": "{ path=/usr/bin/docker ; argv[]=/usr/bin/docker rm matrix-mailer ; ignore_errors=yes ; start_time=[Fri 2020-06-05 16:34:14 CEST] ; stop_time=[Fri 2020-06-05 16:34:14 CEST] ; pid=2476075 ; code=exited ; status=1 }",
            "ExecStartPreEx": "{ path=/usr/bin/docker ; argv[]=/usr/bin/docker rm matrix-mailer ; flags=ignore-failure ; start_time=[Fri 2020-06-05 16:34:14 CEST] ; stop_time=[Fri 2020-06-05 16:34:14 CEST] ; pid=2476075 ; code=exited ; status=1 }",
            "ExecStop": "{ path=/usr/bin/docker ; argv[]=/usr/bin/docker rm matrix-mailer ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }",
            "ExecStopEx": "{ path=/usr/bin/docker ; argv[]=/usr/bin/docker rm matrix-mailer ; flags=ignore-failure ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }",
            "FailureAction": "none",
            "FileDescriptorStoreMax": "0",
            "FinalKillSignal": "9",
            "FragmentPath": "/etc/systemd/system/matrix-mailer.service",
            "GID": "[not set]",
            "GuessMainPID": "yes",
            "IOAccounting": "no",
            "IOReadBytes": "18446744073709551615",
            "IOReadOperations": "18446744073709551615",
            "IOSchedulingClass": "0",
            "IOSchedulingPriority": "0",
            "IOWeight": "[not set]",
            "IOWriteBytes": "18446744073709551615",
            "IOWriteOperations": "18446744073709551615",
            "IPAccounting": "no",
            "IPEgressBytes": "[no data]",
            "IPEgressPackets": "[no data]",
            "IPIngressBytes": "[no data]",
            "IPIngressPackets": "[no data]",
            "Id": "matrix-mailer.service",
            "IgnoreOnIsolate": "no",
            "IgnoreSIGPIPE": "yes",
            "InactiveEnterTimestamp": "Fri 2020-06-05 16:34:17 CEST",
            "InactiveEnterTimestampMonotonic": "400595653537",
            "InactiveExitTimestamp": "Fri 2020-06-05 16:34:17 CEST",
            "InactiveExitTimestampMonotonic": "400595657299",
            "InvocationID": "babbf0177343454b8f2b19806970a09f",
            "JobRunningTimeoutUSec": "infinity",
            "JobTimeoutAction": "none",
            "JobTimeoutUSec": "infinity",
            "KeyringMode": "private",
            "KillMode": "control-group",
            "KillSignal": "15",
            "LimitAS": "infinity",
            "LimitASSoft": "infinity",
            "LimitCORE": "infinity",
            "LimitCORESoft": "infinity",
            "LimitCPU": "infinity",
            "LimitCPUSoft": "infinity",
            "LimitDATA": "infinity",
            "LimitDATASoft": "infinity",
            "LimitFSIZE": "infinity",
            "LimitFSIZESoft": "infinity",
            "LimitLOCKS": "infinity",
            "LimitLOCKSSoft": "infinity",
            "LimitMEMLOCK": "65536",
            "LimitMEMLOCKSoft": "65536",
            "LimitMSGQUEUE": "819200",
            "LimitMSGQUEUESoft": "819200",
            "LimitNICE": "0",
            "LimitNICESoft": "0",
            "LimitNOFILE": "524288",
            "LimitNOFILESoft": "1024",
            "LimitNPROC": "14218",
            "LimitNPROCSoft": "14218",
            "LimitRSS": "infinity",
            "LimitRSSSoft": "infinity",
            "LimitRTPRIO": "0",
            "LimitRTPRIOSoft": "0",
            "LimitRTTIME": "infinity",
            "LimitRTTIMESoft": "infinity",
            "LimitSIGPENDING": "14218",
            "LimitSIGPENDINGSoft": "14218",
            "LimitSTACK": "infinity",
            "LimitSTACKSoft": "8388608",
            "LoadState": "loaded",
            "LockPersonality": "no",
            "LogLevelMax": "-1",
            "LogRateLimitBurst": "0",
            "LogRateLimitIntervalUSec": "0",
            "LogsDirectoryMode": "0755",
            "MainPID": "0",
            "MemoryAccounting": "yes",
            "MemoryCurrent": "[not set]",
            "MemoryDenyWriteExecute": "no",
            "MemoryHigh": "infinity",
            "MemoryLimit": "infinity",
            "MemoryLow": "0",
            "MemoryMax": "infinity",
            "MemoryMin": "0",
            "MemorySwapMax": "infinity",
            "MountAPIVFS": "no",
            "MountFlags": "",
            "NFileDescriptorStore": "0",
            "NRestarts": "11910",
            "NUMAMask": "",
            "NUMAPolicy": "n/a",
            "Names": "matrix-mailer.service",
            "NeedDaemonReload": "no",
            "Nice": "0",
            "NoNewPrivileges": "no",
            "NonBlocking": "no",
            "NotifyAccess": "none",
            "OOMPolicy": "stop",
            "OOMScoreAdjust": "0",
            "OnFailureJobMode": "replace",
            "Perpetual": "no",
            "PrivateDevices": "no",
            "PrivateMounts": "no",
            "PrivateNetwork": "no",
            "PrivateTmp": "no",
            "PrivateUsers": "no",
            "ProtectClock": "no",
            "ProtectControlGroups": "no",
            "ProtectHome": "no",
            "ProtectHostname": "no",
            "ProtectKernelLogs": "no",
            "ProtectKernelModules": "no",
            "ProtectKernelTunables": "no",
            "ProtectSystem": "no",
            "RefuseManualStart": "no",
            "RefuseManualStop": "no",
            "ReloadResult": "success",
            "RemainAfterExit": "no",
            "RemoveIPC": "no",
            "Requires": "system.slice sysinit.target docker.service",
            "Restart": "always",
            "RestartKillSignal": "15",
            "RestartUSec": "30s",
            "RestrictNamespaces": "no",
            "RestrictRealtime": "no",
            "RestrictSUIDSGID": "no",
            "Result": "exit-code",
            "RootDirectoryStartOnly": "no",
            "RuntimeDirectoryMode": "0755",
            "RuntimeDirectoryPreserve": "no",
            "RuntimeMaxUSec": "infinity",
            "SameProcessGroup": "no",
            "SecureBits": "0",
            "SendSIGHUP": "no",
            "SendSIGKILL": "yes",
            "Slice": "system.slice",
            "StandardError": "inherit",
            "StandardInput": "null",
            "StandardInputData": "",
            "StandardOutput": "journal",
            "StartLimitAction": "none",
            "StartLimitBurst": "5",
            "StartLimitIntervalUSec": "10s",
            "StartupBlockIOWeight": "[not set]",
            "StartupCPUShares": "[not set]",
            "StartupCPUWeight": "[not set]",
            "StartupIOWeight": "[not set]",
            "StateChangeTimestamp": "Fri 2020-06-05 16:34:17 CEST",
            "StateChangeTimestampMonotonic": "400595657299",
            "StateDirectoryMode": "0755",
            "StatusErrno": "0",
            "StopWhenUnneeded": "no",
            "SubState": "auto-restart",
            "SuccessAction": "none",
            "SyslogFacility": "3",
            "SyslogIdentifier": "matrix-mailer",
            "SyslogLevel": "6",
            "SyslogLevelPrefix": "yes",
            "SyslogPriority": "30",
            "SystemCallErrorNumber": "0",
            "TTYReset": "no",
            "TTYVHangup": "no",
            "TTYVTDisallocate": "no",
            "TasksAccounting": "yes",
            "TasksCurrent": "[not set]",
            "TasksMax": "4265",
            "TimeoutAbortUSec": "1min 30s",
            "TimeoutCleanUSec": "infinity",
            "TimeoutStartUSec": "1min 30s",
            "TimeoutStopUSec": "1min 30s",
            "TimerSlackNSec": "50000",
            "Transient": "no",
            "Type": "simple",
            "UID": "[not set]",
            "UMask": "0022",
            "UnitFilePreset": "disabled",
            "UnitFileState": "enabled",
            "UtmpMode": "init",
            "WantedBy": "matrix-synapse.service multi-user.target",
            "WatchdogSignal": "6",
            "WatchdogTimestampMonotonic": "0",
            "WatchdogUSec": "0"
        }
    },

**Comment by TheNyneR** [comment]
During the setup task for the mailer nothing seems to get created/downloaded.

Under `/srv/matrix/mailer/` only an empty file `env-mailer` gets created.

**Comment by spantaleev** [comment]
Why `/srv/matrix` and not `/matrix`? Have you changed the `matrix_base_data_path`?
It's okay if you have. I was just wondering.

-------------------------------

The `matrix-mailer` component uses the [devture/exim-relay](https://hub.docker.com/r/devture/exim-relay) Docker image, which is only available for `amd64` for now.

I've updated the playbook in ab32f6adf6a747 to add [self-building](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/self-building.md) support to the `matrix-mailer` role. If the architecture is not `amd64`, then the playbook will build the `matrix-mailer` (`devture/exim-relay`) image for you, like it does for the other services.

I think this should get you one step further in the process of installing. I'm happy that you've mentioned this problem, as `matrix-mailer` is a core service enabled by default. It wasn't hard adding self-building support to it. It's nice we're now one step ahead as well.

Let me know if you hit any other issues!

**Comment by TheNyneR** [comment]
> Have you changed the matrix_base_data_path?

I believe so because I mounted an external Harddrive at `/srv` and wanted it to be installed there.

I'll check if the commit works as soon as I get home.
And thanks for the quick and helpful responses! ^^

**Comment by TheNyneR** [comment]
The setup of the mailer now works.

Running without `matrix_riot_web_enabled: false` results in

> fatal: [matrix.nyner.de]: FAILED! => {"changed": false, "msg": "Error building vectorim/riot-web - code: 134, message: The command '/bin/sh -c yarn --network-timeout=100000 install' returned a non-zero code: 134, logs: ['Step 1/18 : FROM node:10 as builder', '\\n', ' ---> 66001491656e\\n', 'Step 2/18 : ARG USE_CUSTOM_SDKS=false', '\\n', ' ---> Running in 5785c6fbd7fa\\n', 'Removing intermediate container 5785c6fbd7fa\\n', ' ---> 1aad94a30b0e\\n', 'Step 3/18 : ARG REACT_SDK_REPO=\"https://github.com/matrix-org/matrix-react-sdk.git\"', '\\n', ' ---> Running in 0e478c6e87ed\\n', 'Removing intermediate container 0e478c6e87ed\\n', ' ---> 934cadddd165\\n', 'Step 4/18 : ARG REACT_SDK_BRANCH=\"master\"', '\\n', ' ---> Running in 461d9a4a7ca1\\n', 'Removing intermediate container 461d9a4a7ca1\\n', ' ---> a1e2e32f8a11\\n', 'Step 5/18 : ARG JS_SDK_REPO=\"https://github.com/matrix-org/matrix-js-sdk.git\"', '\\n', ' ---> Running in 7a3b691f68d2\\n', 'Removing intermediate container 7a3b691f68d2\\n', ' ---> 747ff5d59a7c\\n', 'Step 6/18 : ARG JS_SDK_BRANCH=\"master\"', '\\n', ' ---> Running in 56bbb06ad143\\n', 'Removing intermediate container 56bbb06ad143\\n', ' ---> edd487a46dee\\n', 'Step 7/18 : RUN apt-get update && apt-get install -y git dos2unix', '\\n', ' ---> Running in cf84117b2a39\\n', 'Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]\\n', 'Ign:2 http://deb.debian.org/debian stretch InRelease\\n', 'Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]\\n', 'Get:4 http://deb.debian.org/debian stretch Release [118 kB]\\n', 'Get:5 http://deb.debian.org/debian stretch Release.gpg [2410 B]\\n', 'Get:6 http://security.debian.org/debian-security stretch/updates/main arm64 Packages [509 kB]\\n', 'Get:7 http://deb.debian.org/debian stretch-updates/main arm64 Packages [28.1 kB]\\n', 'Get:8 http://deb.debian.org/debian stretch/main arm64 Packages [6925 kB]\\n', 'Fetched 7770 kB in 3s (2242 kB/s)\\nReading package lists...', '\\n', 'Reading package lists...', '\\n', 'Building dependency tree...', '\\nReading state information...', '\\n', 'git is already the newest version (1:2.11.0-3+deb9u7).\\nThe following NEW packages will be installed:\\n', '  dos2unix\\n', '0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.\\nNeed to get 365 kB of archives.\\nAfter this operation, 1281 kB of additional disk space will be used.\\nGet:1 http://deb.debian.org/debian stretch/main arm64 dos2unix arm64 7.3.4-3 [365 kB]\\n', '\\x1b[91mdebconf: delaying package configuration, since apt-utils is not installed\\n\\x1b[0m', 'Fetched 365 kB in 0s (2606 kB/s)\\n', 'Selecting previously unselected package dos2unix.\\r\\n', '(Reading database ... \\r', '(Reading database ... 5%\\r(Reading database ... 10%\\r(Reading database ... 15%\\r(Reading database ... 20%\\r(Reading database ... 25%\\r(Reading database ... 30%\\r(Reading database ... 35%\\r(Reading database ... 40%\\r(Reading database ... 45%\\r(Reading database ... 50%\\r', '(Reading database ... 55%\\r(Reading database ... 60%\\r(Reading database ... 65%\\r', '(Reading database ... 70%\\r', '(Reading database ... 75%\\r', '(Reading database ... 80%\\r', '(Reading database ... 85%\\r', '(Reading database ... 90%\\r', '(Reading database ... 95%\\r', '(Reading database ... 100%\\r(Reading database ... 29845 files and directories currently installed.)\\r\\n', 'Preparing to unpack .../dos2unix_7.3.4-3_arm64.deb ...\\r\\n', 'Unpacking dos2unix (7.3.4-3) ...\\r\\n', 'Setting up dos2unix (7.3.4-3) ...\\r\\n', 'Removing intermediate container cf84117b2a39\\n', ' ---> 28487376cdd8\\n', 'Step 8/18 : WORKDIR /src', '\\n', ' ---> Running in 0755fad144d0\\n', 'Removing intermediate container 0755fad144d0\\n', ' ---> fe4415fb8275\\n', 'Step 9/18 : COPY . /src', '\\n', ' ---> 791a25254475\\n', 'Step 10/18 : RUN dos2unix /src/scripts/docker-link-repos.sh && bash /src/scripts/docker-link-repos.sh', '\\n', ' ---> Running in 6cd921d5f714\\n', '\\x1b[91mdos2unix: converting file /src/scripts/docker-link-repos.sh to Unix format...\\n\\x1b[0m', '\\x1b[91m++ git rev-parse --abbrev-ref HEAD\\n\\x1b[0m', '\\x1b[91m+ BRANCH=HEAD\\n\\x1b[0m', \"\\x1b[91m+ '[' false == false ']'\\n+ '[' HEAD == develop ']'\\n\\x1b[0m\", \"\\x1b[91m+ '[' false == false ']'\\n\\x1b[0m\", \"\\x1b[91m+ echo 'skipping react-sdk and js-sdk installs: USE_CUSTOM_SDKS is false'\\n+ exit 0\\n\\x1b[0m\", 'skipping react-sdk and js-sdk installs: USE_CUSTOM_SDKS is false\\n', 'Removing intermediate container 6cd921d5f714\\n', ' ---> aa063a005a32\\n', 'Step 11/18 : RUN yarn --network-timeout=100000 install', '\\n', ' ---> Running in 3ff0d9772725\\n', '\\x1b[91mAborted (core dumped)\\n\\x1b[0m', 'Removing intermediate container 3ff0d9772725\\n']"}

Is it also possible to self build only certain images or provide them from the computer where ansible runs? For Ma1sd I again get the error that gradle can't be used/installed.

**Comment by TheNyneR** [comment]
I also just tried running the playbook with automatic certbot certificates (so no provided ones).
The playbook tries pulling the docker image `certbot/certbot:arm64-v1.5.0` but the [tags](https://hub.docker.com/r/certbot/certbot/tags) are defined like `arm64v8-v1.5.0` so the `v8` after `arm64` is missing.

**Comment by TheNyneR** [comment]
I just explicitly set `matrix_ssl_lets_encrypt_certbot_docker_image: "certbot/certbot:arm64v8-v1.5.0"` and the `setup-all` as well as `start` tasks run correctly.

**Comment by spantaleev** [comment]
I've heard others complain about riot-web building being broken. We should probably investigate why `yarn --network-timeout=100000 install` crashes. Perhaps it should then be reported to the [riot-web](https://github.com/vector-im/riot-web/issues) repository.

---------

Thanks for the report about cerbot's tag usage!

In 831c3f4, I've made the playbook use the appropriate tags for ARM32 and ARM64, so manually overriding `matrix_ssl_lets_encrypt_certbot_docker_image` should not longer be necessary.

**Comment by spantaleev** [comment]
See #510 for the riot-web issue.
