### ISSUE TITLE
Copy vars.yml to the server for easily restoring playbook state

### ISSUE THREAD

**Issue by spantaleev** [spantaleev/matrix-docker-ansible-deploy#542]
If you lose your `vars.yml` file, it becomes hard to rebuild your Matrix server.

You'd have to either start fresh (new secrets, etc., potentially forgetting some configuration keys) or you'd have to work hard to fish out various configuration values by looking at the current state of the `/matrix` directory.

If the playbook were to make a copy of the "last used" `vars.yml` file to the server (e.g. `/matrix/vars.yml`), it would make restoring much easier. Security-wise, it shouldn't be too bad.. All those secret keys and passwords already live in various `/matrix/..` files anyway.

**Comment by dhoffend** [comment]
Can you please make this optional? People that have a different inventory structure are forced to your host syntax.

In my case I use your playbook as git submodule and symlinked your roles into my infrastructure ansible roles folder

**Comment by spantaleev** [comment]
I suspected that this might cause issues for people, but decided not to introduce extra complexity until it's confirmed to be the case. Thanks for letting me know!

I've improved the situation with 7729511. You can either disable it (`matrix_vars_yml_snapshotting_enabled: false`) or point it to your own `vars.yml` file by adjusting `matrix_vars_yml_snapshotting_src`.
