### ISSUE TITLE
Installing error 

### ISSUE THREAD

**Issue by taymur1** [spantaleev/matrix-docker-ansible-deploy#543]
Hi I am new for this but I got this error once I started installation.......

ERROR! no action detected in task

The error appears to have been in '/matrix-docker-ansible-deploy/roles/matrix-base/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- import_tasks: "{{ role_path }}/tasks/sanity_check.yml"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

**Comment by spantaleev** [comment]
Which version of Ansible are you using? See `ansible --version`.

See our Ansible requirements here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md

**Comment by taymur1** [comment]
Thank you spantaleev,  I fixed this issue i the problem I was using older version of ansible..
No using this version  ansible 2.9.9  but I am now facing other problems :). I will try to sort it out

**Comment by spantaleev** [comment]
Good to know! I'll close this issue then.

For your other problems, you might get more timely and better help in our Matrix/IRC room. See the [Support](https://github.com/spantaleev/matrix-docker-ansible-deploy#support) section of our README.

**Comment by VN1977** [comment]
Hello,
I have the same error with Ansible v.2.7.7.
Should I upgrade it to a newer version?

**Comment by spantaleev** [comment]
Yes, you should try to use a newer version. See `docs/ansible.md`.
