### ISSUE TITLE
Dynamic IP address support

### ISSUE THREAD

**Issue by AlwaysLivid** [spantaleev/matrix-docker-ansible-deploy#546]
I'll admit that I'm a inexperienced with Ansible, but by following the instructions, I came across having to set the `ansible_host` variable in the `inventory/hosts` file. My infrastructure is hosted inside of a homelab with dynamic IP support. Could you also consider giving people the option to add hostnames under that variable instead?

**Comment by spantaleev** [comment]
Just to add to this:

As the example `inventory/hosts` file (`examples/hosts`) says:

>  We explicitly ask for your server's external IP address, because the same value is used for configuring Coturn.
> If you'd rather use a local IP here, make sure to set up `matrix_coturn_turn_external_ip_address`.

So you can connect using a local IP (or even some other hostname), as long as you make Coturn happy by either:
- disabling Coturn (`matrix_coturn_enabled: false`)
- or by passing a static IP to Coturn (`matrix_coturn_turn_external_ip_address`) from your `vars.yml` file
- or by telling Coturn to try to dynamically determine the IP address (search for "detect-external-ip" [here](https://hub.docker.com/r/instrumentisto/coturn)). I haven't tested this and I'm not sure if the playbook will try to fight with you or not.

**Comment by AlwaysLivid** [comment]
Sorry for all of that, just got briefly confused because of the documentation in `vars.yml`.
