### ISSUE TITLE
Dimension Integration not working

### ISSUE THREAD

**Issue by PlanetSmasher** [spantaleev/matrix-docker-ansible-deploy#558]
Hi,
we've updated our deployment today but cannot get riot to integrate to our own dimension server.
Now the app on every platform wants to use scalar.vector.im.

The settings page on the browser shows me our own services, but the app the respective offical "vector.im" counterparts.
Either way it will use "vector.im" for Stickers.

Sadly, I cannot tell the exact time, when we have updated the last time, but if I got my thoughts the right way, it has to be around begin of June.

I am glad to assist finding the exact issue.
But as I am not aware of ansible scripts it might take a while to get into it...

greetings
Dan

**Comment by spantaleev** [comment]
Has it ever worked before?

From what I know, mobile apps can't/won't use another integration server.

**Comment by jdreichmann** [comment]
Mobile apps do not currently support costum integration servers afaik.

**Comment by PlanetSmasher** [comment]
For the mobile app I was aswell surprised that Stickers even show up
but on my Browser now the Stickers will showup from vector.im despite its settings show our own dimension server.
![grafik](https://user-images.githubusercontent.com/10109247/86392599-056a6400-bc9c-11ea-843a-b38262dbc623.png)
and 

![grafik](https://user-images.githubusercontent.com/10109247/86392957-96413f80-bc9c-11ea-9950-97f39ea5498e.png)

**Comment by ctwelve** [comment]
I have encountered this as well. It seems to function just fine on the built-in web Riot, but the desktop app does not.

**Comment by ctwelve** [comment]
Also, mobile app *does* show the Dimension integration stuff...but stickers won't remember being set up under that scheme. It's a little odd.

**Comment by PlanetSmasher** [comment]
The Web-Riot aka. Element does show our own Integration Server but only in the Settings page and not in the Sticker Icon
![grafik](https://user-images.githubusercontent.com/10109247/87658976-2aaba780-c75d-11ea-8f1b-60ed7e1c368f.png)

Probably an Element Issue: https://github.com/vector-im/riot-web/issues/14315
