### ISSUE TITLE
Suggestion - 'Preserve vars.yml on the server' is mandatory

### ISSUE THREAD

**Issue by PC-Admin** [spantaleev/matrix-docker-ansible-deploy#565]
Attempting to deploy this script via AWX and it complains that it can't save a copy of the vars.yml on the controller.

```
TASK [matrix-base : Preserve vars.yml on the server for easily restoring if it gets lost later on] ***
10:27:23
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [cheesedomain.xyz]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/awx_54_ghjbsgk1/host_vars/cheesedomain.xyz/vars.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```
Is it possible to make this not compulsory? So it fails softly and continues the script if it cannot backup the vars.yml file?

I'll probably have to fork this in the meantime to resume testing.

**Comment by spantaleev** [comment]
You can disable this feature with with `matrix_vars_yml_snapshotting_enabled: false`

It's probably better to do it explicitly like this, as opposed to making it spew out a warning message which would likely get lost among all the other thousands of messages.
