### ISSUE TITLE
Update maintenance-and-troubleshooting.md to talk about slow synapse

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#57]
Maybe some cache factor advice and a note about presence

Related: https://github.com/matrix-org/synapse/pull/4276/ and your presence issue https://github.com/matrix-org/synapse/issues/3971

**Comment by spantaleev** [comment]
That would be nice!
It could be some new "Performance Tuning" documentation page too.
