### ISSUE TITLE
Using this playbook to install Matrix on a Ubuntu 20.04 server results in no python-docker

### ISSUE THREAD

**Issue by aa1874** [spantaleev/matrix-docker-ansible-deploy#570]
When I use this playbook to install Matrix on an Ubuntu 20.04 server this error appears:

```
TASK [matrix-base : Ensure Docker is installed] ************************************************************************
fatal: [matrix.ncps.xyz]: FAILED! => {"changed": false, "msg": "No package matching 'python-docker' is available"}
```

Please fix this!

**Comment by SuperSandro2000** [comment]
Run ``apt update`` before running the playbook.

**Comment by SuperSandro2000** [comment]
Did you install your Ansible with python2?

**Comment by aa1874** [comment]
I don't know, should I upgrade to python3 on the Ansible client station?

**Comment by SuperSandro2000** [comment]
Yes you should because Python2.7 is mostly dropped from Ubuntu 20.04 and it tries to use Python2 based on this line https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/9a43cc02e0a5b46670d13c7a2c5f8388e7ba3046/roles/matrix-base/tasks/server_base/setup_debian.yml#L39 .
