### ISSUE TITLE
Add instructions/support for migrating from a normal server to a playbook-managed server

### ISSUE THREAD

**Issue by AlwaysLivid** [spantaleev/matrix-docker-ansible-deploy#583]

**Comment by bertiebaggio** [comment]
There are instructions for importing the database ([SQLite](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-sqlite.md) / [Postgres](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-postgres.md)), and [importing media_store](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-media-store.md) ? Is there an area where they could be improved?

Are there other areas that need documented?

(Commenting here as I just migrated from a repo install to using this playbook and it seems to be working well.)

**Comment by AlwaysLivid** [comment]
> There are instructions for importing the database ([SQLite](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-sqlite.md) / [Postgres](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-postgres.md)), and [importing media_store](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-media-store.md) ? Is there an area where they could be improved?
> 
> Are there other areas that need documented?
> 
> (Commenting here as I just migrated from a repo install to using this playbook and it seems to be working well.)

Didn't pay attention to the `media_store` documentation file, but maybe something that was more bound together and clarified (e.g. "Migrating from an existing Matrix installation") could work better. Either way, both the instructions and the support exist, so I'm closing this issue.

**Comment by bertiebaggio** [comment]
Aye, perhaps an additional bullet point on the main [README](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/README.md)? Eg:

- Prerequisites
- Configuring your DNS server
- Getting this playbook's source code
- Configuring the playbook
- Installing
- **Migrating data from an existing Synapse server** ←
- Registering users
- Updating users passwords
- Configuring service discovery via .well-known
- Maintenance / checking if services work
- Maintenance / upgrading services
- Maintenance / Synapse
- Maintenance / PostgreSQL
- Maintenance and Troubleshooting
- Uninstalling

**Comment by spantaleev** [comment]
4eb87c1dcb6c424 tries to improve on this. Thanks for the suggestion!

**Comment by bertiebaggio** [comment]
Looks good!

**Comment by AlwaysLivid** [comment]
> [4eb87c1](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/4eb87c1dcb6c424b394160f5ab57385a6f90e1b0) tries to improve on this. Thanks for the suggestion!

:+1:
