### ISSUE TITLE
[duplicate of #138] Add go-neb to the playbook

### ISSUE THREAD

**Issue by xschlef** [spantaleev/matrix-docker-ansible-deploy#591]
We already have dimension, so why not also add the go-neb bot to the playbook for a tighter integration.

https://github.com/matrix-org/go-neb

Dimension needs go-neb anyway and why rely on remote hosting if we can do it ourselves.

**Comment by lxp** [comment]
There is already an issue for it: #138

**Comment by xschlef** [comment]
Ok sorry. Only searched for go-neb
