### ISSUE TITLE
Add Clarification In Docs About DNS Entry for Nginx Proxy

### ISSUE THREAD

**Issue by ElykDeer** [spantaleev/matrix-docker-ansible-deploy#595]
I'd like some clarification added [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-base-domain-serving.md#L17) about what type of record should be added; it's rather explicit [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md) about CNAME's vs A-records, so it'd be nice to match that.

**Comment by spantaleev** [comment]
Good point! Fixed!
