### ISSUE TITLE
matrix-appservice-discord doesn't sent Discord messages to Matrix

### ISSUE THREAD

**Issue by aa1874** [spantaleev/matrix-docker-ansible-deploy#596]
Please disable it temporaily until the fix is done (this might be related to discord.js)

**Comment by aaronraimist** [comment]
To get support it would be good if you would join #matrix-docker-ansible-deploy:devture.com and explain the issue.

**Comment by spantaleev** [comment]
Closing this issue, because it's very old and whatever it was, `matrix-appservice-discord` definitely does work now.
