### ISSUE TITLE
Setting up Synapse Admin

### ISSUE THREAD

**Issue by CodingAnonymous** [spantaleev/matrix-docker-ansible-deploy#599]
I used the tutorial on this post: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b2ae66956682b808b0e1ba8a1c516894e56ffa87/docs/configuring-playbook-synapse-admin.md

I added this configuration to my vars.yml:
`matrix_synapse_admin_enabled: true`

And run the installation:a
`ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start`

When I open `https://matrix.DOMAIN/synapse-admin/` I'll get this error message:
```
404 Not Found
nginx
```

What did I do wrong?

**Comment by aaronraimist** [comment]
Did you update the playbook with `git pull` first?

Are you using the built in nginx (default) or are you using your own webserver?

**Comment by aaronraimist** [comment]
By the way, for support it is usually easier and faster to join our room rather than create an issue https://github.com/spantaleev/matrix-docker-ansible-deploy#support

**Comment by CodingAnonymous** [comment]
Thanks you very much, `git pull` did it!
