### ISSUE TITLE
synapse admin on port 80

### ISSUE THREAD

**Issue by Metzlmane** [spantaleev/matrix-docker-ansible-deploy#602]
Thanks for adding this package!

I'm running HAProxy infront of everything, so i use the ACL
acl synapse_admin_ui path -i -m beg /synapse-admin
use_backend synapse-admin-gui if synapse_admin_ui

and changed the docker container mapping to some other port than 80.
Sorry for the stupid question, but why was it mapped to 80?

If i use wget to access the http://127.0.0.0:PORT/
is always says: failed: Network is unreachable
I thought this is because HAProxy already blocks port 80 for https redirect, but somehow i can't get it to work.

**Comment by spantaleev** [comment]
synapse-admin uses port 80 inside the container.

When `matrix_nginx_proxy_enabled: true` (the default for the playbook), we don't expose synapse-admin's port and it remains on port 80 and only accessible on the container network (`--network=matrix`).

If the proxy is explicitly disabled (`matrix_nginx_proxy_enabled: false` in your `vars.yml` file), we expose synapse-admin's port 80 to `127.0.0.1:8766`.
