### ISSUE TITLE
"Generate initial Synapse config and signing key" fails on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Duke-Igthorn** [spantaleev/matrix-docker-ansible-deploy#608]
Running the playbook on Ubuntu Server 20.04 LTS ended in a fatal error:
`TASK [matrix-synapse : Generate initial Synapse config and signing key] *********************************************************************************************************************************************************************
fatal: [matrix.DOMAIN.de]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=1001:1001", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=1001", "-e", "GID=1001", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=matrix.DOMAIN.de", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.17.0", "generate"], "delta": "0:00:02.508090", "end": "2020-07-26 21:12:02.596369", "msg": "non-zero return code", "rc": 125, "start": "2020-07-26 21:12:00.088279", "stderr": "docker: Error response from daemon: error while creating mount source path '/matrix/synapse/config': mkdir /matrix: read-only file system.", "stderr_lines": ["docker: Error response from daemon: error while creating mount source path '/matrix/synapse/config': mkdir /matrix: read-only file system."], "stdout": "", "stdout_lines": []}

`
Actual domain name has been purged from the snippet. Playbook was run with --ask-pass and ansible_ssh_user=username become=true become_user=root as well as ansible_connection=local in hosts on the same machine matrix is supposed to be installed on.

It can VERY well be that I made a mistake somewhere, but I'd rather ask anyways. 
Seems like a permission issue? Maybe the sudo elevation failed?
Thanks in advance for helping! 

Edit: Even when run as actual root the error is the same.

**Comment by spantaleev** [comment]
The error seems to indicate that `/matrix` is a read-only filesystem. Does the directory exist? Is it writable? Try doing `stat /matrix`, `stat /matrix/synapse` and `stat /matrix/synapse/config`.

By the way, you may get better help, and faster, if you come to our Matrix (IRC-bridged) room. See here: https://github.com/spantaleev/matrix-docker-ansible-deploy#support

**Comment by Duke-Igthorn** [comment]
Sorry for the late reply! I'll delete the folder and recreate it myself to see of that helps any. The script should have created it on its own... I guess something went awry there.
And yeah, I'll pop into the support chat when I'm back! Thanks for the help so far! :)

**Comment by Olawale1** [comment]
Hi ,

I'm getting a similar error on Ubuntu 18.04 though the cause seems different:

```
TASK [matrix-synapse : Generate initial Synapse config and signing key] ********
fatal: [matrix.mydomain.com]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=1002:1002", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=1002", "-e", "GID=1002", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=matrix.mydomain.com", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.18.0", "generate"], "delta": "0:00:00.847793", "end": "2020-08-04 00:32:26.501423", "msg": "non-zero return code", "rc": 1, "start": "2020-08-04 00:32:25.653630", "stderr": "standard_init_linux.go:211: exec user process caused \"exec format error\"", "stderr_lines": ["standard_init_linux.go:211: exec user process caused \"exec format error\""], "stdout": "", "stdout_lines": []}
```
Any pointers would be greatly appreciated


Thanks

**Comment by spantaleev** [comment]
What architecture are you on?

The Synapse docker image only works on `amd64`, so if you're on some other one, you'll need to do something more special.

See our guide about alternative architectures: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/alternative-architectures.md

**Comment by Olawale1** [comment]
Oh boy! ...Somehow missed that. I've got arm64. Will go through the guide and revert

Thanks Slavi!

**Comment by Olawale1** [comment]
Yup ...it was the architecture. I've gotten past that now

Many thanks
