### ISSUE TITLE
How do I get logs?

### ISSUE THREAD

**Issue by elmehalawi** [spantaleev/matrix-docker-ansible-deploy#618]
The directions mention a couple times to check the logs, but how do I do that? When I run `docker ps` and get the container ID for mautrix-telegram for example, then run:

```
# docker logs a65b716206df
Error response from daemon: configured logging driver does not support reading
```

I get the same error if I try to get the logs for synapse.

Is this documented somewhere I missed?

**Comment by aaronraimist** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5a243caf99a3f135ce3056936d84a74e7bcd44f7/docs/maintenance-and-troubleshooting.md#how-to-see-the-current-status-of-your-services

**Comment by elmehalawi** [comment]
I missed that somehow. Thanks, @aaronraimist
