### ISSUE TITLE
Cannot execute setup-ssl; custom configured non-Matrix SSL certificates expiring.

### ISSUE THREAD

**Issue by admrulankor** [spantaleev/matrix-docker-ansible-deploy#619]
I've tried executing the playbook's setup-ssl role but it doesn't respond to that command. Some of the non-Matrix-related SSL certificates that I have custom set on the `vars.yml` are expiring in around ten days now. Please help me!

Note: I use an external webserver instead of the built-in `matrix-nginx-proxy`.

**Comment by spantaleev** [comment]
Is this still an issue? If yes, please reopen and post additional details.
