### ISSUE TITLE
Where to add environment variables

### ISSUE THREAD

**Issue by Olawale1** [spantaleev/matrix-docker-ansible-deploy#621]
Hi @spantaleev ,

Looks like I need you to bail me out once again! I'm using a simple [web proxy service](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) that serves multiple sites and manages certificates instead of the default web server that ships with the playbook. This service directs traffic to the relevant containers by including some options (-e VIRTUAL_HOST=your.domain.com, -e LETSENCRYPT_HOST=your.domain.com) as environment variables when starting them up

I'm not quite sure where I can include these environment variables in the playbook especially for the main server at matrix.mydomain.com

I'm very new to Docker but I learn quickly :)

Thanks

**Comment by spantaleev** [comment]
You can pass such flags to all containers by the playbook with the `matrix_*_extra_arguments` variables. Example:

```yaml
matrix_synapse_container_extra_arguments:
- "-e VIRTUAL_HOST=matrix.DOMAIN"
- "-e LETSENCRYPT_HOST=matrix.DOMAIN"
```

You also need to disable the internal proxy (`matrix_nginx_proxy_enabled: false`).

-----

Still, I don't think this would be easy, or even possible with this proxy. It only seems to proxy port 80 and 443, and it always goes to port 80 inside the container. Our containers use different ports (not 80). For Synapse, besides SSL on port 443, you also need SSL on port 8448 (for federation).

So.. it's more tricky.. and this proxy doesn't seem flexible enough to make it work.

**Comment by Olawale1** [comment]
Hi @spantaleev 

Thank you so much for the detailed response. I really appreciate it

Will explore the best way forward 

Cheers
