### ISSUE TITLE
Disabling federation breaks ma1sd

### ISSUE THREAD

**Issue by syhe** [spantaleev/matrix-docker-ansible-deploy#626]
If you disable the synapse federation listener completely via `matrix_synapse_federation_enabled: false`, ma1sd will be unable to talk to federation API endpoints. This breaks some workflows related to administration, for example deactivating a user using synapse-admin will fail. It seems it also affects clients trying to switch identity servers (if they had used vector.im before and try to use the local ma1sd).

Would it be enough to add a warning to the documentation? Would it be better to have some logic ensuring ma1sd can still talk to the federation API?

**Comment by spantaleev** [comment]
I believe that this is fixed by c07c927d9f2f379583001.

We now automatically enable the `openid` endpoints on the federation port, even when federation is disabled.
