### ISSUE TITLE
Playbook permissions on Matrix directory not allowing .well-known discovery

### ISSUE THREAD

**Issue by Olawale1** [spantaleev/matrix-docker-ansible-deploy#634]
Hi ,

I noticed that whenever the playbook creates (or updates) the base Matrix directory, the permissions are set to 750 instead of 755 and this prevents the discovery of .well-known files

Could you pls take a look at this? 

Kind regards

**Comment by spantaleev** [comment]
As the [Preparation step in `docs/configuring-playbook-own-webserver.md`](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#preparation) says:

> 1) Make sure your web server user (something like `http`, `apache`, `www-data`, `nginx`) is part of the `matrix` group. You should run something like this: `usermod -a -G matrix nginx`. This allows your webserver user to access files owned by the `matrix` group. When using an external nginx webserver, this allows it to read configuration files from `/matrix/nginx-proxy/conf.d`. When using another server, it would make other files, such as `/matrix/static-files/.well-known`, accessible to it.

This is probably the proper solution to your problem. If not, we should discuss some more!

**Comment by Olawale1** [comment]
Hi @spantaleev 

Good to hear from you. I'm not sure that's the solution because well-known files should be accessible to external traffic (not just internal users who are members of the matrix group)... Please confirm 

Cheers

**Comment by spantaleev** [comment]
Not sure what your setup is like and why you need some other user to have access deep within the `/matrix` directory tree (and why you wouldn't make them a member of the `matrix` group, if such access is required).

In `configuring-well-known.md`, we recommend 3 ways for serving the well-known files **from the base domain**: [Installing well-known files on the base domain's server](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md#installing-well-known-files-on-the-base-domains-server)

**Comment by Olawale1** [comment]
Hi @spantaleev 

The issue here is that Nginx is running within a container and I'm not sure if there's any way to add the nginx user (which is the user defined within the Nginx container) to the matrix group (which doesn't exist inside the Nginx container)

Pls advise

**Comment by Olawale1** [comment]
Just for context... I already added my user, root, and www-data to the matrix group but the validation for .well-known still fails (unless I change the permission for the matrix directory to 755 as mentioned above)

There is no nginx user on the host machine

**Comment by Olawale1** [comment]
Hi @spantaleev 

Have you had an opportunity to test this? Can you confirm that .well-known discovery (using the Playbook self-check) doesn't fail even though the root matrix folder has 'drwxr-x---' permission? 

These kind of permission problems are common in setups using Nginx... even for certbot. If the path to the file is not completely traversable, discovery of well-known files fails

Thanks

**Comment by spantaleev** [comment]
I'm not sure how and what to test. Seems like you have some very custom setup, where you don't run `matrix-nginx-proxy` and you don't run an external webserver, but rather, you run some other server in a container.

You should be able to get better and quicker assistance by joining our support room on Matrix/IRC. See here: https://github.com/spantaleev/matrix-docker-ansible-deploy#support
