### ISSUE TITLE
Nginx and Synapse docker images stopping continuously

### ISSUE THREAD

**Issue by alirezafarahabadi** [spantaleev/matrix-docker-ansible-deploy#639]
Hi!
After installing and starting all services successfully, when I printing docker images status, this result is obtained. nginx and synapse images stopping continuously.
Please see this picture:
![Screenshot from 2020-09-06 10-07-46](https://user-images.githubusercontent.com/28271481/92319096-54c96980-f02a-11ea-9b44-2ca309e0c241.png)
and this:
![Screenshot from 2020-09-06 10-08-12](https://user-images.githubusercontent.com/28271481/92319124-8b06e900-f02a-11ea-9f1e-4a850612ce57.png)

And this process (starting and stopping) happens regularly.

These pictures also is systemctl status log:
![Screenshot from 2020-09-06 10-23-09](https://user-images.githubusercontent.com/28271481/92319164-02d51380-f02b-11ea-8b0a-ef55ad8268b4.png)
![Screenshot from 2020-09-06 10-25-29](https://user-images.githubusercontent.com/28271481/92319235-56dff800-f02b-11ea-9776-8a42d4ccbebb.png)

And this is my config:
![Screenshot from 2020-09-06 10-31-34](https://user-images.githubusercontent.com/28271481/92319343-35cbd700-f02c-11ea-829f-bb5448d1cca9.png)

And this is my host file:
![Screenshot from 2020-09-06 10-34-02](https://user-images.githubusercontent.com/28271481/92319363-85120780-f02c-11ea-8add-8868e9e8e2e5.png)

It might be helpful to say I have't another proxy server and I want to serve my base domain by this docker image and also I am not 
familiar with nginx.

I'm not sure what other information to provide, but will be happy to offer anything else.
Thanks!

**Comment by spantaleev** [comment]
Maybe you're running out of memory and Synapse gets killed?

Check `dmesg` for some OOM messages.

**Comment by alirezafarahabadi** [comment]
Hi
my server has 2GB ram and by see htop command about 1GB of ram is free. also with dmesg command I can't find useful thing because I am not familiar with it. do you have some idea?

result of dmesg:
![image](https://user-images.githubusercontent.com/28271481/92488097-59954580-f203-11ea-9b73-42d38d57f7ae.png)

**Comment by eMPee584** [comment]
`journalctl -u 'matrix*'` should show more details about the failing services.. You may want to post the log here too..

**Comment by spantaleev** [comment]
Closing this issue - it's been inactive for a long time.

If you've fixed it, please post details as to what the problem was.

If it's still an issue, please post additional details about it or join our support room (or IRC channel), so we can help you.
