### ISSUE TITLE
Can't enable lobby in Jitsi

### ISSUE THREAD

**Issue by rmateusucm** [spantaleev/matrix-docker-ansible-deploy#643]
Hello!

I've been trying for several hours to enable the lobby feature in the Jitsi configuration but it's not working.

Here are the steps that I've tried:

1. ) As it says in this [thread(](https://community.jitsi.org/t/how-to-how-do-i-use-the-new-lobby-feature/73100) I've modified the **/matrix/jitsi/prosody/config/conf.d/jitsi-meet.cfg.lua** with the following options:

``` lua
VirtualHost "matrix-jitsi-web"

    authentication = "anonymous"

    ssl = {
        key = "/config/certs/matrix-jitsi-web.key";
        certificate = "/config/certs/matrix-jitsi-web.crt";
    }
    modules_enabled = {
        "bosh";
        "pubsub";
        "ping";
        "speakerstats";
        "conference_duration";
        "muc_lobby_rooms";


    }
 
 
 
    speakerstats_component = "speakerstats.matrix-jitsi-web"
    conference_duration_component = "conferenceduration.matrix-jitsi-web"
 
    c2s_require_encryption = false
    lobby_muc = "lobby.matrix-jitsi-web"
    main_muc = "conference.matrix-jitsi-web"
    -- muc_lobby_whitelist = { "recorder.meet.example.com" }
....
Component "lobby.matrix-jitsi-web" "muc"
    storage = "memory"
    restrict_room_creation = true
    muc_room_locking = false
    muc_room_default_public_jids = true

```

2) When I **create a room**, the **lobby option shows up** and I'm able to enable it:
![image](https://user-images.githubusercontent.com/45385093/92643792-a56aec00-f2e2-11ea-8621-f197070f22aa.png)

But on the **console** it displays the following message:
![image](https://user-images.githubusercontent.com/45385093/92643875-c7fd0500-f2e2-11ea-9e0b-f673d4680ca9.png)

3) When a user tries to get in he sees the correct website where he can click to "ask to join" but that notification never arrives to the owner of the room because it says that it can't find the lobbyroomJid on the console and it stays in a infinite loop.

**Comment by spantaleev** [comment]
Following what [docker-jitsi-meet](https://github.com/jitsi/docker-jitsi-meet) does, I've added a new playbook variable (`matrix_jitsi_enable_lobby: false`), which influences the `ENABLE_LOBBY` environment variable passed to Prosody.

You can try enabling the lobby feature via the playbook (`matrix_jitsi_enable_lobby: true`).

I think you'll have to [Rebuilding your Jitsi installation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md#rebuilding-your-jitsi-installation) for this configuration file to get regenerated though.

------------

Looks like there might have been some minor changes to the lobby feature in recent Jitsi versions (see [a comparison between v4857 and master](https://github.com/jitsi/docker-jitsi-meet/compare/stable-4857...master)). You could try the latest version (`matrix_jitsi_container_image_tag: latest`) as well.

**Comment by rmateusucm** [comment]
It's working! :smiley: Thank you @spantaleev !
