### ISSUE TITLE
Nginx configuration for external docker image

### ISSUE THREAD

**Issue by TheNyneR** [spantaleev/matrix-docker-ansible-deploy#648]
Hey! 
I've been trying to set up a nextcloud server on the same server as the matrix server and can't seem to get the configuration for the nginx reverse proxy right.

Here is the relevant part of the `vars.yml file`:
```
# Cloud domain
cloud_domain: "cloud.{{ matrix_domain }}"

matrix_ssl_domains_to_obtain_certificates_for:
  - '{{ matrix_server_fqn_matrix }}'
  - '{{ matrix_server_fqn_element }}'
  - '{{ matrix_server_fqn_dimension }}'
  - '{{ matrix_domain }}'
  - '{{ matrix_server_fqn_jitsi }}'
  - '{{ cloud_domain }}'

matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    server {
      listen {{ 8080 if matrix_nginx_proxy_enabled else 80 }};
      server_name {{ cloud_domain }};
      return 301 https://{{ cloud_domain }}$request_uri;
      }
  - |
    server {
      listen {{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;
      listen [::]:{{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;

      server_name {{ cloud_domain }};
      server_tokens off;

      ssl_certificate {{ matrix_ssl_config_dir_path }}/live/{{ cloud_domain }}/fullchain.pem;
      ssl_certificate_key {{ matrix_ssl_config_dir_path }}/live/{{ cloud_domain }}/privkey.pem;
      ssl_protocols {{ matrix_nginx_proxy_ssl_protocols }};
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

      #      location / {
      #          proxy_pass http://localhost:5678/;
      #          proxy_set_header Host $host;
      #          proxy_set_header X-Real-IP $remote_addr;
      #          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #          proxy_set_header X-Forwarded-Proto $scheme;
      #      }

      return https://{{ cloud_domain }}:5678$request_uri;
      }
```

As far as I understand it the first `server` block handles a redirect to `https` while the other block should pass the requests to my nextcloud instance running on port `5678`. I first tried this with the `location /` block but enabling it resulted in me not being able to connect to the server via `{{ matrix_domain }}` or `{{ matrix_server_fqn_element }}` at all.

Any help would be appreciated. ^^

**Comment by spantaleev** [comment]
Hmm.. This all seems good.. I don't know why it'd be happening.

By the way, in order for the `proxy_pass` thing `localhost:5687` to work, you have to run outside of a container setup (`matrix_nginx_proxy_enabled: false` and using your own nginx webserver).

If you're running with `matrix_nginx_proxy_enabled: true` (which is the default), you'd need to `proxy_pass` to some container on the same Docker network (called `matrix`, given the `matrix_docker_network: matrix` default).

**Comment by TheNyneR** [comment]
I tried setting the network of the nextcloud container to `matrix` with the following setting:
`networks:
  default:
    external:
      name: matrix
`
With the proxy pass setting like this:
`matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    server {
      listen {{ 8080 if matrix_nginx_proxy_enabled else 80 }};
      server_name {{ cloud_domain }};
      return 301 https://{{ cloud_domain }}$request_uri;
      }
  - |
    server {
      listen {{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;
      listen [::]:{{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;

      server_name {{ cloud_domain }};
      server_tokens off;

      ssl_certificate {{ matrix_ssl_config_dir_path }}/live/{{ cloud_domain }}/fullchain.pem;
      ssl_certificate_key {{ matrix_ssl_config_dir_path }}/live/{{ cloud_domain }}/privkey.pem;
      ssl_protocols {{ matrix_nginx_proxy_ssl_protocols }};
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

      location / {
              proxy_pass http://locahlost:5678/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
      }

      #return https://{{ cloud_domain }}:5678$request_uri;
      }`
I get `ERR_ADDRESS_UNREACHABLE` for `{{ matrix_domain }}` and `ERR_CONNECTION_REFUSED` for all other domains. 

Could it be because the config gets inserted into `nginx-http.conf` that it overwrites something?

**Comment by spantaleev** [comment]
I can't reproduce this.

I'm trying to set up some new vhost server like this:

```yaml
matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    server {
      listen {{ 8080 if matrix_nginx_proxy_enabled else 80 }};
      server_name test.matrix.{{ matrix_domain }};
      return 301 https://{{ matrix_domain }}$request_uri;
      }
```

All of the usual vhosts work well. This one also seems to work and do a redirect, as expected.

I'm only testing plain HTTP though.

**Comment by TheNyneR** [comment]
The HTTP to HTTPS redirect works for me as well.
The HTTPS block with just `return http://{{ cloud_domain }}:5678$request_uri;` returns the login form of the nextloud container but only as HTTP again. As far as I know, nextcloud can only open a HTTP server. That would mean I have to proxy pass the request to get it over a HTTPS connection.
When I add the `location` block with the `proxy_pass` however the mentioned errors appear.

**Comment by spantaleev** [comment]
There are ways to `proxy_pass` to Nextcloud over HTTP and still have it not get confused.

[nextcloud-docker-ansible-deploy](https://github.com/spantaleev/nextcloud-docker-ansible-deploy) handles that by setting some `overwriteprotocol` configuration setting to `https`.

If you'd like to dig into that, see `nextcloud_config_default_parameters`:

- https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/roles/nextcloud-server/defaults/main.yml#L56
- https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/roles/nextcloud-server/tasks/setup_adjust_config.yml
- https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/docs/installing.md#adjusting-the-configuration

**Comment by TheNyneR** [comment]
Okay I just set the `overwriteprotocol` to `https` and also took a look at the `nginx.conf` for nextcloud-docker-ansible-deploy and inserted some values I found there:
```
matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    server {
      listen {{ 8080 if matrix_nginx_proxy_enabled else 80 }};
      server_name {{ cloud_domain }};
      return 301 https://{{ cloud_domain }}$request_uri;
      }
  - |
    server {
      listen {{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;
      listen [::]:{{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;

      server_name {{ cloud_domain }};
      server_tokens off;
      root /dev/null;

      ssl on;
      ssl_certificate {{ matrix_ssl_config_dir_path }}/live/{{ cloud_domain }}/fullchain.pem;
      ssl_certificate_key {{ matrix_ssl_config_dir_path }}/live/{{ cloud_domain }}/privkey.pem;
      ssl_protocols {{ matrix_nginx_proxy_ssl_protocols }};
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

      location / {
          proxy_pass http://localhost:5678/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          add_header Front-End-Https on;
      }

      #      return https://{{ cloud_domain }}:5679$request_uri;
      }
```
Now the `proxy_pass` doesn't destroy the configuration for the other domains at least. Now I'm just getting a 502 Bad Gateway from nginx. I'll try debugging this one.

**Comment by spantaleev** [comment]
`proxy_pass http://localhost:5678/;` is wrong.

There's no `localhost` when you run in a container network. You should reference the container name (like `nextcloud`) and the port **within** the container. I'm guessing `5678` is the exposed port. The one inside is likely `80.

**Comment by TheNyneR** [comment]
Thank you so much!That did it.^^
 `5678` was indeed the exposed port.
