### ISSUE TITLE
Can't accesss federation

### ISSUE THREAD

**Issue by univdet23** [spantaleev/matrix-docker-ansible-deploy#656]
I have my ansible matrix playbook configured and running bridges, whatsapp, instagram and telegram.

On my desktop I use the element desktop app.

If I search for other servers on matrix I get a `"M_UNKNOWN"` error. 

When I try to change the server to matrix.org I get `Federation denied with matrix.org`

I alredy tried to `matrix_synapse_federation_domain_whitelist` and added the servers I wanted to connect but without success. 

Any ideas how I could solve this ?

**Comment by aaronraimist** [comment]
If possible, the best way to get support is in our Matrix room `#matrix-docker-ansible-deploy:devture.com`. You can join using an account on another Matrix server such as Matrix.org or you can join the `#matrix-docker-ansible-deploy` channel on Freenode.

**Comment by aaronraimist** [comment]
Otherwise if that is not possible, can you share your domain?

You should not set `matrix_synapse_federation_domain_whitelist` unless you are intending to federate privately between only servers that you control.

**Comment by spantaleev** [comment]
As Aaron says, joining our support room is usually better for getting such help.

For federation to work, you need the appropriate `.well-known` files served at the base domain, or SRV records (and then matching certificates). Make sure you have not skipped doing the [Well-known setup step](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md) of our guide.


-------

Perhaps you've done this correctly and you'd like to selectively federate with this and that server? You'd like to federate with `matrix.org`, but not with others? This is usually the wrong way to go about things.

When federating selectively, you usually only want to federate with a small number of servers under your control. Not with a huge public server like matrix.org. A public server like this federates and exposes you to thousands of other servers, which yours will not be federating with. Participating in rooms where you only federate with matrix.org and not others, will lead to trouble.
