### ISSUE TITLE
matrix-admin fails on arm

### ISSUE THREAD

**Issue by mattcen** [spantaleev/matrix-docker-ansible-deploy#658]
The `matrix-admin` [Docker image](https://hub.docker.com/r/awesometechnologies/synapse-admin/tags) is only available for amd64, and unlike other roles, isn't configured to build itself on non-amd64 architectures.

I'm still working on getting this compiled for armv7, and haven't yet investigated the effort in implementing the logic to build the image.

Also, as an aside, `matrix_synapse_admin_docker_image` still points to version `0.4.1`, when `0.4.2` and `0.5.0` now exist. Once I get building to work, I intend to check if the later versions work OK with few to zero changes to the playbook.

**Comment by mattcen** [comment]
Ah, I was wrong. There *is* a self-build setup, it's just not configured to be required on non-amd64 arch. That should make this rather easier to fix.

**Comment by spantaleev** [comment]
Good point! I've enabled self-building when the architecture is not `amd64`. I've also verified 0.5.0 works and have upgraded to it.

Thank you! :+1:

**Comment by mattcen** [comment]
Oh, nice one, @spantaleev! I was *getting* around to finishing testing exactly the two changes you've just committed, but wasn't quite there yet. You're terribly efficient! :)
