### ISSUE TITLE
Nginx Proxy fails to start because of permission issue with port 80

### ISSUE THREAD

**Issue by kitzler-walli** [spantaleev/matrix-docker-ansible-deploy#665]
I try to install matrix on a Ubuntu 20.04 container in Proxmox which works well so far except for the nginx docker image.

Command used to start the docker image:
```docker run --rm --name matrix-nginx-proxy --log-driver=none --user=998:1000 --cap-drop=ALL --read-only --tmpfs=/tmp:rw,noexec,nosuid,size=1500m --network=matrix -p 80:8080 -p 443:8443 -p 8448:8448 -v /matrix/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro -v /matrix/ssl/config:/matrix/ssl/config:ro -v /matrix/static-files:/matrix/static-files:ro nginx:1.19.2-alpine```

results in this error:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2020/10/05 19:35:33 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

I can't find the point where port 80 is used here for the docker container.

**Comment by spantaleev** [comment]
This is strange.. `matrix-nginx-proxy` is not supposed to bind on port `80` by itself. It binds on other ports and it's Docker and its firewall rules which take care of the `80 -> 8080` forwarding.

I wonder why `matrix-nginx-proxy` tries to use port `80` for you. Have you modified the configuration somehow? Added your own custom `server` blocks which try to use port `80` directly? You might wish to change those to port `8080`.

Looking at the `docker run` command above, it seems non-standard. The playbook sets things up so that there's also this volume mounted in the `matrix-nginx-proxy` container: `-v /matrix/nginx-proxy/conf.d:/etc/nginx/conf.d:ro`. I can't see it in your example above.

**Comment by kitzler-walli** [comment]
I haven't modified anything - it's the script download from this repo as is.
I always failed at the tags=start step of this ansible script and after investigating it, this docker command turned up in the logs and I can't find any hints on how to solve it. I found a nginx alpine docker image with lower priviledges on the net as it seems that the newer version of this docker image seem to have higher restrictions, but I wasn't able to fix it with another version.

**Comment by kitzler-walli** [comment]
I just solved it but I can't tell why it failed in the first place. This was the matrix-nginx-proxy.service 

```
...
ExecStart=/usr/bin/env docker run --rm --name matrix-nginx-proxy \
                        --log-driver=none \
                        --user=998:1000 \
                        --cap-drop=ALL \
                        --read-only \
                        --tmpfs=/tmp:rw,noexec,nosuid,size=1500m \
                        --network=matrix \
                        -p 80:8080 \
                        -p 443:8443 \
                        -p 8448:8448 \
                        -v /matrix/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro \
                        -v /matrix/nginx-proxy/data:/nginx-data:ro \
                        -v /matrix/nginx-proxy/conf.d:/etc/nginx/conf.d:ro \
                        -v /matrix/ssl/config:/matrix/ssl/config:ro \
                        -v /matrix/static-files:/matrix/static-files:ro \
                        nginx:1.19.2-alpine
...
```

This one failed - then I changed it to this and now it works:
```
...
ExecStart=/usr/bin/env docker run --rm --name matrix-nginx-proxy \
                        --log-driver=none \
                        --user=998:1000 \
                        --cap-drop=ALL \
                        --read-only \
                        --tmpfs=/tmp:rw,noexec,nosuid,size=1500m \
                        --network=matrix \
                        -p 80:8080 \
                        -p 443:8443 \
                        -p 8448:8448 \
                        -v /matrix/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro \
                        -v /matrix/nginx-proxy/data:/nginx-data:ro \
                        -v /matrix/nginx-proxy/conf.d:/etc/nginx/conf.d:ro \
                        -v /matrix/ssl/config:/matrix/ssl/config:ro \
                        -v /matrix/static-files:/matrix/static-files:ro \
                        -v /matrix/nginx-proxy/conf.d:/etc/nginx/conf.d:ro \
                        nginx:1.19.2-alpine
...
````
