### ISSUE TITLE
is deploying node_modules necessary?

### ISSUE THREAD

**Issue by mayhd3** [spantaleev/matrix-docker-ansible-deploy#667]
I am running synapse on a cloud server with very small storage space, and node_modules takes up 500mb in /var/lib/docker/overlay2. Is it necessary to deploy node_modules to the server at all, or could it be stripped during deployment somehow?

**Comment by spantaleev** [comment]
Most likely, yes.

Not sure which service's `node_modules` you've found there, but it might be some service that you can go without.

Try disabling some services and rerunning the playbook if you'd like to run a more minimal server (not just in terms of disk space, but also memory, etc.).

You may need to run `docker system prune -a` on the server to get rid of old Docker images.

**Comment by mayhd3** [comment]
Thanks, that freed up a few gb! The path in overlay2 is ./<hash>/merged/home/node/matrix-dimension, so it looks like the self hosted dimension service is to blame, but I wanna keep it if possible. ./build is also in that folder, and has the expected contents, so I feel like the folder could be excluded, but I am not familiar enough with docker/ansible to know how. Either way your command freed up way more space than that is taking up, so I am fine for now.

**Comment by spantaleev** [comment]
It may be possible to optimize the [turt2live/matrix-dimension](https://hub.docker.com/r/turt2live/matrix-dimension) Docker image. Here's its [Dockerfile](https://github.com/turt2live/matrix-dimension/blob/master/Dockerfile). If you'd like to take a stab at that, please contribute it there (upstream) and it will trickle down to us.
