### ISSUE TITLE
support travis's media repository

### ISSUE THREAD

**Issue by jcgruenhage** [spantaleev/matrix-docker-ansible-deploy#67]
https://github.com/turt2live/matrix-media-repo

**Comment by turt2live** [comment]
`matrix-media-repo` now supports s3 (and s3-like) services by the way. With respect to it being invasive: it is, definitely. There are plans to make that less dangerous though: https://github.com/turt2live/matrix-media-repo/issues/101 and https://github.com/turt2live/matrix-media-repo/issues/60

**Comment by spantaleev** [comment]
Good to hear you've made a lot of progress on this!

I'm guessing this will be a much better way to store files on S3-like services than what we have now (Goofys fuse filesystem with various hacks to make it work). I could see us migrating toward `matrix-media-repo` in the future, if not for other cases, then just for improving and hopefully simplifying the S3 case.

Will keep an eye on this!

**Comment by aaronraimist** [comment]
1.0.0 is out now so it's probably a good time to revisit this.

One reason I would like to use matrix-media-repo even if the deduplication doesn't do that much for me is the ability to configure automatic deletion of remote content (and prevent my URL previews from expiring)
https://github.com/turt2live/matrix-media-repo/commit/0167c87e4278acb596d57164c8a52eef248b4d7d

**Comment by MTRNord** [comment]
Any update on it? Would love to use it

**Comment by ptman** [comment]
This is probably another thing that will be hit when scaling with workers

**Comment by Forden** [comment]
any updates?

**Comment by cvwright** [comment]
Can probably close this one now, with #2783 merged
