### ISSUE TITLE
Cannot reach homeserver on all clients EXCEPT element.domain.tld

### ISSUE THREAD

**Issue by Saik0Shinigami** [spantaleev/matrix-docker-ansible-deploy#670]
I don't even know where to begin here... This issue hurts my brain as it doesn't follow any logical sense.

So out of nowhere, a perfectly function matrix setup running on ubuntu 18.04.5 just died last night. This was running for months (years...) prior to this with minimal issues that I didn't cause myself.

Domains in use: 
matrix.saik0.com
element.saik0.com
dimension.saik0.com

I DO have a reverse proxy in front of it all. But that shouldn't be an issue as everything is accessible through the web-based solution. The web solution works locally, and through VPN connections across the world. 

What happen(ed/s): Last night (about 12 hours ago) all known connections dropped off of matrix. When connecting via app (desktop or phone) all I see is 
![image](https://user-images.githubusercontent.com/37313164/95779174-6e3f8000-0c7e-11eb-8b25-28ded33ae04c.png)

>Cannot reach homeserver
>Ensure you have a stable internet connection, or get in touch with the server admin

Dimension appears dead. Integrations fail to load "cannot reach your homeserver".

When accessing via browser (firefox), it functions. Services like email notices still function. Matrix.saik0.com, element.saik0.com, and dimension.saik0.com are directly addressable in browser and lands on correct pages.

Things I've already tried: Updating certs (I manually pull from my reverse proxy so the certs are homogeneous).
Reverting back to matrix getting it's own certs.
Checking all DNS (including local DNS resolver)
git pulling and setup-all

I cannot self-check, it fails on the cert verify step (which is why I was checking certs)
![image](https://user-images.githubusercontent.com/37313164/95780479-d2fbda00-0c80-11eb-961b-9d9d44e10c9f.png)
but I think this is related to the nature of my reverse proxy, the certs themselves are valid as shown on the domains when you get to them. The address it complains that it can't access does show information when you navigate there in a browser (https://matrix.saik0.com/_matrix/client/versions).

I'm at a loss as everything appears accessible except the app/program clients are just dumb... and dimension...

Logs don't show anything in particular of interest that I see. But maybe I'm just looking at the wrong thing or in the wrong place.

Side note... I do have an annoying issue where I have to sudo apt update to get rid of an python thing with ansible (one of the first checks)... No idea why this works either..

**Comment by aaronraimist** [comment]
It looks OK to me. Are you still experiencing the problem?

<img width="1444" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/95808253-af14b480-0cd1-11eb-8d9a-cb3c2f5aab9a.png">

**Comment by Saik0Shinigami** [comment]
Well after some time it actually resolved itself for some reason. I *think* it has something to do with an SSL mismatch that might have cleared itself up when my script run for homogeneous certs.
