### ISSUE TITLE
[Question] Is Jitsi OpenID Authentication via Matrix integrated?

### ISSUE THREAD

**Issue by 3lpsy** [spantaleev/matrix-docker-ansible-deploy#678]
It appears that Jitsi supports OpenID authentication, at least for widgets. The PR I'm referencing is here: https://github.com/vector-im/element-web/pull/15114 and the documentation/extra service required is here: https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification

My question is: has openid auth via such a prosody mod been integrated into this build? Would it be possible to do so? My main goal is to be able to not have to manage jitsi users separately and instead pass auth to matrix so I can lock down jitsi to valid users.

I ask this question as I'm trying to find out if 1) it's been integrated here and 2) if it's worth building out an integration PR (I'm new to matrix, but know ansible).

**Comment by teutat3s** [comment]
This is not implemented yet, but would be a very nice option IMO. I`d like to offer helping to integrate this, if that's already possible.

**Comment by spantaleev** [comment]
Seems interesting, especially if it can be made work seamlessly!

If anyone's willing to work on it and do a PR, that'd be great!

**Comment by skepticalwaves** [comment]
Definitely worthwhile. The existing "create your own users" for the Jitsi instance isn't workable at all.
