### ISSUE TITLE
Register a new user

### ISSUE THREAD

**Issue by uka7** [spantaleev/matrix-docker-ansible-deploy#680]
I have installed matrix server by docker image in my device, it worked, but when I try to create a new user by a client like "Element", I get an error saying "Registration has been disabled on this homeserver."
I couldn't find how to enable it in the container.
any help please.

**Comment by spantaleev** [comment]
```yaml
matrix_synapse_enable_registration: true
```

in your `vars.yml` file and then re-running the playbook with `--tags=setup-all,start`
