### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by andrewperry** [spantaleev/matrix-docker-ansible-deploy#682]
It would be fantastic if Minimum / Recommended System Requirements were added to /docs/prerequisites.md to help in sizing the host server.

**Comment by thuringia** [comment]
@andrewperry After trying things out on AWS for a couple of days, I came to these sizing requirements for solid performance:
- `t(2/3/3a).micro`: chat using only the Matrix protocol
- `t(2/3/3a).small`: chat using bridges and very light Jitsi use; you may have to restart Jitsi regularly or stop it
- `t(2/3/3a).medium/...`: this has been more than enough in testing with a group of friends and bridging all chat

This means that your server requires 1GB of memory for continuous operation, better 1.5 or 2GB.
As for CPU (cores) it looks like even 1 core on a `micro` instance is enough (w/o Jitsi) based on the performance metrics I observed.

You might be able to scale better with a separate Postgres server. I did not try this type of setup yet.

I hope that helps

**Comment by spantaleev** [comment]
Thanks for the report!

We also have some information about this in the FAQ, which I also linked to from the Prerequisites page.

**Comment by andrewperry** [comment]
Thanks that is excellent. We've had a dedicated server running matrix the 'old fashioned way' for some years so this now gives me confidence to invest some time into spinning up a test vps with a plan to migrate. 

Really appreciate the insights and work done on this!
