### ISSUE TITLE
Supporting notifications to new apps - Sygnal?

### ISSUE THREAD

**Issue by andrewperry** [spantaleev/matrix-docker-ansible-deploy#683]
To be able to push to your own iOS or Android app and for privacy etc I believe you need your own notifications server.

I am just wondering if there is a reason for not include https://registry.hub.docker.com/r/matrixdotorg/sygnal in this script?

**Comment by spantaleev** [comment]
Most of us would rather not compile our own apps (and bother with Apple Developer accounts, etc.), so it's not a priority adding Sygnal to the playbook.

Still, it belongs there and would be useful to some people. If someone would like to work on adding such a `matrix-sygnal` role, it'd be great!

**Comment by andrewperry** [comment]
Thanks, we have the other parts deployed without the playbook currently so will give it a try in development and if it makes sense we'll work on it and send a PR!

Appreciate all you've done here and continue to do on maintaining it.

**Comment by Aeris1One** [comment]
Is there any work going on for integrating sygnal ? 

For me that's the only thing missing in here.
