### ISSUE TITLE
why /_synapse instead of _synapse/client in nginx config?

### ISSUE THREAD

**Issue by localguru** [spantaleev/matrix-docker-ansible-deploy#685]
Hi,

some understanding questions:

why uses `roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2` seperate locations to /_matrix and /_synapse . Both locations contain the same config.

And why is the full /_synapse path published, which opens /_synapse/admin/ to the world.  See here
https://github.com/matrix-org/synapse/blob/master/docs/reverse_proxy.md
where locations are restricted to /_matix and /_synapse/client
```
    location ~* ^(\/_matrix|\/_synapse\/client) {
```
Andy why is it for port 8448 the complete / path open to the world instead of `location ~* ^(\/_matrix|\/_synapse\/client)` ?

**Comment by spantaleev** [comment]
Good point! Thank you! :+1: 

I've made the playbook not expose `/_synapse/admin` by default (see [this changelog entry](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#compatibility-break-_synapseadmin-is-no-longer-publicly-exposed-by-default)).

The `/_matrix` and `/_synapse/client` (and possibly `/_synapse/admin`, if enabled) locations are now combined into a single nginx `location` block, so there's no configuration duplication.

------

As for port `8448`, Synapse only serves the federation API there, so it doesn't hurt forwarding all traffic. There's no `/_synapse/admin` there or anything else that we should protect (as far as I know).

**Comment by localguru** [comment]
@spantaleev Great thank you!

What is the general benefit of splitting up client 443 and federation 8448? With delegation one could put everything into a single vhost e.g. 443. With the upcoming worker PR from @eMPee584 (Marcel) there are different location pathes for some workers, which are not published on port 8448, like media_repository, user_dir and frontend_proxy. In that case I understand two different ports for client and federation.

**Comment by spantaleev** [comment]
I guess the biggest benefit is separation of concerns and simplicity.

We may also put other things (like `matrix-corporal`) in front of the Client API (by overriding where the nginx requests get reverse-proxied to) and still easily leave the federation port completely unaffected.

Good to here that the worker setup benefits from the split as well!
