### ISSUE TITLE
Request to provide example docker-compose.yml for Traefik

### ISSUE THREAD

**Issue by enekonieto** [spantaleev/matrix-docker-ansible-deploy#687]
It would be nice having a example docker-compose.yml for launching a suitable Traefik instance suitable for the steps provided in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#sample-configuration-for-running-behind-traefik-20

Great job, the documentation of this playbook is amazing!

**Comment by spantaleev** [comment]
I don't use Traefik, so I can't help with this. But if you (or someone else) does get a `docker-compose.yml`-based Traefik setup working, contributing to the documentation (or `examples/` directory) would be great.
