### ISSUE TITLE
Jitsi installation - expired SSL certificate

### ISSUE THREAD

**Issue by schopenhauer** [spantaleev/matrix-docker-ansible-deploy#689]
I enabled the Jitsi service using the `matrix_jitsi_enabled: true` over 6 months ago. The self-signed SSL certificates seem to have expired automatically after 6 months and I would like to know, how I can re-generate these using the Ansible script. I also tried deleting the Jitsi folders as described in the documentation, but this did unfortunately not have any effect.

**Comment by spantaleev** [comment]
The playbook generates self-signed SSL certificates with a 10 year validity, by default, see here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5430a6541192b847530af93871ebbc5baaca592b/roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_self_signed_obtain_for_domain.yml#L39

Having them expire after 6 months is strange. Still, if you'd like to get rid of the current certificates and start over, then delete the `/matirx/ssl` directory on the server and re-run the playbook.

**Comment by schopenhauer** [comment]
Ok, understood. Is this self-signed certificate the same being used by Jitsi?

**Comment by spantaleev** [comment]
Jitsi does not use any SSL certificates on its own. It's a local service running in a container in an unsecure manner.

The SSL certificate for `jitsi.DOMAIN` is obtained (or generated, self-signed) via the `matrix-nginx-proxy` role, for use by the integrated nginx webserver which normally fronts all domains used by the playbook (`matrix.DOMAIN`, `element.DOMAIN`, `jitsi.DOMAIN`, `dimension.DOMAIN`, etc.)
