### ISSUE TITLE
After setting up S3 media_store mount, permission is denied and media upload fails

### ISSUE THREAD

**Issue by jxing8** [spantaleev/matrix-docker-ansible-deploy#695]
After setting up S3 mount for media_store following the instructions, I am getting permission denied the for folder:

root@ip-172-31-4-199:/matrix/synapse/storage# ll -la
ls: cannot access 'media-store': Permission denied
total 8
drwxr-x--- 3 matrix matrix 4096 Oct 27 06:09 ./
drwxr-x--- 5 matrix matrix 4096 Oct 27 06:09 ../
d????????? ? ?      ?         ?            ? media-store/

This was also the result during setup 

TASK [matrix-synapse : Check Synapse media store path] *********************************************************************************************************************************************
fatal: [matrix.acadelab.com]: FAILED! => {"changed": false, "msg": "Permission denied"}
...ignoring

TASK [matrix-synapse : Check Matrix Goofys external storage mountpoint path] ***********************************************************************************************************************
fatal: [matrix.acadelab.com]: FAILED! => {"changed": false, "msg": "Permission denied"}
...ignoring

I tried uploading media using the client and all uploads fail immediately. What might be the cause of this? I check the correctness of the credentials and network rules.

**Comment by jxing8** [comment]
It seems to be the same issue described here: https://github.com/kahing/goofys/issues/379. Is this a problem with ansible or my configuration?

**Comment by spantaleev** [comment]
We expect these failures, which is why you can see `...ignoring` in the output. It's not a problem, I suppose.

As for uploads failing, it's something to be investigated. I don't use Goofys on any of my setups, so it's difficult for me to troubleshoot. You should check why it fails by taking a look at Synapse's logs (`journalctl -fu matrix-synapse`) or Goofys logs (`journalctl -fu matrix-goofys`).

**Comment by jxing8** [comment]
This was a decryption problem and I managed to get it to work.

**Comment by jprystowsky** [comment]
@jxing8 Would you mind sharing what your fix was?

**Comment by jxing8** [comment]
I bought a wildcard ssl instead of using let's encrypt and it solved the problem.
