### ISSUE TITLE
Feature: redirect _matrix/static/ to element

### ISSUE THREAD

**Issue by localguru** [spantaleev/matrix-docker-ansible-deploy#696]
Hi,

what about redirecting from nginx client vhost

```
        location / {
                rewrite ^/$ /_matrix/static/ last;
        }
```
to element matrix client vhost in `matrix-client-element.conf` (if matrix-client-element is installed)? 

If a user calls `https://matrix.$host` not the static page from `_matrix/static/` is shown, but redirected to the web client, so something like

```
        location / {
                return 301 https://element.$host$request_uri;
        }
```
Ciao!

**Comment by spantaleev** [comment]
It's possible to make this configurable. It only makes sense if Element is installed and if the user wants such a redirect though.

Perhaps most users would not just know this as "that Element chat thing" and will barely hear the word "matrix" or will think to go to `matrix.DOMAIN`. Not sure how useful such a redirect is in practice.

**Comment by localguru** [comment]
@spantaleev I use SAML login, so the main URL to connect to matrix with the mobile clients is matrix.DOMAIN. It would be nice, if there is just one domain for users and not element.DOMAIN for browser client and matrix.DOMAIN for mobile clients.

**Comment by localguru** [comment]
@spantaleev question: regardless of whether this makes sense in all cases. Is anything wrong with my 301 redirect? Will I run in problems with that? Is there something under `/_matrix/static/` that should be accessible under the last `/` "catch all" location?

**Comment by spantaleev** [comment]
You're right about SAML login!

It does make some sense to include this feature in the playbook. so I've done it in 9a46647010989. It's also enabled by default. Thanks for provoking this change! :+1: 

I've opted for a temporary (`302`) redirect instead of a permanent though.

**Comment by localguru** [comment]
@spantaleev Great, thank you for your feedback, help and time!
