### ISSUE TITLE
remove weak ciphers?

### ISSUE THREAD

**Issue by localguru** [spantaleev/matrix-docker-ansible-deploy#697]
Hi,

ssl ciphers for nginx show some WEAK results on ssllabs.com.

```
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
```
in 
```
roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2
roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2
roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2
roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-riot-web.conf.j2
roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2

```
ssllabs.com results:
```
# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH x25519 (eq. 3072 bits RSA)   FS 	256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH x25519 (eq. 3072 bits RSA)   FS 	128

TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK 	256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK 	256

```
I cannot assess whether this is a security problem or can be ignored, but perhaps the ciphers could be adjusted to make the result "clean" without excluding clients.

And an idea might be to put the content of ssl_ciphers in above file into a ansibles variable, so changes could be done at one place.

Cheers
Marcus

**Comment by FanchTheSystem** [comment]
Maybe we should use mozilla configuration as proposed here: https://ssl-config.mozilla.org/
With only one ansible variable which should be "Modern" "Intermediaite" and "Low".

To understand those proposed value, you may want to read: https://infosec.mozilla.org/guidelines/web_security.html
