### ISSUE TITLE
Plans to add WeChat Bridge

### ISSUE THREAD

**Issue by senzen777** [spantaleev/matrix-docker-ansible-deploy#701]
Are there any plans to integrate add a WeChat bridge? 
https://github.com/wechaty/matrix-appservice-wechaty

**Comment by spantaleev** [comment]
No plans. Most of our bridges are community contributions by people interested in having these bridges.

Looks like the WeChat bridge already has a Docker image, so it shouldn't be too hard to integrate into the playbook. One can use any of the existing bridge roles we have (see the `roles/matrix-bridge-...` directories) and build on that.

This should probably be done by someone who has a WeChat account and can confirm that it all works, etc. Most of us don't. From what I've seen, it's also quite hard to obtain such an account, especially without knowing any Chinese people.

If someone would like to work on adding support for this bridge, it'd be great!

**Comment by neonknight** [comment]
WeChat accounts can be registered by anyone outside PR China without restrictions. Inside PR China the service is called weixin and it's hard to get such an account from outside PR China. WeChat and weixin are currently interoperating.

**Comment by tobiasdiez** [comment]
If someone could give https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3241 a try, this would be very much appreciated.
