### ISSUE TITLE
matrix-synapse[823]: docker: Error response from daemon: path /matrix/synapse/storage is mounted on / but it is not a shared or slave mount.

### ISSUE THREAD

**Issue by RedJohn14** [spantaleev/matrix-docker-ansible-deploy#703]
Hello,

I can start the matrix-synapse container. all other containers are running without problem. In syslog I found this:

matrix-synapse[823]: docker: Error response from daemon: path /matrix/synapse/storage is mounted on / but it is not a shared or slave mount.

And ansible said:
"ansible_loop_var": "item", "changed": false, "item": "matrix-synapse", "msg": "matrix-synapse was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-synapse` and `journalctl -fu matrix-synapse` on the server to investigate."}

Any ideas?

**Comment by spantaleev** [comment]
This turned out to be because the whole thing was installed within an LXC container.

The solution was to remount `/` somehow, before starting this service.

I guess we can close this now. If you can provide more details about how you're solving this, it would probably be helpful to people who will find this thread in the future.

**Comment by bmanturner** [comment]
> The solution was to remount / somehow, before starting this service.

This isn't helpful. I'd like to make sure the solution gets documented here for people like me.

Do you remember what you did?

**Comment by spantaleev** [comment]
I'm just summarizing what someone else told me he did. I haven't had this problem, but it's usually related to running our services within an LXC container, from what I've seen.

You'd need something like `mount -o remount /`, I think. Perhaps some other options next to `remount`. If you find out what works for you, feel free to post it.

**Comment by bmanturner** [comment]
I found that you would need to use `mount -o remount,rw /` but I couldn't figure out how to do it on a running LXC container so I opted to use a VM instead. 

My apologies to anyone hoping for a good solution. I can tell you I tried both a privileged and unprivileged container with nesting and nfs enabled and it made no difference. You __could__ potentially look into disabling AppArmor for this container and see if that helps you make any progress.

**Comment by RedJohn14** [comment]
> I found that you would need to use `mount -o remount,rw /` but I couldn't figure out how to do it on a running LXC container so I opted to use a VM instead.
> 
> My apologies to anyone hoping for a good solution. I can tell you I tried both a privileged and unprivileged container with nesting and nfs enabled and it made no difference. You **could** potentially look into disabling AppArmor for this container and see if that helps you make any progress.

I have fixed is in my lxc container with this command

`mount --make-shared /`

I used this command on every startup my lxc container and restart docker services. lxc container are more leighter than a vm.

Maybe with this solution we can make some fix?

**Comment by shreyasajj** [comment]
@RedJohn14 can we make this a crontab on reboot?

**Comment by RedJohn14** [comment]
> @RedJohn14 can we make this a crontab on reboot?

Hey shreyasajj,

yes I have configure this in the cronjob.

Thank you!

**Comment by Haxprox** [comment]
I think better option here is to edit '_matrix-synapse.service_' systemd unit and add '_ExecStartPre_'.
Somethink like that:

```
[Service]
Type=simple
Environment="HOME=/root"
ExecStartPre=-/usr/bin/env sh -c 'mount --make-shared /'
ExecStartPre=-/usr/bin/env sh -c '/usr/bin/env docker kill matrix-synapse 2>/dev/null'
ExecStartPre=-/usr/bin/env sh -c '/usr/bin/env docker rm matrix-synapse 2>/dev/null'

```

Works flawlessly but looks still awfully instead of using something before running the container.

**Comment by tnijboer** [comment]
Adding an systemd drop-in file is more persistent

`mkdir -p /etc/systemd/system/matrix-synapse.service.d`

create a file _override.conf_ with the following content
```
[Service]
Type=simple
Environment="HOME=/root"
ExecStartPre=-/usr/bin/env sh -c 'mount --make-shared /'
```
After creating the file:
`systemctl daemon-reload `
