### ISSUE TITLE
matrix federation problem 404 not found - tested with matrix.org

### ISSUE THREAD

**Issue by RedJohn14** [spantaleev/matrix-docker-ansible-deploy#706]
Hi,

I have installed matrix server with your ansible playbook, all is fine. But if I try to send message from matrix.org to my domain e.g.

@user:mydomain.com

I get error in my log file and can't send message:

Nov  4 01:28:13 magini matrix-nginx-proxy[9438]: 176.126.240.158 - - [04/Nov/2020:00:28:13 +0000] "GET /_matrix/federation/v1/query/profile?user_id=%40user%3Amydomain.com&field=displayname HTTP/1.1" 404 167 "-" "Synapse/1.22.1 (b=matrix-org-hotfixes,ce2107eee)" "-"
Nov  4 01:28:13 magini matrix-nginx-proxy[9438]: 176.126.240.158 - - [04/Nov/2020:00:28:13 +0000] "PUT /_matrix/federation/v2/invite/%21lgLgBuEApphwrrtkpH%3Amatrix.org/%24ulKqn2wHVV7niDnG5TRnUUYXqkbKZETGrPDNlOob8Ac HTTP/1.1" 404 167 "-" "Synapse/1.22.1 (b=matrix-org-hotfixes,ce2107eee)" "-"

How can I fix it? By the way is there any option to set federation on port 443? The matrix.org servers are only available over 443.

Regards!

**Comment by aaronraimist** [comment]
Can you share the domain? That is how we can help you figure it out.

> How can I fix it? By the way is there any option to set federation on port 443? The matrix.org servers are only available over 443.

It doesn't matter what port matrix.org uses, you can use any port you want including the Matrix spec default of 8448.

**Comment by RedJohn14** [comment]
> Can you share the domain? That is how we can help you figure it out.
> 
> > How can I fix it? By the way is there any option to set federation on port 443? The matrix.org servers are only available over 443.
> 
> It doesn't matter what port matrix.org uses, you can use any port you want including the Matrix spec default of 8448.

Thanks for fast reply. I send you Domain via matrix.

Any idea for my traefik configuration? At the Moment I used build in nginx.

But i want to use traefik with coturn!

**Comment by localguru** [comment]
> How can I fix it? By the way is there any option to set federation on port 443? The matrix.org servers are only available over 443.

If you separate client 443 and federation 8448 it's easier to configure them different, like max upload, separate nginx logging, blacklist IPs, different regex for worker URLs on client and federation etc. You can put client and federation on 443, yes. That should be no problem. I was thinking about that too, when I set up my server, but split it up.
