### ISSUE TITLE
Specify a volume path for the docker containers.

### ISSUE THREAD

**Issue by pintaf** [spantaleev/matrix-docker-ansible-deploy#707]
Hello.

I've seen no way in the config, nor in the code to specify a default path where the docker volumes will be saved.
It's interesting for example if you want to store the data on different partition / disk.

Maybe I missed that, but I looked for it quite seriously.
Thanks.

**Comment by spantaleev** [comment]
We don't use "Docker volumes". That is, we bind-mount regular directories into the containers.

All of these data directories are somewhere in `matrix_base_data_path` (defaulting to `/matrix`, as per `roles/matrix-base/defaults/main.yml`).

You can override `matrix_base_data_path` in your `vars.yml` file to use another directory. Alternatively, you can bind-mount another directory to `/matrix` and use the default configuration.
