### ISSUE TITLE
fatal error in "TASK Generate initial Synapse config and signing key" Raspberry Pi 4

### ISSUE THREAD

**Issue by whowantsmybigdata** [spantaleev/matrix-docker-ansible-deploy#710]
hi, I already posted the same problem in the support room 2 days ago but the solutions („docker network prune, docker system prune, docker restart, upgrade the packages, check the dns config and in the end updating the kernel) unfortunately didn’t work. 
<details>
<summary> The error-log is exactly the same as before. </summary>
<code> TASK [matrix-synapse : Generate initial Synapse config and signing key] **************************************
2020-11-06 22:29:35,030 p=761 u=[user hidden] |  fatal: [matrix.[domain hidden]]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=1001:1001", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=1001", "-e", "GID=1001", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=matrix.[domain hidden]", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.18.0", "generate"], "delta": "0:00:01.829870", "end": "2020-11-06 22:29:35.000965", "msg": "non-zero return code", "rc": 1, "start": "2020-11-06 22:29:33.171095", "stderr": "standard_init_linux.go:211: exec user process caused \"exec format error\"", "stderr_lines": ["standard_init_linux.go:211: exec user process caused \"exec format error\""], "stdout": "", "stdout_lines": []}
2020-11-06 22:29:35,036 p=761 u=[user hidden]
 </code>
</details>

I try to install the playbook on my Raspberry Pi 4 running Raspbian/Debian 10 Buster with the newest 5.4.74-v7l+ kernel. 
Of course I put „matrix-architecture=arm32“ in the vars.yml.
I tried to install it from my Mac and another Raspberry Pi via external and internal ip and on the Raspberry Pi 4 itself (each with the corresponding changes in the inventory/hosts regarding the explanation in this file/in the docs. 
The only thing I could guess which might be different from the docs is my DNS/Domain situation: 
I use a dynamic DNS (desec.io) where I was able to put the the DNS records as given in the docs for the subdomain „matrix.“ and „dimension.“ (I switched off element web ui installation in the playbook).
Any ideas?!
Thanks in advance

**Comment by spantaleev** [comment]
It seems like the Synapse Docker image that you have is for another architecture.

Is it possible that you ran the playbook **without** `matrix-architecture=arm32` at first? Perhaps it pulled an `amd64` image at that time and you re-running it now doesn't cause it to get updated.

You can try getting rid of the current Synapse image like this:
- `systemctl stop matrix*`
- `docker rmi matrixdotorg/synapse:v1.22.1`

You can then re-run the playbook and see if it fixes the problem.

----------

We try to make use of Synapse v1.22's new "multi-arch" Docker images, so that when you specify `matrix-architecture=arm32`, we let you just pull from Docker Hub.

Previously, we were forcing you to [self-build](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/self-building.md) the image, but not anymore.

If you'd like to give self-building a try (only for Synapse), try: `matrix_synapse_container_image_self_build: true`.

(You may need to remove any existing image first with the aforementioned method)

**Comment by whowantsmybigdata** [comment]
Thanks for the fast reply! 
At first it said: 
<code>Failed to stop matrix-docker-ansible-deploy.service: Unit matrix-docker-ansible-deploy.service not loaded.</code>
and
<code> Error: No such image: matrixdotorg/synapse:v1.22.1</code>
but when executing the script /usr/local/bin/matrix-remove-all
it says 
<code>Untagged: matrixdotorg/synapse:v1.18.0</code>
<details><summary>afterwards the playbook fails with the same error:</summary>
<code>fatal: [matrix._[domain hidden]_]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "--name=matrix-config", "--user=1001:1001", "--cap-drop=ALL", "-v", "/matrix/synapse/config:/data", "-e", "UID=1001", "-e", "GID=1001", "-e", "SYNAPSE_CONFIG_PATH=/data/homeserver.yaml", "-e", "SYNAPSE_SERVER_NAME=matrix._[domain hidden]_o", "-e", "SYNAPSE_REPORT_STATS=no", "matrixdotorg/synapse:v1.18.0", "generate"], "delta": "0:00:03.193865", "end": "2020-11-09 09:40:55.044282", "msg": "non-zero return code", "rc": 1, "start": "2020-11-09 09:40:51.850417", "stderr": "standard_init_linux.go:211: exec user process caused \"exec format error\"", "stderr_lines": ["standard_init_linux.go:211: exec user process caused \"exec format error\""], "stdout": "", "stdout_lines": []}</code></details>

in the support-room 
<details><summary>I got the following out of executing the playbook with <code>--tags=self-check</code> instead of <code>--tags=setup-all</code></summary>
<code>TASK [matrix-synapse : Check Matrix Client API] **************************************************************
fatal: [matrix.[domain hidden] -> 127.0.0.1]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Verbindungsaufbau abgelehnt>", "redirected": false, "status": -1, "url": "https://matrix.[domain hidden]/_matrix/client/versions"}
...ignoring

TASK [matrix-synapse : Fail if Matrix Client API not working] ************************************************
fatal: [matrix.[domain hidden] -> 127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed checking Matrix Client API is up at matrix.[domain hidden] (checked endpoint: https://matrix.[domain hidden]/_matrix/client/versions). Is Synapse running? Is port 443 open in your firewall? Full error: {'content': '', 'redirected': False, 'url': 'https://matrix.[domain hidden]/_matrix/client/versions', 'msg': 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Verbindungsaufbau abgelehnt>', 'status': -1, 'failed': True, 'changed': False}"}</code></details>

although DNS and router-portforwarding are exactly as described in the docs
when I put <code>http://matrix._[domain hidden]_</code> in my browser while using a VPN it shows "Welcome to nginx" (because I have another Raspberry Pi running nginx behind the same router)
at the same time <code>https://matrix._[domain hidden]_</code> it shows <code>PR_CONNECT_RESET_ERROR</code>

**Comment by aaronraimist** [comment]
Is your copy of the playbook up to date? Synapse 1.18.0 is from a few months ago.

**Comment by whowantsmybigdata** [comment]
yeah thats strange I also just realized that when you wrote synapse 1.22 will try to redownload the playbook

**Comment by whowantsmybigdata** [comment]
hm when trying to self-build it says:
<code>FAILED! => {"changed": false, "msg": "To self build Synapse image, you should usa ansible 2.8 or higher. E.g. pip contains such packages."}</code>
but <code>pip3 install ansible</code> only installs ansible 2.77 for me

**Comment by spantaleev** [comment]
Take a look at our [Ansible docs page](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md).

You can run Ansible in Docker too. The Ansible Docker image we recommend will not work on ARM though, so you either have to build it yourself, or run Ansible on some other (`amd64`) host.

**Comment by whowantsmybigdata** [comment]
ok I installed it with <code>pip3 install ansible</code> which installed the old 2.77 version. Installing it via <code>python -m pip install ansible</code> installed the newest 2.10.3 version

**Comment by whowantsmybigdata** [comment]
ok I think now I got a big step further but it now says it cant find the certs because it is looking for <code>/etc/letsencrypt/live/matrix.[domain hidden]</code> and not <code> /etc/letsencrypt/live/[domain hidden] </code>
I now just did a <code> ln -s </code> to create the path the playbook wants but still keep the original-base-domain-name-folder for all other applications using this certs but the playbook seems to change the permissions of the certs folder to matrix:matrix which is bad for everything else needing access

**Comment by whowantsmybigdata** [comment]
ok that worked! wow!! thanks a lot
