### ISSUE TITLE
Check existence of matrix-dynamic-dns service failed

### ISSUE THREAD

**Issue by schwony** [spantaleev/matrix-docker-ansible-deploy#715]
setup.yml --tags=setup-all fails here:

`fatal: [matrix.***.de]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'systemd_path' is undefined\n\nThe error appears to be in '/home/***/matrix-docker-ansible-deploy/roles/matrix-dynamic-dns/tasks/uninstall.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Check existence of matrix-dynamic-dns service\n  ^ here\n"}`

any suggestions?

thanks for your great work

**Comment by spantaleev** [comment]
Thanks for catching this! Fixed! :+1:
