### ISSUE TITLE
Why is default_room_version hard set to "6" ?

### ISSUE THREAD

**Issue by localguru** [spantaleev/matrix-docker-ansible-deploy#721]
Hei,

why is `matrix_synapse_default_room_version` set to 6? Wouldn't it make more sense not to set the option at all or to set it only if `matrix_synapse_default_room_version`was defined by hand. By default, `default_room_version` is not defined in homserver.yaml, so that the room version of the developers is used.

```
# For example, for room version 1, default_room_version should be set
# to "1".
#
# default_room_version: {{ matrix_synapse_default_room_version|to_json }}
```

**Comment by spantaleev** [comment]
We can deprecate this variable, not define anything and let Synapse use the default.

People can then override it by injecting stuff into `matrix_synapse_configuration_extension_yaml`, like this:

```yaml
matrix_synapse_configuration_extension_yaml: |
  default_room_version: 6
```

But we've had this variable for a long time. Removing it may cause breakage for people that use it.

Of course, we can define it as no-longer-in-use in `roles/matrix-synapse/tasks/validate_config.yml` and point people to this issue to make them migrate to using `matrix_synapse_configuration_extension_yaml`.

Should we, should we not.. It's no big deal either way, I guess.

**Comment by aaronraimist** [comment]
@localguru why wouldn't there be a variable for it? Having a variable allows people to use the version they want. We keep the default value up to date with the Synapse default. I don't see why you have an issue with it existing.
