### ISSUE TITLE
RFE: please list the no record and no transcript options in configuring-playbook-jitsi.md

### ISSUE THREAD

**Issue by pcfe** [spantaleev/matrix-docker-ansible-deploy#726]
Thanks for creating matrix-docker-ansible-deploy, this made setting up a Matrix homeserver pretty painless
:+1: 

Two things that might be nice to explicitly mention in `configuring-playbook-jitsi.md` would be the options to disable recordings and/or transcripts. 

Something along the lines of

===8<---
## (Optional) Disable Recordings and/or Transcripts

By default the Jitsi Meet instance allows recording meetings and transcribing audio to subtitles.

If you want / need to disable one or both of these options, then add  the appropriate lines to your `inventory/host_vars/matrix.DOMAIN/vars.yml` configuration:

```yaml
matrix_jitsi_enable_recording: false
```

```yaml
matrix_jitsi_enable_transcriptions: false
```
--->8===

Reasoning;
* recordings forced off: I want to allow friends and family to communicate easily, but I have no wish at all to deal with the neither the storage space needs nor the case of user A pressing record against user B's wishes.
* transcription forced off: I have no need for it and have not (yet) checked where the audio would be piped through to achieve the transcription.

**Comment by spantaleev** [comment]
Recording requires an additional component (Jibri) to be installed. Transcriptions likely require something else like that (or Jibri as well, not sure). So it won't work in either case.

Maybe it makes sense to change our defaults to disable these.

**Comment by pcfe** [comment]
> Maybe it makes sense to change our defaults to disable these.

Yes, please.

**Comment by spantaleev** [comment]
Changed the defaults! Thanks! :+1:
