### ISSUE TITLE
Feature Request: Support Container Orchestration

### ISSUE THREAD

**Issue by dnk8n** [spantaleev/matrix-docker-ansible-deploy#733]
I am going to be investigating the use of [Nomad](https://www.nomadproject.io/) in managing a matrix server that can be scaled to multiple containers when necessary (ability to add new nomad clients and allow orchestration to spread the load across the cluster).

For this to happen, an emphasis on separation of server configuration from container specification is required.

Would Nomad job files be of interest to this repo? Maybe someone else with k8s experience can similarly contribute the equivalent infrastructure code.

If not, I am thinking of one-way syncing a fork with this repo but where I will make changes to support Nomad managing containers across a cluster.

This issue can be closed and reopened on the fork. Just interested to know if container orchestration has been considered and whether this would be of value to the maintainer.

**Comment by spantaleev** [comment]
This sounds like a completely different way to do things.

There are other projects (like [dacruz21/matrix-chart](https://github.com/dacruz21/matrix-chart)) which aim to set you up with a Matrix server on top of Kubernetes.

Our intended audience is regular folk who can dedicate 1 regular server to run Matrix. Sometimes they even want to or already host other services on that server, so we do our best to co-exist with them.

Orchestration tools and clusters (multiple machines) sounds like a much larger investment and complicated thing to manage than most of us would like.

While I do find the appeal of managing servers as cattle, not pets, I'm not sure how many of us would like the additional complication.

As for contributing Nomad support here, I'm guessing it would end up being too different to be feasible to maintain along with our current way of doing things.

**Comment by dnk8n** [comment]
I totally agree. Thanks for taking the time to write your thoughts. Already this project must be quite big to maintain. An orchestrated approach would be better off as a separate effort.
