### ISSUE TITLE
Jitsi configuration improvements

### ISSUE THREAD

**Issue by dnk8n** [spantaleev/matrix-docker-ansible-deploy#735]
**[EDIT]:** I thought out and figured out the solution as I was typing this issue. Please first look at follow up comment.

I ran through the Jitsi configuration and found that it did not come with SSL out of the box at jitsi.<ROOT_DOMAIN>.

The docs could do with answering some questions (I am happy to contribute them, but need to clarify a few things in my mind).

1. Is Jitsi connected to Nginx? (I can only really help support a configuration similar to my own where traefik proxies to a containerized nginx)

2. If so, do we extend the following line? (Is there a host variable for jitsi, ```matrix_server_fqn_jitsi` for example?) `  - '--label "traefik.http.routers.matrix-nginx-proxy.rule=Host(`{{ matrix_server_fqn_matrix }}`,`{{ matrix_server_fqn_element }}`,`{{ matrix_server_fqn_dimension }}`)"'```

3. Else, if we are to route through traefik directly (for example) like Synapse is (see my Synapse config)?

```
matrix_synapse_container_extra_arguments
  # May be unnecessary depending on Traefik config, but can't hurt
  - '--label "traefik.enable=true"'

  # The Synapse container will receive traffic from this subdomain
  - '--label "traefik.http.routers.matrix-synapse.rule=Host(`{{ matrix_server_fqn_matrix }}`)"'

  # (The 'synapse' entrypoint must bind to port 8448 in Traefik config)
  - '--label "traefik.http.routers.matrix-synapse.entrypoints=synapse"'

  # (The 'default' certificate resolver must be defined in Traefik config)
  - '--label "traefik.http.routers.matrix-synapse.tls.certResolver=dns"'

  # The Synapse container uses port 8048 internally
  - '--label "traefik.http.services.matrix-synapse.loadbalancer.server.port=8048"'
```
i.e. Would we create jitsi entrypoints (ports 4443/tcp, 10000/udp for example) and follow a similar pattern to matrix-synapse service? In that case what is the equivalent to `matrix_synapse_container_extra_arguments` for jitsi if there is one?

**Comment by dnk8n** [comment]
I found that there is a `matrix_server_fqn_jitsi` variable. And ```,`{{ matrix_server_fqn_jitsi }}` ``` needs to be added inside the parenthesis of Host in line:

```
- '--label "traefik.http.routers.matrix-nginx-proxy.rule=Host()"'
```

**Comment by spantaleev** [comment]
Thanks! :+1:  Updated the docs!
