### ISSUE TITLE
delete specific chat history from room - script for clean chat history

### ISSUE THREAD

**Issue by RedJohn14** [spantaleev/matrix-docker-ansible-deploy#742]
Hello,

I want to delete specific chat history. Like a script that always runs at same time and clear some rooms. I have monitoring room with status messages, but I want to delete old messages from this room. Any idea how can I make it really easy? Maybe with some curl API command?

Thanks!

**Comment by spantaleev** [comment]
This is not really related to the playbook.

You may wish to look into Synapse's [Purge History API](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/purge_history_api.rst).

[This article](https://levans.fr/shrink-synapse-database.html) also mentions it, along with other things you may find useful.
