### ISSUE TITLE
Remove synapse-janitor

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#746]
Okay we can go ahead and fully remove synapse-janitor now. The admin APIs built in to Synapse allow you to replicate the same behavior in a supported way https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md.

I'm pretty sure I saw a script someone already wrote that combines the list room API and the delete room API but I can't quite find it at the moment.

**Comment by spantaleev** [comment]
Good point! :+1:  We shouldn't drag it along anymore. Removed!
