### ISSUE TITLE
Matrix-registration token creation SSL Fail

### ISSUE THREAD

**Issue by angel12** [spantaleev/matrix-docker-ansible-deploy#759]
When I try to request a new registration token, curl gives an error:
TASK [Call matrix-registration token creation API] *********************************************************************fatal: [(mydomain).com]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>", "redirected": false, "status": -1, "url": "https://(mydomain)/matrix-registration/token"}

**Comment by spantaleev** [comment]
What's your `matrix_ssl_retrieval_method` variable like?

Looks like you're using self-signed certificates somehow. Perhaps you've set `matrix_ssl_retrieval_method` to `none`?

If you're using `self-signed`, then we automatically skip SSL certificate validation for such `matrix-registration` requests (and others): https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ca066217d1841b79dd127d27c058280a976fb1de/group_vars/matrix_servers#L1070

If you're using `none` or `manually-managed`, we can't be sure whether your certificates are self-signed or not and whether we should validate them or not.

As a quick workaround, you can set this variable to `false` in your `vars.yml` configuration file:

```yaml
matrix_registration_api_validate_certs: false
```

**Comment by angel12** [comment]
Found the issue, and is almost always true, it was DNS. 

I was setting this up in a new network that I hadn't really done much with, and totally forgot to set an a record locally for the matrix server, so it was actually trying to go out and then back in through my firewall, which was causing the issue.
