### ISSUE TITLE
GeoIP support for Nginx?

### ISSUE THREAD

**Issue by LuigiVampa92** [spantaleev/matrix-docker-ansible-deploy#767]
Hi, first of all thank you for the great work. Deploying personal matrix server never been easier

I would like to know if there is a way to add geoIP support for nginx and be able to blacklist/whitelist requests from certain countries?

Thank you!

**Comment by spantaleev** [comment]
Hi and thank you!

You can accomplish this by switching to another container image for nginx. By default, we use `matrix_nginx_proxy_docker_image: "docker.io/nginx:1.19.6-alpine"`, which does not contain GeoIP support as far as I know.

You can override this variable and point to your own other image.

You can probably use a modification of the original `Dockerfile` (living in [this repository](https://github.com/nginxinc/docker-nginx)).

---------

To add additional statements to nginx `server{}` blocks (so you can do GeoIP restrictions), you can use the various `matrix_*_additional_server_configuration_blocks` variables that we have: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/c0a62d6c17a17248757db5f71b0431f5ee44c0e4/roles/matrix-nginx-proxy/defaults/main.yml#L197-L216
