### ISSUE TITLE
Add Caddy 2 instructions for Synapse Admin

### ISSUE THREAD

**Issue by n0toose** [spantaleev/matrix-docker-ansible-deploy#768]
- [Caddy Examples](https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/examples/caddy)
- [Setting up Synapse Admin (optional)](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-synapse-admin.md)

**Comment by vaivars** [comment]
Added example for synapse admin - 
https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1985
