### ISSUE TITLE
tulir's dockerhub account seems to have been deleted, update playbook?

### ISSUE THREAD

**Issue by 0spinboson** [spantaleev/matrix-docker-ansible-deploy#773]
This is probably unrelated to the issues I've run into since trying to get mautrix-telegram to work again since the dec 23 update to the playbook, but it seems tulir's docker builds of the bridge bots are gone?

**Comment by spantaleev** [comment]
We use `matrix_mautrix_telegram_docker_image: "dock.mau.dev/tulir/mautrix-telegram:v0.9.0"` by default.

`docker pull dock.mau.dev/tulir/mautrix-telegram:v0.9.0` works for me.
