### ISSUE TITLE
AnsibleFileNotFound: Could not find or access <matrix_base_data_path>/vars.yml' on the Ansible Controller.

### ISSUE THREAD

**Issue by leematos** [spantaleev/matrix-docker-ansible-deploy#779]
Trying to deploy (ansible-playbook -i inventory/hosts setup.yml --tags=setup-all) to a current arch host  and getting this error based on:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-base/tasks/setup_matrix_base.yml#L16

I think this error is okay to ignore, but as an ansible newbie, i'm not sure if this should be host-vars.yml or if some other prereq to create vars.yml silently failed.

Happy to submit an change if anyone can point me in the right direction.

**Comment by leematos** [comment]
I realized i could skip this with matrix_vars_yml_snapshotting_enabled:false in host_vars.yml, and that appears to get my installation further :P 

i'm running ansible based on a mac, installed via homebrew if that is the root of the problem (I suspect it is)

**Comment by aaronraimist** [comment]
I use Ansible on a Mac installed via Homebrew so that shouldn't be a problem unless you haven't upgraded in a long time and are on an old version of Ansible.

Can you paste in a comment showing what the new error is?

**Comment by lexiconzero** [comment]
I've just had the same thing on Fedora 32 ansible. Feels a little like a bug to me given that host_vars.yml is where all overrides are made

**Comment by spantaleev** [comment]
The file should be named `inventory/host_vars/matrix.DOMAIN/vars.yml`.

If you've called it something other than `vars.yml`, it may be what leads to this error.

**Comment by lexiconzero** [comment]
Yep - 

> The file should be named `inventory/host_vars/matrix.DOMAIN/vars.yml`.
> 
> If you've called it something other than `vars.yml`, it may be what leads to this error.

Yep - you're right. User error. I didn't specify a destination name in the copy.

**Comment by leematos** [comment]
For some reason i named mine /inventory/host_vars/matrix.domain/host_vars.yml

Dunno why, just went back and re-read the instructions and didn't find that error anywhere

Thanks!

**Comment by phuhl** [comment]
Litrially did the same mistake, probably because in the example directory the file is called host-vars.yml and I copied the file to the other directory without renaming.

Maybe the file name in example could be improved?

**Comment by spantaleev** [comment]
Good point! I just renamed it! Thanks! :+1:
