### ISSUE TITLE
Name of the Homeserver / DNS Conifg

### ISSUE THREAD

**Issue by jstampfer** [spantaleev/matrix-docker-ansible-deploy#781]
Hi, I am sorry, I am absolutely new in ansible and matrix too.
I set up my homeserver, it works absolutely perfect. Many thx Slavi.
I have just one qestion because of the name of the homeserver.
Is it necessary, that the server is named matrix.DOMAIN or, can
I rename the server for example connect.Domain.

Of course, if I change the DNS Setting correctly.

Thx in advance

**Comment by spantaleev** [comment]
You can name it anything you want. It's controlled by these variables here:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/0f9be8321c56bd98ae8f5333a5edb089caa89db7/roles/matrix-base/defaults/main.yml#L10-L22

Feel free to redefine them in your own `vars.yml` server.

**Comment by jstampfer** [comment]
Did this. But have some troubles now.
- named conference.domain.tld instead of jitsi.domain.tld - DNS entries are correct. If I click "I am the host" it always say connecting- but no connection will be established.
- cannot add email or mobile number on IPhone Element App. Get Error 401  unauthorized. It works perfokt on Windows app and browser too.

Would it be possible to buy some support hours from you?
