### ISSUE TITLE
OIDC configurable for Synapse

### ISSUE THREAD

**Issue by ghost** [spantaleev/matrix-docker-ansible-deploy#784]
OIDC should be configurable. 

oidc_config variable in roles/matrix-synapse/templates/synapse/homeserver.yaml.j2

I need this for my employer, so i might put together a merge request.

**Comment by spantaleev** [comment]
We have `matrix_synapse_configuration_extension_yaml` for this and everything else which doesn't have a dedicated variable.

It is configurable even now, no need to do anything.

**Comment by chaotika** [comment]
Nice, this might suffice ;)
