### ISSUE TITLE
ma1sd Fails to Start

### ISSUE THREAD

**Issue by thw26** [spantaleev/matrix-docker-ansible-deploy#785]
On a run of this ansible-playbook with importing an old database and media store, I am getting the following warning and error.

```…
Error response from daemon: Cannot kill container: matrix-ma1sd: No such container: matrix-ma1sd
WARNING: Error loading config file: .dockercfg: $HOME is not defined
…
FATAL: password authentication failed for user "matrix_ma1sd"
…
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "matrix_ma1sd"
```

I haven't been able to find instructions on fixing this one. Based on the playbook, it looks like the matrix_ma1sd user utilizes the `matrix_synapse_macaroon_secret_key`.

Given that I have imported a new database, I'm guessing this user needs to be manually created after database import. What would be the best way to accomplish this?

**Comment by spantaleev** [comment]
Have you tried rerunning the playbook (`--tags=setup-all,start`) after the import?

**Comment by thw26** [comment]
I checked over my installation and performed another run; all seems to be working. It seems I wrote too soon.
