### ISSUE TITLE
Problem with "Getting Administrator access in a room" step in /docs/configuring-playbook-bridge-appservice-discord.md 

### ISSUE THREAD

**Issue by cmdruid** [spantaleev/matrix-docker-ansible-deploy#795]
The step says to execute the following command:
(indented for readability)
```bash
docker exec -it matrix-appservice-discord /bin/sh -c '
    cp /build/tools/adminme.js /tmp/adminme.js && 
    cp /cfg/registration.yaml /tmp/discord-registration.yaml && 
    cd /tmp && 
    node /tmp/adminme.js -c /cfg/config.yaml -r "!ROOM_ID:SERVER" -u "@USER:SERVER" -p 100
'
```

However, the above command syntax is incorrect and will fail. This syntax works:
(indented for readability)
```bash
docker exec -it matrix-appservice-discord /bin/sh -c '
    cp /cfg/registration.yaml /tmp/discord-registration.yaml && 
    cd /tmp && 
    node /build/tools/adminme.js -c /cfg/config.yaml -m "!ROOM_ID:SERVER" -u "@USER:SERVER" -p 100
'
````

Also, I think the step should should clarify that "!ROOM_ID:SERVER" is not the same ID as in previous steps, but the more obscure _Internal Room ID_ found in the advanced section of **Room Settings**.

* Link to readme: [/docs/configuring-playbook-bridge-appservice-discord.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-appservice-discord.md)

**Comment by spantaleev** [comment]
The registration file goes unused in your new command.

We were going with such an ugly command (and copying things to `/tmp`), because `adminme.js` was was insisting on loading `discord-registration.yaml` from the same directory it runs from. We could pass the configuration using `-c`, but not the registration file.

Is it not necessary to do that anymore?

I see that the script now takes:

> Options
> 
>   -h, --help                                       Display this usage guide. 
>   -c, --config <config.yaml>                       The AS config file.       
>   **-r, --registration <discord-registration.yaml>   The AS registration file. **
>   -m, --roomid string                              The roomid to modify      
>   -u, --userid string                              The userid to give powers 
>   -p, --power <0-100>                              The power to set

So even if we really do need to pass a registration file, we should be able to now.

---------

We may be able to simplify the whole command to just this:

```
docker exec -it matrix-appservice-discord \
node /build/tools/adminme.js -c /cfg/config.yaml -m "!ROOM_ID:SERVER" -u "@USER:SERVER" -p 100
```

Or (if we need the registration file):


```
docker exec -it matrix-appservice-discord \
node /build/tools/adminme.js -c /cfg/config.yaml -r /cfg/registration.yaml -m "!ROOM_ID:SERVER" -u "@USER:SERVER" -p 100
```

**Comment by cmdruid** [comment]
> We were going with such an ugly command (and copying things to /tmp), because adminme.js was was insisting on loading discord-registration.yaml from the same directory it runs from.

You are still right about that. There's a bug in the original adminme.ts file from the original project, that fails to pass the -r option, always defaulting to ./discord-registration.yaml. In [/Half-Shot/matrix-appservice-discord/blob/develop/tools/adminme.ts](https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/tools/adminme.ts), line 98:
```
const {appservice} = ToolsHelper.getToolDependencies(options.config, options.reg, false);
```
The second argument should be options.registration, or the option alias should be changed "reg".

**Comment by spantaleev** [comment]
Can you report that upstream and link to this issue? It'd be nice to get it fixed for everyone and for us to simplify invocation

**Comment by cmdruid** [comment]
Done. :-)
[/Half-Shot/matrix-appservice-discord/pull/666](https://github.com/Half-Shot/matrix-appservice-discord/pull/666)
