### ISSUE TITLE
matrix-synapse.service failure

### ISSUE THREAD

**Issue by twonfkennedy** [spantaleev/matrix-docker-ansible-deploy#799]
Hoping for some help as I believe I'm having similar issues to #12 

On my first fresh playbook, `setup-all` and `start` matrix-synapse seems to be working properly. However, as soon as I attempt to create a user I get the error:

``` 
fatal: [matrix.adomain.com]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/matrix-synapse-register-user", "<adminuser>", "<theadminpassword>", "1"], "delta": "0:00:00.038671", "end": "2021-01-18 18:59:08.647687", "msg": "non-zero return code", "rc": 1, "start": "2021-01-18 18:59:08.609016", "stderr": "Error: No such container: matrix-synapse", "stderr_lines": ["Error: No such container: matrix-synapse"], "stdout": "", "stdout_lines": []} 
```

Simularly if i rerun the `setup-all` command and issue the start command after I attempt to create a user I get the following error:

``` 
failed: [matrix.adomain.com] (item=matrix-synapse.service) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-synapse.service", "msg": "matrix-synapse.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-synapse.service` and `journalctl -fu matrix-synapse.service` on the server to investigate."} 
```

I tried the fix mentioned by the OP by running `docker network create --driver=bridge matrix` to no avail and by [36658ad](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/36658addcd688074eb9062ee71f16ed8a0bcad1b) however it seems the /roles/matrix-server/tasks/setup_main.yml are different in this version?

systemctl shows this:

```
● matrix-synapse.service - Synapse server
   Loaded: loaded (/etc/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-01-18 19:26:46 UTC; 2s ago
  Process: 7684 ExecStart=/usr/bin/env docker run --rm --name matrix-synapse --log-driver=none --user=999:1001 --cap-drop=ALL --entrypoint=python --read-only --tmpfs=/tmp:r
  Process: 7675 ExecStartPre=/usr/bin/env docker rm matrix-synapse (code=exited, status=1/FAILURE)
  Process: 7653 ExecStartPre=/usr/bin/env docker kill matrix-synapse (code=exited, status=1/FAILURE)
 Main PID: 7684 (code=exited, status=1/FAILURE)
```

Any suggestions? "attempting" to run this on Ubuntu 18.04.5 ansible is version 2.9.16

**Comment by spantaleev** [comment]
Perhaps `journalctl -fu matrix-synapse` will tell you more about why Synapse is not starting.

**Comment by spantaleev** [comment]
> self.federation_domain_whitelist[domain] = True
> TypeError: unhashable type: 'list'

Seems like you've been playing with the federation whitelist settings that the playbook provides?

You've probably done something wrong with the syntax there.

**Comment by T3chTobi** [comment]
What is your configuration of the `vars.yml`?
The line stood out to me: `Jan 18 20:38:17 ts-matrix matrix-synapse[6251]: TypeError: unhashable type: 'list'`
Probably a "TypeError"

**Comment by twonfkennedy** [comment]
You guys are the best... seriously what a silly mistake!

I had the wrong syntax in my vars.yml. It was originally:

```
## Federation control

matrix_synapse_federation_domain_whitelist:
- []

matrix_synapse_allow_public_rooms_over_federation: true
```

I removed the entire `matrix_synsapse_federation_domain_whitelist:` and `- []`. All worked as needed.

Cheers and have a beer on me
