### ISSUE TITLE
Add option for Dendrite

### ISSUE THREAD

**Issue by gururise** [spantaleev/matrix-docker-ansible-deploy#800]
Now that dendrite server is BETA, would be great to have an option to install [dendrite](https://matrix.org/docs/projects/server/dendrite) instead of synapse.

**Comment by aaronraimist** [comment]
This can be closed

**Comment by spantaleev** [comment]
Ah, yes it can.

Dendrite support [has been added on 2022-01-07](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#2022-01-07).
