### ISSUE TITLE
Fail on update-user-password task

### ISSUE THREAD

**Issue by berdav** [spantaleev/matrix-docker-ansible-deploy#814]
Hi.

Changing a password of an user with

```
ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=user1 password=password1' --tags=update-user-password
```
fails on `matrix-synapse : Update user password hash` with the following error (slightly censored):
```
ASK [matrix-synapse : Update user password hash] ******************************************************************************************************************************
fatal: [matrix.ourdomain.lol]: FAILED! => {"changed": true, "cmd":
["/usr/local/bin/matrix-postgres-update-user-password-hash", "user1", "hashofpassword1"], "delta": "0:00:01.698913", "end": "2021-01-23 09:23:08.189748", "msg": "non-zero return code", "rc": 1, "start": "2021-01-23 09:23:06.490835", "stderr": "ERROR:  relation \"users\" does not exist\nLINE 1: UPDATE users set password_hash='...\n               ^", "stderr_lines": ["ERROR:  relation \"users\" does not exist", "LINE 1: UPDATE users set password_hash='...", "               ^"], "stdout": "", "stdout_lines": []}
``` 

The matrix setup is fresh, it was not updated from an older version.

I think that this is related to the recent breaking changes introduced for postgres in 95346f3117f2a3a6 :
 an older setup, with a repository synchronized before the breaking change, does not present issues.
 We haven't updated the older one.
 
 There are additional steps to change the user passwords after the refactoring of the DB?

**Comment by spantaleev** [comment]
You're right! We needed some adjustments after 95346f3.

Fixed now! Thanks for the report! :+1:

**Comment by berdav** [comment]
I confirm, the new commit fixes this issue :smile: :partying_face: 

Thank you!
