### ISSUE TITLE
telegram fails if api_id and api_hash are not quoted

### ISSUE THREAD

**Issue by silasdb** [spantaleev/matrix-docker-ansible-deploy#824]
Hi. First, thanks for the great work on this playbook!

The [mautrix telegram bridge documentation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-telegram.md) states:
  
    matrix_mautrix_telegram_enabled: true
    matrix_mautrix_telegram_api_id: YOUR_TELEGRAM_APP_ID
    matrix_mautrix_telegram_api_hash: YOUR_TELEGRAM_API_HASH

I copied the telegram app_id and api_hash directly to this, without worrying about quoting. Ansible wrote wrote it literally to `/matrix/mautrix-telegram/config/config.yaml` (without quotes). The Python YAML parser, later, fails to parse this file or parses it incorrectly because of lacking of double quotes (single quotes doesn't seem to work) and the mautrix-telegram bridge fails with api_id/api_hash mismatch error.

I'm not an Ansible specialist, so I don't know if surrounding the app_id and api_hash with double quotes results in the api_id and api_hash being written with double quotes in config.yaml (or if they are lost on the expansion rules), but maybe it is a good idea to be more strict about quoting when setting the matrix_mautrix_telegram_api* variables.

**Comment by spantaleev** [comment]
See if it works now. Should be fixed by dd24942.

**Comment by silasdb** [comment]
It worked.  Thanks!
