### ISSUE TITLE
matrix-synapse.conf.j2 mixes tabs and spaces

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#83]
Not sure if any other files do, also not sure which one you want otherwise I would have PR'd

Might be nice to add an editorconfig file https://editorconfig.org

**Comment by aaronraimist** [comment]
https://streamable.com/tgi5e

**Comment by spantaleev** [comment]
Fixed in 1a80058.

I was confused as to why you're seeing spaces in `matrix-synapse.conf.j2` and I wasn't.
Turns out, it's `matrix-riot-web.conf.j2` that was the one with the problem.

I've also found out spaces being used in other files and have corrected it as well.

Thank you!

**Comment by aaronraimist** [comment]
Oops 🤦‍♂️
