### ISSUE TITLE
[feature-request] Migrate from local user database to openLDAP

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [spantaleev/matrix-docker-ansible-deploy#836]
Is there any way to migrate *locally* created (aka inside Synapse's DB) users to an LDAP server like openLDAP ?

In my case, we started a small Matrix service which is now expanding to more and more tools for which we would like to provide unified authentication. Hence, we would like to migrate Synapse's users to an LDAP provider.

Is this somehow possible?

**Comment by tntclaus** [comment]
I guess it is. 

Following steps may get you what you need:

0. **Backup your matrix db :)**
1. Install and setup OpenLDAP (_see comment below_)
2. Setup user accounts in OpenLDAP which will have exactly same ids that your users do have in matrix now
3. Enable LDAP auth in synapse and allow login with ids same as existing users have.
4. Disable in-matrix registration.

Little advice_: check FreeIPA. Any LDAP server by itself is more pain in the ass than advantage. It should work in conjunction with bunch of other software and services. Or you can try KeyCloak / JetBrains Hub (free, project-oriented, but not foss) that are more handy if you need SSO or won't ever need HBAC (host based access control), PAM and other kerberos stuff to controll access to numerous linux-operated vm fleet or employee desktops.

**Comment by TheOneWithTheBraid** [comment]
I will give FreeIPA a try.

Anyway, if I set up the new user accounts on the LDAP server, there's no way to import the existing passwords, right? All users are forced to re-create their passwords that way, right.

**Comment by tntclaus** [comment]
Yes, there is no way to do so as passwords are normally hashed.

**Comment by TheOneWithTheBraid** [comment]
Do you know which password hashing algorithm Synapse uses? Maybe it's possible to manually import them...

**Comment by pushytoxin** [comment]
bcrypt, and if I read correctly rounds == salt == 12 (default)

**Comment by 3nprob** [comment]
For anyone else coming here, I can recommend checking out [glauth](https://github.com/glauth/glauth). While it probably has the features you'd want from an LDAP server (and other services can take responsibility for other parts of your ID/auth stack), it has way less features then FreeIPA and is orders of magnitude simpler to configure and maintain.

FreeIPA is still a great project and has its use-cases but it may be way more than you're bargaining for.
