### ISSUE TITLE
Embedded etherpad complains can't be embedded

### ISSUE THREAD

**Issue by skepticalwaves** [spantaleev/matrix-docker-ansible-deploy#849]
I updated the dimension settings per the docs:
```
https://dimension.<your-domain>/etherpad/p/$roomId_$padName?showChat=false
```

However the etherpad when added as a widget complains:

(trimmed etherpad name)
![image](https://user-images.githubusercontent.com/66973897/106497332-e6c78800-648b-11eb-9a14-3f36f406a5eb.png)

**Comment by skepticalwaves** [comment]
The room name it generates is a typical 3-word combo, not the format I set in the dimension settings. I can successfully access the pad directly from the name of the pad it does generate.

**Comment by pushytoxin** [comment]
Make sure the padname is fewer than 50 characters
The bug is in Dimension (but also in the vector.scalar.im proprietary integrations manager that Dimension copies the template from)
https://github.com/turt2live/matrix-dimension/issues/395

**Comment by skepticalwaves** [comment]
> Make sure the padname is fewer than 50 characters

Okay. This is a silly bug on etherpad's side. But how do I do that? I've done nothing to control the pad name anywhere, I have no idea what does that.

**Comment by skepticalwaves** [comment]
Explanation found elsewhere, https://github.com/turt2live/matrix-dimension/issues/372 one can manually set URL and padname.

**Comment by skepticalwaves** [comment]
This probably just needs an update to the documentation. I've managed to fix things by dropping the roomID

**Comment by pushytoxin** [comment]
I'll add a line, but the real fix should be in Dimension (bc Etherpad rejects the change)
