### ISSUE TITLE
Playbook setup fails: [matrix-nginx-proxy : Attempt initial SSL certificate retrieval with standalone authenticator (directly)]

### ISSUE THREAD

**Issue by sluTTYusr** [spantaleev/matrix-docker-ansible-deploy#850]
I followed the guide almost to the letter and did it several times with even setting up a new VM a couple of times.
I am using the free Oracle Cloud Always free plan.
I am not a Linux expert, so please forgive me if the reason for my problems are obvious to some of you.

The output of 
:~$ ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start

runs for a couple of minutes with no red on the screen but then stops at what I believe is the end at NGINX and certificate setup.
These are the red entries:

TASK [matrix-nginx-proxy : Attempt initial SSL certificate retrieval with standalone authenticator (directly)] ***************************************
fatal: [matrix.xxxx.xx]: FAILED! => {"changed": true, "cmd": "/usr/bin/env docker run --rm --name=matrix-certbot --user=998:1002 --cap-drop=ALL -p 80:8080 --mount type=bind,src=/matrix/ssl/config,dst=/etc/letsencrypt --mount type=bind,src=/matrix/ssl/log,dst=/var/log/letsencrypt docker.io/certbot/certbot:amd64-v1.11.0 certonly --non-interactive --work-dir=/tmp --http-01-port 8080  --standalone --preferred-challenges http --agree-tos --email=someone@somewhere.com -d matrix.xxxx.xx", "delta": "0:00:14.878177", "end": "2021-02-02 10:16:41.271167", "msg": "non-zero return code", "rc": 1, "start": "2021-02-02 10:16:26.392990", "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator standalone, Installer None\nPerforming the following challenges:\nhttp-01 challenge for matrix.xxxx.xx\nWaiting for verification...\nChallenge failed for domain matrix.xxxx.xx\nhttp-01 challenge for matrix.xxxx.xx\nCleaning up challenges\nSome challenges have failed.", "stderr_lines": ["Saving debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authenticator standalone, Installer None", "Performing the following challenges:", "http-01 challenge for matrix.xxxx.xx", "Waiting for verification...", "Challenge failed for domain matrix.xxxx.xx", "http-01 challenge for matrix.xxxx.xx", "Cleaning up challenges", "Some challenges have failed."], "stdout": "Requesting a certificate for matrix.xxxx.xx\nIMPORTANT NOTES:\n - The following errors were reported by the server:\n\n   Domain: matrix.xxxx.xx\n   Type:   connection\n   Detail: Fetching\n   http://matrix.xxxx.xx/.well-known/acme-challenge/PuM05XfyTVt4tynFnnv7AleeYtpguPm3HQJTVXsl-zw:\n   Timeout during connect (likely firewall problem)\n\n   To fix these errors, please make sure that your domain name was\n   entered correctly and the DNS A/AAAA record(s) for that domain\n   contain(s) the right IP address. Additionally, please check that\n   your computer has a publicly routable IP address and that no\n   firewalls are preventing the server from communicating with the\n   client. If you're using the webroot plugin, you should also verify\n   that you are serving files from the webroot path you provided.", "stdout_lines": ["Requesting a certificate for matrix.xxxx.xx", "IMPORTANT NOTES:", " - The following errors were reported by the server:", "", "   Domain: matrix.xxxx.xx", "   Type:   connection", "   Detail: Fetching", "   http://matrix.xxxx.xx/.well-known/acme-challenge/PuM05XfyTVt4tynFnnv7AleeYtpguPm3HQJTVXsl-zw:", "   Timeout during connect (likely firewall problem)", "", "   To fix these errors, please make sure that your domain name was", "   entered correctly and the DNS A/AAAA record(s) for that domain", "   contain(s) the right IP address. Additionally, please check that", "   your computer has a publicly routable IP address and that no", "   firewalls are preventing the server from communicating with the", "   client. If you're using the webroot plugin, you should also verify", "   that you are serving files from the webroot path you provided."]}
...ignoring

TASK [matrix-nginx-proxy : Attempt initial SSL certificate retrieval with standalone authenticator (via proxy)] **************************************
fatal: [matrix.xxxx.xx]: FAILED! => {"changed": true, "cmd": "/usr/bin/env docker run --rm --name=matrix-certbot --user=998:1002 --cap-drop=ALL -p 127.0.0.1:2402:8080 --network=matrix --mount type=bind,src=/matrix/ssl/config,dst=/etc/letsencrypt --mount type=bind,src=/matrix/ssl/log,dst=/var/log/letsencrypt docker.io/certbot/certbot:amd64-v1.11.0 certonly --non-interactive --work-dir=/tmp --http-01-port 8080  --standalone --preferred-challenges http --agree-tos --email=someone@somewhere.com -d matrix.xxxx.xx", "delta": "0:00:19.506250", "end": "2021-02-02 10:17:01.096542", "msg": "non-zero return code", "rc": 1, "start": "2021-02-02 10:16:41.590292", "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator standalone, Installer None\nPerforming the following challenges:\nhttp-01 challenge for matrix.xxxx.xx\nWaiting for verification...\nChallenge failed for domain matrix.xxxx.xx\nhttp-01 challenge for matrix.xxxx.xx\nCleaning up challenges\nSome challenges have failed.", "stderr_lines": ["Saving debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authenticator standalone, Installer None", "Performing the following challenges:", "http-01 challenge for matrix.xxxx.xx", "Waiting for verification...", "Challenge failed for domain matrix.xxxx.xx", "http-01 challenge for matrix.xxxx.xx", "Cleaning up challenges", "Some challenges have failed."], "stdout": "Requesting a certificate for matrix.xxxx.xx\nIMPORTANT NOTES:\n - The following errors were reported by the server:\n\n   Domain: matrix.xxxx.xx\n   Type:   connection\n   Detail: Fetching\n   http://matrix.xxxx.xx/.well-known/acme-challenge/obs0pnPeAIi5yU8GrQp7WUEzOa3znpx_i2Vog1DGRto:\n   Timeout during connect (likely firewall problem)\n\n   To fix these errors, please make sure that your domain name was\n   entered correctly and the DNS A/AAAA record(s) for that domain\n   contain(s) the right IP address. Additionally, please check that\n   your computer has a publicly routable IP address and that no\n   firewalls are preventing the server from communicating with the\n   client. If you're using the webroot plugin, you should also verify\n   that you are serving files from the webroot path you provided.", "stdout_lines": ["Requesting a certificate for matrix.xxxx.xx", "IMPORTANT NOTES:", " - The following errors were reported by the server:", "", "   Domain: matrix.xxxx.xx", "   Type:   connection", "   Detail: Fetching", "   http://matrix.xxxx.xx/.well-known/acme-challenge/obs0pnPeAIi5yU8GrQp7WUEzOa3znpx_i2Vog1DGRto:", "   Timeout during connect (likely firewall problem)", "", "   To fix these errors, please make sure that your domain name was", "   entered correctly and the DNS A/AAAA record(s) for that domain", "   contain(s) the right IP address. Additionally, please check that", "   your computer has a publicly routable IP address and that no", "   firewalls are preventing the server from communicating with the", "   client. If you're using the webroot plugin, you should also verify", "   that you are serving files from the webroot path you provided."]}
...ignoring

TASK [matrix-nginx-proxy : Fail if all SSL certificate retrieval attempts failed] ********************************************************************
fatal: [matrix.xxxx.xx]: FAILED! => {"changed": false, "msg": "Failed to obtain a certificate directly (by listening on port 80)\nand also failed to obtain by relying on the server at port 80 to proxy the request.\nSee above for details.\nYou may wish to set up proxying of /.well-known/acme-challenge to 2402 or,\nmore easily, stop the server on port 80 while this playbook runs.\n"}

PLAY RECAP *******************************************************************************************************************************************
matrix.xxxx.xx             : ok=149  changed=10   unreachable=0    failed=1    skipped=1130 rescued=0    ignored=2

**Comment by aaronraimist** [comment]
Make sure:

1. your DNS records are pointing at the correct server
1. your firewall is allowing all of the required ports through https://matrix.org/docs/guides/free-small-matrix-server#oracle-cloud-security-lists
1. there is no other program listening on port 80

**Comment by sluTTYusr** [comment]
1. I set up a dedicated TLD for this. Both <domain> and www.<domain> have A records pointing to the public IP address of the VM. nslookup <domain> returns the expected IP address. I have added CNAME records for the ELEMENTS and MATRIX subdomains pointing to <domain>.
2. I will attach a screen shot of the Oracle cloud dashboard ingress rules. I did  'apt purge netfilter-persistent iptables-persistent' as the guide says.
<img width="1084" alt="2021-02-02_203607" src="https://user-images.githubusercontent.com/11618119/106654180-14015c80-6598-11eb-8e2d-be853531b82f.png">
3. Output of 'ss -plnt': 
<img width="702" alt="2021-02-02_205059" src="https://user-images.githubusercontent.com/11618119/106654475-73f80300-6598-11eb-82ac-e808e28c5a4a.png">

**Comment by sluTTYusr** [comment]
I tried opening ports with iptables as follows, didnt help either. Still the same error messages.
sudo iptables -A INPUT -i lo -j ACCEPT
sudo iptables -A OUTPUT -o lo -j ACCEPT
sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
sudo iptables -A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

**Comment by sluTTYusr** [comment]
User "underscore_j" from the support room on matrix.org had the right hint. The ingress rules on the Oracle cloud need to have "Source port range" set to "All". Thanks to everyone who helped or tried to.
