### ISSUE TITLE
I followed the update directions with the breaking changes and now I can't access my database

### ISSUE THREAD

**Issue by elmehalawi** [spantaleev/matrix-docker-ansible-deploy#855]
I followed [these directions](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#breaking-change-postgres-changes-that-require-manual-intervention%22}) and I'm stuck on the last step.  When I run this:

```
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
```

I get this error:

> fatal: [matrix.elmehalawi.com]: FAILED! => {"changed": true, "cmd": ["/usr/bin/env", "docker", "run", "--rm", "--user=1000:1000", "--cap-drop=ALL", "--env-file=/matrix/postgres/env-postgres-psql", "--network", "matrix", "--mount", "type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro", "--entrypoint=/bin/sh", "docker.io/postgres:12.5-alpine", "-c", "psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql"], "delta": "0:00:00.962546", "end": "2021-02-03 22:51:16.378733", "msg": "non-zero return code", "rc": 2, "start": "2021-02-03 22:51:15.416187", "stderr": "psql: error: FATAL:  password authentication failed for user \"matrix\"", "stderr_lines": ["psql: error: FATAL:  password authentication failed for user \"matrix\""], "stdout": "", "stdout_lines": []}

Even though I set the password in my vars file. I get the same error when I try to log into postgres on the server:

```
# /usr/local/bin/matrix-postgres-cli
psql: error: FATAL:  password authentication failed for user "matrix"
```

What can I do now? Did I just lose all my data?

**Comment by elmehalawi** [comment]
So if you're like me and you make a stupid mistake, you can recover your database like this:

Stop the matrix server with `--tags=stop`. Then SSH into your server. Make sure the postgres server is down with `systemctl stop matrix-postgres`. Then run:

```
docker run -it --rm --name matrix-postgres --log-driver=none --user=1000:1000 --cap-drop=ALL --read-only --tmpfs=/tmp:rw,noexec,nosuid,size=100m --tmpfs=/run/postgresql:rw,noexec,nosuid,size=100m --network=matrix --env-file=/matrix/postgres/env-postgres-server --mount type=bind,src=/matrix/postgres/data,dst=/var/lib/postgresql/data --mount type=bind,src=/etc/passwd,dst=/etc/passwd,ro docker.io/postgres:12.5-alpine sh
```

This will give you a shell into the postgres server's docker container. From there, you can get into postgres's single user mode like this:

```
postgres --single postgres
```

Now you're in the postgres shell. Now you can follow the directions as before and enter:

```sql
CREATE ROLE matrix LOGIN SUPERUSER PASSWORD 'YOUR_POSTGRES_PASSWORD_HERE';

CREATE DATABASE matrix OWNER matrix;

ALTER DATABASE postgres OWNER TO matrix;
ALTER DATABASE template0 OWNER TO matrix;
ALTER DATABASE template1 OWNER TO matrix;

ALTER DATABASE homeserver RENAME TO synapse;

ALTER ROLE synapse NOSUPERUSER NOCREATEDB NOCREATEROLE;
```

I got rid of the `\c` since you won't be able to run those from here. Just type those in carefully and don't forget the semicolons. Then, get out of all those shells with Ctrl+D a bunch of times and you should be able to rerun the playbook like normal.

Hopefully no one will need this, but I thought I'd document it just in case someone makes the same mistake.

**Comment by spantaleev** [comment]
We've had this happen before (when people forget the `;` for the SQL query that creates the `matrix` user).

We've also discussed potential solutions in our Support room: https://matrix.to/#/!PukFFdIcHgtaaHZflT:devture.com/$161133838467284dVQau:matrix.org?via=matrix.org&via=tchncs.de&via=maunium.net

Thanks for documenting it here (in a much more accessible way) as well! And sorry about the trouble!

It should be noticed that you're on an older version of Postgres (12.5). Other users may need to adapt your command to `13.1` or something.
