### ISSUE TITLE
Stuck on documentation setting up .well-known (nginx method, option 3) 

### ISSUE THREAD

**Issue by LuckySandwich** [spantaleev/matrix-docker-ansible-deploy#873]
Hi

I'm a little stuck on the documentation (which is excellent, by the way)

I've followed the docs very closely.. but I'm stuck on [configuring .well-known](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md)

I'm using `matrix.<DOMAIN>` 

I'm following "Option 3" with Nginx.   The playbook installs and configures its own copy of nginx, but I don't think it's safe to go inside the nginx container and start messing with the nginx configs, since these are generated files.

If I go with Option 3, am I expected to [disable the integrated nginx server](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md) and set up my own?  I'd rather **not** do this if possible.  

I'm not sure how to proceed here, the docs kinda left me hanging on this part.

Thank you

**Comment by spantaleev** [comment]
Option 3 tells you how to set up your base domain (which is usually on another server).

If you're not using the base domain for anything, you can go with [making the playbook serve the base domain](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-base-domain-serving.md). Then you won't need to do anything manually - the playbook will take care of everything.

**Comment by LuckySandwich** [comment]
Ohh, thank you!  I'll give that a shot.
