### ISSUE TITLE
E2EE from Element to Signal Bridge

### ISSUE THREAD

**Issue by ionwerz** [spantaleev/matrix-docker-ansible-deploy#877]
I'm trying to set up E2E encryption from my Android Element client, when I'm inside the Settings of Signal room there is next message `You don't have permission to enable encryption in this room`, is there ability to activate it?

**Comment by calebstewart** [comment]
Does anyone know an answer to this? [This](https://github.com/mautrix/signal/issues/61) seems related, but I'm not sure how to rectify it. Thanks!
