### ISSUE TITLE
where is the ansible-playbook executable?

### ISSUE THREAD

**Issue by mweissen** [spantaleev/matrix-docker-ansible-deploy#878]
Yes, I'm going to assume for once that this is a silly question. Nevertheless! I have performed all the steps in the instructions to install a new server: DNS configured, program fetched with git, playbook configured. 
Now I'm in the "Installing" section at the line **Run this as-is to set up a server:**
But where is the ansible-playbook executable?
Thanks a lot, M.W.

**Comment by aaronraimist** [comment]
You'll have to install it. There are some methods listed in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md#using-ansible-via-docker.
