### ISSUE TITLE
Failure during Ensure Matrix network is created in Docker

### ISSUE THREAD

**Issue by jonchar** [spantaleev/matrix-docker-ansible-deploy#886]
I recently received this failure when running the usual `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start -K`:

```
TASK [matrix-base : Ensure Matrix network is created in Docker] **************************************
fatal: [matrix.<myhost>]: FAILED! => changed=false
  msg: 'Error: Docker SDK for Python version is 1.9.0 (<myhost>''s Python /usr/bin/python3). Minimum version required is 
1.10.0.Use `pip install --upgrade docker-py` to upgrade. Hint: if you do not need Python 2.6 support, try `pip uninstall 
docker-py` instead, followed by `pip install docker`.'
```

Is this an inconsistency in the playbook or do I manually need to upgrade the docker SDK somewhere? Happy to provide more info if needed.

Thanks again for creating this playbook -- it's been awesome to use.

**Comment by spantaleev** [comment]
Perhaps you need `ansible_python_interpreter=/usr/bin/python3` added to your host line in `inventory/hosts`

**Comment by jonchar** [comment]
Thanks for the quick response! I do have that line in my `inventory/hosts`, but I've figure it out:

I was on Debian 9.13 where `python3-docker` -> Docker SDK v1.9.0. I've since upgraded to Debian Buster where `python3-docker` -> Docker SDK v3.4.1. Now the playbook runs successfully.
