### ISSUE TITLE
[support]: SQL network does not resolve

### ISSUE THREAD

**Issue by ma-karai** [spantaleev/matrix-docker-ansible-deploy#889]
I run into an error that the matrix network is not resolved. Any idea what this might be?
```
TASK [matrix-postgres : Execute Postgres additional database initialization SQL file for synapse] ********************************************************
fatal: [matrix.domain.org]: FAILED! => changed=true
  cmd:
  - /usr/bin/env
  - docker
  - run
  - --rm
  - --user=998:1102
  - --cap-drop=ALL
  - --env-file=/matrix/postgres/env-postgres-psql
  - --network
  - matrix
  - --mount
  - type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro
  - --entrypoint=/bin/sh
  - docker.io/postgres:13.2-alpine
  - -c
  - psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql
  delta: '0:00:00.684295'
  end: '2021-02-19 13:14:14.011247'
  msg: non-zero return code
  rc: 2
  start: '2021-02-19 13:14:13.326952'
  stderr: 'psql: error: could not translate host name "matrix-postgres" to address: Name does not resolve'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP ***********************************************************************************************************************************************
matrix.domain.org            : ok=52   changed=1    unreachable=0    failed=1    skipped=52   rescued=0    ignored=0
```

**Comment by tchapi** [comment]
Same here on the latest commit !

**Comment by tchapi** [comment]
I think this is linked to: 

```
Feb 19 14:07:20 vps-49bcf83d systemd[1]: Starting Matrix Postgres server...
Feb 19 14:07:20 vps-49bcf83d matrix-postgres[21803]: Error response from daemon: No such container: matrix-postgres
```

**Comment by tchapi** [comment]
.. but maybe https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/1dbdfeec07335873bd652ef1ac32114b12ecb3a9 fixes it — I'm testing right now

**Comment by nebocamin** [comment]
it does not fix for me.

**Comment by tchapi** [comment]
Yes, still errored. @spantaleev any idea ?

**Comment by nebocamin** [comment]
no further detail using -vvvv

``` (1, b'\n{"cmd": ["/usr/bin/env", "docker", "run", "--rm", "--user=998:1001", "--cap-drop=ALL", "--env-file=/matrix/postgres/env-postgres-psql", "--network", "matrix", "--mount", "type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro", "--entrypoint=/bin/sh", "docker.io/postgres:13.2-alpine", "-c", "psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql"], "stdout": "", "stderr": "psql: error: could not translate host name \\"matrix-postgres\\" to address: Name does not resolve", ```

**Comment by tchapi** [comment]
There is `chmod: /var/run/postgresql: Operation not permitted` when the postgres container is starting, not sure that it's a problem though.

**Comment by spantaleev** [comment]
Should be fixed by 108aed5. Please give that a try!

**Comment by nebocamin** [comment]
yes, can confirm.

**Comment by tchapi** [comment]
super, thanks @spantaleev 🎉

**Comment by ma-karai** [comment]
Awesome fastest fix on github i have seen :D Thanks man (just a pleeb tho)

**Comment by hanthor** [comment]
I'm getting this issue again

**Comment by schopenhauer** [comment]
same here, getting the issue also

**Comment by chr151ux** [comment]
I am also getting this error on the last commit.

**Comment by ijiti** [comment]
I am also getting this and am unable to debug or get any further. Any troubleshooting assistance would be appreciated. Cannot get past this step no matter what I try. My install was working fine, but then my server crashed. Upon reboot, I kept encountering this error and have not currently figuired out how to resolve it.

**Comment by hanthor** [comment]
Take a look journalctl -fu matrix-postgres and systemctl status matrix-postgres. Make sure the service exists. See if you can run it manually

**Comment by chr151ux** [comment]
For me, this was a docker networking issue. Apparently, the docker0 interface came not up correctly after a reboot. You can test your docker networking by following the official [networking tutorial](https://docs.docker.com/network/network-tutorial-standalone/).
