### ISSUE TITLE
ERROR! vars file roles/matrix-synapse/vars/workers.yml was not found

### ISSUE THREAD

**Issue by rakshazi** [spantaleev/matrix-docker-ansible-deploy#895]
Hello,
if you run `setup.yml` playbook from different place (or symlink), it will fail, because vars file `roles/matrix-synapse/vars/workers.yml` has been imported directly to playbook, full error message:

```
ERROR! vars file roles/matrix-synapse/vars/workers.yml was not found
Could not find file on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

In my case, i use different ansible project structure with symlink to `setup.yml`.

Could you move that file's contents to `defaults/main.yml` of matrix-synapse role, please?
Or is it some special case and that file must be included directly in playbook?

**Comment by spantaleev** [comment]
We have a script (`roles/matrix-synapse/files/workers-doc-to-yaml.sh`), which currently rebuilds/overwrites the whole file.

We should either make that update the contents in `defaults/main.yml` somehow, or find a way to include this file in a more reliable way. Hmm

**Comment by rakshazi** [comment]
I think vars/main.yml may be a good choise here

vars/*.yml has lower priority than host vars, but higher than role defaults

Could you try it, please?

**Comment by spantaleev** [comment]
It still leads to the same problem if we use `roles/matrix-synapse/vars/main.yml`.

We can't overwrite the whole file, because that file is also used for other things.

**Comment by rakshazi** [comment]
OK, why not use vars/workers.yml and import that file in role? Like this:

**Comment by rakshazi** [comment]
Sorry, accidentally closed the issue.

Example: https://gitlab.com/rakshazi/matrix-ansible/-/blob/master/roles/matrix/nginx-proxy-health/tasks/main.yml#L2

**Comment by spantaleev** [comment]
#456 used to load `workers.yml` from within the `matrix-synapse` role, which caused other issues. See cc5cf0d7257ed093abad322

**Comment by rakshazi** [comment]
Hm... ok, may be in that case path (actually, prefix) to that file may be set in group_vars? In that case the path may be overridden if required.

Right now, i just put required path in [duplicate of setup.yml](https://gitlab.com/rakshazi/matrix-ansible/-/blob/master/play/matrix.yml#L8) , but with variable on group or host vars level it will work without duplicating playbook file

**Comment by spantaleev** [comment]
Does it have to be in `group_vars`? Or can it be in the `matrix-base` role for example (and then overridden by your own `vars.yml` file)?

**Comment by rakshazi** [comment]
Actually, doesn't matter
I suppose, it will be better to set it it group_vars (default value) and that allows overrides in host_vars

**Comment by pcfe** [comment]
> In my case, i use different ansible project structure with symlink to `setup.yml`.

If you could describe what you are trying to achieve, then maybe we can find a solution for you that does not involve symlinks.

For what it's worth;
I have this repo checked out somewhere that is **not** under my standard Ansible directory structure. My inventory file is an edited copy of this repo's `inventory/hosts` and lives at `/home/foo/bar/baz/ansible/inventories/matrix-docker-ansible-deploy-inventory` and my (vaulted) `host_vars` are at /home/foo/bar/baz/ansible/inventories/host_vars/matrix.pcfe.net/vars.yml`
To use the playbook, I `cd into the checkout of this repo and then point at my inventory file, for example `ansible-playbook --ask-vault-pass -i /home/foo/bar/baz/ansible/inventories/matrix-docker-ansible-deploy-inventory setup.yml --tags=self-check`
No need for symlinks.

The [relevant part of the Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#organizing-host-and-group-variables) explains this way better than the above example.
