### ISSUE TITLE
Given caddy config doesn't work

### ISSUE THREAD

**Issue by samyak-jain** [spantaleev/matrix-docker-ansible-deploy#900]
I've tried using the caddy 2 configuration given in the repository but it doesn't seem to work. I made a few tweaks because my setup is that caddy runs in a docker image along with all my services and they are all in the same docker network. 

This config just redirects me to https://{matrix_domain}/_matrix/static/ and then nothing loads

Here's how it looks like:
```
matrix.{$MY_DOMAIN} {
    import proxy_template

    @identity {
        path /_matrix/identity/*
    }

    @noidentity {
        not path /_matrix/identity/*
    }

    @search {
        path /_matrix/client/r0/user_directory/search/*
    }

    @nosearch {
        not path /_matrix/client/r0/user_directory/search/*
    }

    @static {
        path /_matrix/static
    }

    @nostatic {
        not path /_matrix/static
    }

    header {
        # Enable HTTP Strict Transport Security (HSTS) to force clients to always connect via HTTPS
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        # Enable cross-site filter (XSS) and tell browser to block detected attacks
        X-XSS-Protection "1; mode=block"
        # Prevent some browsers from MIME-sniffing a response away from the declared Content-Type
        X-Content-Type-Options "nosniff"
        # Disallow the site to be rendered within a frame (clickjacking protection)
        X-Frame-Options "DENY"
        # X-Robots-Tag
        X-Robots-Tag "noindex, noarchive, nofollow"
        167,9         79%
    }

    # Cache
    header @static {
        # Cache
        Cache-Control "public, max-age=31536000"
        defer
    }

    # identity
    handle @identity {
        reverse_proxy matrix-ma1sd:8090  {
            header_up X-Forwarded-Port {http.request.port}
            header_up X-Forwarded-Proto {http.request.scheme}
            header_up X-Forwarded-TlsProto {tls_protocol}
            header_up X-Forwarded-TlsCipher {tls_cipher}
            header_up X-Forwarded-HttpsProto {proto}
        }
    }

    # search
    handle @search {
        reverse_proxy matrix-ma1sd:8090   {
            header_up X-Forwarded-Port {http.request.port}
            header_up X-Forwarded-Proto {http.request.scheme}
            header_up X-Forwarded-TlsProto {tls_protocol}
            header_up X-Forwarded-TlsCipher {tls_cipher}
            header_up X-Forwarded-HttpsProto {proto}
        }
    }

    encode zstd gzip

    reverse_proxy matrix-synapse:8008  {
        header_up X-Forwarded-Port {http.request.port}
        header_up X-Forwarded-Proto {http.request.scheme}
        header_up X-Forwarded-TlsProto {tls_protocol}
        header_up X-Forwarded-TlsCipher {tls_cipher}
        header_up X-Forwarded-HttpsProto {proto}
    }
}
```

However, removing a lot of stuff and then changing the config to this works:
```
matrix.{$MY_DOMAIN} {
    import proxy_template
    reverse_proxy matrix-synapse:8008  {
        header_up X-Forwarded-Port {http.request.port}
        header_up X-Forwarded-Proto {http.request.scheme}
        header_up X-Forwarded-TlsProto {tls_protocol}
        header_up X-Forwarded-TlsCipher {tls_cipher}
        header_up X-Forwarded-HttpsProto {proto}
    }
}
```

But I don't have stuff like identity servers working for me. 

Also for context, the ```import proxy_template``` portion of the code is just setting up tls.

**Comment by bmanturner** [comment]
I just set up caddy with this this morning.

1. left managed nginx on
2. disabled ssl (only ports being used are 80 and 8448, listening on 0.0.0.0)
3. configured caddy as follows

```
matrix.DOMAIN, dimension.DOMAIN, element.DOMAIN, jitsi.DOMAIN {
        reverse_proxy matrix:80
}
matrix.DOMAIN:8448 {
        reverse_proxy matrix:8448
}
DOMAIN {
        reverse_proxy /.well-known/matrix/* https://matrix.foglet.io {
                header_up Host {http.reverse_proxy.upstream.hostport}
        }
}
```

**Comment by samyak-jain** [comment]
Thanks @bmanturner. I'll try to give this a shot. 
What values did you give for the following vars?:
```matrix_nginx_proxy_container_http_host_bind_port``` and ```matrix_nginx_proxy_container_federation_host_bind_port```

From looking at your caddy config, it looks like you are connecting to the hostname ```matrix```. Is ```matrix``` the name of the nginx container generated by this playbook?

Also, do you have coturn enabled? Any idea on that would work with this configuration?

**Comment by bmanturner** [comment]
In my set-up, I have caddy on server A and matrix on server B. As such, my bind ports are `0.0.0.0:80` and `0.0.0.0:8448` (respectively http / federation).

`matrix` is the host name of server B. Instead of using `10.10.10.X:80` I just added `10.10.10.X    matrix` to my `/etc/hosts`

I do not have coturn enabled, but assume it would work similarly to this rule (replacing 8448 with coturn ports):

```
matrix.DOMAIN:8448 {
        reverse_proxy matrix:8448
}
```

**Comment by samyak-jain** [comment]
Makes sense! 
So, how does tls for federation work for you? I'm using caddy to manage my certificates so I have the tls directive inside ```matrix.DOMAIN, dimension.DOMAIN, element.DOMAIN, jitsi.DOMAIN```

However, if I add the tls directive to ```matrix.DOMAIN:8448```, I get an error from caddy about ambiguity in hostname. 

However, if I don't add the tls directive to ```matrix.DOMAIN:8448```, everything works but I am not able to reach the federation url over https, only http.

**Comment by bmanturner** [comment]
I've never manually specified the TLS directive. It just works for me. Caddy handles it automatically without specifying the tls directive.

**Comment by samyak-jain** [comment]
Did you set ```matrix_nginx_proxy_https_enabled``` to ```false```? Because, while 8080 is working for me, I'm facing issues with the federation port. 
When I curl my federation server over http, I get the json with the version number of synapse. However, when I curl with https, I get ```curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number```. 
Some googling suggests that this is because nginx isn't listening over ssl. But since I want my certificates to be managed by caddy and not nginx, I didn't enable ssl for the nginx proxy. 

So maybe I need a way for caddy to take the ssl request from the client and then use an http connection with the nginx proxy rather than https? I don't know how to do something like that though. Any ideas?

**Comment by bmanturner** [comment]
My settings

```
# Do not retrieve SSL certificates. This shall be managed by another webserver >
matrix_ssl_retrieval_method: none

# Do not try to serve HTTPS, since we have no SSL certificates.
# Disabling this also means services will be served on the HTTP port
# (`matrix_nginx_proxy_container_http_host_bind_port`).
matrix_nginx_proxy_https_enabled: false

# Do not listen for HTTP on port 80 globally (default), listen on the loopback >
# If you'd like, you can make it use the local network as well and reverse-prox>
matrix_nginx_proxy_container_http_host_bind_port: '0.0.0.0:80'

# Likewise, expose the Matrix Federation port on the loopback interface.
# Since `matrix_nginx_proxy_https_enabled` is set to `false`, this federation p>
# If you'd like, you can make it use the local network as well and reverse-prox>
#
# You'd most likely need to expose it publicly on port 8448 (8449 was chosen fo>
matrix_nginx_proxy_container_federation_host_bind_port: '0.0.0.0:8448'
```

**Comment by samyak-jain** [comment]
Finally fixed the issue. 
Basically ```matrix_nginx_proxy_container_federation_host_bind_port``` was interfearing with caddy. So I removed that and exposed 8448 on caddy so everything was routed through that. Caddy then communicated with the nginx proxy over the docker network. 

This is how my final configuration looks like:
```
matrix_ssl_retrieval_method: none
matrix_nginx_proxy_https_enabled: false
matrix_nginx_proxy_container_http_host_bind_port: ''
matrix_nginx_proxy_container_federation_host_bind_port: ''
```

My Caddyfile
```
matrix.{$MY_DOMAIN}, dimension.{$MY_DOMAIN}, element.{$MY_DOMAIN}, jitsi.{$MY_DOMAIN} {
    import proxy_template
    
    reverse_proxy matrix-nginx-proxy:8080
}

matrix.{$MY_DOMAIN}:8448 {
    reverse_proxy matrix-nginx-proxy:8448
}

```

Thanks @bmanturner for your help.
