### ISSUE TITLE
srv record issue

### ISSUE THREAD

**Issue by Happyfeet01** [spantaleev/matrix-docker-ansible-deploy#903]
Hello,

I try to setup Matrix but i got one issue.

I setup at the vars.yml as matrix_domain: dackelexpress.com

At the host file i enter matrix.dackelexpress.com

My settings at the provider dns settings are:
![image_20210222222314](https://user-images.githubusercontent.com/3295104/108771910-95775980-755c-11eb-8250-a722bcbd80ad.png)

Is that wrong? 

Error Message:

```
 msg: 'It appears the DNS SRV record for _matrix-identity._tcp on matrix.dackelexpress.com. is not set up correctly. Expected it to point to `matrix.matrix.dackelexpress.com.` (port 443). See the ''Configuring DNS'' documentation for this playbook. Full response from the `dig` lookup was: {''cmd'': ''dig -t srv _matrix-identity._tcp.matrix.dackelexpress.com.'', ''stdout'': ''\n; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> -t srv _matrix-identity._tcp.matrix.dackelexpress.com.\n;; global options: +cmd\n;; Got answer:\n;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56168\n;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1\n\n;; OPT PSEUDOSECTION:\n; EDNS: version: 0, flags:; udp: 4096\n;; QUESTION SECTION:\n;_matrix-identity._tcp.matrix.dackelexpress.com.\tIN SRV\n\n;; AUTHORITY SECTION:\ndackelexpress.com.\t2654\tIN\tSOA\thydrogen.ns.hetzner.com. dns.hetzner.com. 2021022215 86400 10800 3600000 3600\n\n;; Query time: 17 msec\n;; SERVER: 213.133.100.100#53(213.133.100.100)\n;;
    WHEN: Mon Feb 22 22:09:08 CET 2021\n;; MSG SIZE  rcvd: 135'', ''stderr'': '''', ''rc'': 0, ''start'': ''2021-02-22 22:09:08.631501'', ''end'': ''2021-02-22 22:09:08.691627'', ''delta'': ''0:00:00.060126'', ''changed'': False, ''stdout_lines'': ['''', ''; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> -t srv _matrix-identity._tcp.matrix.dackelexpress.com.'', '';; global options: +cmd'', '';; Got answer:'', '';; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56168'', '';; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1'', '''', '';; OPT PSEUDOSECTION:'', ''; EDNS: version: 0, flags:; udp: 4096'', '';; QUESTION SECTION:'', '';_matrix-identity._tcp.matrix.dackelexpress.com.\tIN SRV'', '''', '';; AUTHORITY SECTION:'', ''dackelexpress.com.\t2654\tIN\tSOA\thydrogen.ns.hetzner.com. dns.hetzner.com. 2021022215 86400 10800 3600000 3600'', '''', '';; Query time: 17 msec'', '';; SERVER: 213.133.100.100#53(213.133.100.100)'', '';; WHEN: Mon Feb 22 22:09:08 CET 2021'', '';; MSG SIZE  rcvd:
    135''], ''stderr_lines'': [], ''failed'': False}'
```
Why matrix.matrix.dackelexpress.com?

**Comment by aaronraimist** [comment]
Hmm can you show your `vars.yml` file? Make sure to redact the secret keys.

**Comment by Happyfeet01** [comment]
Thanks for answering @aaronraimist the srv record issue is gone. But now i can´t recieve an valid Certificate.
I setup the domain.tld at the vars.yml and the matrix.domain.tld at the host file.

is that correct? https://federationtester.matrix.org/#dackelexpress.com

Federationtester is telling me that the Cert is for matrix.domain.tld not domain.tld. 
i also tried this https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-base-domain-serving.md

here is my vars.yml

https://paste.dasnetzundich.de/view/3b428ee2

**Comment by aaronraimist** [comment]
<img width="1663" src="https://user-images.githubusercontent.com/5855073/108885372-59c8a800-75cd-11eb-9618-da89b5c8e1ac.png">

The federation tester looks good to me

**Comment by aaronraimist** [comment]
Oh I see. You have a `_matrix._tcp.dackelexpress.com.` SRV record as well. You should remove that because that will cause inconsistent results since this playbook does not meet the requirements of the `_matrix._tcp` SRV record.
