### ISSUE TITLE
Bridges can get misconfigured with workers

### ISSUE THREAD

**Issue by Cadair** [spantaleev/matrix-docker-ansible-deploy#904]
I have noticed on the whatsapp bridge at least that when I moved the media repo off to a worker it can no longer upload media as it is directly talking to the synapse main process rather than the reverse proxy for is CS API traffic.

I assume it's likely that other bridges do this also.

**Comment by spantaleev** [comment]
Most bridges had been fixed as part of the work on #456 (see d3ecc6f017c801fcf5de).

A few remained that I fixed in f9a0ec6 just now. Thanks for reporting this!
