### ISSUE TITLE
connection to signal and Facebook don't work

### ISSUE THREAD

**Issue by Happyfeet01** [spantaleev/matrix-docker-ansible-deploy#906]
Hello,

Since yesterday Matrix runs fine on my server. Bridges to Telegram and Whatsapp already working but when i try to connect to Signal i get this message.

This is the log entry:
`Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 84, in register
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:     username = await evt.bridge.signal.register(phone, voice=voice)
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:   File "/opt/mautrix-signal/mausignald/signald.py", line 105, in register
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:     resp = await self.request("register", "verification_required", username=phone,
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 205, in request
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:     resp_type, resp_data = await self._raw_request(command, **data)
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 202, in _raw_request
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]:     return await future
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]: mausignald.errors.UnexpectedError: Unexpected error with no message
Feb 24 05:28:07 ubuntu-4gb-fsn1-1 matrix-mautrix-signal[29798]: [2021-02-24 04:28:07,791] [INFO@aiohttp.access] 172.21.0.4 [24/Feb/2021:04:28:07 +0000] "PUT /transactions/18?access_token=tokenID HTTP/1.1" 200 158 "-" "Synapse/1.27.0"`

On Facebook Login:

`Feb 24 05:57:02 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]: [2021-02-24 04:57:02,497] [INFO@aiohttp.access] 172.21.0.4 [24/Feb/2021:04:57:02 +0000] "PUT /transactions/26?access_token=tokenID e1f HTTP/1.1" 200 158 "-" "Synapse/1.27.0"
Feb 24 05:57:02 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]: [2021-02-24 04:57:02,531] [DEBUG@mau.mx] Received Matrix event $Mb6-VJ6mLdZsHypextb5uPImHIrCF4_UInfPjBTZ1tg from @lars:dackelexpress.com in !EfibAuMgCNSJCvOzjd:dackelexpress.com
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]: [2021-02-24 04:57:03,402] [ERROR@mau.commands] Unhandled error while handling command login facebook@domain.tld somepassword from @lars:dackelexpress.com (ref: 1614140275)
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]: Traceback (most recent call last):
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     await self._run_handler(handler, evt)
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     return await self._handler(evt)
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/auth.py", line 64, in login
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     await evt.az.intent.redact(evt.room_id, evt.event_id)
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 95, in wrapper
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     return await __method(*args, **kwargs)
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix/client/api/events.py", line 521, in redact
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     resp = await self.api.request(Method.PUT, url, content={"reason": reason}, **kwargs)
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 233, in requestFeb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     return await self._send(method, full_url, content, query_params, headers or {})
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]:     raise make_request_error(http_status=response.status,
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]: mautrix.errors.request.MForbidden: You don't have permission to redact events
Feb 24 05:57:03 ubuntu-4gb-fsn1-1 matrix-mautrix-facebook[29471]: [2021-02-24 04:57:03,564] [INFO@aiohttp.access] 172.21.0.4 [24/Feb/2021:04:57:03 +0000] "PUT /transactions/27?access_token=TOKENID HTTP/1.1" 200 158 "-" "Synapse/1.27.0"`

What is wrong?

**Comment by skepticalwaves** [comment]
You may want to redact those access tokens...

**Comment by pushytoxin** [comment]
I can still see the tokens

**Comment by aaronraimist** [comment]
Yes GitHub has edit history. You can't redact them at this point, you'll have to change them.

**Comment by Happyfeet01** [comment]
Old versions deleted

**Comment by Happyfeet01** [comment]
has anyone an idea why i cant login to the services?

**Comment by ThellraAK** [comment]
@Happyfeet01 Turn on 2FA, when you get your code (either from 2FA app, or from SMS) copy and paste it in, it sorta silently fails without it.
