### ISSUE TITLE
matrix_nginx_proxy_proxy_synapse_metrics does not forward /_synapse/metrics externally

### ISSUE THREAD

**Issue by Centzilius** [spantaleev/matrix-docker-ansible-deploy#914]
Hi,
Although mentioned [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-prometheus-grafana.md) setting `matrix_nginx_proxy_proxy_synapse_metrics` to `true` does not forward the metrics endpoint to `matrix.DOMAIN/_synapse/metrics` (the required change is likely needed in `matrix_nginx_proxy_base_domain_homepage_template` in `roles/matrix-nginx-proxy/defaults/main.yml`).

Kind regards,
Centzilius

**Comment by spantaleev** [comment]
You're right, it was broken! Thanks for reporting it! It's fixed now
