### ISSUE TITLE
Error getting ssl certificate

### ISSUE THREAD

**Issue by luke2m** [spantaleev/matrix-docker-ansible-deploy#917]
I am trying to deploy matrix, but keep getting this error. I can tell that certbot is looking for something on my bare domain, but I am trying to run matrix on a subdomain. I do have a website on the bare domain, and I could copy a challenge over, but it seems to change each time. How can I deploy this, and what have I done wrong? I can give more information if needed.
- Ubuntu 20.04 with Ansible from the PPA 
- Ansible running directly on the server
<details>
<summary>Output</summary>
<pre>
$ ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
#all worked fine until here
TASK [matrix-nginx-proxy : Attempt initial SSL certificate retrieval with standalone authenticator (via proxy)] ***
fatal: [matrix.lukesempire.com]: FAILED! => changed=true 
  cmd: /usr/bin/env docker run --rm --name=matrix-certbot --user=998:1002 --cap-drop=ALL -p 127.0.0.1:2402:8080 --network=matrix --mount type=bind,src=/matrix/ssl/config,dst=/etc/letsencrypt --mount type=bind,src=/matrix/ssl/log,dst=/var/log/letsencrypt docker.io/certbot/certbot:amd64-v1.11.0 certonly --non-interactive --work-dir=/tmp --http-01-port 8080  --standalone --preferred-challenges http --agree-tos --email=hello@mydomain.com -d mydomain.com
  delta: '0:00:10.978509'
  end: '2021-03-02 19:34:36.810029'
  msg: non-zero return code
  rc: 1
  start: '2021-03-02 19:34:25.831520'
  stderr: |-
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator standalone, Installer None
    Performing the following challenges:
    http-01 challenge for mydomain.com
    Waiting for verification...
    Challenge failed for domain mydomain.com
    http-01 challenge for mydomain.com
    Cleaning up challenges
    Some challenges have failed.
  stderr_lines: <omitted>
  stdout: |-
    Requesting a certificate for mydomain.com
    IMPORTANT NOTES:
     - The following errors were reported by the server:
  
       Domain: mydomain.com
       Type:   unauthorized
       Detail: Invalid response from
       https://mydomain.com/.well-known/acme-challenge/9YsZQQK05NlRCB4OGuZBs0yP0MBDUJUAr8BvqHMWtj0
       [2604:a880:400:d0::1738:6001]: "<!DOCTYPE html>\n<html>\n  <head>\n
       <meta charset=\"utf-8\">\n    <meta name=\"viewport\"
       content=\"width=device-width, initial-scale="
  
       To fix these errors, please make sure that your domain name was
       entered correctly and the DNS A/AAAA record(s) for that domain
       contain(s) the right IP address.
  stdout_lines: <omitted>
...ignoring

TASK [matrix-nginx-proxy : Fail if all SSL certificate retrieval attempts failed] ***
fatal: [matrix.lukesempire.com]: FAILED! => changed=false 
  msg: |-
    Failed to obtain a certificate directly (by listening on port 80)
    and also failed to obtain by relying on the server at port 80 to proxy the request.
    See above for details.
    You may wish to set up proxying of /.well-known/acme-challenge to 2402 or,
    more easily, stop the server on port 80 while this playbook runs.

PLAY RECAP *********************************************************************
matrix.mydomain.com     : ok=169  changed=9    unreachable=0    failed=1    skipped=1269 rescued=0    ignored=2   
</pre>
</details>

**Comment by aaronraimist** [comment]
Can you post your `vars.yml` config file? Make sure to redact the secret keys.

**Comment by luke2m** [comment]
```
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: mydomain.com

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: 'hello@mydomain.com'

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: 'KEY’

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: 'KEY’

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: 'PASSWORD'
matrix_nginx_proxy_base_domain_serving_enabled: true
matrix_mailer_enabled: false
matrix_coturn_enabled: true 
matrix_coturn_turn_external_ip_address: 555.555.555.555

```

**Comment by aaronraimist** [comment]
You enabled base domain serving `matrix_nginx_proxy_base_domain_serving_enabled: true`

That means you are asking the playbook to serve on the base domain for you. If you want to control the base domain yourself then you shouldn't enable this option.

**Comment by luke2m** [comment]
Thank you for your help! I forgot to change that from the guide I was following (on the matrix.org website).
