### ISSUE TITLE
matrix-client-element shows container IP instead of a real IP address

### ISSUE THREAD

**Issue by sernik** [spantaleev/matrix-docker-ansible-deploy#922]
In "Security & Privacy" / "Where you’re logged in" / "Last seen" column.

**Comment by pushytoxin** [comment]
Do you have an AAAA DNS entry for matrix.YOURDOMAIN?

**Comment by sernik** [comment]
> Do you have an AAAA DNS entry for matrix.YOURDOMAIN?

I have DNS records configured as written in [Configuring your DNS server](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md). Nothing about AAAA IPv6 records there.

What does it has to do with showing logged-in external IP address? I was rather thinking of `matrix-client-element` not reading `proxy_set_header X-Forwarded-For $remote_addr;` header properly.

**Comment by spantaleev** [comment]
Supposedly fixed in f0698ee6414d5.

**Comment by sernik** [comment]
> Supposedly fixed in [f0698ee](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/f0698ee6414d5006e6d904a96c1f6927a8efb124).

Working ok now, thank you :-)
