### ISSUE TITLE
Youtube widgets?

### ISSUE THREAD

**Issue by akshaylive** [spantaleev/matrix-docker-ansible-deploy#924]
I was taking a look at [dimension](https://github.com/turt2live/matrix-dimension) and it looks like it's possible to add "widgets" to rooms. I'm trying to set one up for youtube but I don't know how to. Can someone help?

**Comment by skepticalwaves** [comment]
This isn't a question for spantaleev/matrix-docker-ansible-deploy

**Comment by akshaylive** [comment]
> This Ansible playbook is meant to help you run your own Matrix homeserver, along with the various services related to that.

I believe this question fits that category. Regardless, if not this repo, could you help me figure out which repo? :)

**Comment by skepticalwaves** [comment]
https://dimension.t2bot.io/

**Comment by akshaylive** [comment]
I did some trial and error. I think the "regular dimension user" needs to be a dimension admin. It's either that or I had to logout and log back in.

To add widgets, need to click on the "room info" icon and the widgets should appear there.
