### ISSUE TITLE
Etherpad widget address blacklisted

### ISSUE THREAD

**Issue by baloan** [spantaleev/matrix-docker-ansible-deploy#934]
Hi, I have setup my self-hosted instance for dimension, jitsi and etherpad. Jitsi work as expected, etherpad works standalone, but not as a widget. When I try to pin the etherpad widget I get: "Sorry, this content cannot be embedded", and the log file as enclosed.
Is this something I can resolve?

```
Mar 14 19:23:30 matrix-dimension[17844]: Mar-14-2021 18:23:30.962 +00:00 info [Webserver] Incoming request: GET /widgets/generic?url=https%3A%2F%2Fdimension.zntrl.de%2Fetherpad%2Fp%2FHypocriticalCaptainWand&widgetId=dimension-m.etherpad-1615744593199&parentUrl=vector%3A%2F%2Fvector%2Fwebapp%2F
Mar 14 19:23:32 matrix-dimension[17844]: Mar-14-2021 18:23:32.925 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/widgets/embeddable?url=https://dimension.zntrl.de/etherpad/p/HypocriticalCaptainWand
Mar 14 19:23:32 matrix-dimension[17844]: Mar-14-2021 18:23:32.927 +00:00 info [DimensionWidgetService] Checking to see if a url is embeddable: https://dimension.zntrl.de/etherpad/p/HypocriticalCaptainWand
Mar 14 19:23:32 matrix-dimension[17844]: Mar-14-2021 18:23:32.943 +00:00 warn [Webserver] Handling ApiError 400 {"message":"Address blacklisted","dim_errcode":"M_UNKNOWN","error":"Address blacklisted","errcode":"M_UNKNOWN"}
M
```

**Comment by spantaleev** [comment]
Hey!

It seems like the domain name of `https://dimension.DOMAIN/etherpad/....` (`dimension.DOMAIN`) resolves to some local address, which Dimension refuses to work with (because that local IP is part of Dimension's default `widgetBlacklist` configuration).

If you were to adjust `widgetBlacklist` or to make `dimension.DOMAIN` resolve to the external IP address, the issue should be resolved.

I'm not sure why `dimension.DOMAIN` resolves to a local IP address for you. I can't seem to reproduce this.

**Comment by baloan** [comment]
The culprit was 
```
root@mail:~# cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       v2202002113968108706.luckysrv.de v2202002113968108706
127.0.2.1       mail.zntrl.de mail
127.0.3.1       matrix.zntrl.de matrix

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
Commenting the hostnames from hosts solved the issue.
```
root@mail:~# cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       v2202002113968108706.luckysrv.de v2202002113968108706
# 127.0.2.1       mail.zntrl.de mail
# 127.0.3.1       matrix.zntrl.de matrix

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by spantaleev** [comment]
Ah! So `dimension.DOMAIN` was a `CNAME` record pointing to `matrix.DOMAIN`, which was hardcoded as `127.0.0.1`.

----------

Our documentation doesn't encourage modifying `/etc/hosts` from what I remember. Maybe you got inspired by some mail-server setup documentation or some other Matrix guide.

**Comment by jfisherp** [comment]
I have the same problem but I dont have nothing on /etc/hosts:

[root@matrix-pl1-n1 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
