### ISSUE TITLE
Unable to start setup on Ubuntu 18.04 server

### ISSUE THREAD

**Issue by vadiof** [spantaleev/matrix-docker-ansible-deploy#935]
Trying to deploy on Ubuntu 18.04 and getting this error:
fatal: [<server.name>]: FAILED! => changed=false 
  ansible_facts: {}
  failed_modules:
    setup:
      ansible_facts:
        discovered_interpreter_python: /usr/bin/python
      deprecations:
      - msg: Distribution Ubuntu 18.04 on host <server.name> should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information
        version: '2.12'
      failed: true
      module_stderr: "sudo:  "
      module_stdout: ''
      msg: |-
        MODULE FAILURE
        See stdout/stderr for the exact error
      rc: 1
  msg: |-
    The following modules failed to execute: setup

I do realize I have to setup ansible in some proper way but I'm noob and have no clue how to do it. Would appreciate if someone provide simple point to what should be done here. Thanks!

**Comment by spantaleev** [comment]
As `examples/hosts` says, you may need to append `ansible_python_interpreter=/usr/bin/python3` to your host line in `inventory/hosts`.
