### ISSUE TITLE
backup_server.yml Syntax Error

### ISSUE THREAD

**Issue by NbIServ** [spantaleev/matrix-docker-ansible-deploy#938]
Hello,

after start/stop i get this error:
root@matrix:~/matrix-docker-ansible-deploy# ansible-playbook -i inventory/hosts setup.yml --tags=stop
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/matrix-docker-ansible-deploy/roles/matrix-awx/tasks/backup_server.yml': line 36, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Recreate 'Backup Server' job template
  ^ here

root@matrix:~/matrix-docker-ansible-deploy#

**Comment by er0k** [comment]
Same error here. This looks like it was introduced in 011e95c1d2276e03168098d8fb22f44291859855.

If I reset to the previous commit (b46ef46663041ee65f380a926f3b6d519c06c901) I no longer get this error.

**Comment by spantaleev** [comment]
Fixed in #939

**Comment by er0k** [comment]
Thanks!
