### ISSUE TITLE
Add info on matrix_ssl_domains_to_obtain_certificates_for to configuring-playbook-ssl-certificates.md

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#94]
I keep checking https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ssl-certificates.md for the info but it's actually in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/howto-server-delegation.md#server-delegation-via-a-well-known-file

**Comment by spantaleev** [comment]
You're right!

I've moved it to the SSL certificate document and set up a link to it.
It's a better place and also keeps the Server Delegation document cleaner.

Thanks! :+1:
