### ISSUE TITLE
psql: error: could not translate host name \"matrix-postgres\" to address: Try again

### ISSUE THREAD

**Issue by featherbutt** [spantaleev/matrix-docker-ansible-deploy#943]
```
TASK [matrix-postgres : Execute Postgres additional database initialization SQL file for synapse]
fatal: [matrix.featherbutt.com]: FAILED! => {
    "changed": true,
    "cmd": [
        "/usr/bin/env",
        "docker",
        "run",
        "--rm",
        "--user=997:1001",
        "--cap-drop=ALL",
        "--env-file=/matrix/postgres/env-postgres-psql",
        "--network",
        "matrix",
        "--mount",
        "type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro",
        "--entrypoint=/bin/sh",
        "docker.io/postgres:13.2-alpine",
        "-c",
        "psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql"
    ],
    "delta": "0:00:05.786164",
    "end": "2021-03-16 07:35:22.075133",
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/env docker run --rm --user=997:1001 --cap-drop=ALL --env-file=/matrix/postgres/env-postgres-psql --network matrix --mount type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro --entrypoint=/bin/sh docker.io/postgres:13.2-alpine -c 'psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql'",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 2,
    "start": "2021-03-16 07:35:16.288969",
    "stderr": "psql: error: could not translate host name \"matrix-postgres\" to address: Try again",
    "stderr_lines": [
        "psql: error: could not translate host name \"matrix-postgres\" to address: Try again"
    ],
    "stdout": "",
    "stdout_lines": []
}
PLAY RECAP ********************************************************************************************************************************
matrix.featherbutt.com     : ok=51   changed=19   unreachable=0    failed=1    skipped=55   rescued=0    ignored=0
```

This is with the most recent commits, so it's not #889 or #913 

Things I already tried:
- Uninstalling and reinstalling
- Removing all the fields I added to vars.yml

I'm attempting to install on a Raspberry Pi 4 running Raspian, running Ansible from a docker container on a Windows machine using WSL as my command line.

**Comment by featherbutt** [comment]
Here's the logs at -vv level

[vv.log](https://github.com/spantaleev/matrix-docker-ansible-deploy/files/6152078/vv.log)

**Comment by featherbutt** [comment]
By polling `docker container ls -a --no-trunc` while the setup is running, I can see that ansible does create a doctor container named matrix-postgres:

```
CONTAINER ID                                                       IMAGE                            COMMAND                           CREATED         STATUS        PORTS      NAMES
e617c0ffb56c8e109676f9bc7f76936739e7f4ec44374cd84c94402d4a5019ce   docker.io/postgres:13.2-alpine   "docker-entrypoint.sh postgres"   4 seconds ago   Up 1 second   5432/tcp   matrix-postgres
```

However, by the time ansible gets to the failing action, that container no longer exists. At the time of the failing command, `docker container ls -a --no-trunc` returns:

```
CONTAINER ID                                                       IMAGE                            COMMAND                                                             CREATED         STATUS                  PORTS      NAMES
3c8ad858735dfec958f4a6a25503dfb5a9d16b7890eaf4cf8d91dcd5b0ce6102   docker.io/postgres:13.2-alpine   "/bin/sh -c 'psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql'"   2 seconds ago   Up Less than a second   5432/tcp   trusting_leakey
```

**Comment by featherbutt** [comment]
There appears to be an issue with postgres starting up. When I attempt to manually start it up with `systemctl start matrix-postgres`, I get the following logs:

```
Mar 16 22:34:06 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 202012
Mar 16 22:34:06 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Mar 16 22:34:06 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  listening on IPv6 address "::", port 5432
Mar 16 22:34:06 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Mar 16 22:34:14 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  startup process (PID 13) was terminated by signal 11: Segmentation fault
Mar 16 22:34:14 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  aborting startup due to startup process failure
Mar 16 22:34:15 raspberry-fuzz matrix-postgres[16557]: 1970-05-01 13:02:32.010 GMT [1] LOG:  database system is shut down
Mar 16 22:34:15 raspberry-fuzz systemd[1]: matrix-postgres.service: Main process exited, code=exited, status=1/FAILURE
Mar 16 22:34:15 raspberry-fuzz systemd[1]: matrix-postgres.service: Failed with result 'exit-code'.
Mar 16 22:34:21 raspberry-fuzz systemd[1]: Stopped Matrix Postgres server.
```

**Comment by featherbutt** [comment]
I would expect that the "Ensure matrix-postgres is started" and the "Wait a bit, so that Postgres can start" tasks would be failing here, since postgres isn't actually starting up. But these checks appear to be passing, delaying the failure to when "Execute Postgres additional database initialization SQL file for synapse" actually tries to contact the database that isn't running.

**Comment by featherbutt** [comment]
So it turns out this is a big case of "didn't read all the instructions carefully."

I was missing the `matrix_architecture: "arm32"` setting from my vars.yml, so by default the playbook was targeting amd64.

That said, it feels like it could be possible to improve the checks and error messaging here in a couple of ways:

- The fact that the postgreSQL server was failing to start feels like something that could be detected by the a playbook check, especially given that one of them is called "Ensure matrix-postgres is started"
- Detecting an architecture mismatch may not  always be possible, but if the host supports `uname -m` or `dpkg --print-architecture`, we could potentially detect obvious mismatches.

**Comment by aaronraimist** [comment]
@featherbutt I have added a sanity check for the wrong architecture in #991. If you could test that on your arm32 server I would appreciate it.

**Comment by harris012** [comment]
> Hello everyone,
> 
> This issue is back on Raspberry Pi 4 arm64 confused :
> 
> ```
> TASK [matrix-postgres : Execute Postgres additional database initialization SQL file for synapse] *****
> fatal: [matrix.roiarthurb.xyz]: FAILED! => changed=true 
>   cmd:
>   - /usr/bin/env
>   - docker
>   - run
>   - --rm
>   - --user=998:1001
>   - --cap-drop=ALL
>   - --env-file=/matrix/postgres/env-postgres-psql
>   - --network
>   - matrix
>   - --mount
>   - type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro
>   - --entrypoint=/bin/sh
>   - docker.io/postgres:14.0-alpine
>   - -c
>   - psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql
>   delta: '0:00:04.767939'
>   end: '2021-10-08 18:16:05.345016'
>   msg: non-zero return code
>   rc: 2
>   start: '2021-10-08 18:16:00.577077'
>   stderr: 'psql: error: could not translate host name "matrix-postgres" to address: Name does not resolve'
>   stderr_lines: <omitted>
>   stdout: ''
>   stdout_lines: <omitted>
> ```
> 
> ```
> ~$ journalctl -fu matrix-postgres
> -- Logs begin at Fri 2021-10-08 18:11:45 +07. --
> Oct 08 18:16:35 osmc matrix-postgres[2742]: PostgreSQL Database directory appears to contain a database; Skipping initialization
> Oct 08 18:16:35 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  starting PostgreSQL 14.0 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 32-bit
> Oct 08 18:16:35 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> Oct 08 18:16:35 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> Oct 08 18:16:35 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> Oct 08 18:16:45 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  startup process (PID 13) was terminated by signal 11: Segmentation fault
> Oct 08 18:16:45 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  aborting startup due to startup process failure
> Oct 08 18:16:45 osmc matrix-postgres[2742]: 1970-07-26 14:38:48.017 UTC [1] LOG:  database system is shut down
> Oct 08 18:16:47 osmc systemd[1]: matrix-postgres.service: Main process exited, code=exited, status=1/FAILURE
> Oct 08 18:16:47 osmc systemd[1]: matrix-postgres.service: Failed with result 'exit-code'.
> ```

are you able to solve it ? ... I am also having the same issue

**Comment by aaronraimist** [comment]
@RoiArthurB @harris012 I doubt this is the same issue. Are you both using Postgres 14? Can you open a new issue and include the contents of your `vars.yml` file? Make sure to redact the secret keys.
