### ISSUE TITLE
new Docker images (Prometheus, Grafana, etc.) are not being pulled

### ISSUE THREAD

**Issue by schwony** [spantaleev/matrix-docker-ansible-deploy#954]
I'm not sure if that's a real issue or a misunderstanding on my side. I believe ever since the signal-bridge was introduced I've not been able to "play" with these new improvements as none of the corresponding docker images are pulled/started. the playbook runs fine when trying to make "Enabling metrics and graphs for your Matrix server (optional)" work. even though, no errors are encountered, there is no Prometheus nor Grafana Docker image showing up. stats.matrix-server shows "bad gateway". 
Do these optional instructions presume that the software/docker image is installed prior (if so, documentation is not clear about this)? 
What else could be the issue?

Thanks in advance!

**Comment by aaronraimist** [comment]
> Do these optional instructions presume that the software/docker image is installed prior (if so, documentation is not clear about this)?

No. The playbook installs and configures everything. Can you share what commit of the playbook you are on and the contents of your `vars.yml` config file? Make sure to redact the secret keys.

**Comment by schwony** [comment]
Hi, thank you for your quick response. 
vars.yml:

`matrix_prometheus_enabled: true
matrix_prometheus_node_exporter_enabled: true
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: false
matrix_grafana_default_admin_user: ***
matrix_grafana_default_admin_password: ***
matrix_etherpad_enabled: true
matrix_postgres_connection_password: ***
matrix_synapse_ext_password_provider_rest_auth_enabled: true
matrix_synapse_ext_password_provider_rest_auth_endpoint: "http://matrix-ma1sd:8090"
matrix_synapse_ext_password_provider_rest_auth_registration_enforce_lowercase: false
matrix_synapse_ext_password_provider_rest_auth_registration_profile_name_autofill: true
matrix_synapse_ext_password_provider_rest_auth_login_profile_name_autofill: false
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: “***I”
matrix_dynamic_dns_enabled: false
matrix_synapse_admin_enabled: true
matrix_nginx_proxy_enabled: false
#matrix_ssl_retrieval_method: self-signed
matrix_domain: ***
matrix_ssl_lets_encrypt_support_email: ***
matrix_coturn_turn_static_auth_secret: “***”
matrix_synapse_macaroon_secret_key: “***”
matrix_element_web_jitsi_preferredDomain: ‘***’
#matrix_synapse_enable_registration: true
#matrix_synapse_registration_shared_secret: “***”
#matrix_synapse_registrations_require_3pid: email
#matrix_synapse_enable_registration_captcha: true
#matrix_synapse_recaptcha_public_key: “***”
#matrix_synapse_recaptcha_private_key: “***”
matrix_element_web_themes_enabled: true

matrix_dimension_enabled: true

matrix_dimension_access_token: “***”
matrix_dimension_admins:
  - “@***:{{ matrix_domain }}"
  - “@***:{{ matrix_domain }}"
#matrix_nginx_proxy_base_domain_serving_enabled: true
#matrix_nginx_proxy_base_domain_homepage_enabled: true

matrix_jitsi_enabled: true

matrix_jitsi_jicofo_component_secret: “***”
matrix_jitsi_jicofo_auth_password: “***”
matrix_jitsi_jvb_auth_password: “***”
matrix_jitsi_jibri_recorder_password: “***”
matrix_jitsi_jibri_xmpp_password: “***”
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true`

**Comment by aaronraimist** [comment]
When you run the `setup-all` all tag what happens? Can you post the log of all stuff the `ansible-playbook` command spits out?

**Comment by schwony** [comment]
setup-all completes without errors. I can post the complete log. however, here are the lines regarding my example: 

TASK [matrix-prometheus-node-exporter : set_fact] ************************************************************************************************************************
task path: /home/***/matrix-docker-ansible-deploy/roles/matrix-prometheus-node-exporter/tasks/init.yml:1
ok: [matrix.***] => changed=false 
  ansible_facts:
    matrix_systemd_services_list:
    - matrix-mailer.service
    - matrix-postgres.service
    - matrix-synapse.service
    - matrix-synapse-admin.service
    - matrix-prometheus-node-exporter.service

TASK [matrix-prometheus : set_fact] **************************************************************************************************************************************
task path: /home/***/matrix-docker-ansible-deploy/roles/matrix-prometheus/tasks/init.yml:1
ok: [matrix.***] => changed=false 
  ansible_facts:
    matrix_systemd_services_list:
    - matrix-mailer.service
    - matrix-postgres.service
    - matrix-synapse.service
    - matrix-synapse-admin.service
    - matrix-prometheus-node-exporter.service
    - matrix-prometheus.service

TASK [matrix-grafana : set_fact] *****************************************************************************************************************************************
task path: /home/***/matrix-docker-ansible-deploy/roles/matrix-grafana/tasks/init.yml:1
ok: [matrix.***] => changed=false 
  ansible_facts:
    matrix_systemd_services_list:
    - matrix-mailer.service
    - matrix-postgres.service
    - matrix-synapse.service
    - matrix-synapse-admin.service
    - matrix-prometheus-node-exporter.service
    - matrix-prometheus.service
    - matrix-grafana.service

**Comment by aaronraimist** [comment]
Yeah you are going to need to share more than that.

**Comment by schwony** [comment]
sorry for the delay. here you go. I hope all sensitive information are redacted. 

thanks again
[ansible.log](https://github.com/spantaleev/matrix-docker-ansible-deploy/files/6193416/ansible.log)

**Comment by aaronraimist** [comment]
Hmm. What do `docker ps` and `sudo systemctl status matrix-grafana` show?

**Comment by schwony** [comment]
finally getting somewhere. with docker-ps I just noticed that even though I used the —restart tag, all containers had been up for several days without actually restarting. so I stopped them and then ran the playbook with —start tag. now it fails with the prometheus-node-exporter not starting as it can‘t bind port 9100 - already used by docker-proxy. however, the grafana, prometheus et al containers started, finally.

journalctl -fu matrix-prometheus-node-exporter.service
-- Logs begin at Thu 2021-02-18 22:55:24 CET. --
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.944Z caller=node_exporter.go:113 collector=timex
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.944Z caller=node_exporter.go:113 collector=udp_queues
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.944Z caller=node_exporter.go:113 collector=uname
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.944Z caller=node_exporter.go:113 collector=vmstat
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.944Z caller=node_exporter.go:113 collector=xfs
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.945Z caller=node_exporter.go:113 collector=zfs
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=info ts=2021-03-24T07:50:20.945Z caller=node_exporter.go:195 msg="Listening on" address=:9100
Mar 24 08:50:20 *domain* matrix-prometheus-node-exporter[644384]: level=error ts=2021-03-24T07:50:20.946Z caller=node_exporter.go:198 err="listen tcp :9100: bind: address already in use"
Mar 24 08:50:21 *domain* systemd[1]: matrix-prometheus-node-exporter.service: Main process exited, code=exited, status=1/FAILURE
Mar 24 08:50:21 *domain* systemd[1]: matrix-prometheus-node-exporter.service: Failed with result 'exit-code'.

 netstat -antup | grep 9100
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      633373/docker-proxy

**Comment by aaronraimist** [comment]
Hmm interesting. I wouldn't have thought anything should be listening on 9100 since you haven't set `matrix_prometheus_node_exporter_container_http_host_bind_port`. You could try setting that to a different port like `matrix_prometheus_node_exporter_container_http_host_bind_port: 9101` or killing that process and seeing if it will start then.

**Comment by spantaleev** [comment]
Rebooting the server may also be a good idea. The `docker` (`containerd`) daemon may have ended up in some bad state, where it's still holding on to some ports.

**Comment by schwony** [comment]
tried all of the above. trying to change the port, which it won‘t accept. is there any other way?

 ps aux | grep 9100                                                       
root       96867  0.0  0.6 905124 56828 ?        Ssl  09:49   0:00 docker run --rm --name matrix-synapse --log-driver=none --user=991:991 --env=UID=991 --env=GID=991 --cap-drop=ALL --read-only --tmpfs=/tmp:rw,noexec,nosuid,size=2500m --network=matrix -p 127.0.0.1:8008:8008 -p 127.0.0.1:8048:8048 -p 127.0.0.1:9100:9100 --mount type=bind,src=/matrix/synapse/config,dst=/data,ro --mount type=bind,src=/matrix/synapse/storage,dst=/matrix-media-store-parent,bind-propagation=slave --mount type=bind,src=/matrix/mautrix-signal/bridge/registration.yaml,dst=/matrix-mautrix-signal-registration.yaml,ro --mount type=bind,src=/matrix/synapse/ext/rest_auth_provider.py,dst=/usr/local/lib/python3.8/site-packages/rest_auth_provider.py,ro --mount type=bind,src=/matrix/synapse/ext/shared_secret_authenticator.py,dst=/usr/local/lib/python3.8/site-packages/shared_secret_authenticator.py,ro docker.io/matrixdotorg/synapse:v1.30.0 run -m synapse.app.homeserver -c /data/homeserver.yaml
root       96934  0.0  0.0 549024  3932 ?        Sl   09:49   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 9100 -container-ip 172.20.0.4 -container-port 9100

**Comment by schwony** [comment]
so just for verification:

492c825859bc   matrixdotorg/synapse:v1.30.0               "/start.py run -m sy…"   56 minutes ago   Up 56 minutes (healthy)   127.0.0.1:8008->8008/tcp, 8009/tcp, 127.0.0.1:8048->8048/tcp, 127.0.0.1:9100->9100/tcp, 8448/tcp                                       matrix-synapse
