### ISSUE TITLE
Add self-build option for matrix-dimension image

### ISSUE THREAD

**Issue by mattcen** [spantaleev/matrix-docker-ansible-deploy#959]
This issue is dependent on https://github.com/turt2live/matrix-dimension/pull/403, which still needs some work, but I wanted to create it as a placeholder nonetheless.

Long story short, the linked PR *does* apparently build the matrix-dimension image correctly on arm64, but leaves a bunch of unnecessary build stuff in the final image, which isn't ideal, so we need to work out how to reduce that by copying pre-built node packages from the build stage of the Dockerfile.

**Comment by johndotpub** [comment]
@mattcen Feel free to check out the branch my [recent PR](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1445) is using and let shout if you have any issues with the self-build option for matrix-dimension.

**Comment by spantaleev** [comment]
Closed by #1445
