### ISSUE TITLE
TASK [matrix-base : Preserve vars.yml on the server for easily restoring if it gets lost later on] Fails

### ISSUE THREAD

**Issue by KAPPAsper** [spantaleev/matrix-docker-ansible-deploy#968]
So I am trying the playbook it fails on the task `TASK [matrix-base : Preserve vars.yml on the server for easily restoring if it gets lost later on]` with error: `An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [matrix.my-domain.xyz]: FAILED! => {"changed": false, "msg": "Could not find or access '/home/user/matrix-docker-ansible-deploy/inventory/host_vars/matrix.my-domain.xyz/vars.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}`
I saw an other issues where putting the line: `matrix_vars_yml_snapshotting_enabled: false` inside vars.yml would solve it. But it still fails for me.

**Comment by spantaleev** [comment]
Does that file (`/home/user/matrix-docker-ansible-deploy/inventory/host_vars/matrix.my-domain.xyz/vars.yml`) exist? Do you have a typo somewhere? Have you named it `vars.yaml` or `host_vars.yml` instead of `vars.yml` or something?

**Comment by KAPPAsper** [comment]
Yes my bad .yaml and not .yml
