### ISSUE TITLE
Use Python3 in Ansible by default

### ISSUE THREAD

**Issue by jdreichmann** [spantaleev/matrix-docker-ansible-deploy#97]
On Fedora 28+, the python2 package for firewalld was removed: https://bugzilla.redhat.com/show_bug.cgi?id=1575428 so you need to use the python3-firewalld package and therefore use python3.

To make this happen, we need to overwrite `ansible_python_interpreter` (according to https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#list-of-behavioral-inventory-parameters):
`ansible_python_interpreter: "/usr/bin/python3"`

**Comment by spantaleev** [comment]
I think we don't really even need the `firewalld` module calls.

Every time a Docker container opens a port, the Docker daemon adjusts the iptables rules automatically. See [Docker and iptables](https://docs.docker.com/network/iptables/).

So I'm guessing we can probably even remove all of our firewalld-related code and services wouldn't be affected.

If we get rid of that (which we probably should), I wonder if we'd still need to mess with `ansible_python_interpreter` for Fedora 28+.

**Comment by spantaleev** [comment]
The playbook no longer installs, nor manages `firewalld` anymore.

Not touching anything `firewalld`-related anymore, means that we shouldn't run into Fedora package dependency issues.

Thanks for provoking this improvement! :+1:
