### ISSUE TITLE
matrix_jisti_web_interface_config_show_deep_linking_image typo

### ISSUE THREAD

**Issue by KyleMiles** [spantaleev/matrix-docker-ansible-deploy#970]
`matrix_jisti_web_interface_config_show_deep_linking_image` should probably be `matrix_jitsi_web_interface_config_show_deep_linking_image`

(`jisti` -> `jitsi`)

**Comment by spantaleev** [comment]
Fixed! Thanks for reporting this :+1:

**Comment by pushytoxin** [comment]
If you mean this: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/179b416ed5d1139d3e14464e46ee1d5e90ae645f

There's also this: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/179b416ed5d1139d3e14464e46ee1d5e90ae645f/roles/matrix-jitsi/templates/web/interface_config.js.j2#L180
