### ISSUE TITLE
Jitsi image upgrade to stable-5390-3, unable to work with XMPP websocket

### ISSUE THREAD

**Issue by NeoN0x** [spantaleev/matrix-docker-ansible-deploy#975]
Hi all,

I'm trying to update the jitsi image from stable-5142 to stable-5390-3, by updating the setting **matrix_jitsi_version**

    matrix_jitsi_version: stable-5390-3

However, it appears that a breaking change occured on 5142-1 (unstable but fixed in 5142-4) enables XMPP sockets by default.

Symptoms : unable to join room, "You have been disconected, check your connection", as WS request are failing with 403.

There are numerous issues related to this on the docker-jitsi-meet image when using a reverse proxy [992](https://github.com/jitsi/docker-jitsi-meet/issues/992), [992](https://github.com/jitsi/docker-jitsi-meet/issues/992), [987](https://github.com/jitsi/docker-jitsi-meet/issues/987), [962](https://github.com/jitsi/docker-jitsi-meet/issues/962), ....

I'm trying to add the xmpp websocket forward in the nginx proxy

**roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2**

Line ~48, after  colibri (JVB) websockets (based on [this anwer](https://github.com/jitsi/docker-jitsi-meet/issues/962#issuecomment-787003189)) : 

```
	# XMPP websockets
	location /xmpp-websocket {
		{% if matrix_nginx_proxy_enabled %}
			resolver 127.0.0.11 valid=30s;
			set $backend "matrix-jitsi-prosody:80/xmpp-websocket";
			proxy_pass http://$backend;
		{% endif %}

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		proxy_set_header Host $host;
	}

```

I've tried a lot of variations without success.

Does anyone have an idea of what coud be done here ?

Thanks !

Note
* Sorry if i'm not clear, I'm not an expert in jitsi - I'll be happy to help debugging things
* Thank you for this awesome project ! It works very well (including turn setup, certificates etc)

**Comment by imperative** [comment]
This issue still exists in 5765-1.
