### ISSUE TITLE
Riot Web lots of "missing translation en"

### ISSUE THREAD

**Issue by NullIsNot0** [spantaleev/matrix-docker-ansible-deploy#98]
Just upgraded to Riot Web 1.0.1, but now I get lots of "missing translation en" messages in interface on browsers where previous release Riot Web was opened (see image here: https://ibb.co/YWMyvq7). New browsers open with correctly translated interface. Tried to clean browser's cache, but without any success.
Found a pull request on `vector-im/riot-web` about correct caching implementation on self-hosted solutions: https://github.com/vector-im/riot-web/pull/8702/commits/f9551ddff54bfe042cbe77b8f0172d87cc220e87
I'm not good at nginx configuration, so I could not provide a pull request for this issue.

**Comment by NullIsNot0** [comment]
Opening https://riot.MYSITE.com/i18n/en_EN.json and force-reloading (cmd+R or Ctrl+F5) reads correct file and interface shows up correctly.

**Comment by spantaleev** [comment]
I can't see your screenshot (seems broken), but think I've noticed this same problem too in the past.. Especially regarding `config.json` changes not taking effect and requiring a manual Ctrl+F5.. Quite annoying.

I've applied the non-caching rules recommendation proposed in vector-im/riot-web#8702, which should fix this problem.

Thanks for bringing my attention to this! :+1:
