### ISSUE TITLE
matrixdotorg/synapse:v1.30.1 taking up port 9100 required by matrix-prometheus-node-exporter

### ISSUE THREAD

**Issue by schwony** [spantaleev/matrix-docker-ansible-deploy#983]
I‘m unable to use „matrix_prometheus_node_exporter_enabled: true“

it will fail to start due to port 9100 already in use by the matrix-synapse docker image

```
journalctl -fu matrix-prometheus-node-exporter.service shows

„err="listen tcp :9100: bind: address already in use"“
```

```
docker ps | grep 9100                                 
864d1774f819   matrixdotorg/synapse:v1.30.1               "/start.py run -m sy…"   7 minutes ago   Up 7 minutes (healthy)    127.0.0.1:8008->8008/tcp, 8009/tcp, 127.0.0.1:8048->8048/tcp, 8448/tcp, 0.0.0.0:9100->9100/tcp                                         matrix-synapse
```

I‘ve tried binding to a different port via: 
`matrix_prometheus_node_exporter_container_http_host_bind_port: '9101'`
or even
`matrix_synapse_container_metrics_api_host_bind_port: '9101'`

in inventory/host_vars/matrix.DOMAIN/vars.yml to no avail.

any suggestions?

**Comment by spantaleev** [comment]
This only happened when `matrix_nginx_proxy_enabled: false`.

The playbook was trying to expose both Synapse's metrics port and prometheus-node-exporter at `127.0.0.1:9100`.

With a1a0d91, we now expose prometheus-node-exporter at `127.0.0.1:9200`, should you need it.

If you're using the integrated prometheus service, it will scrape it over the local `matrix` Docker network and won't even use that `127.0.0.1:9200` port.
