### ISSUE TITLE
Where to find /var/log/nginx/access.log?

### ISSUE THREAD

**Issue by Devenda** [spantaleev/matrix-docker-ansible-deploy#989]
When trying to setup fail2ban I would like to read the access.log directly.

However the file does not exist here: /var/log/nginx/access.log
Even though this setting is set to true:
`# Option to disable the access log`
`matrix_nginx_proxy_access_log_enabled: true`

Where is this logfile located?

**Comment by skepticalwaves** [comment]
journalctl -u matrix-nginx-proxy.service

**Comment by Devenda** [comment]
> journalctl -u matrix-nginx-proxy.service

Thanks, but given that most standard regexes provided by fail2ban assume the default logfile format I would like to monitor the default logfile, is there a way to do so?

**Comment by aaronraimist** [comment]
I don’t think we log to a file anywhere. You can use fail2ban with journalctl https://unix.stackexchange.com/questions/268357/how-to-configure-fail2ban-with-systemd-journal#335528

**Comment by Devenda** [comment]
> 
> 
> I don’t think we log to a file anywhere. You can use fail2ban with journalctl https://unix.stackexchange.com/questions/268357/how-to-configure-fail2ban-with-systemd-journal#335528

Great!
Together with slightly different filters I got this working.

Example regex:
`^%(__prefix_line)s<HOST> -.*GET.*(\.php|\.asp|\.exe|\.pl)`
